const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');

test('login possui opção Ver senha sem alterar a senha armazenada',()=>{const h=read('frontend/login.html'),j=read('frontend/js/login.js'),css=read('frontend/style.css');assert.match(h,/id="showPassword"[^>]*type="checkbox"/);assert.match(h,/Ver senha/);assert.match(j,/senha\.type=e\.target\.checked\?'text':'password'/);assert.match(css,/\.show-password-check/)});

test('step-up usa somente TOTP antirreplay quando 2FA está ativo e somente senha sem 2FA',()=>{const a=read('backend/src/routes/auth.js'),c=read('frontend/js/common.js');const block=a.slice(a.indexOf("'/step-up'"),a.indexOf('LOGOUT'));assert.match(block,/if\(usuario\.mfa_enabled\)/);assert.match(block,/verifyAndConsumeTotp\(req\.usuario\.id,secret,req\.body\?\.mfa_code\)/);assert.match(block,/bcrypt\.compare\(boundedPassword\(req\.body\?\.senha\)/);assert.match(c,/mode:mfa\?'totp':'password'/);assert.match(c,/mfa\?\{mfa_code:value\}:\{senha:value\}/);assert.match(block,/setStepUpCookie\(res,req\.usuario,metodo\)/);assert.match(a,/expiresIn:'10m'/)});



test('confirmação de 2FA ou senha usa modal próprio e não prompt/alert do navegador',()=>{const c=read('frontend/js/common.js'),l=read('frontend/js/login.js'),css=read('frontend/style.css');assert.match(c,/function securityChallenge\(/);assert.match(c,/id='bfSecurityChallenge'|root.id='bfSecurityChallenge'/);assert.match(c,/show-password-check/);assert.match(c,/Verificando\.\.\./);assert.doesNotMatch(c,/\bprompt\(/);assert.doesNotMatch(l,/\bprompt\(|\balert\(/);assert.match(l,/securityChallenge\(\{mode:'totp'/);assert.match(css,/\.security-challenge-card/);assert.match(css,/@media\(max-width:600px\)[\s\S]*security-challenge-card/)});
test('ações importantes usam step-up central e exclusão de tenant exige 2FA fresco',()=>{const m=read('backend/src/routes/master.js'),t=read('backend/src/routes/tenant.js'),p=read('backend/src/routes/pagamentos.js'),s=read('backend/src/routes/store.js');for(const route of ["/barbearias/:id/status","/payment-gateways/:provedor/credenciais","/perfil/senha"])assert.match(m,new RegExp(route.replace(/[/:]/g,x=>x==='/'?'\\/':':')+"[^\\n]{0,180}exigirStepUp"));assert.match(m,/barbearias\/:id'?,exigir2FAExclusao/);assert.match(m,/barbearias\/:id\/permanente'?,exigir2FAExclusao/);assert.match(m,/verifyAndConsumeTotp\(req\.usuario\.id,secret,req\.body\?\.mfa_code\)/);assert.match(t,/financeiro\/metas'[^\n]{0,220}exigirStepUp/);assert.match(t,/usuarios\/:id'[^\n]{0,220}exigirStepUp/);assert.match(p,/gateways\/:provedor\/credenciais'[^\n]{0,220}exigirStepUp/);assert.match(s,/put\('\/config',exigirStepUp/);assert.match(s,/produtos\/:id',exigirStepUp/)});

test('loja 2.7 possui carrinho checkout Pix cartão e pedido persistido',()=>{const h=read('frontend/loja.html'),j=read('frontend/js/loja-publica.js'),r=read('backend/src/routes/storePublic.js'),svc=read('backend/src/services/storeCommerce.js');for(const id of ['cartDrawer','checkoutModal','paymentArea','pixArea','cardArea','storeCardBrick'])assert.match(h,new RegExp(`id="${id}"`));assert.match(j,/MercadoPago\(store\.public_key/);assert.match(r,/pedidos\/:token\/pix/);assert.match(r,/pedidos\/:token\/cartao/);assert.match(svc,/CREATE TABLE IF NOT EXISTS loja_pedidos/);assert.match(svc,/loja_pedido_itens/)});

test('e-commerce reserva estoque e converte pagamento aprovado em venda financeira',()=>{const s=read('backend/src/services/storeCommerce.js');assert.match(s,/UPDATE produtos SET estoque=estoque-\$1/);assert.match(s,/expira_em.*30 minutes/s);assert.match(s,/releaseExpiredStoreOrders/);assert.match(s,/INSERT INTO vendas\(barbearia_id,cliente_id,forma_pagamento,status,total/);assert.match(s,/INSERT INTO venda_itens/);assert.match(s,/estoque_reservado=false/)});

test('frete possui retirada, preço por km, grátis por distância ou valor e limite máximo',()=>{const s=read('backend/src/services/storeCommerce.js'),a=read('frontend/pages/loja.html');for(const x of ['loja_aceitar_retirada','loja_aceitar_entrega','loja_frete_taxa_base','loja_frete_por_km','loja_frete_gratis_ate_km','loja_frete_gratis_acima','loja_frete_distancia_max_km'])assert.match(a,new RegExp(x));assert.match(s,/taxa_base\+route\.km\*cfg\.valor_por_km/);assert.match(s,/route\.km<=cfg\.gratis_ate_km/);assert.match(s,/subtotal>=cfg\.gratis_acima/);assert.match(s,/route\.km>cfg\.distancia_max_km/);assert.match(s,/tipo_entrega==='retirada'/)});

test('distância usa Google Routes quando configurado e fallback OSM/OSRM',()=>{const s=read('backend/src/services/storeCommerce.js'),env=read('backend/.env.example');assert.match(s,/routes\.googleapis\.com\/directions\/v2:computeRoutes/);assert.match(s,/routes\.\[0\]\.distanceMeters|routes\[0\]\.distanceMeters/);assert.match(s,/router\.project-osrm\.org/);assert.match(s,/nominatim\.openstreetmap\.org/);assert.match(env,/GOOGLE_MAPS_ROUTES_API_KEY=/);assert.match(env,/ROUTING_FALLBACK_OSM=true/)});

test('checkout consulta CEP e aceita entrega ou retirada',()=>{const r=read('backend/src/routes/storePublic.js'),j=read('frontend/js/loja-publica.js');assert.match(r,/viacep\.com\.br\/ws/);assert.match(r,/loja\/cep\/:cep/);assert.match(j,/deliveryCep.*addEventListener\('blur'/s);assert.match(j,/delivery='retirada'/);assert.match(j,/delivery='entrega'/)});

test('Mercado Pago por tenant aceita segredo de webhook criptografado',()=>{const g=read('backend/src/services/paymentGateways.js'),w=read('backend/src/routes/integracoes.js');assert.match(g,/webhook_secret/);assert.match(g,/encrypt\(JSON\.stringify\(c\.secret\)\)/);assert.match(g,/tenantWebhookSecret/);assert.match(w,/tenantWebhookSecret\(candidate\)/);assert.match(w,/paymentScope==='subscription'/);assert.match(w,/else secret=\(await tenantWebhookSecret\(candidate\)\)/);assert.match(w,/validarWebhook/)});

test('schema e migração 2.7 incluem pedidos e configuração de frete',()=>{const m=read('backend/migrar-banco.js'),s=read('database/schema.sql');for(const x of ['loja_pedidos','loja_pedido_itens','loja_frete_por_km','loja_aceitar_retirada']){assert.match(m,new RegExp(x));assert.match(s,new RegExp(x))}});
