const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');

test('Marketing é recurso Premium e aparece nos planos/menu',()=>{const cat=read('backend/src/services/planCatalog.js'),menu=read('frontend/js/common.js'),ass=read('frontend/pages/assinatura.html');assert.match(cat,/premium[\s\S]*?'marketing'/);const pro=cat.slice(cat.indexOf('pro:Object'),cat.indexOf('premium:Object'));assert.doesNotMatch(pro,/'marketing'/);assert.match(menu,/groupHtml\('marketing'/);assert.match(menu,/marketing-campanhas/);assert.match(ass,/Marketing, campanhas, cupons e indicações/)});

test('Marketing possui áreas completas e UI sem prompt de navegador',()=>{const h=read('frontend/pages/marketing.html'),j=read('frontend/js/marketing.js'),css=read('frontend/style.css');for(const s of ['resumo','campanhas','publicos','cupons','indicacoes','links','modelos'])assert.match(j,new RegExp(`['\"]${s}['\"]`));assert.match(h,/marketingModal/);assert.doesNotMatch(j,/window\.prompt|\bprompt\(/);assert.match(css,/\.marketing-modal-box/);assert.match(css,/@media\(max-width:700px\)[\s\S]*marketing-modal-box/)});

test('schema Marketing é criado automaticamente no boot e migrate',()=>{const svc=read('backend/src/services/marketing.js'),server=read('backend/server.js'),mig=read('backend/migrar-banco.js'),schema=read('database/schema.sql');for(const t of ['marketing_modelos','marketing_cupons','marketing_campanhas','marketing_envios','marketing_links','marketing_cupom_usos','marketing_indicacoes_config','marketing_indicacao_codigos','marketing_indicacao_conversoes']){assert.match(svc,new RegExp(t));assert.match(schema,new RegExp(t))}assert.match(server,/ensureMarketingSchema\(\)/);assert.match(server,/processMarketingCampaigns\(2\)/);assert.match(mig,/ensureMarketingSchema\(client\)/)});

test('públicos dinâmicos exigem opt-in e incluem segmentos de agenda e loja',()=>{const svc=read('backend/src/services/marketing.js');assert.match(svc,/c\.barbearia_id=\$1 AND c\.marketing_opt_in=true/);for(const s of ['aniversariantes','novos','inativos','vip','frequentes','faltosos','compradores_loja','carrinho_abandonado'])assert.match(svc,new RegExp(`segmento==='${s}'`));assert.match(svc,/loja_pedidos[\s\S]*total_gasto/)});

test('consentimento promocional é explícito em cliente, agendamento e loja',()=>{const c=read('backend/src/routes/clientes.js'),pub=read('frontend/publico.html'),pj=read('frontend/js/publico.js'),store=read('frontend/loja.html'),sj=read('frontend/js/loja-publica.js'),svc=read('backend/src/services/storeCommerce.js');assert.match(c,/marketing_opt_in/);assert.match(pub,/marketingOptIn/);assert.match(pj,/marketing_opt_in/);assert.match(store,/storeMarketingOptIn/);assert.match(sj,/marketing_opt_in/);assert.match(svc,/marketing_opt_in_em/);assert.match(svc,/loja_checkout/)});

test('WhatsApp trata SAIR/PARAR e reautorização PROMOÇÕES',()=>{const wa=read('backend/src/services/whatsapp.js');assert.match(wa,/sair\|parar/);assert.match(wa,/marketing_opt_in=false/);assert.match(wa,/promoções\|promocoes/);assert.match(wa,/marketing_opt_in=true/);assert.match(wa,/Ainda não encontrei um cadastro/)});

test('campanhas usam template oficial, lotes, retry e step-up',()=>{const r=read('backend/src/routes/marketing.js'),svc=read('backend/src/services/marketing.js');assert.match(r,/campanhas\/:id\/agendar',exigirStepUp/);assert.match(svc,/claimCampaignBatch\(camp\.id,25\)/);assert.match(svc,/tentativas=COALESCE\(tentativas,0\)\+1/);assert.match(svc,/tentativas\|\|0\)>=3/);assert.match(svc,/sendTemplate\(/);assert.match(svc,/Nenhum provedor WhatsApp ativo/);assert.match(svc,/activeConnection/)});

test('webhook WhatsApp atualiza enviado, entregue e lido por message id',()=>{const r=read('backend/src/routes/whatsapp.js'),svc=read('backend/src/services/marketing.js');assert.match(r,/v\.statuses/);assert.match(r,/updateWhatsAppMarketingStatus/);assert.match(svc,/provider_message_id/);assert.match(svc,/status='lido'|mapped=s==='read'\?'lido'/);assert.match(svc,/entregue_em/);assert.match(svc,/lido_em/)});

test('links rastreáveis medem clique e conversão em agendamento e loja',()=>{const pub=read('backend/src/routes/marketingPublic.js'),svc=read('backend/src/services/marketing.js'),booking=read('backend/src/routes/publico.js'),store=read('backend/src/services/storeCommerce.js');assert.match(pub,/cliques=cliques\+1/);assert.match(pub,/\?mkt=/);assert.match(svc,/recordMarketingConversion/);assert.match(booking,/marketing_token/);assert.match(store,/marketing_token/);assert.match(booking,/revenue:0/);assert.match(store,/revenue:Number\(o\.total/)});

test('campanha pode criar botão URL dinâmico rastreável',()=>{const svc=read('backend/src/services/marketing.js'),wa=read('backend/src/services/whatsappProviders.js'),ui=read('frontend/js/marketing.js');assert.match(svc,/ensureCampaignLink/);assert.match(svc,/urlButtonParam:trackedLink\?\.token/);assert.match(wa,/sub_type:'url'/);assert.match(ui,/\/m\/\{\{1\}\}/)});

test('cupons têm validação server-side, validade e limites',()=>{const svc=read('backend/src/services/marketing.js'),store=read('backend/src/services/storeCommerce.js'),route=read('backend/src/routes/marketing.js');assert.match(svc,/limite_total/);assert.match(svc,/limite_por_cliente/);assert.match(svc,/pedido_minimo/);assert.match(svc,/desconto_maximo/);assert.match(store,/validateCoupon/);assert.match(route,/router\.post\('\/cupons',exigirStepUp/)});

test('indicações evitam autoindicação e geram recompensas automáticas',()=>{const svc=read('backend/src/services/marketing.js');assert.match(svc,/própria indicação|autoindicação|próprio código/i);assert.match(svc,/rewardCoupon/);assert.match(svc,/marketing_indicacao_conversoes/);assert.match(svc,/cupom_indicador_id/);assert.match(svc,/cupom_indicado_id/)});

test('rota Marketing tem isolamento, assinatura e rate limit público',()=>{const r=read('backend/src/routes/marketing.js'),app=read('backend/src/app.js');assert.match(r,/router\.use\(autenticar,exigirAssinatura,exigirPapel\('dono','gerente'\),exigirRecurso\('marketing'\)\)/);assert.match(r,/req\.usuario\.barbearia_id/);assert.match(app,/marketingLinkLimit/);assert.match(app,/MARKETING_LINK_RATE_LIMIT_PER_MINUTE/);assert.match(app,/app\.use\('\/m',marketingLinkLimit,marketingPublic\)/)});

test('verificador e auditoria conhecem os objetos críticos de Marketing',()=>{const v=read('backend/verificar.js'),a=read('backend/auditar-seguranca.js'),c=read('backend/check.js');assert.match(v,/marketing_campanhas/);assert.match(v,/ux_marketing_envio_provider_message/);assert.match(a,/Marketing exige plano compatível/);assert.match(c,/src\/services\/marketing\.js/)});
