const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');

test('menu lateral possui área dedicada de Pagamentos',()=>{const c=read('frontend/js/common.js');assert.match(c,/\['pagamentos','\/pages\/pagamentos\.html','💳','Pagamentos'/);const h=read('frontend/pages/pagamentos.html');assert.match(h,/<h1>Pagamentos<\/h1>/);assert.match(h,/Credenciais dos gateways/);assert.match(h,/Configuração do checkout/)});

test('aba Configurações não possui mais recebimentos ou gateways',()=>{const h=read('frontend/pages/configuracoes.html'),j=read('frontend/js/configuracoes.js');for(const term of ['Recebimentos','aceitar_mercadopago','pix_chave','pagamento_agendamento','conectarMP','mpStatus']){assert.doesNotMatch(h,new RegExp(term));assert.doesNotMatch(j,new RegExp(term))}});
test('API geral de Configurações também não lê nem grava campos de pagamento',()=>{const t=read('backend/src/routes/tenant.js');const block=t.slice(t.indexOf("router.get('/configuracoes'"),t.indexOf("router.get('/usuarios'"));for(const term of ['pagamento_agendamento','aceitar_mercadopago','pix_chave','percentual_sinal'])assert.doesNotMatch(block,new RegExp(term))});

test('catálogo prepara credenciais para Mercado Pago, PagBank, Asaas, Pagar.me e Stripe',()=>{const s=read('backend/src/services/paymentGateways.js');for(const g of ['mercadopago','pagbank','asaas','pagarme','stripe'])assert.match(s,new RegExp(`${g}:\\{`));for(const key of ['Access Token','Public Key','Token de autenticação','API Key','Secret Key','Publishable Key'])assert.match(s,new RegExp(key))});

test('gateways são configurados apenas por credenciais nesta etapa, sem OAuth no fluxo de Pagamentos',()=>{const r=read('backend/src/routes/pagamentos.js'),j=read('frontend/js/pagamentos.js'),a=read('backend/src/app.js');assert.match(r,/gateways\/:provedor\/credenciais/);assert.match(j,/\/pagamentos\/gateways\/\$\{currentGateway\.id\}\/credenciais/);assert.doesNotMatch(j,/mercadopago\/conectar|oauth|location\.href/);assert.doesNotMatch(r,/oauth\/:provedor|createOauthUrl|finishOauth/);assert.doesNotMatch(a,/app\.use\('\/api\/mercadopago',mercadoPagoConnect\)/)});

test('salvar credenciais exige dono e plano com pagamentos',()=>{const r=read('backend/src/routes/pagamentos.js');assert.match(r,/gateways\/:provedor\/credenciais'[\s\S]*exigirPapel\('dono'\)[\s\S]*exigirRecurso\('pagamentos_online'\)/);assert.match(r,/gateways\/:provedor'[\s\S]*exigirPapel\('dono'\)[\s\S]*exigirRecurso\('pagamentos_online'\)/)});

test('credenciais privadas são criptografadas e nunca retornam no status',()=>{const s=read('backend/src/services/paymentGateways.js');assert.match(s,/secretEnc=encrypt\(JSON\.stringify\(c\.secret\)\)/);assert.match(s,/accessTokenEnc=provedor==='mercadopago'\?encrypt\(c\.accessToken\):null/);const statusBlock=s.slice(s.indexOf('async function listGateways'),s.indexOf('async function tenantWebhookSecret'));assert.doesNotMatch(statusBlock,/(secret_enc|access_token_enc|refresh_token_enc)/);assert.match(s,/credenciais_salvas:saved/)});

test('Mercado Pago manual mantém Access Token separado para o driver de checkout existente',()=>{const s=read('backend/src/services/paymentGateways.js'),p=read('backend/src/routes/pagamentos.js');assert.match(s,/provedor==='mercadopago'\?'conectado':'credenciais_salvas'/);assert.match(s,/access_token_enc/);assert.match(p,/provedor='mercadopago' AND status='conectado' AND access_token_enc IS NOT NULL/)});

test('checkout e gateways ficam juntos na página Pagamentos',()=>{const h=read('frontend/pages/pagamentos.html');assert.match(h,/href="#gateways"/);assert.match(h,/href="#checkout"/);assert.match(h,/Gateway do checkout online/);assert.match(h,/Cobrança antecipada/);assert.match(h,/Aceitar Pix/);assert.match(h,/Aceitar cartão/);assert.match(h,/Aceitar dinheiro/)});

test('schema multi-gateway continua preparado automaticamente no boot',()=>{const s=read('backend/server.js'),g=read('backend/src/services/paymentGateways.js');assert.match(s,/ensurePaymentGatewaySchema/);assert.match(s,/await ensurePaymentGatewaySchema\(\)/);for(const c of ['provider_account_id','secret_enc','environment','metadata','capabilities','last_verified_at','last_error'])assert.match(g,new RegExp(`ADD COLUMN IF NOT EXISTS ${c}`))});
