const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');

test('menu lateral possui área dedicada de Pagamentos',()=>{const c=read('frontend/js/common.js');assert.match(c,/\['pagamentos','\/pages\/pagamentos\.html','💳','Pagamentos'/);const h=read('frontend/pages/pagamentos.html');assert.match(h,/<h1>Pagamentos<\/h1>/);assert.match(h,/Gateways de pagamento/)});
test('Mercado Pago pode ser conectado pelo dono via OAuth existente',()=>{const r=read('backend/src/routes/mercadoPagoConnect.js'),p=read('frontend/js/pagamentos.js');assert.match(r,/exigirPapel\('dono'\)/);assert.match(p,/\/mercadopago\/conectar/);assert.match(r,/pagamentos\.html\?gateway=mercadopago/)});
test('catálogo prepara Mercado Pago, PagBank, Asaas, Pagar.me e Stripe',()=>{const s=read('backend/src/services/paymentGateways.js');for(const g of ['mercadopago','pagbank','asaas','pagarme','stripe'])assert.match(s,new RegExp(`${g}:\\{`));assert.match(s,/checkout:true/);assert.match(s,/checkout:false/)});
test('segredos dos gateways manuais são criptografados e não retornam no status',()=>{const s=read('backend/src/services/paymentGateways.js');assert.match(s,/secret\?encrypt\(secret\):null/);assert.match(s,/accessToken\?encrypt\(accessToken\):null/);assert.doesNotMatch(s,/SELECT[^`]*(secret_enc|access_token_enc|refresh_token_enc)[^`]*FROM integracoes_pagamento WHERE barbearia_id=\$1/)});
test('conectar e desconectar gateways exige dono e plano de pagamentos',()=>{const r=read('backend/src/routes/pagamentos.js');assert.match(r,/gateways\/asaas\/conectar'[\s\S]*exigirPapel\('dono'\)[\s\S]*exigirRecurso\('pagamentos_online'\)/);assert.match(r,/gateways\/pagarme\/conectar'[\s\S]*exigirPapel\('dono'\)[\s\S]*exigirRecurso\('pagamentos_online'\)/);assert.match(r,/gateways\/:provedor'[\s\S]*exigirPapel\('dono'\)[\s\S]*exigirRecurso\('pagamentos_online'\)/)});
test('Asaas e Pagar.me validam credenciais com chamadas somente leitura',()=>{const s=read('backend/src/services/paymentGateways.js');assert.match(s,/myAccount\/accountNumber/);assert.match(s,/core\/v5\/subscriptions\?size=1/);assert.match(s,/signal:externalSignal\(\)/)});
test('PagBank e Stripe usam OAuth com state por tenant',()=>{const s=read('backend/src/services/paymentGateways.js');assert.match(s,/connect\.pagbank\.com\.br\/oauth2\/authorize/);assert.match(s,/connect\.stripe\.com\/oauth\/authorize/);assert.match(s,/oauth_states\(barbearia_id,state,code_verifier,provedor,expira_em\)/);assert.match(s,/consumeOauthState\(state,provedor\)/)});
test('schema multi-gateway é preparado automaticamente no boot',()=>{const s=read('backend/server.js'),g=read('backend/src/services/paymentGateways.js');assert.match(s,/ensurePaymentGatewaySchema/);assert.match(s,/await ensurePaymentGatewaySchema\(\)/);for(const c of ['provider_account_id','secret_enc','environment','metadata','capabilities','last_verified_at','last_error'])assert.match(g,new RegExp(`ADD COLUMN IF NOT EXISTS ${c}`))});
test('tela deixa transparente que apenas Mercado Pago possui driver de checkout nesta versão',()=>{const h=read('frontend/pages/pagamentos.html'),j=read('frontend/js/pagamentos.js');assert.match(h,/motor de checkout online já usa Mercado Pago/);assert.match(j,/Conexão pronta • cobrança em próxima etapa/)});
