const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const front=path.resolve(root,'../frontend');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');

test('CTA de planos tenta migrar assinatura recorrente e abre checkout quando necessário',()=>{const s=fs.readFileSync(path.join(front,'js/assinatura.js'),'utf8');assert.match(s,/\/assinatura\/migrar/);assert.match(s,/requires_checkout/);assert.match(s,/openCheckout/)});
test('checkout de assinatura usa Mercado Pago externo para cartão e Pix interno',()=>{const h=fs.readFileSync(path.join(front,'pages/assinatura.html'),'utf8');assert.match(h,/id="payMethodCard"/);assert.match(h,/id="payMethodPix"/);assert.match(h,/id="openMercadoPagoCard"/);assert.match(h,/checkout oficial do Mercado Pago/i);assert.match(h,/pixQrImage/);assert.match(h,/pixCopyCode/);assert.doesNotMatch(h,/cardPaymentBrick_container|sdk\.mercadopago\.com\/js\/v2/)});
test('cartão da assinatura redireciona para checkout oficial e não coleta dados no frontend',()=>{const f=fs.readFileSync(path.join(front,'js/assinatura.js'),'utf8');const t=read('src/routes/tenant.js');const mp=read('src/services/mercadoPago.js');assert.match(f,/api\('\/assinatura\/checkout'/);assert.match(f,/window\.location\.assign\(r\.checkout_url\)/);assert.doesNotMatch(f,/formData\.token|cardPaymentBrick|MercadoPago\(/);assert.match(mp,/status:\s*'pending'/);assert.doesNotMatch(mp,/card_token_id/);assert.match(t,/checkoutUrl=checkoutUrlAssinatura\(mp\)/);assert.match(t,/CARTAO_CHECKOUT_EXTERNO/)});
test('Pix da assinatura retorna QR base64 e copia e cola',()=>{const t=read('src/routes/tenant.js');const mp=read('src/services/mercadoPago.js');assert.match(t,/qr_code_base64/);assert.match(t,/qr_code:/);assert.match(mp,/payment_method_id:'pix'/);assert.match(mp,/date_of_expiration/)});
test('Pix SaaS é isolado por tenant e valida valor antes de ativar',()=>{const s=read('src/services/subscriptionPayments.js');assert.match(s,/expectedTenantId/);assert.match(s,/barberflow-subscription-pix/);assert.match(s,/Math\.abs\(amount-Number\(row\.valor\)\)>0\.01/);assert.match(s,/WHERE id=\$1 AND barbearia_id=\$2 FOR UPDATE/)});
test('migração recorrente atualiza preapproval existente em vez de criar segunda assinatura',()=>{const t=read('src/routes/tenant.js');const mp=read('src/services/mercadoPago.js');assert.match(t,/active|status==='ativa'/i);assert.match(t,/atualizarPlanoAssinatura/);assert.match(mp,/PUT/);assert.match(mp,/auto_recurring:\{frequency:r\.frequency,frequency_type:r\.frequency_type,transaction_amount:precoPlano\(plano,r\.ciclo\),currency_id:'BRL'\}/)});
test('downgrade respeita limite de profissionais no servidor',()=>{const t=read('src/routes/tenant.js');assert.match(t,/validarLimitePlano/);assert.match(t,/COUNT\(\*\)::int n FROM barbeiros WHERE barbearia_id=\$1 AND ativo=true/);assert.match(t,/LIMITE_PROFISSIONAIS/)});
test('Pix pré-pago vencido não continua ativo indefinidamente',()=>{const s=read('src/services/planos.js');assert.match(s,/pixPrePagoExpirado/);assert.match(s,/a\.provedor!==['"]mercadopago_pix['"]/);assert.match(s,/proxima_cobranca/);assert.match(s,/ctx\.ativa/)});
test('Pix pendente válido é reutilizado e não cria cobrança paralela',()=>{const t=read('src/routes/tenant.js');assert.match(t,/status IN \('criando','pendente'\) AND expira_em>NOW\(\)/);assert.match(t,/reutilizado:true/);assert.match(t,/qr_code_base64/)});
test('Pix cancelado limpa mudança de plano pendente',()=>{const s=read('src/services/subscriptionPayments.js');assert.match(s,/if\(status==='cancelado'\)/);assert.match(s,/plano_pendente=NULL,billing_change_pending=false/)});

test('CSP não precisa liberar SDK ou Secure Fields porque cartão usa checkout externo',()=>{const app=read('src/app.js');assert.doesNotMatch(app,/sdk\.mercadopago\.com|secure-fields\.mercadopago\.com/);assert.match(app,/frameSrc:\['https:\/\/challenges\.cloudflare\.com'\]/)});
test('checkout externo de cartão evita cliques concorrentes e reutiliza assinatura pendente',()=>{const f=fs.readFileSync(path.join(front,'js/assinatura.js'),'utf8');const h=fs.readFileSync(path.join(front,'pages/assinatura.html'),'utf8');const t=read('src/routes/tenant.js');assert.match(h,/id="openMercadoPagoCard"/);assert.match(f,/cardRedirecting/);assert.match(f,/Preparando o checkout seguro do Mercado Pago/);assert.match(t,/reutilizado:true/);assert.match(t,/Continue a assinatura no checkout seguro do Mercado Pago/)});
