if(currentUser().papel==='super_admin'){location.href='/master.html'}else if(requireAuth()){
  document.getElementById('shell').innerHTML=renderShell('dashboard');
  const u=currentUser(),role=u.papel;document.body.dataset.role=role;
  const E=id=>document.getElementById(id),phoneDigits=v=>String(v||'').replace(/\D/g,''),waHref=x=>{let p=phoneDigits(x.telefone);if(p.length===10||p.length===11)p='55'+p;return `https://wa.me/${p}`};
  const firstName=String(u.nome||'').trim().split(/\s+/)[0]||'Usuário';
  const hour=new Date().getHours(),hello=hour<12?'Bom dia':hour<18?'Boa tarde':'Boa noite';
  E('greeting').textContent=`${hello}, ${firstName}! 👋`;
  E('mobileGreeting').textContent=`Olá, ${firstName}`;
  E('mobileOwnerAvatar').innerHTML=userAvatarHtml(u,'mobile-owner');
  const roleCopy={dono:'Aqui está o resumo da sua barbearia hoje.',gerente:'Acompanhe equipe, agenda, caixa e crescimento da barbearia.',recepcao:'Organize a recepção e mantenha o atendimento em dia.',barbeiro:'Sua agenda e seus próximos clientes hoje.'};
  E('dashboardSubtitle').textContent=roleCopy[role]||'Aqui está sua operação hoje.';
  const setIcon=(id,name)=>{const el=E(id);if(el)el.innerHTML=iconSVG(name,20)};
  setIcon('kpiCalendar','calendar');setIcon('kpiRevenue','wallet');setIcon('kpiTicket','users');setIcon('kpiOccupancy','chart');setIcon('dashboardPixIcon','wallet');
  if(role==='barbeiro'){E('dashboardPrimaryAction').href='/pages/agendamentos.html';E('dashboardPrimaryAction').textContent='Minha agenda'}

  const initials=name=>String(name||'BF').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
  const avatar=(name,url,cls='')=>{const safe=safeClientUrl(url);return `<span class="bf-data-avatar ${cls}">${safe?`<img src="${esc(safe)}" alt="${esc(name||'Profissional')}">`:`<span>${esc(initials(name))}</span>`}</span>`};
  function sparkline(values){const nums=(values||[]).map(x=>Number(x?.total ?? x ?? 0)),w=92,h=30,p=2,max=Math.max(1,...nums),min=Math.min(0,...nums),range=Math.max(1,max-min);if(!nums.length)return '';const pts=nums.map((v,i)=>`${p+(i*(w-p*2)/Math.max(1,nums.length-1))},${h-p-((v-min)/range)*(h-p*2)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><polyline points="${pts}"/></svg>`}
  function compactMoney(v){const n=Number(v||0);return n>=1000?`R$ ${(n/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})}k`:money(n)}

  function renderMobileStatus(d){
    const r=d.resumo||{},items=[['Aguardando',r.aguardando_confirmacao||0,'waiting'],['Confirmados',r.confirmados_hoje||0,'confirmed'],['Atendendo',r.em_atendimento_hoje||0,'serving'],['Concluídos',r.concluidos_hoje||0,'done']];
    E('mobileStatusGrid').innerHTML=items.map(([label,value,state])=>`<article class="mobile-status-item ${state}"><i></i><strong>${Number(value)||0}</strong><span>${label}</span></article>`).join('');
    const late=Number(r.atrasados_hoje||0),waiting=Number(r.aguardando_confirmacao||0),serving=Number(r.em_atendimento_hoje||0),alert=E('mobileOperationAlert');
    if(late){alert.className='mobile-operation-alert danger';alert.innerHTML=`<strong>${late} ${late===1?'atendimento atrasado':'atendimentos atrasados'}</strong><span>Abra a agenda para reorganizar o atendimento.</span>`}
    else if(waiting){alert.className='mobile-operation-alert warning';alert.innerHTML=`<strong>${waiting} ${waiting===1?'confirmação pendente':'confirmações pendentes'}</strong><span>Confirme os próximos clientes para reduzir faltas.</span>`}
    else if(serving){alert.className='mobile-operation-alert success';alert.innerHTML=`<strong>${serving} em atendimento agora</strong><span>A operação está fluindo normalmente.</span>`}
    else{alert.className='mobile-operation-alert neutral';alert.innerHTML='<strong>Operação em dia</strong><span>Nenhuma pendência urgente neste momento.</span>'}
  }

  function renderMobileHighlights(d){
    const r=d.resumo||{};let title='Indicadores importantes',items=[];
    if(['dono','gerente'].includes(role)){title='Saúde do negócio';items=[['Faturamento no mês',compactMoney(r.faturamento_mes||0),'Consolidado'],['Previsto hoje',compactMoney(r.receita_prevista_hoje||0),'Agenda ativa'],['Ocupação',`${Number(r.ocupacao_hoje||0)}%`,'Capacidade da equipe']]}
    else if(role==='recepcao'){title='Estrutura da recepção';items=[['Clientes',Number(r.clientes||0),'Cadastrados'],['Profissionais',Number(r.barbeiros||0),'Ativos'],['Serviços',Number(r.servicos||0),'Disponíveis']]}
    else{title='Meu desempenho';items=[['Comissão hoje',compactMoney(r.comissao_hoje||0),'Concluídos'],['Comissão no mês',compactMoney(r.comissao_mes||0),'Acumulada'],['Minha ocupação',`${Number(r.ocupacao_hoje||0)}%`,'Agenda de hoje']]}
    E('mobileHighlightsTitle').textContent=title;E('mobileRoleHighlights').innerHTML=items.map(([label,value,hint])=>`<article><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(hint)}</small></article>`).join('');
  }

  function renderMobileWeek(d){
    const items=d.tendencias?.agendamentos||[],values=items.map(x=>Number(x.total||0)),max=Math.max(1,...values),total=values.reduce((sum,x)=>sum+x,0);E('mobileWeekTotal').textContent=`${total} agend.`;
    E('mobileWeekChart').innerHTML=items.length?items.map((x,i)=>`<div class="mobile-week-day"><b>${values[i]}</b><div><i style="height:${Math.max(5,Math.round(values[i]*100/max))}%"></i></div><span>${esc(x.label||'')}</span></div>`).join(''):'<div class="mobile-home-empty">Sem movimento registrado nesta semana.</div>';
  }

  function renderMobileUpcoming(d){
    const rows=(d.proximos||[]).slice(0,4);E('mobileUpcomingList').innerHTML=rows.length?rows.map(x=>`<a class="mobile-upcoming-row" href="/pages/agendamentos.html"><div class="mobile-upcoming-time"><strong>${timeBR(x.horario)}</strong><span>${dateBR(x.data)}</span></div>${avatar(x.barbeiro,x.barbeiro_foto,'mobile-upcoming')}<div class="mobile-upcoming-copy"><strong>${esc(x.cliente||'Cliente')}</strong><span>${esc(x.servico||'Serviço')} · ${role==='barbeiro'?'Você':esc(x.barbeiro||'Profissional')}</span></div><b class="mobile-upcoming-status status-${esc(x.status)}">${esc(String(x.status||'agendado').replaceAll('_',' '))}</b></a>`).join(''):'<div class="mobile-home-empty"><strong>Agenda livre</strong><span>Nenhum próximo atendimento marcado.</span></div>';
  }

  function appointmentCard(x){return `<article class="premium-appointment-row"><div class="premium-appointment-time"><strong>${timeBR(x.horario)}</strong><span>${Number(x.duracao||0)}min</span></div>${avatar(x.barbeiro,x.barbeiro_foto,'appointment')}<div class="premium-appointment-client"><strong>${esc(x.cliente)}</strong><span>${esc(x.servico||'Serviço')}</span></div><div class="premium-appointment-barber">${role==='barbeiro'?'Você':esc(x.barbeiro||'')}</div><span class="premium-status status-${esc(x.status)}">${esc(String(x.status||'').replaceAll('_',' '))}</span><a class="appointment-wa" href="${waHref(x)}" target="_blank" rel="noopener" aria-label="WhatsApp de ${esc(x.cliente)}">${iconSVG('whatsapp',17)}</a></article>`}
  function mobileActions(){const items=role==='barbeiro'?[['/pages/agendamentos.html','calendar','Minha agenda'],['/pages/suporte.html','support','Suporte']]:role==='recepcao'?[['/pages/agendamentos.html','calendar','Agenda'],['/pages/clientes.html','users','Clientes'],['/pages/gestao.html?secao=comandas','clipboard','Comandas'],['/pages/suporte.html','support','Suporte']]:[['/pages/agendamentos.html','calendar','Agenda'],['/pages/clientes.html','users','Clientes'],['/pages/servicos.html','scissors','Serviços'],['/pages/financeiro.html','wallet','Financeiro'],['/pages/gestao.html?secao=relatorios','chart','Relatórios'],['/pages/automacoes.html','whatsapp','WhatsApp']];E('mobileActionGrid').innerHTML=items.map(([href,ic,label])=>`<a href="${href}">${iconSVG(ic,22)}<span>${label}</span></a>`).join('')}
  mobileActions();

  const canApprovePix=['dono','gerente','recepcao'].includes(role),pixPanel=E('dashboardPixApprovals'),pixList=E('dashboardPixList'),pixCount=E('dashboardPixCount'),pixModal=E('dashboardPixModal'),pixModalDetails=E('dashboardPixModalDetails'),pixModalFeedback=E('dashboardPixModalFeedback'),pixModalConfirm=E('dashboardPixModalConfirm'),pixModalCancel=E('dashboardPixModalCancel'),pixModalClose=E('dashboardPixModalClose');
  let pendingPixRows=[],selectedPendingPix=null;
  function pendingPixRow(x){return `<article class="dashboard-pix-row"><div class="dashboard-pix-person"><span class="dashboard-pix-avatar">${esc(initials(x.nome))}</span><div><strong>${esc(x.nome||'Cliente')}</strong><small>${esc(x.telefone||'')}</small></div></div><div class="dashboard-pix-service"><span>${esc(x.servico||'Serviço')}</span><small>com ${esc(x.barbeiro||'Profissional')}</small></div><div class="dashboard-pix-when"><strong>${dateBR(x.data)}</strong><small>${timeBR(x.horario)}</small></div><div class="dashboard-pix-value"><span>Valor recebido</span><strong>${money(x.valor_cobrado)}</strong></div><button class="btn btn-primary dashboard-pix-confirm-btn" type="button" data-dashboard-pix="${Number(x.id)}">Confirmar Pix</button></article>`}
  function closePixModal(){if(!pixModal)return;pixModal.classList.add('hidden');document.body.classList.remove('modal-open');selectedPendingPix=null;pixModalFeedback.className='notice hidden';pixModalFeedback.textContent='';pixModalConfirm.disabled=false;pixModalConfirm.textContent='Confirmar Pix recebido';pixModalCancel.classList.remove('hidden')}
  function openPixModal(id){const x=pendingPixRows.find(row=>Number(row.id)===Number(id));if(!x)return;selectedPendingPix=x;pixModalDetails.innerHTML=`<div><span>Cliente</span><strong>${esc(x.nome||'Cliente')}</strong></div><div><span>Serviço</span><strong>${esc(x.servico||'Serviço')}</strong></div><div><span>Profissional</span><strong>${esc(x.barbeiro||'Profissional')}</strong></div><div><span>Data e horário</span><strong>${dateBR(x.data)} às ${timeBR(x.horario)}</strong></div><div class="dashboard-pix-modal-value"><span>Valor a conferir</span><strong>${money(x.valor_cobrado)}</strong></div>`;pixModalFeedback.className='notice hidden';pixModalFeedback.textContent='';pixModalConfirm.disabled=false;pixModalConfirm.textContent='Confirmar Pix recebido';pixModalCancel.classList.remove('hidden');pixModal.classList.remove('hidden');document.body.classList.add('modal-open');pixModalConfirm.focus()}
  function whatsappFailureText(reason){return ({whatsapp_not_connected:'WhatsApp não conectado',invalid_phone:'telefone do cliente inválido',not_found:'agendamento não encontrado'})[String(reason||'')]||'não foi possível entregar a mensagem'}
  async function confirmSelectedPix(){if(!selectedPendingPix)return;const id=selectedPendingPix.id;try{pixModalConfirm.disabled=true;pixModalConfirm.textContent='Confirmando…';const r=await api(`/pagamentos-pendentes/${id}/confirmar`,{method:'POST'});if(r.whatsapp_enviado===true){pixModalFeedback.className='notice success';pixModalFeedback.innerHTML='<strong>Pagamento aprovado.</strong> Agendamento criado e confirmação enviada ao cliente pelo WhatsApp.'}else if(r.whatsapp_enviado===false){pixModalFeedback.className='notice warning';pixModalFeedback.innerHTML=`<strong>Agendamento criado.</strong> A confirmação não foi enviada automaticamente: ${esc(whatsappFailureText(r.whatsapp_motivo))}.` }else{pixModalFeedback.className='notice success';pixModalFeedback.textContent=r.mensagem||'Pagamento já estava confirmado.'}pixModalConfirm.textContent='Concluído';pixModalCancel.textContent='Fechar';pixModalCancel.classList.remove('hidden');await loadPendingPixDashboard()}catch(e){pixModalFeedback.className='notice error';pixModalFeedback.textContent=e.message;pixModalConfirm.disabled=false;pixModalConfirm.textContent='Tentar novamente'}}
  async function loadPendingPixDashboard(){if(!canApprovePix||!pixPanel)return;pixPanel.classList.remove('hidden');try{pendingPixRows=await api('/pagamentos-pendentes');pixCount.textContent=String(pendingPixRows.length);pixCount.setAttribute('aria-label',`${pendingPixRows.length} pagamentos aguardando aprovação`);pixPanel.classList.toggle('has-pending',pendingPixRows.length>0);pixList.innerHTML=pendingPixRows.length?pendingPixRows.map(pendingPixRow).join(''):'<div class="dashboard-pix-empty"><strong>Nenhum Pix aguardando aprovação</strong><span>Quando um cliente escolher Pix manual, a reserva aparecerá aqui para conferência.</span></div>';pixList.querySelectorAll('[data-dashboard-pix]').forEach(btn=>btn.addEventListener('click',()=>openPixModal(btn.dataset.dashboardPix)))}catch(e){pixList.innerHTML=`<div class="dashboard-pix-empty error"><strong>Não foi possível carregar os pagamentos</strong><span>${esc(e.message)}</span></div>`}}
  E('dashboardPixRefresh')?.addEventListener('click',loadPendingPixDashboard);pixModalConfirm?.addEventListener('click',confirmSelectedPix);pixModalCancel?.addEventListener('click',closePixModal);pixModalClose?.addEventListener('click',closePixModal);pixModal?.addEventListener('click',e=>{if(e.target===pixModal)closePixModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pixModal&&!pixModal.classList.contains('hidden'))closePixModal()});

  async function loadOnboarding(){if(!['dono','gerente'].includes(role))return;try{const o=await api('/onboarding'),panel=E('onboardingPanel');if(!panel)return;panel.classList.toggle('hidden',o.completo);E('onboardingPercent').textContent=`${o.progresso}%`;E('onboardingCount').textContent=`${o.concluidas}/${o.total}`;E('onboardingBar').style.width=`${o.progresso}%`;E('onboardingPublic').href=o.public_url;E('onboardingSteps').innerHTML=o.steps.map((x,i)=>`<a class="onboarding-step ${x.concluido?'done':''}" href="${esc(x.href)}" ${x.id==='publicar'?'target="_blank" rel="noopener"':''}><span class="onboarding-step-num">${x.concluido?'✓':i+1}</span><div><strong>${esc(x.titulo)}</strong><small>${esc(x.descricao)}</small></div><b>→</b></a>`).join('');E('onboardingShared').disabled=!!o.steps.find(x=>x.id==='publicar')?.concluido;E('onboardingShared').textContent=E('onboardingShared').disabled?'Link compartilhado ✓':'Já compartilhei o link'}catch(e){console.error('onboarding',e)}}
  E('onboardingShared')?.addEventListener('click',async()=>{try{await api('/onboarding/link-compartilhado',{method:'POST'});await loadOnboarding()}catch(e){console.error(e)}});

  function renderRevenueChart(state){
    const items=state?.series?.diario||[],chart=E('dashboardRevenueChart');
    if(!items.length){chart.innerHTML='<div class="premium-empty">Sem faturamento registrado nos últimos 7 dias.</div>';E('sparkRevenue').innerHTML='';E('revSemana').textContent=money(state?.totais?.semana||0);return}
    const values=items.map(x=>Number(x.total||0)),max=Math.max(1,...values),week=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
    const labels=items.map((x,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(items.length-1-i));return week[d.getDay()]});
    chart.innerHTML=`<div class="premium-bar-chart" role="img" aria-label="Faturamento dos últimos 7 dias">${items.map((x,i)=>{const v=values[i],height=Math.max(3,Math.round(v/max*100));return `<div class="premium-bar-item"><b class="premium-bar-value">${v?esc(compactMoney(v)):''}</b><div class="premium-bar-track"><i style="height:${height}%" title="${esc(labels[i])} — ${money(v)}"></i></div><span>${esc(labels[i])}</span></div>`}).join('')}</div>`;
    E('sparkRevenue').innerHTML=sparkline(items);E('revSemana').textContent=money(state?.totais?.semana||0)
  }

  function renderBarberPerformance(state){const rows=state?.barbeiros||[],max=Math.max(1,...rows.map(x=>Number(x.total||0)));E('barberPerformance').innerHTML=rows.length?rows.slice(0,5).map((x,i)=>{const total=Number(x.total||0),pct=Math.max(4,total/max*100);return `<div class="barber-performance-row">${avatar(x.nome,x.foto_url,'performance')}<strong>${esc(x.nome)}</strong><div class="barber-performance-track"><i style="width:${pct}%"></i></div><b>${money(total)}</b><span>${i===0&&total>0?'+ destaque':''}</span></div>`}).join(''):'<div class="premium-empty">Os resultados dos barbeiros aparecerão após os primeiros atendimentos concluídos.</div>'}

  function applyRoleMetrics(d,revenue){const r=d.resumo||{};if(['dono','gerente'].includes(role)){E('aHoje').textContent=r.agendamentos_hoje||0;E('receitaHoje').textContent=money(revenue?.totais?.hoje??r.faturamento_hoje);E('ticketMedio').textContent=r.clientes||0;E('ocupacaoHoje').textContent=`${r.ocupacao_hoje||0}%`;E('agendaHint').textContent='Atendimentos programados';E('receitaHint').textContent='Faturamento consolidado hoje';E('ticketHint').textContent='Clientes cadastrados';E('ocupacaoHint').textContent='Capacidade da equipe';E('sparkAppointments').innerHTML=sparkline(d.tendencias?.agendamentos);E('sparkClients').innerHTML=sparkline(d.tendencias?.clientes);E('occupancyRing').style.setProperty('--pct',`${Math.max(0,Math.min(100,Number(r.ocupacao_hoje||0)))}%`)}else if(role==='recepcao'){E('aHoje').textContent=r.agendamentos_hoje||0;E('receitaHoje').textContent=r.confirmados_hoje||0;E('kpiRevenueLabel').textContent='Confirmados';E('ticketMedio').textContent=r.em_atendimento_hoje||0;E('kpiTicketLabel').textContent='Em atendimento';E('ocupacaoHoje').textContent=r.atrasados_hoje||0;E('kpiOccupancyLabel').textContent='Atrasados';E('sparkAppointments').innerHTML=sparkline(d.tendencias?.agendamentos)}else{const next=d.proximos?.[0];E('aHoje').textContent=r.agendamentos_hoje||0;E('receitaHoje').textContent=next?timeBR(next.horario):'—';E('kpiRevenueLabel').textContent='Próximo horário';E('ticketMedio').textContent=r.concluidos_hoje||0;E('kpiTicketLabel').textContent='Concluídos';E('ocupacaoHoje').textContent=money(r.comissao_hoje||0);E('kpiOccupancyLabel').textContent='Comissão hoje';E('sparkAppointments').innerHTML=sparkline(d.tendencias?.agendamentos)}}

  (async()=>{try{
    const [d,revenue]=await Promise.all([api('/dashboard'),['dono','gerente'].includes(role)&&hasFeature('financeiro_basico')?api('/financeiro/dashboard').catch(()=>null):Promise.resolve(null)]);
    applyRoleMetrics(d,revenue);
    E('proximosCards').innerHTML=d.proximos?.length?d.proximos.map(appointmentCard).join(''):`<div class="premium-empty"><strong>Agenda livre</strong><span>Nenhum próximo atendimento neste momento.</span></div>`;
    const next=d.proximos?.[0];if(next){E('mobileNextTime').textContent=`Hoje • ${timeBR(next.horario)}`;E('mobileNextClient').textContent=`${next.cliente} · ${next.servico}`}else{E('mobileNextTime').textContent='Agenda livre';E('mobileNextClient').textContent='Nenhum cliente próximo.'}
    E('mobileSummaryAppointments').textContent=d.resumo?.agendamentos_hoje||0;
    if(role==='recepcao'){E('mobileSummaryClients').textContent=d.resumo?.confirmados_hoje||0;E('mobileSummarySecondLabel').textContent='Confirmados';E('mobileSummaryRevenue').textContent=d.resumo?.atrasados_hoje||0;E('mobileSummaryThirdLabel').textContent='Atrasados'}
    else if(role==='barbeiro'){E('mobileSummaryClients').textContent=d.resumo?.concluidos_hoje||0;E('mobileSummarySecondLabel').textContent='Concluídos';E('mobileSummaryRevenue').textContent=money(d.resumo?.comissao_hoje||0);E('mobileSummaryThirdLabel').textContent='Comissão'}
    else{E('mobileSummaryClients').textContent=d.resumo?.clientes||0;E('mobileSummaryRevenue').textContent=compactMoney((revenue?.totais?.hoje ?? d.resumo?.faturamento_hoje ?? 0))}
    renderMobileStatus(d);renderMobileHighlights(d);renderMobileWeek(d);renderMobileUpcoming(d);
    if(revenue){renderRevenueChart(revenue);renderBarberPerformance(revenue)}else{E('dashboardRevenue').classList.add('dashboard-no-finance');E('barberPerformance').innerHTML='<div class="premium-empty">Dados financeiros disponíveis para gestão.</div>'}
    await Promise.all([loadOnboarding(),loadPendingPixDashboard()]);
  }catch(e){console.error('dashboard',e)}})();
}
