require('dotenv').config(); const bcrypt=require('bcryptjs'); const pool=require('./src/config/db');
async function main(){const client=await pool.connect();try{await client.query('BEGIN');
await client.query(`CREATE TABLE IF NOT EXISTS barbearias(id SERIAL PRIMARY KEY,nome VARCHAR(120) NOT NULL,slug VARCHAR(120) UNIQUE NOT NULL,telefone VARCHAR(30),email VARCHAR(160),endereco VARCHAR(200),cidade VARCHAR(100),estado VARCHAR(2),logo_url TEXT,cor_primaria VARCHAR(20) DEFAULT '#f59e0b',ativo BOOLEAN DEFAULT true,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS usuarios(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,email VARCHAR(160) UNIQUE NOT NULL,senha_hash TEXT NOT NULL,papel VARCHAR(30) DEFAULT 'recepcao',ativo BOOLEAN DEFAULT true,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS assinaturas(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id),plano VARCHAR(30) DEFAULT 'pro',status VARCHAR(30) DEFAULT 'trial',inicio DATE DEFAULT CURRENT_DATE,fim_trial DATE,proxima_cobranca DATE,provedor VARCHAR(40),referencia_externa TEXT,checkout_url TEXT,provedor_status VARCHAR(40),atualizado_em TIMESTAMP DEFAULT NOW(),criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS password_resets(id SERIAL PRIMARY KEY,usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,token_hash TEXT NOT NULL,expira_em TIMESTAMP NOT NULL,usado BOOLEAN DEFAULT false,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS clientes(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,telefone VARCHAR(30) NOT NULL,email VARCHAR(160),observacoes TEXT,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS barbeiros(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,telefone VARCHAR(30),ativo BOOLEAN DEFAULT true)`);
await client.query(`CREATE TABLE IF NOT EXISTS servicos(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,duracao INTEGER NOT NULL,preco NUMERIC(10,2) DEFAULT 0,ativo BOOLEAN DEFAULT true)`);
await client.query(`CREATE TABLE IF NOT EXISTS horarios_trabalho(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),barbeiro_id INTEGER NOT NULL REFERENCES barbeiros(id) ON DELETE CASCADE,dia_semana INTEGER NOT NULL,hora_inicio TIME NOT NULL,hora_fim TIME NOT NULL)`);
await client.query(`CREATE TABLE IF NOT EXISTS agendamentos(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),cliente_id INTEGER NOT NULL REFERENCES clientes(id),barbeiro_id INTEGER NOT NULL REFERENCES barbeiros(id),servico_id INTEGER NOT NULL REFERENCES servicos(id),data DATE NOT NULL,horario TIME NOT NULL,status VARCHAR(30) DEFAULT 'agendado',observacoes TEXT,origem VARCHAR(30) DEFAULT 'painel',criado_em TIMESTAMP DEFAULT NOW())`);
const extras=[['clientes','barbearia_id','INTEGER'],['clientes','email','VARCHAR(160)'],['clientes','observacoes','TEXT'],['clientes','criado_em','TIMESTAMP DEFAULT NOW()'],['barbeiros','barbearia_id','INTEGER'],['barbeiros','telefone','VARCHAR(30)'],['barbeiros','ativo','BOOLEAN DEFAULT true'],['servicos','barbearia_id','INTEGER'],['servicos','preco','NUMERIC(10,2) DEFAULT 0'],['servicos','ativo','BOOLEAN DEFAULT true'],['horarios_trabalho','barbearia_id','INTEGER'],['agendamentos','barbearia_id','INTEGER'],['agendamentos','status',"VARCHAR(30) DEFAULT 'agendado'"],['agendamentos','observacoes','TEXT'],['agendamentos','origem',"VARCHAR(30) DEFAULT 'painel'"],['agendamentos','criado_em','TIMESTAMP DEFAULT NOW()'],['usuarios','barbeiro_id','INTEGER'],['assinaturas','checkout_url','TEXT'],['assinaturas','provedor_status','VARCHAR(40)'],['assinaturas','atualizado_em','TIMESTAMP DEFAULT NOW()']];for(const[t,c,ty]of extras)await client.query(`ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS ${c} ${ty}`);
let t=await client.query(`SELECT * FROM barbearias ORDER BY id LIMIT 1`);if(!t.rowCount)t=await client.query(`INSERT INTO barbearias(nome,slug,ativo) VALUES('Barbearia Demo','barbearia-demo',true) RETURNING *`);const tid=t.rows[0].id;for(const table of ['clientes','barbeiros','servicos','horarios_trabalho','agendamentos'])await client.query(`UPDATE ${table} SET barbearia_id=$1 WHERE barbearia_id IS NULL`,[tid]);
await client.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_usuarios_barbeiro') THEN ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_barbeiro FOREIGN KEY (barbeiro_id) REFERENCES barbeiros(id) ON DELETE SET NULL; END IF; END $$`);await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS ux_usuarios_barbeiro ON usuarios(barbearia_id,barbeiro_id) WHERE barbeiro_id IS NOT NULL`);await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS ux_horario_tenant_dia ON horarios_trabalho(barbearia_id,barbeiro_id,dia_semana)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_agenda_tenant_data ON agendamentos(barbearia_id,data,barbeiro_id)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_clientes_tenant_nome ON clientes(barbearia_id,nome)`);
if(!(await client.query(`SELECT 1 FROM assinaturas WHERE barbearia_id=$1`,[tid])).rowCount)await client.query(`INSERT INTO assinaturas(barbearia_id,plano,status,inicio,fim_trial) VALUES($1,'pro','trial',CURRENT_DATE,CURRENT_DATE+INTERVAL '14 days')`,[tid]);
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'admin@barberflow.local';if(!(await client.query(`SELECT 1 FROM usuarios WHERE LOWER(email)=LOWER($1)`,[email])).rowCount){const senha=process.env.BOOTSTRAP_ADMIN_PASSWORD||'TroqueEstaSenha123!';const hash=await bcrypt.hash(senha,12);await client.query(`INSERT INTO usuarios(barbearia_id,nome,email,senha_hash,papel,ativo) VALUES($1,'Administrador',$2,$3,'dono',true)`,[tid,email,hash]);console.log(`Usuário inicial: ${email}`);console.log('Senha inicial: valor de BOOTSTRAP_ADMIN_PASSWORD do .env');}
const masterEmail=process.env.MASTER_ADMIN_EMAIL;const masterPassword=process.env.MASTER_ADMIN_PASSWORD;if(masterEmail&&masterPassword){if(masterPassword.length<12)throw new Error('MASTER_ADMIN_PASSWORD deve ter pelo menos 12 caracteres');const mh=await bcrypt.hash(masterPassword,12);const mr=await client.query(`SELECT id FROM usuarios WHERE LOWER(email)=LOWER($1)`,[masterEmail]);if(mr.rowCount){await client.query(`UPDATE usuarios SET papel='super_admin',senha_hash=$1,ativo=true WHERE id=$2`,[mh,mr.rows[0].id]);}else{await client.query(`INSERT INTO usuarios(barbearia_id,nome,email,senha_hash,papel,ativo) VALUES($1,'BarberFlow Master',$2,$3,'super_admin',true)`,[tid,masterEmail.toLowerCase(),mh]);}console.log(`Master admin configurado: ${masterEmail}`);} 
await client.query('COMMIT');console.log('✅ Migração SaaS concluída. Banco pronto para dados antigos ou instalação nova.');}catch(e){await client.query('ROLLBACK');console.error(e);process.exitCode=1;}finally{client.release();await pool.end();}}main();
