require('dotenv').config(); const bcrypt=require('bcryptjs'); const pool=require('./src/config/db');
async function main(){const client=await pool.connect();try{await client.query('BEGIN');
await client.query(`CREATE TABLE IF NOT EXISTS barbearias(id SERIAL PRIMARY KEY,nome VARCHAR(120) NOT NULL,slug VARCHAR(120) UNIQUE NOT NULL,telefone VARCHAR(30),email VARCHAR(160),endereco VARCHAR(200),cidade VARCHAR(100),estado VARCHAR(2),logo_url TEXT,cor_primaria VARCHAR(20) DEFAULT '#f59e0b',ativo BOOLEAN DEFAULT true,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS usuarios(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,email VARCHAR(160) UNIQUE NOT NULL,senha_hash TEXT NOT NULL,papel VARCHAR(30) DEFAULT 'recepcao',ativo BOOLEAN DEFAULT true,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS assinaturas(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id),plano VARCHAR(30) DEFAULT 'premium',status VARCHAR(30) DEFAULT 'trial',inicio DATE DEFAULT CURRENT_DATE,fim_trial DATE,proxima_cobranca DATE,provedor VARCHAR(40),referencia_externa TEXT,checkout_url TEXT,provedor_status VARCHAR(40),atualizado_em TIMESTAMP DEFAULT NOW(),criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS password_resets(id SERIAL PRIMARY KEY,usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,token_hash TEXT NOT NULL,expira_em TIMESTAMP NOT NULL,usado BOOLEAN DEFAULT false,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS clientes(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,telefone VARCHAR(30) NOT NULL,email VARCHAR(160),observacoes TEXT,criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS barbeiros(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,telefone VARCHAR(30),ativo BOOLEAN DEFAULT true)`);
await client.query(`CREATE TABLE IF NOT EXISTS servicos(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),nome VARCHAR(120) NOT NULL,duracao INTEGER NOT NULL,preco NUMERIC(10,2) DEFAULT 0,ativo BOOLEAN DEFAULT true)`);
await client.query(`CREATE TABLE IF NOT EXISTS horarios_trabalho(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),barbeiro_id INTEGER NOT NULL REFERENCES barbeiros(id) ON DELETE CASCADE,dia_semana INTEGER NOT NULL,hora_inicio TIME NOT NULL,hora_fim TIME NOT NULL)`);
await client.query(`CREATE TABLE IF NOT EXISTS agendamentos(id SERIAL PRIMARY KEY,barbearia_id INTEGER REFERENCES barbearias(id),cliente_id INTEGER NOT NULL REFERENCES clientes(id),barbeiro_id INTEGER NOT NULL REFERENCES barbeiros(id),servico_id INTEGER NOT NULL REFERENCES servicos(id),data DATE NOT NULL,horario TIME NOT NULL,status VARCHAR(30) DEFAULT 'agendado',observacoes TEXT,origem VARCHAR(30) DEFAULT 'painel',criado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS reservas_pagamento(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,barbeiro_id INTEGER NOT NULL REFERENCES barbeiros(id),servico_id INTEGER NOT NULL REFERENCES servicos(id),nome VARCHAR(120) NOT NULL,telefone VARCHAR(30) NOT NULL,email VARCHAR(160),data DATE NOT NULL,horario TIME NOT NULL,valor_total NUMERIC(10,2) NOT NULL,valor_cobrado NUMERIC(10,2) NOT NULL,status VARCHAR(40) DEFAULT 'aguardando_pagamento',expira_em TIMESTAMP NOT NULL,mp_preference_id TEXT,mp_payment_id TEXT,mp_status VARCHAR(40),agendamento_id INTEGER REFERENCES agendamentos(id),criado_em TIMESTAMP DEFAULT NOW(),atualizado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS integracoes_pagamento(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,provedor VARCHAR(40) NOT NULL,mp_user_id TEXT,access_token_enc TEXT,refresh_token_enc TEXT,public_key TEXT,scope TEXT,expires_at TIMESTAMP,status VARCHAR(30) DEFAULT 'desconectado',conectado_em TIMESTAMP,atualizado_em TIMESTAMP DEFAULT NOW(),UNIQUE(barbearia_id,provedor))`);

await client.query(`CREATE TABLE IF NOT EXISTS integracoes_whatsapp(id SERIAL PRIMARY KEY,barbearia_id INTEGER UNIQUE NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,phone_number_id TEXT UNIQUE NOT NULL,business_account_id TEXT,numero VARCHAR(40),access_token_enc TEXT,status VARCHAR(30) DEFAULT 'desconectado',conectado_em TIMESTAMP,atualizado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS whatsapp_sessoes(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,telefone VARCHAR(40) NOT NULL,etapa VARCHAR(40) NOT NULL,dados JSONB DEFAULT '{}'::jsonb,atualizado_em TIMESTAMP DEFAULT NOW(),UNIQUE(barbearia_id,telefone))`);
await client.query(`CREATE TABLE IF NOT EXISTS automacoes_config(id SERIAL PRIMARY KEY,barbearia_id INTEGER UNIQUE NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,lembrete_24h BOOLEAN DEFAULT false,lembrete_2h BOOLEAN DEFAULT false,pos_atendimento BOOLEAN DEFAULT false,template_lembrete_24h VARCHAR(120),template_lembrete_2h VARCHAR(120),template_pos_atendimento VARCHAR(120),atualizado_em TIMESTAMP DEFAULT NOW())`);
await client.query(`CREATE TABLE IF NOT EXISTS automacoes_envios(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,agendamento_id INTEGER NOT NULL REFERENCES agendamentos(id) ON DELETE CASCADE,tipo VARCHAR(40) NOT NULL,status VARCHAR(30) NOT NULL,erro TEXT,enviado_em TIMESTAMP DEFAULT NOW(),UNIQUE(agendamento_id,tipo))`);

await client.query(`CREATE TABLE IF NOT EXISTS oauth_states(id SERIAL PRIMARY KEY,barbearia_id INTEGER NOT NULL REFERENCES barbearias(id) ON DELETE CASCADE,state TEXT UNIQUE NOT NULL,code_verifier TEXT NOT NULL,expira_em TIMESTAMP NOT NULL,criado_em TIMESTAMP DEFAULT NOW())`);
const extras=[['clientes','barbearia_id','INTEGER'],['clientes','email','VARCHAR(160)'],['clientes','observacoes','TEXT'],['clientes','criado_em','TIMESTAMP DEFAULT NOW()'],['barbeiros','barbearia_id','INTEGER'],['barbeiros','telefone','VARCHAR(30)'],['barbeiros','ativo','BOOLEAN DEFAULT true'],['servicos','barbearia_id','INTEGER'],['servicos','preco','NUMERIC(10,2) DEFAULT 0'],['servicos','ativo','BOOLEAN DEFAULT true'],['horarios_trabalho','barbearia_id','INTEGER'],['agendamentos','barbearia_id','INTEGER'],['agendamentos','status',"VARCHAR(30) DEFAULT 'agendado'"],['agendamentos','observacoes','TEXT'],['agendamentos','origem',"VARCHAR(30) DEFAULT 'painel'"],['agendamentos','criado_em','TIMESTAMP DEFAULT NOW()'],['usuarios','barbeiro_id','INTEGER'],['assinaturas','checkout_url','TEXT'],['assinaturas','provedor_status','VARCHAR(40)'],['assinaturas','atualizado_em','TIMESTAMP DEFAULT NOW()'],['barbearias','pagamento_agendamento',"VARCHAR(20) DEFAULT 'nenhum'"],['barbearias','percentual_sinal','NUMERIC(5,2) DEFAULT 50'],['barbearias','banner_url','TEXT'],['barbearias','cor_secundaria',"VARCHAR(20) DEFAULT '#111827'"],['barbearias','cor_botao',"VARCHAR(20) DEFAULT '#f59e0b'"],['barbearias','cor_fundo',"VARCHAR(20) DEFAULT '#f7f7f8'"],['barbearias','tema',"VARCHAR(20) DEFAULT 'claro'"],['barbearias','descricao_publica','TEXT'],['barbearias','texto_boas_vindas','VARCHAR(200)'],['barbearias','instagram','VARCHAR(160)'],['barbearias','whatsapp_publico','VARCHAR(30)'],['barbearias','mostrar_precos','BOOLEAN DEFAULT true'],['barbearias','mostrar_duracao','BOOLEAN DEFAULT true'],['barbearias','politica_cancelamento','TEXT'],['barbearias','aceitar_mercadopago','BOOLEAN DEFAULT false'],['barbearias','mp_aceitar_pix','BOOLEAN DEFAULT true'],['barbearias','mp_aceitar_cartao','BOOLEAN DEFAULT true'],['barbearias','aceitar_pix_manual','BOOLEAN DEFAULT false'],['barbearias','pix_chave','TEXT'],['barbearias','pix_nome','VARCHAR(160)'],['barbearias','pix_banco','VARCHAR(120)'],['barbearias','aceitar_dinheiro','BOOLEAN DEFAULT true'],['agendamentos','forma_pagamento',"VARCHAR(30) DEFAULT 'nao_informado'"],['agendamentos','status_pagamento',"VARCHAR(30) DEFAULT 'nao_exigido'"],['agendamentos','valor_cobrado','NUMERIC(10,2) DEFAULT 0'],['agendamentos','valor_pago','NUMERIC(10,2) DEFAULT 0'],['reservas_pagamento','forma_pagamento',"VARCHAR(30) DEFAULT 'mercado_pago'"]];for(const[t,c,ty]of extras)await client.query(`ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS ${c} ${ty}`);
let t=await client.query(`SELECT * FROM barbearias ORDER BY id LIMIT 1`);if(!t.rowCount)t=await client.query(`INSERT INTO barbearias(nome,slug,ativo) VALUES('Barbearia Demo','barbearia-demo',true) RETURNING *`);const tid=t.rows[0].id;for(const table of ['clientes','barbeiros','servicos','horarios_trabalho','agendamentos'])await client.query(`UPDATE ${table} SET barbearia_id=$1 WHERE barbearia_id IS NULL`,[tid]);
await client.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_usuarios_barbeiro') THEN ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_barbeiro FOREIGN KEY (barbeiro_id) REFERENCES barbeiros(id) ON DELETE SET NULL; END IF; END $$`);await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS ux_usuarios_barbeiro ON usuarios(barbearia_id,barbeiro_id) WHERE barbeiro_id IS NOT NULL`);await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS ux_horario_tenant_dia ON horarios_trabalho(barbearia_id,barbeiro_id,dia_semana)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_agenda_tenant_data ON agendamentos(barbearia_id,data,barbeiro_id)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_reservas_slot ON reservas_pagamento(barbearia_id,data,barbeiro_id,horario)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_reservas_status_expira ON reservas_pagamento(status,expira_em)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_clientes_tenant_nome ON clientes(barbearia_id,nome)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_oauth_states_expira ON oauth_states(expira_em)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_integracoes_pagamento_tenant ON integracoes_pagamento(barbearia_id,provedor,status)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_whatsapp_phone ON integracoes_whatsapp(phone_number_id,status)`);await client.query(`CREATE INDEX IF NOT EXISTS ix_automacoes_envios ON automacoes_envios(barbearia_id,tipo,enviado_em)`);
if(!(await client.query(`SELECT 1 FROM assinaturas WHERE barbearia_id=$1`,[tid])).rowCount)await client.query(`INSERT INTO assinaturas(barbearia_id,plano,status,inicio,fim_trial) VALUES($1,'premium','trial',CURRENT_DATE,CURRENT_DATE+INTERVAL '7 days')`,[tid]);
await client.query(`UPDATE assinaturas SET plano='premium', atualizado_em=NOW() WHERE status='trial'`);
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'admin@barberflow.local';if(!(await client.query(`SELECT 1 FROM usuarios WHERE LOWER(email)=LOWER($1)`,[email])).rowCount){const senha=process.env.BOOTSTRAP_ADMIN_PASSWORD||'TroqueEstaSenha123!';const hash=await bcrypt.hash(senha,12);await client.query(`INSERT INTO usuarios(barbearia_id,nome,email,senha_hash,papel,ativo) VALUES($1,'Administrador',$2,$3,'dono',true)`,[tid,email,hash]);console.log(`Usuário inicial: ${email}`);console.log('Senha inicial: valor de BOOTSTRAP_ADMIN_PASSWORD do .env');}
const masterEmail=process.env.MASTER_ADMIN_EMAIL;const masterPassword=process.env.MASTER_ADMIN_PASSWORD;if(masterEmail&&masterPassword){if(masterPassword.length<12)throw new Error('MASTER_ADMIN_PASSWORD deve ter pelo menos 12 caracteres');const mh=await bcrypt.hash(masterPassword,12);const mr=await client.query(`SELECT id FROM usuarios WHERE LOWER(email)=LOWER($1)`,[masterEmail]);if(mr.rowCount){await client.query(`UPDATE usuarios SET papel='super_admin',senha_hash=$1,ativo=true WHERE id=$2`,[mh,mr.rows[0].id]);}else{await client.query(`INSERT INTO usuarios(barbearia_id,nome,email,senha_hash,papel,ativo) VALUES($1,'BarberFlow Master',$2,$3,'super_admin',true)`,[tid,masterEmail.toLowerCase(),mh]);}console.log(`Master admin configurado: ${masterEmail}`);} 
await client.query('COMMIT');console.log('✅ Migração SaaS concluída. Banco pronto para dados antigos ou instalação nova.');}catch(e){await client.query('ROLLBACK');console.error(e);process.exitCode=1;}finally{client.release();await pool.end();}}main();
