require('dotenv').config();
const pool=require('./src/config/db');
(async()=>{let fail=0;try{
 console.log('=== Verificação estrutural BarberFlow V2 ===');
 await pool.query('SELECT 1');console.log('✅ Conexão PostgreSQL: OK');
 const required=['barbearias','usuarios','assinaturas','clientes','barbeiros','servicos','horarios_trabalho','agendamentos','reservas_pagamento','integracoes_pagamento','webhook_events','booking_otps','produtos','vendas','venda_itens','fila_espera','avaliacoes','automacoes_config','automacoes_envios','audit_logs','ai_config','ai_uso_mensal','assinaturas_pagamentos','legal_acceptances','support_tickets','system_events','backup_runs','metas_financeiras','platform_payment_gateways','platform_settings','loja_pedidos','loja_pedido_itens','marketing_modelos','marketing_cupons','marketing_campanhas','marketing_envios','marketing_links','marketing_cupom_usos','marketing_indicacoes_config','marketing_indicacao_codigos','marketing_indicacao_conversoes'];
 const r=await pool.query(`SELECT unnest($1::text[]) nome`,[required]);
 const tables=[];for(const x of r.rows){const q=await pool.query(`SELECT to_regclass($1) reg`,[`public.${x.nome}`]);const ok=!!q.rows[0].reg;tables.push({tabela:x.nome,status:ok?'OK':'AUSENTE'});if(!ok)fail++}console.table(tables);
 const cols=[['barbearias','is_system'],['barbearias','email'],['barbearias','endereco'],['barbearias','cidade'],['barbearias','estado'],['barbearias','logo_url'],['barbearias','banner_url'],['barbearias','pagamento_agendamento'],['barbearias','onboarding_link_compartilhado'],['barbearias','onboarding_concluido_em'],['barbearias','mostrar_whatsapp_publico'],['barbearias','mostrar_mapa_publico'],['usuarios','token_version'],['usuarios','mfa_enabled'],['usuarios','mfa_pending_secret_enc'],['barbeiros','comissao_servico_pct'],['barbeiros','comissao_produto_pct'],['agendamentos','public_token'],['agendamentos','valor_servico'],['agendamentos','valor_final'],['agendamentos','status_pagamento'],['agendamentos','reembolso_status'],['reservas_pagamento','public_token'],['automacoes_config','canal_lembretes'],['automacoes_config','mensagem_lembrete_24h'],['webhook_events','payload'],['webhook_events','tentativas'],['vendas','valor_pre_pago'],['vendas','valor_recebido'],['automacoes_envios','tentativas'],['automacoes_envios','atualizado_em'],['ai_config','nome_assistente'],['ai_config','tom'],['ai_config','limite_mensal'],['assinaturas_pagamentos','idempotency_key'],['assinaturas_pagamentos','referencia_externa'],['assinaturas_pagamentos','qr_code_base64'],['integracoes_pagamento','provider_account_id'],['integracoes_pagamento','secret_enc'],['integracoes_pagamento','environment'],['integracoes_pagamento','metadata'],['integracoes_pagamento','capabilities'],['oauth_states','provedor'],['metas_financeiras','mes'],['metas_financeiras','valor'],['produtos','imagem_url'],['platform_payment_gateways','secret_enc'],['platform_payment_gateways','public_key'],['platform_payment_gateways','environment'],['platform_payment_gateways','status'],['barbearias','loja_aceitar_retirada'],['barbearias','loja_aceitar_entrega'],['barbearias','loja_frete_por_km'],['barbearias','loja_frete_distancia_max_km'],['loja_pedidos','status_pagamento'],['loja_pedidos','status_pedido'],['loja_pedidos','estoque_reservado'],['loja_pedido_itens','produto_id'],['clientes','data_nascimento'],['clientes','marketing_opt_in'],['clientes','marketing_opt_in_em'],['clientes','marketing_opt_in_origem'],['marketing_campanhas','link_destino'],['marketing_campanhas','marketing_link_id'],['marketing_envios','provider_message_id'],['marketing_envios','tentativas'],['marketing_envios','entregue_em'],['marketing_envios','lido_em'],['loja_pedidos','desconto'],['loja_pedidos','cupom_id'],['loja_pedidos','marketing_link_id'],['loja_pedidos','marketing_opt_in'],['agendamentos','marketing_link_id'],['reservas_pagamento','marketing_link_id'],['reservas_pagamento','marketing_opt_in']];
 const cm=[];for(const [t,c] of cols){const q=await pool.query(`SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND column_name=$2) ok`,[t,c]);cm.push({campo:`${t}.${c}`,status:q.rows[0].ok?'OK':'AUSENTE'});if(!q.rows[0].ok)fail++}console.table(cm);
 const securityIndexes=['ux_barbearias_single_system','ux_reserva_mp_payment','ux_venda_final_agendamento','ux_produtos_tenant_sku_lower','ux_meta_financeira_geral_mes','ux_meta_financeira_barbeiro_mes','ux_marketing_envio_provider_message'];for(const idx of securityIndexes){const q=await pool.query(`SELECT to_regclass($1) reg`,[`public.${idx}`]);if(!q.rows[0].reg){fail++;console.error(`❌ Índice de segurança ausente: ${idx}`)}else console.log(`✅ Índice: ${idx}`)}
 const trig=await pool.query(`SELECT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='trg_bf_user_tenant_kind' AND NOT tgisinternal) ok`);if(!trig.rows[0].ok){fail++;console.error('❌ Trigger de isolamento do Supermaster ausente')}else console.log('✅ Trigger de isolamento do Supermaster: OK');
 const invalid=await pool.query(`SELECT conname,conrelid::regclass::text tabela FROM pg_constraint WHERE conname LIKE ANY(ARRAY['fk_%_tenant','ck_%']) AND NOT convalidated ORDER BY conname`);if(invalid.rowCount){fail++;console.error('❌ Constraints não validadas:');console.table(invalid.rows)}else console.log('✅ Constraints de integridade estão validadas');
 const sys=await pool.query(`SELECT COUNT(*)::int n FROM barbearias WHERE COALESCE(is_system,false)=true`);if(Number(sys.rows[0].n)!==1){fail++;console.error('❌ Deve existir exatamente 1 tenant interno do sistema')}else console.log('✅ Tenant interno do sistema: OK');
 const master=await pool.query(`SELECT COUNT(*)::int n,COUNT(*) FILTER(WHERE COALESCE(mfa_enabled,false)=true)::int mfa FROM usuarios u JOIN barbearias b ON b.id=u.barbearia_id WHERE u.papel='super_admin' AND u.ativo=true AND COALESCE(b.is_system,false)=true`);if(Number(master.rows[0].n)!==1){fail++;console.error('❌ Deve existir exatamente 1 Supermaster ativo no tenant interno')}else console.log('✅ Supermaster isolado: OK');if(process.env.NODE_ENV==='production'&&Number(master.rows[0].mfa)!==1){fail++;console.error('❌ MFA do Supermaster não está habilitado em produção')}
 const pendingTrial=await pool.query(`SELECT COUNT(*)::int n FROM assinaturas WHERE status='trial_pendente'`);if(Number(pendingTrial.rows[0].n)>0){fail++;console.error(`❌ Existem ${pendingTrial.rows[0].n} assinatura(s) presas em trial_pendente mesmo sem verificação obrigatória de e-mail`)}else console.log('✅ Nenhuma assinatura presa em trial_pendente');
 const web=await pool.query(`SELECT status,COUNT(*)::int quantidade FROM webhook_events GROUP BY status ORDER BY status`);if(web.rowCount)console.table(web.rows);
 if(fail){console.error(`❌ Verificação terminou com ${fail} falha(s).`);process.exitCode=1}else console.log('✅ Estrutura e invariantes essenciais validados.');
}catch(e){console.error('❌ Verificação falhou:',e.message);process.exitCode=1}finally{await pool.end()}})();
