const pool=require('../config/db');
const {externalSignal}=require('../utils/http');
const {getAiConfig}=require('./aiConfig');

function available(){return !!String(process.env.OPENAI_API_KEY||'').trim()}
function model(){return String(process.env.AI_MODEL||'gpt-5.6-luna').trim().slice(0,80)}
function extractOutput(body){if(typeof body?.output_text==='string')return body.output_text;for(const item of body?.output||[]){if(item?.type==='message')for(const c of item.content||[])if(c?.type==='output_text'&&c.text)return c.text}return null}
async function recordUsage(barbeariaId,usage={}){const input=Number(usage.input_tokens||usage.input_tokens_details?.total||0),output=Number(usage.output_tokens||usage.output_tokens_details?.total||0);await pool.query(`INSERT INTO ai_uso_mensal(barbearia_id,mes,atendimentos,tokens_entrada,tokens_saida,custo_centavos) VALUES($1,date_trunc('month',CURRENT_DATE)::date,1,$2,$3,0) ON CONFLICT(barbearia_id,mes) DO UPDATE SET atendimentos=ai_uso_mensal.atendimentos+1,tokens_entrada=ai_uso_mensal.tokens_entrada+EXCLUDED.tokens_entrada,tokens_saida=ai_uso_mensal.tokens_saida+EXCLUDED.tokens_saida,atualizado_em=NOW()`,[barbeariaId,input,output])}
async function routeIntent({barbeariaId,message,services=[],barbers=[]}){
  if(!available())return null;const cfg=await getAiConfig(barbeariaId);if(!cfg.ativo)return null;const u=(await pool.query(`SELECT atendimentos FROM ai_uso_mensal WHERE barbearia_id=$1 AND mes=date_trunc('month',CURRENT_DATE)::date`,[barbeariaId])).rows[0];if(Number(u?.atendimentos||0)>=Number(cfg.limite_mensal||500))return null;
  const schema={type:'object',properties:{intent:{type:'string',enum:['agendar','consultar_horarios','reagendar','cancelar','precos','status_agendamento','falar_humano','saudacao','outro']},servico:{type:['string','null']},barbeiro:{type:['string','null']},data:{type:['string','null'],description:'YYYY-MM-DD quando o usuário informou uma data reconhecível; caso contrário null'},horario:{type:['string','null'],description:'HH:MM quando informado; caso contrário null'},resposta:{type:['string','null']},confidence:{type:'number',minimum:0,maximum:1}},required:['intent','servico','barbeiro','data','horario','resposta','confidence'],additionalProperties:false};
  const system=`Você é o roteador seguro do WhatsApp de uma barbearia. Apenas classifique a intenção e extraia dados citados. Não invente disponibilidade, preço, reserva ou confirmação. Não execute ações. Serviços válidos: ${services.map(x=>x.nome).join(', ')||'nenhum'}. Barbeiros válidos: ${barbers.map(x=>x.nome).join(', ')||'nenhum'}. Hoje é ${new Date().toISOString().slice(0,10)}. Respostas curtas em português do Brasil.`;
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},signal:externalSignal(),body:JSON.stringify({model:model(),reasoning:{effort:'low'},input:[{role:'developer',content:system},{role:'user',content:String(message||'').slice(0,1200)}],text:{format:{type:'json_schema',name:'barberflow_intent',strict:true,schema}},max_output_tokens:350})});
  const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error?.message||`OpenAI HTTP ${r.status}`);const raw=extractOutput(body);if(!raw)throw new Error('IA sem saída estruturada');const parsed=JSON.parse(raw);await recordUsage(barbeariaId,body.usage||{});return parsed;
}
module.exports={available,model,routeIntent,recordUsage};
