const pool=require('../config/db');
const {decrypt}=require('./secrets');
const {contextoPlano}=require('./planos');
const {horaParaMinutos,minutosParaHora}=require('../utils/time');

function digits(v){return String(v||'').replace(/\D/g,'')}
async function integrationByPhoneId(phoneId){const r=await pool.query(`SELECT * FROM integracoes_whatsapp WHERE phone_number_id=$1 AND status='conectado'`,[phoneId]);return r.rows[0]||null}
async function sendText(integ,to,body){const token=decrypt(integ.access_token_enc);const version=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';const r=await fetch(`https://graph.facebook.com/${version}/${integ.phone_number_id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to:digits(to),type:'text',text:{preview_url:true,body:String(body).slice(0,4096)}})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error?.message||`WhatsApp respondeu ${r.status}`);return d}
async function getSession(barbeariaId,telefone){const r=await pool.query(`SELECT * FROM whatsapp_sessoes WHERE barbearia_id=$1 AND telefone=$2`,[barbeariaId,digits(telefone)]);return r.rows[0]||null}
async function saveSession(barbeariaId,telefone,etapa,dados={}){await pool.query(`INSERT INTO whatsapp_sessoes(barbearia_id,telefone,etapa,dados,atualizado_em) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(barbearia_id,telefone) DO UPDATE SET etapa=EXCLUDED.etapa,dados=EXCLUDED.dados,atualizado_em=NOW()`,[barbeariaId,digits(telefone),etapa,JSON.stringify(dados)])}
async function resetSession(barbeariaId,telefone){await pool.query(`DELETE FROM whatsapp_sessoes WHERE barbearia_id=$1 AND telefone=$2`,[barbeariaId,digits(telefone)])}
async function slots(barbeariaId,barbeiroId,servicoId,data){const s=await pool.query(`SELECT duracao FROM servicos WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[servicoId,barbeariaId]);if(!s.rowCount)return[];const dur=Number(s.rows[0].duracao);const dow=Number((await pool.query(`SELECT EXTRACT(ISODOW FROM $1::date) dia`,[data])).rows[0].dia);const e=await pool.query(`SELECT hora_inicio,hora_fim FROM horarios_trabalho WHERE barbearia_id=$1 AND barbeiro_id=$2 AND dia_semana=$3`,[barbeariaId,barbeiroId,dow]);if(!e.rowCount)return[];const ag=(await pool.query(`SELECT a.horario,s.duracao FROM agendamentos a JOIN servicos s ON s.id=a.servico_id WHERE a.barbearia_id=$1 AND a.barbeiro_id=$2 AND a.data=$3 AND a.status NOT IN ('cancelado','nao_compareceu')`,[barbeariaId,barbeiroId,data])).rows;const holds=(await pool.query(`SELECT r.horario,s.duracao FROM reservas_pagamento r JOIN servicos s ON s.id=r.servico_id WHERE r.barbearia_id=$1 AND r.barbeiro_id=$2 AND r.data=$3 AND r.expira_em>NOW() AND r.status IN ('aguardando_pagamento','pagamento_pendente','aguardando_pix_manual')`,[barbeariaId,barbeiroId,data])).rows;const busy=[...ag,...holds];const ini=horaParaMinutos(e.rows[0].hora_inicio),fim=horaParaMinutos(e.rows[0].hora_fim),out=[];for(let m=ini;m+dur<=fim;m+=30){if(!busy.some(a=>m<horaParaMinutos(a.horario)+Number(a.duracao)&&m+dur>horaParaMinutos(a.horario)))out.push(minutosParaHora(m))}return out}
function parseDate(txt){const s=String(txt||'').trim().toLowerCase();const now=new Date();if(s==='hoje')return now.toISOString().slice(0,10);if(s==='amanhã'||s==='amanha'){now.setDate(now.getDate()+1);return now.toISOString().slice(0,10)}const m=s.match(/^(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{4}))?$/);if(!m)return null;const y=m[3]||new Date().getFullYear();return `${y}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`}
function choice(txt,max){const n=Number(String(txt||'').trim());return Number.isInteger(n)&&n>=1&&n<=max?n-1:-1}
async function publicConfig(barbeariaId){const r=await pool.query(`SELECT id,nome,slug,pagamento_agendamento,percentual_sinal,aceitar_mercadopago,aceitar_pix_manual,aceitar_dinheiro,pix_chave,pix_nome,pix_banco FROM barbearias WHERE id=$1`,[barbeariaId]);return r.rows[0]}
async function processIncoming(integ,from,text){const ctx=await contextoPlano(integ.barbearia_id);if(!ctx.recursos.includes('automacoes'))return sendText(integ,from,'Este atendimento automático está temporariamente indisponível. Fale com a barbearia para agendar.');const msg=String(text||'').trim();if(/^menu$|^oi$|^ol[aá]$|^in[ií]cio$|^inicio$/i.test(msg))await resetSession(integ.barbearia_id,from);let s=await getSession(integ.barbearia_id,from);if(!s){const serv=(await pool.query(`SELECT id,nome,duracao,preco FROM servicos WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[integ.barbearia_id])).rows;if(!serv.length)return sendText(integ,from,'Ainda não há serviços disponíveis para agendamento.');await saveSession(integ.barbearia_id,from,'servico',{servicos:serv});return sendText(integ,from,`Olá! 👋 Sou o assistente de agendamento.\n\nEscolha um serviço:\n${serv.map((x,i)=>`${i+1}. ${x.nome} — R$ ${Number(x.preco).toFixed(2).replace('.',',')}`).join('\n')}\n\nDigite o número da opção.`)}
const d=typeof s.dados==='string'?JSON.parse(s.dados):s.dados||{};
if(s.etapa==='servico'){const i=choice(msg,d.servicos.length);if(i<0)return sendText(integ,from,'Digite o número de um serviço da lista.');d.servico=d.servicos[i];const bs=(await pool.query(`SELECT id,nome FROM barbeiros WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[integ.barbearia_id])).rows;d.barbeiros=bs;await saveSession(integ.barbearia_id,from,'barbeiro',d);return sendText(integ,from,`Ótimo: ${d.servico.nome}.\n\nEscolha o barbeiro:\n${bs.map((x,j)=>`${j+1}. ${x.nome}`).join('\n')}`)}
if(s.etapa==='barbeiro'){const i=choice(msg,d.barbeiros.length);if(i<0)return sendText(integ,from,'Digite o número de um barbeiro da lista.');d.barbeiro=d.barbeiros[i];await saveSession(integ.barbearia_id,from,'data',d);return sendText(integ,from,'Qual data você prefere? Envie DD/MM, ou digite *hoje* / *amanhã*.')}
if(s.etapa==='data'){const data=parseDate(msg);if(!data)return sendText(integ,from,'Não entendi a data. Envie no formato DD/MM, ou digite hoje/amanhã.');const hs=await slots(integ.barbearia_id,d.barbeiro.id,d.servico.id,data);if(!hs.length)return sendText(integ,from,'Não há horários disponíveis nessa data. Envie outra data.');d.data=data;d.horarios=hs;await saveSession(integ.barbearia_id,from,'horario',d);return sendText(integ,from,`Horários disponíveis:\n${hs.map((h,i)=>`${i+1}. ${h.slice(0,5)}`).join('\n')}\n\nDigite o número do horário.`)}
if(s.etapa==='horario'){const i=choice(msg,d.horarios.length);if(i<0)return sendText(integ,from,'Escolha um dos horários pelo número.');d.horario=d.horarios[i];await saveSession(integ.barbearia_id,from,'nome',d);return sendText(integ,from,'Perfeito. Qual é o seu nome?')}
if(s.etapa==='nome'){if(msg.length<2)return sendText(integ,from,'Digite seu nome para continuar.');d.nome=msg;const cfg=await publicConfig(integ.barbearia_id);d.cfg=cfg;if(cfg.pagamento_agendamento==='nenhum'){d.forma='dinheiro';return finishBooking(integ,from,d,true)}const methods=[];if(cfg.aceitar_mercadopago)methods.push({id:'mercado_pago',nome:'Mercado Pago'});if(cfg.aceitar_pix_manual)methods.push({id:'pix_manual',nome:'Pix manual'});if(cfg.aceitar_dinheiro)methods.push({id:'dinheiro',nome:'Dinheiro no local'});if(!methods.length)return sendText(integ,from,'A barbearia exige pagamento, mas ainda não configurou uma forma de recebimento.');d.metodos=methods;await saveSession(integ.barbearia_id,from,'pagamento',d);return sendText(integ,from,`Como deseja pagar?\n${methods.map((x,i)=>`${i+1}. ${x.nome}`).join('\n')}`)}
if(s.etapa==='pagamento'){const i=choice(msg,d.metodos.length);if(i<0)return sendText(integ,from,'Escolha a forma de pagamento pelo número.');d.forma=d.metodos[i].id;return finishBooking(integ,from,d,false)}
return resetSession(integ.barbearia_id,from).then(()=>sendText(integ,from,'Vamos recomeçar. Digite *oi* para ver os serviços.'))}
async function finishBooking(integ,from,d,semCobranca){const app=(process.env.APP_URL||'http://localhost:3001').replace(/\/$/,'');const cfg=d.cfg||await publicConfig(integ.barbearia_id);const r=await fetch(`${app}/api/publico/${cfg.slug}/agendar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:d.nome,telefone:digits(from),email:null,servico_id:Number(d.servico.id),barbeiro_id:Number(d.barbeiro.id),data:d.data,horario:d.horario,forma_pagamento:semCobranca?null:d.forma})});let out={};try{out=await r.json()}catch{}if(!r.ok){await resetSession(integ.barbearia_id,from);return sendText(integ,from,`Não consegui finalizar: ${out.erro||'erro no agendamento'}. Digite *oi* para tentar novamente.`)}await resetSession(integ.barbearia_id,from);if(out.checkout_url)return sendText(integ,from,`Seu horário foi reservado. ✅\n\nPague pelo link para confirmar:\n${out.checkout_url}\n\nA reserva expira em alguns minutos.`);if(out.payment_type==='pix_manual')return sendText(integ,from,`Seu horário foi reservado. Faça o Pix de R$ ${Number(out.valor_cobrado||0).toFixed(2).replace('.',',')}.\n\nChave: ${out.pix.chave}\nRecebedor: ${out.pix.nome}${out.pix.banco?`\nBanco: ${out.pix.banco}`:''}\n\nA barbearia confirmará após verificar o pagamento.`);return sendText(integ,from,`Agendamento realizado! ✅\n${d.servico.nome} com ${d.barbeiro.nome}\n${d.data.split('-').reverse().join('/')} às ${String(d.horario).slice(0,5)}.\n\nDigite *oi* quando quiser agendar novamente.`)}
async function sendTemplate(integ,to,name,params=[],language='pt_BR'){const token=decrypt(integ.access_token_enc);const version=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';const components=params.length?[{type:'body',parameters:params.map(x=>({type:'text',text:String(x)}))}]:[];const r=await fetch(`https://graph.facebook.com/${version}/${integ.phone_number_id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:digits(to),type:'template',template:{name,language:{code:language},components}})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error?.message||`WhatsApp respondeu ${r.status}`);return d}
module.exports={integrationByPhoneId,sendText,sendTemplate,processIncoming};
