const pool=require('../config/db');
const providers=require('./whatsappProviders');
const {contextoPlano}=require('./planos');
const {horaParaMinutos,minutosParaHora}=require('../utils/time');
const {createTrustedAppointment,lockSlot,slotContext}=require('./booking');
const {criarPreferenciaAgendamento,safeMercadoPagoCheckoutUrl}=require('./mercadoPago');
const {getSellerAccessToken}=require('./mercadoPagoOAuth');
const {routeIntent}=require('./aiAgent');
const {getAiConfig}=require('./aiConfig');
const {formatTrackingCode,statusLabel,trackingUrl,normalizeTrackingCode}=require('./bookingTracking');

function digits(v){return String(v||'').replace(/\D/g,'').slice(-15)}
function validPhone(v){const d=digits(v);return d.length>=10&&d.length<=15}
async function integrationByPhoneId(phoneId){return providers.findMetaByPhoneId(phoneId)}
async function sendText(integ,to,body){return providers.sendText(integ,to,body)}
async function getSession(barbeariaId,telefone){const r=await pool.query(`SELECT * FROM whatsapp_sessoes WHERE barbearia_id=$1 AND telefone=$2`,[barbeariaId,digits(telefone)]);return r.rows[0]||null}
async function saveSession(barbeariaId,telefone,etapa,dados={}){await pool.query(`INSERT INTO whatsapp_sessoes(barbearia_id,telefone,etapa,dados,atualizado_em) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(barbearia_id,telefone) DO UPDATE SET etapa=EXCLUDED.etapa,dados=EXCLUDED.dados,atualizado_em=NOW()`,[barbeariaId,digits(telefone),etapa,JSON.stringify(dados)])}
async function resetSession(barbeariaId,telefone){await pool.query(`DELETE FROM whatsapp_sessoes WHERE barbearia_id=$1 AND telefone=$2`,[barbeariaId,digits(telefone)])}
async function slots(barbeariaId,barbeiroId,servicoId,data){const s=await pool.query(`SELECT duracao FROM servicos WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[servicoId,barbeariaId]);if(!s.rowCount)return[];const dur=Number(s.rows[0].duracao);const dow=Number((await pool.query(`SELECT EXTRACT(ISODOW FROM $1::date) dia`,[data])).rows[0].dia);const e=await pool.query(`SELECT hora_inicio,hora_fim FROM horarios_trabalho WHERE barbearia_id=$1 AND barbeiro_id=$2 AND dia_semana=$3`,[barbeariaId,barbeiroId,dow]);if(!e.rowCount)return[];const ag=(await pool.query(`SELECT a.horario,s.duracao FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND a.barbeiro_id=$2 AND a.data=$3 AND a.status NOT IN ('cancelado','nao_compareceu')`,[barbeariaId,barbeiroId,data])).rows;const holds=(await pool.query(`SELECT r.horario,s.duracao FROM reservas_pagamento r JOIN servicos s ON s.id=r.servico_id AND s.barbearia_id=r.barbearia_id WHERE r.barbearia_id=$1 AND r.barbeiro_id=$2 AND r.data=$3 AND r.expira_em>NOW() AND r.status IN ('aguardando_pagamento','pagamento_pendente','aguardando_pix_manual')`,[barbeariaId,barbeiroId,data])).rows;const busy=[...ag,...holds];const ini=horaParaMinutos(e.rows[0].hora_inicio),fim=horaParaMinutos(e.rows[0].hora_fim),out=[];for(let m=ini;m+dur<=fim;m+=30){if(!busy.some(a=>m<horaParaMinutos(a.horario)+Number(a.duracao)&&m+dur>horaParaMinutos(a.horario)))out.push(minutosParaHora(m))}return out}
function parseDate(txt){const s=String(txt||'').trim().toLowerCase();const now=new Date();if(s==='hoje')return now.toISOString().slice(0,10);if(s==='amanhã'||s==='amanha'){now.setDate(now.getDate()+1);return now.toISOString().slice(0,10)}const m=s.match(/^(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{4}))?$/);if(!m)return null;const y=m[3]||new Date().getFullYear();return `${y}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`}
function choice(txt,max){const n=Number(String(txt||'').trim());return Number.isInteger(n)&&n>=1&&n<=max?n-1:-1}
async function publicConfig(barbeariaId){const r=await pool.query(`SELECT b.id,b.nome,b.slug,b.pagamento_agendamento,b.percentual_sinal,b.aceitar_mercadopago,b.mp_aceitar_pix,b.mp_aceitar_cartao,b.aceitar_pix_manual,b.aceitar_dinheiro,b.pix_chave,b.pix_nome,b.pix_banco,EXISTS(SELECT 1 FROM integracoes_pagamento ip WHERE ip.barbearia_id=b.id AND ip.provedor='mercadopago' AND ip.status='conectado') mp_conectado FROM barbearias b WHERE b.id=$1 AND b.ativo=true AND b.excluido_em IS NULL`,[barbeariaId]);return r.rows[0]}
async function trackingReply(integ,from,msg){
  const tel=digits(from),maybeCode=normalizeTrackingCode(String(msg||'').replace(/^acompanhar\s*/i,''));
  const vals=[integ.barbearia_id,tel];let codeFilter='';if(maybeCode.length>=8){vals.push(maybeCode);codeFilter=` AND a.tracking_code=$3`;}
  const r=await pool.query(`SELECT a.data,a.horario,a.status,a.tracking_code,s.nome servico,b.nome barbeiro,br.slug FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id AND c.barbearia_id=a.barbearia_id JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id JOIN barbeiros b ON b.id=a.barbeiro_id AND b.barbearia_id=a.barbearia_id JOIN barbearias br ON br.id=a.barbearia_id WHERE a.barbearia_id=$1 AND regexp_replace(c.telefone,'\D','','g')=$2 ${codeFilter} AND a.data>=CURRENT_DATE AND a.status NOT IN ('cancelado','concluido','nao_compareceu') ORDER BY a.data,a.horario LIMIT 8`,vals);
  if(!r.rowCount)return sendText(integ,from,maybeCode.length>=8?'Não encontrei um agendamento ativo com esse código para este WhatsApp.':'Não encontrei agendamentos futuros vinculados a este WhatsApp.');
  const lines=r.rows.map((a,i)=>{const url=trackingUrl(a.slug,a.tracking_code);return `${i+1}. *${a.servico}* com ${a.barbeiro}\n   ${String(a.data).slice(0,10).split('-').reverse().join('/')} às ${String(a.horario).slice(0,5)} • ${statusLabel(a.status)}\n   Código: *${formatTrackingCode(a.tracking_code)}*${url?`\n   ${url}`:''}`}).join('\n\n');
  return sendText(integ,from,`Seus agendamentos 📅\n\n${lines}\n\nVocê pode acompanhar também pela página pública usando seu WhatsApp e o código acima.`);
}

async function aiInitial(integ,from,msg,ctx){
  if(!ctx.recursos.includes('ia_whatsapp')||/^(menu|oi|ol[aá]|in[ií]cio|inicio)$/i.test(msg))return false;
  const cfg=await getAiConfig(integ.barbearia_id);if(!cfg.ativo)return false;
  const [servicos,barbeiros]=await Promise.all([pool.query(`SELECT id,nome,duracao,preco FROM servicos WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[integ.barbearia_id]),pool.query(`SELECT id,nome FROM barbeiros WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[integ.barbearia_id])]);
  let ai;try{ai=await routeIntent({barbeariaId:integ.barbearia_id,message:msg,services:servicos.rows,barbers:barbeiros.rows})}catch(e){console.error('ai_router_fallback',e.message);return false}if(!ai||Number(ai.confidence||0)<0.45)return false;
  const match=(list,name)=>{const q=String(name||'').trim().toLowerCase();if(!q)return null;return list.find(x=>x.nome.toLowerCase()===q)||list.find(x=>x.nome.toLowerCase().includes(q)||q.includes(x.nome.toLowerCase()))||null};
  if(ai.intent==='precos'&&cfg.informar_precos){await sendText(integ,from,`Serviços e preços:\n${servicos.rows.map((x,i)=>`${i+1}. ${x.nome} — R$ ${Number(x.preco).toFixed(2).replace('.',',')}`).join('\n')}\n\nSe quiser agendar, responda *oi*.`);return true}
  if(ai.intent==='falar_humano'){await sendText(integ,from,cfg.mensagem_fallback||'Vou chamar alguém da equipe para continuar seu atendimento.');return true}
  if(['status_agendamento','cancelar','reagendar'].includes(ai.intent)){
    const tel=digits(from),r=await pool.query(`SELECT a.id,a.data,a.horario,a.status,s.nome servico,b.nome barbeiro FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id AND c.barbearia_id=a.barbearia_id JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id JOIN barbeiros b ON b.id=a.barbeiro_id AND b.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND regexp_replace(c.telefone,'\\D','','g')=$2 AND a.data>=CURRENT_DATE AND a.status NOT IN ('cancelado','concluido','nao_compareceu') ORDER BY a.data,a.horario LIMIT 10`,[integ.barbearia_id,tel]);
    if(!r.rowCount){await sendText(integ,from,'Não encontrei agendamentos futuros vinculados a este WhatsApp.');return true}
    const list=r.rows.map((x,i)=>`${i+1}. ${x.servico} com ${x.barbeiro} — ${String(x.data).slice(0,10).split('-').reverse().join('/')} ${String(x.horario).slice(0,5)}`).join('\n');
    if(ai.intent==='status_agendamento'){await sendText(integ,from,`Seus próximos agendamentos:\n${list}`);return true}
    if(ai.intent==='cancelar'&&cfg.cancelar){await saveSession(integ.barbearia_id,from,'ai_cancelar_select',{agendamentos:r.rows});await sendText(integ,from,`Qual agendamento deseja cancelar?\n${list}\n\nDigite o número.`);return true}
    if(ai.intent==='reagendar'&&cfg.reagendar){await saveSession(integ.barbearia_id,from,'ai_reagendar_select',{agendamentos:r.rows});await sendText(integ,from,`Qual agendamento deseja reagendar?\n${list}\n\nDigite o número.`);return true}
  }
  if((ai.intent==='agendar'||ai.intent==='consultar_horarios')&&cfg.criar_agendamento){
    const sv=match(servicos.rows,ai.servico),br=match(barbeiros.rows,ai.barbeiro);
    if(ai.intent==='consultar_horarios'&&cfg.consultar_horarios&&sv&&br&&ai.data){const hs=await slots(integ.barbearia_id,br.id,sv.id,ai.data);await sendText(integ,from,hs.length?`Horários de ${sv.nome} com ${br.nome} em ${String(ai.data).split('-').reverse().join('/')}:\n${hs.slice(0,12).map(x=>String(x).slice(0,5)).join(', ')}\n\nDigite *oi* para agendar.`:'Não encontrei horários livres nessa combinação. Digite *oi* para escolher outra opção.');return true}
    if(sv){const d={servico:sv,servicos:servicos.rows,barbeiros:barbeiros.rows};if(br){d.barbeiro=br;if(ai.data){const hs=await slots(integ.barbearia_id,br.id,sv.id,ai.data);if(hs.length){d.data=ai.data;d.horarios=hs;await saveSession(integ.barbearia_id,from,'horario',d);await sendText(integ,from,`Entendi: ${sv.nome} com ${br.nome}. Horários em ${String(ai.data).split('-').reverse().join('/')}:\n${hs.map((h,i)=>`${i+1}. ${String(h).slice(0,5)}`).join('\n')}\n\nDigite o número do horário.`);return true}}await saveSession(integ.barbearia_id,from,'data',d);await sendText(integ,from,`Entendi: ${sv.nome} com ${br.nome}. Qual data você prefere? Envie DD/MM, hoje ou amanhã.`);return true}await saveSession(integ.barbearia_id,from,'barbeiro',d);await sendText(integ,from,`Entendi que você quer ${sv.nome}. Escolha o barbeiro:\n${barbeiros.rows.map((x,i)=>`${i+1}. ${x.nome}`).join('\n')}`);return true}
  }
  if(ai.intent==='saudacao'){await sendText(integ,from,cfg.mensagem_inicial||'Olá! Como posso ajudar? Digite *oi* para agendar.');return true}
  if(ai.resposta){await sendText(integ,from,`${ai.resposta}\n\nPara agendar, digite *oi*.`);return true}
  return false;
}

async function processIncoming(integ,from,text){const ctx=await contextoPlano(integ.barbearia_id);if(!ctx.recursos.includes('automacoes'))return sendText(integ,from,'Este atendimento automático está temporariamente indisponível. Fale com a barbearia para agendar.');const msg=String(text||'').trim();const tel=digits(from);if(/^(sair|parar|cancelar\s*(promoções|promocoes)?|não\s+quero\s+(promoções|promocoes)|nao\s+quero\s+(promoções|promocoes))$/i.test(msg)){await pool.query(`UPDATE clientes SET marketing_opt_in=false,marketing_opt_out_em=NOW() WHERE barbearia_id=$1 AND regexp_replace(telefone,'\\D','','g')=$2`,[integ.barbearia_id,tel]);await resetSession(integ.barbearia_id,from);return sendText(integ,from,'Tudo certo. Você não receberá mais promoções da barbearia. Mensagens do seu atendimento e agendamentos continuam funcionando normalmente.');}if(/^(promoções|promocoes|quero\s+promoções|quero\s+promocoes)$/i.test(msg)){const opt=await pool.query(`UPDATE clientes SET marketing_opt_in=true,marketing_opt_in_em=NOW(),marketing_opt_out_em=NULL,marketing_opt_in_origem='whatsapp' WHERE barbearia_id=$1 AND regexp_replace(telefone,'\\D','','g')=$2 RETURNING id`,[integ.barbearia_id,tel]);await resetSession(integ.barbearia_id,from);if(!opt.rowCount)return sendText(integ,from,'Ainda não encontrei um cadastro com este WhatsApp. Faça um agendamento ou compra e marque a opção de receber promoções; depois você poderá gerenciar a autorização por aqui.');return sendText(integ,from,'Pronto! Você autorizou o recebimento de promoções da barbearia. Para cancelar quando quiser, responda *SAIR*.');}if(/^(acompanhar|meus?\s+agendamentos?|status)(?:\s+[A-Za-z0-9-]{8,20})?$/i.test(msg)||/^(?:[A-F0-9]{4}-?){3}$/i.test(msg)){await resetSession(integ.barbearia_id,from);return trackingReply(integ,from,msg);}if(/^menu$|^oi$|^ol[aá]$|^in[ií]cio$|^inicio$/i.test(msg))await resetSession(integ.barbearia_id,from);let s=await getSession(integ.barbearia_id,from);if(!s&&await aiInitial(integ,from,msg,ctx))return; s=await getSession(integ.barbearia_id,from);if(!s){const serv=(await pool.query(`SELECT id,nome,duracao,preco FROM servicos WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[integ.barbearia_id])).rows;if(!serv.length)return sendText(integ,from,'Ainda não há serviços disponíveis para agendamento.');await saveSession(integ.barbearia_id,from,'servico',{servicos:serv});return sendText(integ,from,`Olá! 👋 Sou o assistente de agendamento.\n\nEscolha um serviço:\n${serv.map((x,i)=>`${i+1}. ${x.nome} — R$ ${Number(x.preco).toFixed(2).replace('.',',')}`).join('\n')}\n\nDigite o número da opção.`)}
const d=typeof s.dados==='string'?JSON.parse(s.dados):s.dados||{};
if(s.etapa==='ai_cancelar_select'){const i=choice(msg,d.agendamentos?.length||0);if(i<0)return sendText(integ,from,'Digite o número do agendamento que deseja cancelar.');const ag=d.agendamentos[i];const r=await pool.query(`UPDATE agendamentos SET status='cancelado',reembolso_status=CASE WHEN status_pagamento IN ('pago','parcial') THEN 'pendente' ELSE reembolso_status END WHERE id=$1 AND barbearia_id=$2 AND status NOT IN ('cancelado','concluido','nao_compareceu') RETURNING id,reembolso_status`,[ag.id,integ.barbearia_id]);await resetSession(integ.barbearia_id,from);if(!r.rowCount)return sendText(integ,from,'Esse agendamento não pode mais ser cancelado.');return sendText(integ,from,r.rows[0].reembolso_status==='pendente'?'Agendamento cancelado. ✅ A equipe precisa concluir o reembolso do valor já pago.':'Agendamento cancelado com sucesso. ✅')}
if(s.etapa==='ai_reagendar_select'){const i=choice(msg,d.agendamentos?.length||0);if(i<0)return sendText(integ,from,'Digite o número do agendamento que deseja reagendar.');const ag=(await pool.query(`SELECT a.*,s.nome servico,s.preco,s.duracao,b.nome barbeiro FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id JOIN barbeiros b ON b.id=a.barbeiro_id AND b.barbearia_id=a.barbearia_id WHERE a.id=$1 AND a.barbearia_id=$2`,[d.agendamentos[i].id,integ.barbearia_id])).rows[0];if(!ag){await resetSession(integ.barbearia_id,from);return sendText(integ,from,'Agendamento não encontrado.')}d.agendamento=ag;await saveSession(integ.barbearia_id,from,'ai_reagendar_data',d);return sendText(integ,from,'Para qual nova data? Envie DD/MM, hoje ou amanhã.')}
if(s.etapa==='ai_reagendar_data'){const data=parseDate(msg);if(!data)return sendText(integ,from,'Não entendi a data. Envie DD/MM, hoje ou amanhã.');const a=d.agendamento,hs=await slots(integ.barbearia_id,a.barbeiro_id,a.servico_id,data);if(!hs.length)return sendText(integ,from,'Não há horários livres nessa data. Envie outra data.');d.nova_data=data;d.horarios=hs;await saveSession(integ.barbearia_id,from,'ai_reagendar_horario',d);return sendText(integ,from,`Horários disponíveis:\n${hs.map((h,i)=>`${i+1}. ${String(h).slice(0,5)}`).join('\n')}\n\nDigite o número.`)}
if(s.etapa==='ai_reagendar_horario'){const i=choice(msg,d.horarios?.length||0);if(i<0)return sendText(integ,from,'Escolha o horário pelo número.');const a=d.agendamento,novo=d.horarios[i],c=await pool.connect();try{await c.query('BEGIN');await lockSlot(c,integ.barbearia_id,a.barbeiro_id,d.nova_data);const sc=await slotContext(c,{barbeariaId:integ.barbearia_id,barbeiroId:a.barbeiro_id,servicoId:a.servico_id,data:d.nova_data,horario:novo,ignoreAppointmentId:a.id});if(!sc.ok)throw new Error(sc.error||'Horário indisponível');await c.query(`UPDATE agendamentos SET data=$1,horario=$2,status='agendado' WHERE id=$3 AND barbearia_id=$4`,[d.nova_data,novo,a.id,integ.barbearia_id]);await c.query('COMMIT');await resetSession(integ.barbearia_id,from);return sendText(integ,from,`Reagendamento confirmado! ✅\n${String(d.nova_data).split('-').reverse().join('/')} às ${String(novo).slice(0,5)}.`)}catch(e){try{await c.query('ROLLBACK')}catch{}return sendText(integ,from,`Não consegui reagendar: ${e.message}.`)}finally{c.release()}}
if(s.etapa==='servico'){const i=choice(msg,d.servicos.length);if(i<0)return sendText(integ,from,'Digite o número de um serviço da lista.');d.servico=d.servicos[i];const bs=(await pool.query(`SELECT id,nome FROM barbeiros WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[integ.barbearia_id])).rows;d.barbeiros=bs;await saveSession(integ.barbearia_id,from,'barbeiro',d);return sendText(integ,from,`Ótimo: ${d.servico.nome}.\n\nEscolha o barbeiro:\n${bs.map((x,j)=>`${j+1}. ${x.nome}`).join('\n')}`)}
if(s.etapa==='barbeiro'){const i=choice(msg,d.barbeiros.length);if(i<0)return sendText(integ,from,'Digite o número de um barbeiro da lista.');d.barbeiro=d.barbeiros[i];await saveSession(integ.barbearia_id,from,'data',d);return sendText(integ,from,'Qual data você prefere? Envie DD/MM, ou digite *hoje* / *amanhã*.')}
if(s.etapa==='data'){const data=parseDate(msg);if(!data)return sendText(integ,from,'Não entendi a data. Envie no formato DD/MM, ou digite hoje/amanhã.');const hs=await slots(integ.barbearia_id,d.barbeiro.id,d.servico.id,data);if(!hs.length)return sendText(integ,from,'Não há horários disponíveis nessa data. Envie outra data.');d.data=data;d.horarios=hs;await saveSession(integ.barbearia_id,from,'horario',d);return sendText(integ,from,`Horários disponíveis:\n${hs.map((h,i)=>`${i+1}. ${h.slice(0,5)}`).join('\n')}\n\nDigite o número do horário.`)}
if(s.etapa==='horario'){const i=choice(msg,d.horarios.length);if(i<0)return sendText(integ,from,'Escolha um dos horários pelo número.');d.horario=d.horarios[i];await saveSession(integ.barbearia_id,from,'nome',d);return sendText(integ,from,'Perfeito. Qual é o seu nome?')}
if(s.etapa==='nome'){if(msg.length<2)return sendText(integ,from,'Digite seu nome para continuar.');d.nome=msg;const cfg=await publicConfig(integ.barbearia_id);d.cfg=cfg;if(cfg.pagamento_agendamento==='nenhum'){d.forma='dinheiro';return finishBooking(integ,from,d,true)}const methods=[];if(cfg.aceitar_mercadopago&&cfg.mp_conectado&&(cfg.mp_aceitar_pix!==false||cfg.mp_aceitar_cartao!==false))methods.push({id:'mercado_pago',nome:'Mercado Pago'});if(cfg.aceitar_pix_manual&&cfg.pix_chave)methods.push({id:'pix_manual',nome:'Pix manual'});if(cfg.aceitar_dinheiro)methods.push({id:'dinheiro',nome:'Dinheiro no local'});if(!methods.length)return sendText(integ,from,'A barbearia exige pagamento, mas ainda não configurou uma forma de recebimento.');d.metodos=methods;await saveSession(integ.barbearia_id,from,'pagamento',d);return sendText(integ,from,`Como deseja pagar?\n${methods.map((x,i)=>`${i+1}. ${x.nome}`).join('\n')}`)}
if(s.etapa==='pagamento'){const i=choice(msg,d.metodos.length);if(i<0)return sendText(integ,from,'Escolha a forma de pagamento pelo número.');d.forma=d.metodos[i].id;return finishBooking(integ,from,d,false)}
return resetSession(integ.barbearia_id,from).then(()=>sendText(integ,from,'Vamos recomeçar. Digite *oi* para ver os serviços.'))}
function valorCobranca(preco,modo,percentual){const total=Number(preco||0);if(modo==='total')return total;if(modo==='sinal')return Math.max(0.01,Math.round(total*Math.max(1,Math.min(100,Number(percentual||50)))/100*100)/100);return 0}
async function finishBooking(integ,from,d,semCobranca){
  const cfg=d.cfg||await publicConfig(integ.barbearia_id);if(!cfg){await resetSession(integ.barbearia_id,from);return sendText(integ,from,'A barbearia está indisponível no momento.');}
  const base={barbeariaId:integ.barbearia_id,nome:d.nome,telefone:digits(from),email:null,barbeiroId:Number(d.barbeiro.id),servicoId:Number(d.servico.id),data:d.data,horario:d.horario};
  try{
    if(semCobranca||cfg.pagamento_agendamento==='nenhum'){
      const out=await createTrustedAppointment({...base,origem:'whatsapp',formaPagamento:'nao_informado',statusPagamento:'nao_exigido'});if(!out.ok)throw new Error(out.error);await resetSession(integ.barbearia_id,from);return sendText(integ,from,`Agendamento realizado! ✅\n${d.servico.nome} com ${d.barbeiro.nome}\n${d.data.split('-').reverse().join('/')} às ${String(d.horario).slice(0,5)}.\n\nCódigo de acompanhamento: *${formatTrackingCode(out.appointment.tracking_code)}*${trackingUrl(cfg.slug,out.appointment.tracking_code)?`\nAcompanhe: ${trackingUrl(cfg.slug,out.appointment.tracking_code)}`:''}\n\nDepois, envie *ACOMPANHAR* aqui no WhatsApp para consultar.`);
    }
    const charge=valorCobranca(d.servico.preco,cfg.pagamento_agendamento,cfg.percentual_sinal);if(!(charge>0))throw new Error('O serviço não possui valor válido para cobrança.');
    if(d.forma==='dinheiro'){
      const out=await createTrustedAppointment({...base,origem:'whatsapp_dinheiro',formaPagamento:'dinheiro',statusPagamento:'aguardando',valorCobrado:charge,valorPago:0});if(!out.ok)throw new Error(out.error);await resetSession(integ.barbearia_id,from);return sendText(integ,from,`Agendamento realizado! ✅\nPagamento em dinheiro no atendimento.\n${d.data.split('-').reverse().join('/')} às ${String(d.horario).slice(0,5)}.\n\nCódigo de acompanhamento: *${formatTrackingCode(out.appointment.tracking_code)}*${trackingUrl(cfg.slug,out.appointment.tracking_code)?`\nAcompanhe: ${trackingUrl(cfg.slug,out.appointment.tracking_code)}`:''}\n\nDepois, envie *ACOMPANHAR* aqui no WhatsApp para consultar.`);
    }
    const db=await pool.connect();let reserva;try{await db.query('BEGIN');await lockSlot(db,integ.barbearia_id,d.barbeiro.id,d.data);const ctx=await slotContext(db,{barbeariaId:integ.barbearia_id,barbeiroId:d.barbeiro.id,servicoId:d.servico.id,data:d.data,horario:d.horario});if(!ctx.ok){await db.query('ROLLBACK');throw new Error(ctx.error)}const status=d.forma==='pix_manual'?'aguardando_pix_manual':'aguardando_pagamento',mins=Math.max(5,Math.min(30,Number(process.env.BOOKING_HOLD_MINUTES||15)));reserva=(await db.query(`INSERT INTO reservas_pagamento(barbearia_id,barbeiro_id,servico_id,nome,telefone,email,data,horario,valor_total,valor_cobrado,status,expira_em,forma_pagamento) VALUES($1,$2,$3,$4,$5,NULL,$6,$7,$8,$9,$10,NOW()+($11*INTERVAL '1 minute'),$12) RETURNING *`,[integ.barbearia_id,d.barbeiro.id,d.servico.id,d.nome,digits(from),d.data,d.horario,Number(d.servico.preco||0),charge,status,mins,d.forma])).rows[0];await db.query('COMMIT')}catch(e){try{await db.query('ROLLBACK')}catch{}throw e}finally{db.release()}
    await resetSession(integ.barbearia_id,from);
    if(d.forma==='pix_manual')return sendText(integ,from,`Seu horário foi reservado. Faça o Pix de R$ ${charge.toFixed(2).replace('.',',')}.\n\nChave: ${cfg.pix_chave}\nRecebedor: ${cfg.pix_nome||cfg.nome}${cfg.pix_banco?`\nBanco: ${cfg.pix_banco}`:''}\n\nA barbearia confirmará após verificar o pagamento.`);
    if(d.forma==='mercado_pago'){
      if(!cfg.mp_conectado)throw new Error('Mercado Pago não está conectado.');const token=await getSellerAccessToken(integ.barbearia_id);const mp=await criarPreferenciaAgendamento({reservaId:reserva.id,reservaToken:reserva.public_token,barbeariaId:integ.barbearia_id,slug:cfg.slug,servicoId:d.servico.id,servicoNome:d.servico.nome,valor:charge,nome:d.nome,email:null,accessToken:token,aceitarPix:cfg.mp_aceitar_pix!==false,aceitarCartao:cfg.mp_aceitar_cartao!==false});const checkout=safeMercadoPagoCheckoutUrl(mp.init_point);if(!checkout)throw new Error('Link de pagamento inválido');await pool.query(`UPDATE reservas_pagamento SET mp_preference_id=$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3`,[mp.id,reserva.id,integ.barbearia_id]);return sendText(integ,from,`Seu horário foi reservado. ✅\n\nPague pelo link para confirmar:\n${checkout}\n\nA reserva expira em alguns minutos.`);
    }
    throw new Error('Forma de pagamento indisponível.');
  }catch(e){console.error('whatsapp_booking_finish',{tenant:integ.barbearia_id,message:e.message});await resetSession(integ.barbearia_id,from);return sendText(integ,from,'Não consegui finalizar o agendamento agora. Digite *oi* para tentar novamente ou fale com a barbearia.')}
}
async function sendTemplate(integ,to,name,params=[],language='pt_BR',options={}){return providers.sendTemplate(integ,to,name,params,language,options)}
module.exports={integrationByPhoneId,sendText,sendTemplate,processIncoming};
