const path=require('path');const express=require('express');const cors=require('cors');const helmet=require('helmet');const {rateLimit}=require('express-rate-limit');const {requestContext}=require('./middlewares/observability');
const operacao=require('./routes/operacao'),master=require('./routes/master'),whatsapp=require('./routes/whatsapp'),ai=require('./routes/ai'),uploads=require('./routes/uploads'),automacoes=require('./routes/automacoes'),pagamentos=require('./routes/pagamentos'),auth=require('./routes/auth'),clientes=require('./routes/clientes'),barbeiros=require('./routes/barbeiros'),servicos=require('./routes/servicos'),agendamentos=require('./routes/agendamentos'),tenant=require('./routes/tenant'),publico=require('./routes/publico'),integracoes=require('./routes/integracoes'),support=require('./routes/support'),store=require('./routes/store'),storePublic=require('./routes/storePublic');

if(process.env.NODE_ENV==='production'){
  const required=['JWT_SECRET','APP_URL','APP_SECRETS_ENCRYPTION_KEY','MP_WEBHOOK_SECRET'];
  if(process.env.WHATSAPP_ENABLED==='true')required.push('META_WHATSAPP_APP_SECRET');
  if(process.env.REQUIRE_TURNSTILE!=='false')required.push('TURNSTILE_SECRET_KEY','TURNSTILE_SITE_KEY');
  if(process.env.ALLOW_PUBLIC_REGISTRATION!=='false'||process.env.PUBLIC_BOOKING_REQUIRE_OTP!=='false')required.push('RESEND_API_KEY','EMAIL_FROM');
  const missing=required.filter(k=>!process.env[k]);if(missing.length)throw new Error(`Configuração segura ausente: ${missing.join(', ')}`);
}
const app=express();app.set('trust proxy',1);app.disable('x-powered-by');
app.use(helmet({
  contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'",'https://challenges.cloudflare.com','https://sdk.mercadopago.com','https://www.mercadopago.com','https://www.mercadopago.com.br'],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https:'],fontSrc:["'self'",'data:'],connectSrc:["'self'",'https://challenges.cloudflare.com','https://api.mercadopago.com','https://www.mercadopago.com','https://www.mercadopago.com.br'],frameSrc:['https://challenges.cloudflare.com','https://www.mercadopago.com','https://www.mercadopago.com.br'],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"],frameAncestors:["'none'"],upgradeInsecureRequests:process.env.NODE_ENV==='production'?[]:null}},
  referrerPolicy:{policy:'strict-origin-when-cross-origin'},crossOriginEmbedderPolicy:false
}));
const allowedOrigins=new Set();if(process.env.APP_URL){try{allowedOrigins.add(new URL(process.env.APP_URL).origin)}catch{}}if(process.env.NODE_ENV!=='production')['http://localhost:3001','http://127.0.0.1:3001','http://localhost:5500','http://127.0.0.1:5500'].forEach(x=>allowedOrigins.add(x));
app.use(cors({origin(origin,cb){if(!origin||allowedOrigins.has(origin))return cb(null,true);cb(new Error('Origem não permitida pelo CORS'))},credentials:true,methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Request-Id','X-Cron-Secret','X-Signature','X-CSRF-Token']}));
app.use(express.json({limit:'200kb',verify:(req,res,buf)=>{req.rawBody=Buffer.from(buf)}}));app.use(requestContext);app.use('/api',(req,res,next)=>{res.setHeader('Cache-Control','no-store');next()});
const gl=rateLimit({windowMs:60000,limit:Number(process.env.API_RATE_LIMIT_PER_MINUTE||300),standardHeaders:'draft-8',legacyHeaders:false});const al=rateLimit({windowMs:15*60000,limit:Number(process.env.AUTH_RATE_LIMIT_PER_15_MIN||30),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas. Aguarde alguns minutos e tente novamente.'}});const sensitive=rateLimit({windowMs:10*60000,limit:Number(process.env.SENSITIVE_AUTH_RATE_LIMIT_PER_10_MIN||10),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas de segurança. Aguarde e tente novamente.'}});const supportLimit=rateLimit({windowMs:15*60000,limit:Number(process.env.SUPPORT_RATE_LIMIT_PER_15_MIN||20),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitos chamados em pouco tempo. Aguarde antes de tentar novamente.'}});const uploadLimit=rateLimit({windowMs:10*60000,limit:Number(process.env.UPLOAD_RATE_LIMIT_PER_10_MIN||20),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitos uploads. Aguarde e tente novamente.'}});const otpLimit=rateLimit({windowMs:30*60000,limit:Number(process.env.PUBLIC_OTP_RATE_LIMIT_PER_30_MIN||10),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas solicitações de código. Aguarde antes de tentar novamente.'}});const pl=rateLimit({windowMs:60000,limit:Number(process.env.PUBLIC_RATE_LIMIT_PER_MINUTE||120),standardHeaders:'draft-8',legacyHeaders:false});const publicTokenLimit=rateLimit({windowMs:15*60000,limit:Number(process.env.PUBLIC_TOKEN_ATTEMPTS_PER_15_MIN||20),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas com código seguro. Aguarde alguns minutos e tente novamente.'}});
app.use('/api',gl);app.use('/api/auth/login',al);app.use('/api/auth/registrar',al);app.use('/api/auth/reenviar-verificacao',al);app.use('/api/auth/solicitar-reset',al);app.use('/api/auth/mfa',sensitive);app.use('/api/auth/change-password',sensitive);app.use('/api/auth/step-up',sensitive);app.use('/api/suporte/tickets',supportLimit);app.use('/api/uploads',uploadLimit);app.use('/api/publico/:slug/otp/solicitar',otpLimit);app.use('/api/publico/:slug/agendamentos',publicTokenLimit);app.use('/api/publico/:slug/reservas',publicTokenLimit);app.use('/api/publico',pl);
app.get('/api/health/live',(req,res)=>res.json({ok:true,servico:'BarberFlow API',versao:process.env.RELEASE_VERSION||'2.7.1'}));app.get('/api/health/ready',async(req,res)=>{try{const pool=require('./config/db');const inicio=Date.now();await pool.query('SELECT 1');res.json({ok:true,banco:'ok',latencia_ms:Date.now()-inicio,versao:process.env.RELEASE_VERSION||'2.7.1'})}catch{res.status(503).json({ok:false,banco:'erro',request_id:req.requestId})}});app.get('/api/health',(req,res)=>res.json({ok:true,servico:'BarberFlow API'}));
app.use('/api/suporte',support);app.use('/api/loja',store);app.use('/api/publico',storePublic);app.use('/api/pagamentos',pagamentos);app.use('/api/operacao',operacao);app.use('/api/whatsapp',whatsapp);app.use('/api/ia',ai);app.use('/api/cron/automacoes',automacoes);app.use('/api/master',master);app.use('/api/uploads',uploads);app.use('/api/auth',auth);app.use('/api/publico',publico);app.use('/api/webhooks',integracoes);app.use('/api/clientes',clientes);app.use('/api/barbeiros',barbeiros);app.use('/api/servicos',servicos);app.use('/api/agendamentos',agendamentos);app.use('/api',tenant);
const frontend=path.resolve(__dirname,'../../frontend');app.use((req,res,next)=>{if(req.method==='GET'&&(req.path==='/'||/\.(?:html|js|css)$/i.test(req.path)))res.setHeader('Cache-Control','no-store, max-age=0');next()});app.use(express.static(frontend,{maxAge:0,etag:true}));app.get('/agendar/:slug',(req,res)=>res.sendFile(path.join(frontend,'publico.html')));app.get('/loja/:slug',(req,res)=>res.sendFile(path.join(frontend,'loja.html')));app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return next();if(req.method==='GET')return res.sendFile(path.join(frontend,'index.html'));next()});app.use((req,res)=>res.status(404).json({erro:'Rota não encontrada',request_id:req.requestId}));
app.use((err,req,res,next)=>{console.error(JSON.stringify({nivel:'error',evento:'request_error',request_id:req.requestId,mensagem:err.message,stack:process.env.NODE_ENV==='production'?undefined:err.stack}));if(err.message==='Origem não permitida pelo CORS')return res.status(403).json({erro:'Origem não permitida',request_id:req.requestId});res.status(500).json({erro:'Erro interno do servidor',request_id:req.requestId})});module.exports=app;
