const path=require('path');const express=require('express');const cors=require('cors');const helmet=require('helmet');const {rateLimit}=require('express-rate-limit');const {requestContext}=require('./middlewares/observability');
const advanced=require('./routes/advanced'),operacao=require('./routes/operacao'),master=require('./routes/master'),whatsapp=require('./routes/whatsapp'),ai=require('./routes/ai'),uploads=require('./routes/uploads'),automacoes=require('./routes/automacoes'),pagamentos=require('./routes/pagamentos'),auth=require('./routes/auth'),clientes=require('./routes/clientes'),barbeiros=require('./routes/barbeiros'),servicos=require('./routes/servicos'),agendamentos=require('./routes/agendamentos'),tenant=require('./routes/tenant'),publico=require('./routes/publico'),integracoes=require('./routes/integracoes'),support=require('./routes/support'),notificacoes=require('./routes/notificacoes'),store=require('./routes/store'),storePublic=require('./routes/storePublic'),marketing=require('./routes/marketing'),marketingPublic=require('./routes/marketingPublic'),legal=require('./routes/legal');

if(process.env.NODE_ENV==='production'){
  // Só bloqueia o boot por configuração necessária para servir a aplicação.
  // Integrações opcionais (billing externo e backup remoto) falham fechadas no próprio recurso/job.
  const required=['JWT_SECRET','APP_URL','DB_HOST','DB_NAME','DB_USER','DB_PASSWORD','APP_SECRETS_ENCRYPTION_KEY','BOOKING_OTP_PEPPER','CRON_SECRET','MP_WEBHOOK_TENANT_SECRET','TURNSTILE_SECRET_KEY','TURNSTILE_SITE_KEY','RESEND_API_KEY','EMAIL_FROM','DB_SSL'];
  const missing=required.filter(k=>!process.env[k]);if(missing.length)throw new Error(`Configuração segura ausente: ${missing.join(', ')}`);
  const mandatorySecrets=['JWT_SECRET','APP_SECRETS_ENCRYPTION_KEY','BOOKING_OTP_PEPPER','CRON_SECRET','MP_WEBHOOK_TENANT_SECRET'];
  const optionalSecrets=['LOGIN_THROTTLE_SECRET','BILLING_WEBHOOK_SECRET','BACKUP_ENCRYPTION_KEY'];
  for(const k of mandatorySecrets)if(String(process.env[k]).length<48||/change.?me|troque|example|barberflow|eliteflow/i.test(process.env[k]))throw new Error(`Segredo inseguro em ${k}`);
  for(const k of optionalSecrets)if(process.env[k]&&(String(process.env[k]).length<48||/change.?me|troque|example|barberflow|eliteflow/i.test(process.env[k])))throw new Error(`Segredo inseguro em ${k}`);
  const configuredSecrets=[...mandatorySecrets,...optionalSecrets].filter(k=>process.env[k]);
  if(new Set(configuredSecrets.map(k=>process.env[k])).size!==configuredSecrets.length)throw new Error('Cada finalidade sensível configurada deve usar um segredo diferente');
  {const u=new URL(process.env.APP_URL);if(u.protocol!=='https:'||u.username||u.password)throw new Error('APP_URL deve ser HTTPS e não pode conter credenciais')}
  if(process.env.BACKUP_UPLOAD_URL){const u=new URL(process.env.BACKUP_UPLOAD_URL);if(u.protocol!=='https:'||u.username||u.password)throw new Error('BACKUP_UPLOAD_URL deve ser HTTPS e não pode conter credenciais');if(!process.env.BACKUP_ENCRYPTION_KEY)throw new Error('BACKUP_ENCRYPTION_KEY é obrigatório quando BACKUP_UPLOAD_URL estiver configurada')}
  for(const k of ['MP_OAUTH_REDIRECT_URI','EVOLUTION_API_URL','NFSE_API_URL','ALERT_WEBHOOK_URL','AUTOMATION_WEBHOOK_URL'])if(process.env[k]){const u=new URL(process.env[k]);if(u.protocol!=='https:'||u.username||u.password)throw new Error(`${k} deve ser HTTPS e não pode conter credenciais`)}
  if(process.env.MP_OAUTH_REDIRECT_URI&&new URL(process.env.MP_OAUTH_REDIRECT_URI).origin!==new URL(process.env.APP_URL).origin)throw new Error('MP_OAUTH_REDIRECT_URI deve usar a mesma origem de APP_URL');
  if(process.env.ALLOW_LEGACY_PLATFORM_MP_ENV==='true')throw new Error('ALLOW_LEGACY_PLATFORM_MP_ENV não é permitido em produção');
}
const app=express();app.set('trust proxy',1);app.disable('x-powered-by');
app.use(helmet({
  contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'",'https://challenges.cloudflare.com'],scriptSrcAttr:["'none'"],styleSrc:["'self'",'https://fonts.googleapis.com'],styleSrcAttr:["'unsafe-inline'"],imgSrc:["'self'",'data:','https:'],fontSrc:["'self'",'data:','https://fonts.gstatic.com'],connectSrc:["'self'",'https://challenges.cloudflare.com'],frameSrc:['https://challenges.cloudflare.com'],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"],frameAncestors:["'none'"],upgradeInsecureRequests:process.env.NODE_ENV==='production'?[]:null}},
  referrerPolicy:{policy:'strict-origin-when-cross-origin'},crossOriginEmbedderPolicy:false
}));
app.use((req,res,next)=>{res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()');if(req.originalUrl.length>2048)return res.status(414).json({erro:'URL muito longa'});next()});
const allowedOrigins=new Set();if(process.env.APP_URL){try{allowedOrigins.add(new URL(process.env.APP_URL).origin)}catch{}}if(process.env.NODE_ENV!=='production')['http://localhost:3001','http://127.0.0.1:3001','http://localhost:5500','http://127.0.0.1:5500'].forEach(x=>allowedOrigins.add(x));
app.use(cors({origin(origin,cb){if(!origin||allowedOrigins.has(origin))return cb(null,true);cb(new Error('Origem não permitida pelo CORS'))},credentials:true,methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Request-Id','X-Cron-Secret','X-Signature','X-CSRF-Token']}));
app.use(express.json({limit:'200kb',verify:(req,res,buf)=>{req.rawBody=Buffer.from(buf)}}));app.use(express.urlencoded({extended:false,limit:'100kb'}));app.use(requestContext);app.use('/api',(req,res,next)=>{res.setHeader('Cache-Control','no-store');next()});
function envLimit(name,fallback,min,max){const n=Number(process.env[name]);return Number.isInteger(n)&&n>=min&&n<=max?n:fallback}
const gl=rateLimit({windowMs:60000,limit:envLimit('API_RATE_LIMIT_PER_MINUTE',300,30,1000),standardHeaders:'draft-8',legacyHeaders:false});const marketingLinkLimit=rateLimit({windowMs:60000,limit:envLimit('MARKETING_LINK_RATE_LIMIT_PER_MINUTE',90,10,300),standardHeaders:'draft-8',legacyHeaders:false});const al=rateLimit({windowMs:15*60000,limit:envLimit('AUTH_RATE_LIMIT_PER_15_MIN',30,5,100),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas. Aguarde alguns minutos e tente novamente.'}});const sensitive=rateLimit({windowMs:10*60000,limit:envLimit('SENSITIVE_AUTH_RATE_LIMIT_PER_10_MIN',10,3,30),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas de segurança. Aguarde e tente novamente.'}});const supportLimit=rateLimit({windowMs:15*60000,limit:envLimit('SUPPORT_RATE_LIMIT_PER_15_MIN',20,3,100),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitos chamados em pouco tempo. Aguarde antes de tentar novamente.'}});const uploadLimit=rateLimit({windowMs:10*60000,limit:envLimit('UPLOAD_RATE_LIMIT_PER_10_MIN',20,2,100),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitos uploads. Aguarde e tente novamente.'}});const otpLimit=rateLimit({windowMs:30*60000,limit:envLimit('PUBLIC_OTP_RATE_LIMIT_PER_30_MIN',10,2,30),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas solicitações de código. Aguarde antes de tentar novamente.'}});const pl=rateLimit({windowMs:60000,limit:envLimit('PUBLIC_RATE_LIMIT_PER_MINUTE',120,20,300),standardHeaders:'draft-8',legacyHeaders:false});const publicTokenLimit=rateLimit({windowMs:15*60000,limit:envLimit('PUBLIC_TOKEN_ATTEMPTS_PER_15_MIN',20,3,50),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas com código seguro. Aguarde alguns minutos e tente novamente.'}});const checkoutLimit=rateLimit({windowMs:10*60000,limit:envLimit('PUBLIC_CHECKOUT_RATE_LIMIT_PER_10_MIN',30,3,100),standardHeaders:'draft-8',legacyHeaders:false,message:{erro:'Muitas tentativas de checkout. Aguarde e tente novamente.'}});const cronLimit=rateLimit({windowMs:5*60000,limit:envLimit('CRON_RATE_LIMIT_PER_5_MIN',30,3,100),standardHeaders:'draft-8',legacyHeaders:false});
app.use('/api',gl);app.use('/api/auth/login',al);app.use('/api/auth/registrar',al);app.use('/api/auth/reenviar-verificacao',al);app.use('/api/auth/solicitar-reset',al);app.use('/api/auth/validar-reset',sensitive);app.use('/api/auth/redefinir-senha',sensitive);app.use('/api/auth/mfa',sensitive);app.use('/api/auth/change-password',sensitive);app.use('/api/auth/step-up',sensitive);app.use('/api/master/barbearias',(req,res,next)=>req.method==='DELETE'?sensitive(req,res,next):next());app.use('/api/suporte/tickets',supportLimit);app.use('/api/uploads',uploadLimit);app.use('/api/publico/:slug/otp/solicitar',otpLimit);app.use('/api/publico/:slug/agendamentos',publicTokenLimit);app.use('/api/publico/:slug/acompanhar',publicTokenLimit);app.use('/api/publico/:slug/reservas',publicTokenLimit);app.use('/api/publico/:slug/loja',checkoutLimit);app.use('/api/cron',cronLimit);app.use('/api/webhooks/processar-pendentes',cronLimit);app.use('/api/publico',pl);
app.get('/api/health/live',(req,res)=>res.json({ok:true}));app.get('/api/health/ready',async(req,res)=>{try{const pool=require('./config/db');await pool.query('SELECT 1');res.json({ok:true})}catch{res.status(503).json({ok:false,request_id:req.requestId})}});app.get('/api/health',(req,res)=>res.json({ok:true}));
app.use('/api/legal',legal);app.use('/m',marketingLinkLimit,marketingPublic);app.use('/api/suporte',support);app.use('/api/notificacoes',notificacoes);app.use('/api/marketing',marketing);app.use('/api/loja',store);app.use('/api/publico',storePublic);app.use('/api/pagamentos',pagamentos);app.use('/api/avancado',advanced);app.use('/api/operacao',operacao);app.use('/api/whatsapp',whatsapp);app.use('/api/ia',ai);app.use('/api/cron/automacoes',automacoes);app.use('/api/master',master);app.use('/api/uploads',uploads);app.use('/api/auth',auth);app.use('/api/publico',publico);app.use('/api/webhooks',integracoes);app.use('/api/clientes',clientes);app.use('/api/barbeiros',barbeiros);app.use('/api/servicos',servicos);app.use('/api/agendamentos',agendamentos);app.use('/api',tenant);
const frontend=path.resolve(__dirname,'../../frontend');app.use((req,res,next)=>{if(req.method==='GET'&&(req.path==='/'||/\.(?:html|js|css)$/i.test(req.path)))res.setHeader('Cache-Control','no-store, max-age=0');next()});app.use(express.static(frontend,{maxAge:0,etag:true}));app.get('/agendar/:slug',(req,res)=>res.sendFile(path.join(frontend,'publico.html')));app.get('/loja/:slug',(req,res)=>{if(process.env.ENABLE_PUBLIC_STORE!=='true')return res.status(404).send('Vitrine online indisponível');res.sendFile(path.join(frontend,'loja.html'))});app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return next();if(req.method==='GET')return res.sendFile(path.join(frontend,'index.html'));next()});app.use((req,res)=>res.status(404).json({erro:'Rota não encontrada',request_id:req.requestId}));
app.use((err,req,res,next)=>{console.error(JSON.stringify({nivel:'error',evento:'request_error',request_id:req.requestId,mensagem:err.message,stack:process.env.NODE_ENV==='production'?undefined:err.stack}));if(err.message==='Origem não permitida pelo CORS')return res.status(403).json({erro:'Origem não permitida',request_id:req.requestId});res.status(500).json({erro:'Erro interno do servidor',request_id:req.requestId})});module.exports=app;
