const express=require('express');
const pool=require('../config/db');
const {autenticar,exigirAssinatura,exigirPapel}=require('../middlewares/auth');
const {horaParaMinutos,minutosParaHora}=require('../utils/time');
const {notificar}=require('../services/notifications');
const {intId,isoDate,hhmm,dateWithinBookingWindow,cleanText,finiteMoney}=require('../utils/validation');
const {lockSlot,slotContext,HOLD_STATUSES}=require('../services/booking');
const {notifyWaitlistForSlot}=require('../services/advancedOps');
const {sendAppointmentTracking}=require('../services/bookingTracking');
const router=express.Router();router.use(autenticar,exigirAssinatura);
const VALIDOS=['agendado','confirmado','em_atendimento','concluido','cancelado','nao_compareceu'];
const TRANSICOES={agendado:new Set(['confirmado','em_atendimento','cancelado','nao_compareceu']),confirmado:new Set(['em_atendimento','concluido','cancelado','nao_compareceu']),em_atendimento:new Set(['concluido','cancelado']),concluido:new Set(),cancelado:new Set(),nao_compareceu:new Set()};
async function horariosDisponiveis(barbeariaId,barbeiroId,servicoId,data,ignorarId=null,db=pool){
  const bid=intId(barbeiroId),sid=intId(servicoId);if(!bid||!sid||!dateWithinBookingWindow(String(data||'')))return [];
  const s=await db.query(`SELECT duracao FROM servicos WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[sid,barbeariaId]);if(!s.rowCount)return [];
  const dur=Number(s.rows[0].duracao);const dow=Number((await db.query(`SELECT EXTRACT(ISODOW FROM $1::date) dia`,[data])).rows[0].dia);
  const exp=await db.query(`SELECT hora_inicio,hora_fim FROM horarios_trabalho WHERE barbeiro_id=$1 AND barbearia_id=$2 AND dia_semana=$3`,[bid,barbeariaId,dow]);if(!exp.rowCount)return [];
  const vals=[barbeariaId,bid,data];let sql=`SELECT a.id,a.horario,s.duracao FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND a.barbeiro_id=$2 AND a.data=$3 AND a.status NOT IN ('cancelado','nao_compareceu')`;
  if(ignorarId){vals.push(intId(ignorarId));sql+=` AND a.id<>$4`;}
  const ag=(await db.query(sql,vals)).rows;
  const holds=(await db.query(`SELECT horario,(SELECT duracao FROM servicos s WHERE s.id=r.servico_id AND s.barbearia_id=r.barbearia_id) duracao FROM reservas_pagamento r WHERE r.barbearia_id=$1 AND r.barbeiro_id=$2 AND r.data=$3 AND r.status=ANY($4::text[]) AND r.expira_em>NOW()`,[barbeariaId,bid,data,HOLD_STATUSES])).rows;
  const ocupados=[...ag,...holds];const inicio=horaParaMinutos(exp.rows[0].hora_inicio),fim=horaParaMinutos(exp.rows[0].hora_fim),out=[];
  for(let m=inicio;m+dur<=fim;m+=30){const conflito=ocupados.some(a=>m<horaParaMinutos(a.horario)+Number(a.duracao)&&m+dur>horaParaMinutos(a.horario));if(!conflito)out.push(minutosParaHora(m));}return out;
}
router.get('/horarios-disponiveis',async(req,res)=>{try{const {barbeiro_id,servico_id,data,ignorar_id}=req.query;if(!intId(barbeiro_id)||!intId(servico_id)||!dateWithinBookingWindow(String(data||'')))return res.status(400).json({erro:'Parâmetros de disponibilidade inválidos'});res.json(await horariosDisponiveis(req.usuario.barbearia_id,barbeiro_id,servico_id,data,ignorar_id||null));}catch(e){console.error(e);res.status(500).json({erro:'Erro ao calcular horários'});}});
router.get('/',async(req,res)=>{try{const{data,barbeiro,status,inicio,fim}=req.query;const dataVal=data?isoDate(data):null,inicioVal=inicio?isoDate(inicio):null,fimVal=fim?isoDate(fim):null,barbeiroVal=barbeiro?intId(barbeiro):null;if(data&&!dataVal)return res.status(400).json({erro:'Data inválida'});if(inicio&&!inicioVal)return res.status(400).json({erro:'Data inicial inválida'});if(fim&&!fimVal)return res.status(400).json({erro:'Data final inválida'});if(barbeiro&&!barbeiroVal)return res.status(400).json({erro:'Barbeiro inválido'});if(inicioVal&&fimVal&&inicioVal>fimVal)return res.status(400).json({erro:'Período inválido'});if(status&&!VALIDOS.includes(status))return res.status(400).json({erro:'Status inválido'});const vals=[req.usuario.barbearia_id];const filtros=['a.barbearia_id=$1'];if(req.usuario.papel==='barbeiro'){if(!req.usuario.barbeiro_id)return res.json([]);vals.push(req.usuario.barbeiro_id);filtros.push(`a.barbeiro_id=$${vals.length}`);}if(dataVal){vals.push(dataVal);filtros.push(`a.data=$${vals.length}`);}if(barbeiroVal){vals.push(barbeiroVal);filtros.push(`a.barbeiro_id=$${vals.length}`);}if(status){vals.push(status);filtros.push(`a.status=$${vals.length}`);}if(inicioVal){vals.push(inicioVal);filtros.push(`a.data >= $${vals.length}`);}if(fimVal){vals.push(fimVal);filtros.push(`a.data <= $${vals.length}`);}const r=await pool.query(`SELECT a.id,a.cliente_id,a.barbeiro_id,a.servico_id,a.data,a.horario,a.status,a.observacoes,c.nome cliente,c.telefone,b.nome barbeiro,s.nome servico,s.duracao,COALESCE(a.valor_servico,s.preco) preco,a.forma_pagamento,a.status_pagamento,a.valor_cobrado,a.valor_pago,a.valor_final,a.reembolso_status,a.tracking_code FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id AND c.barbearia_id=a.barbearia_id JOIN barbeiros b ON b.id=a.barbeiro_id AND b.barbearia_id=a.barbearia_id JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE ${filtros.join(' AND ')} ORDER BY a.data,a.horario`,vals);res.json(r.rows);}catch(e){console.error(e);res.status(500).json({erro:'Erro ao buscar agendamentos'});}});
router.post('/',exigirPapel('dono','gerente','recepcao'),async(req,res)=>{const client=await pool.connect();try{const clienteId=intId(req.body.cliente_id),barbeiroId=intId(req.body.barbeiro_id),servicoId=intId(req.body.servico_id),data=String(req.body.data||''),horario=hhmm(req.body.horario),observacoes=cleanText(req.body.observacoes,1000)||null;if(!clienteId||!barbeiroId||!servicoId||!horario||!dateWithinBookingWindow(data))return res.status(400).json({erro:'Dados do agendamento inválidos'});await client.query('BEGIN');await lockSlot(client,req.usuario.barbearia_id,barbeiroId,data);if(!(await client.query(`SELECT 1 FROM clientes WHERE id=$1 AND barbearia_id=$2`,[clienteId,req.usuario.barbearia_id])).rowCount)throw new Error('Cliente inválido');const ctx=await slotContext(client,{barbeariaId:req.usuario.barbearia_id,barbeiroId,servicoId,data,horario});if(!ctx.ok)throw new Error(ctx.error||'Horário indisponível');const r=await client.query(`INSERT INTO agendamentos(barbearia_id,cliente_id,barbeiro_id,servico_id,data,horario,status,observacoes,origem,forma_pagamento,status_pagamento,valor_servico,valor_final) VALUES($1,$2,$3,$4,$5,$6,'agendado',$7,'painel','nao_informado','nao_exigido',$8,$8) RETURNING *`,[req.usuario.barbearia_id,clienteId,barbeiroId,servicoId,data,horario,observacoes,Number(ctx.servico.preco||0)]);await client.query('COMMIT');notificar('agendamento_criado',{barbearia_id:req.usuario.barbearia_id,agendamento_id:r.rows[0].id});sendAppointmentTracking({barbeariaId:req.usuario.barbearia_id,appointmentId:r.rows[0].id}).catch(()=>{});res.status(201).json(r.rows[0]);}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(e.message.includes('indispon')?409:400).json({erro:e.message||'Erro ao criar agendamento'});}finally{client.release();}});
router.put('/:id',exigirPapel('dono','gerente','recepcao'),async(req,res)=>{const client=await pool.connect();try{const id=intId(req.params.id),clienteId=intId(req.body.cliente_id),barbeiroId=intId(req.body.barbeiro_id),servicoId=intId(req.body.servico_id),data=String(req.body.data||''),horario=hhmm(req.body.horario),observacoes=cleanText(req.body.observacoes,1000)||null;if(!id||!clienteId||!barbeiroId||!servicoId||!horario||!dateWithinBookingWindow(data))return res.status(400).json({erro:'Dados do agendamento inválidos'});await client.query('BEGIN');const atual=(await client.query(`SELECT * FROM agendamentos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[id,req.usuario.barbearia_id])).rows[0];if(!atual){await client.query('ROLLBACK');return res.status(404).json({erro:'Agendamento não encontrado'});}if(['cancelado','concluido','nao_compareceu'].includes(atual.status))throw new Error('Este agendamento não pode mais ser editado');if(['pago','parcial'].includes(atual.status_pagamento)&&Number(servicoId)!==Number(atual.servico_id))throw new Error('Não altere o serviço de um agendamento que já possui pagamento');await lockSlot(client,req.usuario.barbearia_id,barbeiroId,data);if(!(await client.query(`SELECT 1 FROM clientes WHERE id=$1 AND barbearia_id=$2`,[clienteId,req.usuario.barbearia_id])).rowCount)throw new Error('Cliente inválido');const ctx=await slotContext(client,{barbeariaId:req.usuario.barbearia_id,barbeiroId,servicoId,data,horario,ignoreAppointmentId:id});if(!ctx.ok)throw new Error(ctx.error||'Horário indisponível');const valorServico=Number(servicoId)===Number(atual.servico_id)?Number(atual.valor_servico||ctx.servico.preco||0):Number(ctx.servico.preco||0);const r=await client.query(`UPDATE agendamentos SET cliente_id=$1,barbeiro_id=$2,servico_id=$3,data=$4,horario=$5,observacoes=$6,valor_servico=$7,valor_final=CASE WHEN status_pagamento IN ('pago','parcial') THEN valor_final ELSE $7 END WHERE id=$8 AND barbearia_id=$9 RETURNING *`,[clienteId,barbeiroId,servicoId,data,horario,observacoes,valorServico,id,req.usuario.barbearia_id]);await client.query('COMMIT');res.json(r.rows[0]);}catch(e){try{await client.query('ROLLBACK')}catch{}res.status(e.message.includes('indispon')?409:400).json({erro:e.message||'Erro ao editar agendamento'});}finally{client.release();}});
router.patch('/:id/status',async(req,res)=>{try{const id=intId(req.params.id),status=String(req.body.status||'');if(!id||!VALIDOS.includes(status))return res.status(400).json({erro:'Status inválido'});const atual=(await pool.query(`SELECT * FROM agendamentos WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows[0];if(!atual)return res.status(404).json({erro:'Agendamento não encontrado'});if(req.usuario.papel==='barbeiro'){if(!req.usuario.barbeiro_id||Number(atual.barbeiro_id)!==Number(req.usuario.barbeiro_id))return res.status(403).json({erro:'Sem permissão'});if(!['confirmado','em_atendimento','concluido','nao_compareceu'].includes(status))return res.status(403).json({erro:'Barbeiro não pode aplicar este status'});}if(atual.status!==status&&!TRANSICOES[atual.status]?.has(status))return res.status(409).json({erro:`Transição ${atual.status} → ${status} não permitida`});const refund=['pago','parcial'].includes(atual.status_pagamento)&&status==='cancelado'?'pendente':atual.reembolso_status;const r=await pool.query(`UPDATE agendamentos SET status=$1,reembolso_status=$2 WHERE id=$3 AND barbearia_id=$4 RETURNING *`,[status,refund,id,req.usuario.barbearia_id]);if(status==='concluido'&&r.rows[0].forma_pagamento==='dinheiro'&&r.rows[0].status_pagamento!=='pago')await pool.query(`UPDATE agendamentos SET status_pagamento='pago',valor_pago=COALESCE(NULLIF(valor_final,0),valor_servico,valor_cobrado,0) WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id]);notificar('agendamento_status',{barbearia_id:req.usuario.barbearia_id,agendamento_id:id,status});if(status==='confirmado'&&atual.status!=='confirmado')sendAppointmentTracking({barbeariaId:req.usuario.barbearia_id,appointmentId:id,confirmed:true}).catch(()=>{});if(status==='cancelado')notifyWaitlistForSlot({barbeariaId:req.usuario.barbearia_id,barbeiroId:atual.barbeiro_id,servicoId:atual.servico_id,data:atual.data,horario:atual.horario}).catch(()=>{});res.json(r.rows[0]);}catch(e){res.status(500).json({erro:'Erro ao atualizar status'});}});
router.patch('/:id/pagamento',exigirPapel('dono','gerente','recepcao'),async(req,res)=>{try{const id=intId(req.params.id),status=String(req.body.status_pagamento||'');if(!id||!['aguardando','pago','parcial','reembolsado','falhou','nao_exigido'].includes(status))return res.status(400).json({erro:'Status de pagamento inválido'});const ag=(await pool.query(`SELECT * FROM agendamentos WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows[0];if(!ag)return res.status(404).json({erro:'Agendamento não encontrado'});let valor=finiteMoney(req.body.valor_pago??ag.valor_pago??0,{min:0,max:1_000_000});if(valor===null)return res.status(400).json({erro:'Valor pago inválido'});const total=Number(ag.valor_final||ag.valor_servico||0);if(status==='pago'&&valor<=0)valor=total;if(status==='pago'&&valor+0.009<total)return res.status(400).json({erro:'Valor insuficiente para marcar como pago; use pagamento parcial'});if(status==='parcial'&&(valor<=0||valor+0.009>=total))return res.status(400).json({erro:'Pagamento parcial deve ser maior que zero e menor que o total'});const r=await pool.query(`UPDATE agendamentos SET status_pagamento=$1,valor_pago=$2,reembolso_status=CASE WHEN $1='reembolsado' THEN 'concluido' ELSE reembolso_status END WHERE id=$3 AND barbearia_id=$4 RETURNING *`,[status,valor,id,req.usuario.barbearia_id]);res.json(r.rows[0]);}catch(e){res.status(500).json({erro:'Erro ao atualizar pagamento'});}});
router.delete('/:id',exigirPapel('dono','gerente','recepcao'),async(req,res)=>{try{const id=intId(req.params.id);const ag=(await pool.query(`SELECT * FROM agendamentos WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows[0];if(!ag)return res.status(404).json({erro:'Agendamento não encontrado'});if(['cancelado','concluido','nao_compareceu'].includes(ag.status))return res.status(409).json({erro:'Agendamento não pode ser cancelado neste estado'});const refund=['pago','parcial'].includes(ag.status_pagamento)?'pendente':ag.reembolso_status;const r=await pool.query(`UPDATE agendamentos SET status='cancelado',reembolso_status=$1 WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[refund,id,req.usuario.barbearia_id]);notifyWaitlistForSlot({barbeariaId:req.usuario.barbearia_id,barbeiroId:ag.barbeiro_id,servicoId:ag.servico_id,data:ag.data,horario:ag.horario}).catch(()=>{});res.json({mensagem:refund==='pendente'?'Agendamento cancelado. Reembolso pendente.':'Agendamento cancelado',agendamento:r.rows[0]});}catch(e){res.status(500).json({erro:'Erro ao cancelar agendamento'});}});
router.horariosDisponiveis=horariosDisponiveis;module.exports=router;
