const express=require('express');
const {autenticar,exigirPapel,exigirAssinatura,exigirStepUp}=require('../middlewares/auth');
const {contextoPlano,exigirRecurso}=require('../services/planos');
const {getAiConfig,updateAiConfig,getAiUsage}=require('../services/aiConfig');
const {allowedAiTools}=require('../services/aiPolicy');
const {available,model}=require('../services/aiAgent');
const {audit}=require('../services/audit');
const router=express.Router();
router.use(autenticar,exigirPapel('dono','gerente'),exigirAssinatura);
router.get('/status',async(req,res)=>{try{const ctx=await contextoPlano(req.usuario.barbearia_id),config=await getAiConfig(req.usuario.barbearia_id),uso=await getAiUsage(req.usuario.barbearia_id),premium=ctx.recursos.includes('ia_config'),infra=available(),motor=!!(premium&&ctx.recursos.includes('ia_whatsapp')&&infra&&config.ativo);res.json({fase:motor?'ativa':'disponivel',motor_ativo:motor,infra_disponivel:infra,modelo:model(),recurso_disponivel:premium,plano_efetivo:ctx.plano_efetivo,addon_elegivel:ctx.recursos.includes('ia_addon_elegivel'),incluido_no_premium:ctx.recursos.includes('ia_whatsapp'),config,ferramentas_permitidas:premium?allowedAiTools(config):[],uso});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar IA'})}});
router.put('/config',exigirRecurso('ia_config'),exigirStepUp,async(req,res)=>{try{if(req.body?.ativo===true&&!available())return res.status(503).json({erro:'Configure OPENAI_API_KEY no ambiente antes de ativar a IA'});const config=await updateAiConfig(req.usuario.barbearia_id,req.body||{});await audit(req,{acao:'ia.config.atualizada',barbeariaId:req.usuario.barbearia_id,alvoTipo:'ai_config',alvoId:req.usuario.barbearia_id,detalhes:{ativo:config.ativo,tom:config.tom,nome_assistente:config.nome_assistente}});res.json({mensagem:config.ativo?'IA ativada com fallback seguro para o fluxo clássico.':'Configuração da IA salva.',config,motor_ativo:config.ativo&&available(),ferramentas_permitidas:allowedAiTools(config)});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao salvar IA'})}});
module.exports=router;
