const express=require('express'); const pool=require('../config/db'); const {autenticar,exigirAssinatura,exigirPapel}=require('../middlewares/auth'); const router=express.Router(); router.use(autenticar,exigirAssinatura);
router.get('/',async(req,res)=>{try{const vals=[req.usuario.barbearia_id];let sql=`SELECT id,nome,telefone,ativo FROM barbeiros WHERE barbearia_id=$1`;if(req.usuario.papel==='barbeiro'){if(!req.usuario.barbeiro_id)return res.json([]);vals.push(req.usuario.barbeiro_id);sql+=` AND id=$2`;}sql+=` ORDER BY ativo DESC,nome`;const r=await pool.query(sql,vals);res.json(r.rows);}catch(e){res.status(500).json({erro:'Erro ao buscar barbeiros'});}});
router.post('/',exigirPapel('dono','gerente'),async(req,res)=>{try{const{nome,telefone}=req.body;if(!nome)return res.status(400).json({erro:'Nome é obrigatório'});const r=await pool.query(`INSERT INTO barbeiros(barbearia_id,nome,telefone,ativo) VALUES($1,$2,$3,true) RETURNING *`,[req.usuario.barbearia_id,nome,telefone||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(500).json({erro:'Erro ao criar barbeiro'});}});
router.put('/:id',exigirPapel('dono','gerente'),async(req,res)=>{try{const{nome,telefone,ativo}=req.body;const r=await pool.query(`UPDATE barbeiros SET nome=$1,telefone=$2,ativo=$3 WHERE id=$4 AND barbearia_id=$5 RETURNING *`,[nome,telefone||null,ativo!==false,req.params.id,req.usuario.barbearia_id]);if(!r.rowCount)return res.status(404).json({erro:'Barbeiro não encontrado'});res.json(r.rows[0]);}catch(e){res.status(500).json({erro:'Erro ao editar barbeiro'});}});
router.patch('/:id/status',exigirPapel('dono','gerente'),async(req,res)=>{try{const r=await pool.query(`UPDATE barbeiros SET ativo=$1 WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[!!req.body.ativo,req.params.id,req.usuario.barbearia_id]);if(!r.rowCount)return res.status(404).json({erro:'Barbeiro não encontrado'});res.json(r.rows[0]);}catch(e){res.status(500).json({erro:'Erro ao alterar barbeiro'});}});
router.get('/:id/horarios',async(req,res)=>{try{if(req.usuario.papel==='barbeiro'&&Number(req.params.id)!==Number(req.usuario.barbeiro_id))return res.status(403).json({erro:'Você só pode ver seu próprio expediente'});const r=await pool.query(`SELECT id,dia_semana,hora_inicio,hora_fim FROM horarios_trabalho WHERE barbeiro_id=$1 AND barbearia_id=$2 ORDER BY dia_semana`,[req.params.id,req.usuario.barbearia_id]);res.json(r.rows);}catch(e){res.status(500).json({erro:'Erro ao buscar horários'});}});
router.put('/:id/horarios',exigirPapel('dono','gerente'),async(req,res)=>{const client=await pool.connect();try{const dias=Array.isArray(req.body.horarios)?req.body.horarios:[];await client.query('BEGIN');const exists=await client.query(`SELECT 1 FROM barbeiros WHERE id=$1 AND barbearia_id=$2`,[req.params.id,req.usuario.barbearia_id]);if(!exists.rowCount){await client.query('ROLLBACK');return res.status(404).json({erro:'Barbeiro não encontrado'});}await client.query(`DELETE FROM horarios_trabalho WHERE barbeiro_id=$1 AND barbearia_id=$2`,[req.params.id,req.usuario.barbearia_id]);for(const d of dias){if(Number(d.dia_semana)<1||Number(d.dia_semana)>7||!d.hora_inicio||!d.hora_fim||d.hora_inicio>=d.hora_fim)throw new Error('Horário inválido');await client.query(`INSERT INTO horarios_trabalho(barbearia_id,barbeiro_id,dia_semana,hora_inicio,hora_fim) VALUES($1,$2,$3,$4,$5)`,[req.usuario.barbearia_id,req.params.id,Number(d.dia_semana),d.hora_inicio,d.hora_fim]);}await client.query('COMMIT');res.json({mensagem:'Expediente atualizado'});}catch(e){await client.query('ROLLBACK');console.error(e);res.status(400).json({erro:e.message||'Erro ao salvar expediente'});}finally{client.release();}});
router.delete('/:id',exigirPapel('dono','gerente'),async(req,res)=>{try{const ag=await pool.query(`SELECT 1 FROM agendamentos WHERE barbeiro_id=$1 AND barbearia_id=$2 LIMIT 1`,[req.params.id,req.usuario.barbearia_id]);if(ag.rowCount)return res.status(409).json({erro:'Barbeiro possui histórico. Desative em vez de excluir.'});const r=await pool.query(`DELETE FROM barbeiros WHERE id=$1 AND barbearia_id=$2 RETURNING id`,[req.params.id,req.usuario.barbearia_id]);if(!r.rowCount)return res.status(404).json({erro:'Barbeiro não encontrado'});res.json({mensagem:'Barbeiro excluído'});}catch(e){res.status(500).json({erro:'Erro ao excluir barbeiro'});}});
module.exports=router;
