const express=require('express');
const pool=require('../config/db');
const {autenticar,exigirAssinatura,exigirPapel}=require('../middlewares/auth');
const {normalizePhone,validEmail}=require('../utils/security');
const {intId,cleanText,emailOrNull,isoDate}=require('../utils/validation');
const router=express.Router();router.use(autenticar,exigirAssinatura);router.use(exigirPapel('dono','gerente','recepcao'));
function bodyCliente(body={}){
  const nome=cleanText(body.nome,120,{required:true});const telefone=normalizePhone(body.telefone);const email=emailOrNull(body.email,validEmail);const observacoes=cleanText(body.observacoes,1500)||null;const data_nascimento=body.data_nascimento?String(body.data_nascimento):null;const marketing_opt_in=body.marketing_opt_in===true;
  if(!nome)return {erro:'Nome é obrigatório'};if(telefone.length<10)return {erro:'Telefone inválido'};if(String(body.email||'').trim()&&!email)return {erro:'E-mail inválido'};if(data_nascimento&&!isoDate(data_nascimento))return {erro:'Data de nascimento inválida'};return {nome,telefone,email,observacoes,data_nascimento,marketing_opt_in};
}
router.get('/',async(req,res)=>{try{const b=req.usuario.barbearia_id;const q=cleanText(req.query.busca,120)||'';const vals=[b];let sql=`SELECT id,nome,telefone,email,observacoes,data_nascimento,marketing_opt_in,criado_em FROM clientes WHERE barbearia_id=$1`;if(q){vals.push(`%${q}%`);sql+=` AND (nome ILIKE $2 OR telefone ILIKE $2 OR COALESCE(email,'') ILIKE $2)`}sql+=' ORDER BY nome LIMIT 1000';res.json((await pool.query(sql,vals)).rows)}catch(e){console.error(e);res.status(500).json({erro:'Erro ao buscar clientes'})}});
router.get('/:id/historico',async(req,res)=>{try{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Cliente inválido'});const r=await pool.query(`SELECT a.id,a.data,a.horario,a.status,s.nome servico,COALESCE(a.valor_final,a.valor_servico,s.preco) preco,b.nome barbeiro FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id JOIN barbeiros b ON b.id=a.barbeiro_id AND b.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND a.cliente_id=$2 ORDER BY a.data DESC,a.horario DESC LIMIT 500`,[req.usuario.barbearia_id,id]);res.json(r.rows)}catch(e){res.status(500).json({erro:'Erro ao buscar histórico'})}});
router.post('/',async(req,res)=>{try{const v=bodyCliente(req.body);if(v.erro)return res.status(400).json({erro:v.erro});const tenant=req.usuario.barbearia_id;const dup=await pool.query(`SELECT id FROM clientes WHERE barbearia_id=$1 AND regexp_replace(COALESCE(telefone,''),'\\D','','g')=$2 LIMIT 1`,[tenant,v.telefone]);if(dup.rowCount)return res.status(409).json({erro:'Já existe um cliente com este telefone'});const r=await pool.query(`INSERT INTO clientes(barbearia_id,nome,telefone,email,observacoes,data_nascimento,marketing_opt_in,marketing_opt_in_em,marketing_opt_in_origem,marketing_opt_out_em) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $7 THEN NOW() ELSE NULL END,CASE WHEN $7 THEN 'painel' ELSE NULL END,NULL) RETURNING *`,[tenant,v.nome,v.telefone,v.email,v.observacoes,v.data_nascimento,v.marketing_opt_in]);res.status(201).json(r.rows[0])}catch(e){console.error(e);res.status(500).json({erro:'Erro ao cadastrar cliente'})}});
router.put('/:id',async(req,res)=>{try{const id=intId(req.params.id),v=bodyCliente(req.body);if(!id)return res.status(400).json({erro:'Cliente inválido'});if(v.erro)return res.status(400).json({erro:v.erro});const tenant=req.usuario.barbearia_id;const dup=await pool.query(`SELECT id FROM clientes WHERE barbearia_id=$1 AND id<>$2 AND regexp_replace(COALESCE(telefone,''),'\\D','','g')=$3 LIMIT 1`,[tenant,id,v.telefone]);if(dup.rowCount)return res.status(409).json({erro:'Já existe outro cliente com este telefone'});const r=await pool.query(`UPDATE clientes SET nome=$1,telefone=$2,email=$3,observacoes=$4,data_nascimento=$5,marketing_opt_in=$6,marketing_opt_in_em=CASE WHEN $6 AND marketing_opt_in=false THEN NOW() ELSE marketing_opt_in_em END,marketing_opt_in_origem=CASE WHEN $6 AND marketing_opt_in=false THEN 'painel' ELSE marketing_opt_in_origem END,marketing_opt_out_em=CASE WHEN $6 THEN NULL WHEN marketing_opt_in=true THEN NOW() ELSE marketing_opt_out_em END WHERE id=$7 AND barbearia_id=$8 RETURNING *`,[v.nome,v.telefone,v.email,v.observacoes,v.data_nascimento,v.marketing_opt_in,id,tenant]);if(!r.rowCount)return res.status(404).json({erro:'Cliente não encontrado'});res.json(r.rows[0])}catch(e){console.error(e);res.status(500).json({erro:'Erro ao editar cliente'})}});
router.delete('/:id',async(req,res)=>{try{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Cliente inválido'});const ag=await pool.query(`SELECT 1 FROM agendamentos WHERE cliente_id=$1 AND barbearia_id=$2 LIMIT 1`,[id,req.usuario.barbearia_id]);if(ag.rowCount)return res.status(409).json({erro:'Cliente possui histórico. Mantenha-o para preservar os agendamentos.'});const r=await pool.query(`DELETE FROM clientes WHERE id=$1 AND barbearia_id=$2 RETURNING id`,[id,req.usuario.barbearia_id]);if(!r.rowCount)return res.status(404).json({erro:'Cliente não encontrado'});res.json({mensagem:'Cliente excluído'})}catch(e){res.status(500).json({erro:'Erro ao excluir cliente'})}});
module.exports=router;
