const express=require('express');
const crypto=require('crypto');
const pool=require('../config/db');
const {autenticar,exigirAssinatura,exigirPapel,exigirStepUp}=require('../middlewares/auth');
const {exigirRecurso}=require('../services/planos');
const {cleanText,intId,finiteMoney}=require('../utils/validation');
const {resolveAudience,referralCode}=require('../services/marketing');
const wp=require('../services/whatsappProviders');

const router=express.Router();
router.use(autenticar,exigirAssinatura,exigirPapel('dono','gerente'),exigirRecurso('marketing'));
const tenant=req=>req.usuario.barbearia_id;
const SEGMENTS=new Set(['todos','aniversariantes','novos','inativos','vip','frequentes','faltosos','compradores_loja','carrinho_abandonado']);
function upperCode(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,40)}
function segment(v){const x=String(v||'todos').slice(0,40);return SEGMENTS.has(x)?x:'todos'}

router.get('/resumo',async(req,res)=>{try{
  const t=tenant(req);const [base,camp,delivery,cup,links,refs]=await Promise.all([
    pool.query(`SELECT COUNT(*)::int clientes,COUNT(*) FILTER(WHERE marketing_opt_in=true)::int optin,COUNT(*) FILTER(WHERE criado_em>=NOW()-INTERVAL '30 days')::int novos,COUNT(*) FILTER(WHERE data_nascimento IS NOT NULL AND EXTRACT(MONTH FROM data_nascimento)=EXTRACT(MONTH FROM CURRENT_DATE))::int aniversariantes FROM clientes WHERE barbearia_id=$1`,[t]),
    pool.query(`SELECT COUNT(*) FILTER(WHERE status='enviada')::int campanhas,COALESCE(SUM(enviados),0)::int enviados,COALESCE(SUM(erros),0)::int erros,COALESCE(SUM(cliques),0)::int cliques,COALESCE(SUM(conversoes),0)::int conversoes,COALESCE(SUM(receita),0)::numeric receita,COALESCE(SUM(investimento),0)::numeric investimento FROM marketing_campanhas WHERE barbearia_id=$1`,[t]),
    pool.query(`SELECT COUNT(*) FILTER(WHERE status IN ('entregue','lido'))::int entregues,COUNT(*) FILTER(WHERE status='lido')::int lidos FROM marketing_envios WHERE barbearia_id=$1`,[t]),
    pool.query(`SELECT COUNT(*) FILTER(WHERE ativo=true)::int ativos,COALESCE(SUM(usos),0)::int usos,COALESCE((SELECT SUM(valor_desconto) FROM marketing_cupom_usos WHERE barbearia_id=$1),0)::numeric descontos FROM marketing_cupons WHERE barbearia_id=$1`,[t]),
    pool.query(`SELECT COALESCE(SUM(cliques),0)::int cliques,COALESCE(SUM(conversoes),0)::int conversoes,COALESCE(SUM(receita),0)::numeric receita FROM marketing_links WHERE barbearia_id=$1`,[t]),
    pool.query(`SELECT COUNT(*)::int conversoes FROM marketing_indicacao_conversoes WHERE barbearia_id=$1`,[t])
  ]);
  const receita=Number(camp.rows[0].receita||0),inv=Number(camp.rows[0].investimento||0);
  res.json({clientes:base.rows[0],campanhas:{...camp.rows[0],...delivery.rows[0]},cupons:cup.rows[0],links:links.rows[0],indicacoes:refs.rows[0],roi:inv>0?Number(((receita-inv)/inv*100).toFixed(1)):null});
}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar Marketing'})}});

router.get('/publicos',async(req,res)=>{try{const rows=await resolveAudience(tenant(req),segment(req.query.segmento),req.query,500);res.json({total:rows.length,clientes:rows.slice(0,100)})}catch(e){console.error(e);res.status(500).json({erro:'Erro ao montar público'})}});
router.get('/publicos/exportar',async(req,res)=>{try{const rows=await resolveAudience(tenant(req),segment(req.query.segmento),req.query,5000);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="publico-marketing.csv"');res.send('\ufeffnome;telefone;email;visitas;total_gasto;ultima_visita\n'+rows.map(x=>[x.nome,x.telefone,x.email||'',x.visitas,x.total_gasto||0,x.ultima_visita||''].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'))}catch(e){res.status(500).send('Erro ao exportar')}});

router.get('/modelos',async(req,res)=>{res.json((await pool.query(`SELECT * FROM marketing_modelos WHERE barbearia_id=$1 ORDER BY ativo DESC,nome`,[tenant(req)])).rows)});
router.post('/modelos',async(req,res)=>{try{const x=req.body||{},nome=cleanText(x.nome,120,{required:true}),meta=cleanText(x.template_nome_meta,512),msg=cleanText(x.mensagem_preview,4000),idioma=cleanText(x.idioma,20)||'pt_BR',params=Array.isArray(x.parametros)?x.parametros.map(v=>cleanText(v,200)).filter(Boolean).slice(0,10):[];if(!nome)return res.status(400).json({erro:'Nome obrigatório'});const r=await pool.query(`INSERT INTO marketing_modelos(barbearia_id,nome,template_nome_meta,idioma,mensagem_preview,parametros) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[tenant(req),nome,meta||null,idioma,msg||null,JSON.stringify(params)]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({erro:'Não foi possível criar o modelo'})}});
router.delete('/modelos/:id',exigirPapel('dono'),exigirStepUp,async(req,res)=>{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Modelo inválido'});await pool.query(`DELETE FROM marketing_modelos WHERE id=$1 AND barbearia_id=$2`,[id,tenant(req)]);res.json({mensagem:'Modelo excluído'})});

router.get('/cupons',async(req,res)=>{res.json((await pool.query(`SELECT c.*,cl.nome cliente_nome FROM marketing_cupons c LEFT JOIN clientes cl ON cl.id=c.cliente_id AND cl.barbearia_id=c.barbearia_id WHERE c.barbearia_id=$1 ORDER BY c.ativo DESC,c.criado_em DESC`,[tenant(req)])).rows)});
router.post('/cupons',exigirStepUp,async(req,res)=>{try{
  const x=req.body||{},codigo=upperCode(x.codigo),tipo=['percentual','fixo'].includes(x.tipo)?x.tipo:null,valor=finiteMoney(x.valor,{min:.01,max:100000}),min=finiteMoney(x.pedido_minimo??0,{max:100000}),max=x.desconto_maximo===''||x.desconto_maximo==null?null:finiteMoney(x.desconto_maximo,{min:.01,max:100000}),cliente=intId(x.cliente_id);
  if(!codigo||!tipo||valor===null||min===null||(tipo==='percentual'&&valor>100))return res.status(400).json({erro:'Cupom inválido'});
  const start=x.inicio?new Date(x.inicio):null,end=x.fim?new Date(x.fim):null;if((start&&Number.isNaN(start.getTime()))||(end&&Number.isNaN(end.getTime()))||(start&&end&&end<=start))return res.status(400).json({erro:'Validade do cupom inválida'});
  const r=await pool.query(`INSERT INTO marketing_cupons(barbearia_id,cliente_id,codigo,descricao,tipo,valor,pedido_minimo,desconto_maximo,inicio,fim,limite_total,limite_por_cliente,ativo) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true) RETURNING *`,[tenant(req),cliente||null,codigo,cleanText(x.descricao,200)||null,tipo,valor,min,max,start?.toISOString()||null,end?.toISOString()||null,intId(x.limite_total)||null,Math.max(1,Math.min(100,Number(x.limite_por_cliente||1)))]);res.status(201).json(r.rows[0]);
}catch(e){if(e.code==='23505')return res.status(409).json({erro:'Código de cupom já existe'});res.status(400).json({erro:'Não foi possível criar o cupom'})}});
router.patch('/cupons/:id',exigirStepUp,async(req,res)=>{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Cupom inválido'});const r=await pool.query(`UPDATE marketing_cupons SET ativo=$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[!!req.body.ativo,id,tenant(req)]);if(!r.rowCount)return res.status(404).json({erro:'Cupom não encontrado'});res.json(r.rows[0])});
router.delete('/cupons/:id',exigirPapel('dono'),exigirStepUp,async(req,res)=>{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Cupom inválido'});const used=(await pool.query(`SELECT 1 FROM marketing_cupom_usos WHERE cupom_id=$1 LIMIT 1`,[id])).rowCount;if(used)return res.status(409).json({erro:'Cupom já foi utilizado. Desative-o em vez de excluir.'});await pool.query(`DELETE FROM marketing_cupons WHERE id=$1 AND barbearia_id=$2`,[id,tenant(req)]);res.json({mensagem:'Cupom excluído'})});

router.get('/campanhas',async(req,res)=>{res.json((await pool.query(`SELECT c.*,m.nome modelo_nome,cp.codigo cupom_codigo,l.token link_token,l.destino link_destino_real,
  (SELECT COUNT(*) FROM marketing_envios e WHERE e.campanha_id=c.id AND e.status IN ('entregue','lido'))::int entregues,
  (SELECT COUNT(*) FROM marketing_envios e WHERE e.campanha_id=c.id AND e.status='lido')::int lidos
  FROM marketing_campanhas c LEFT JOIN marketing_modelos m ON m.id=c.modelo_id LEFT JOIN marketing_cupons cp ON cp.id=c.cupom_id LEFT JOIN marketing_links l ON l.id=c.marketing_link_id
  WHERE c.barbearia_id=$1 ORDER BY c.criado_em DESC`,[tenant(req)])).rows)});
router.post('/campanhas',async(req,res)=>{try{
  const x=req.body||{},nome=cleanText(x.nome,160,{required:true}),seg=segment(x.segmento),modelo=intId(x.modelo_id),cupom=intId(x.cupom_id),invest=finiteMoney(x.investimento??0,{max:1000000}),linkDest=['agendamento','loja'].includes(x.link_destino)?x.link_destino:null;if(!nome||invest===null)return res.status(400).json({erro:'Campanha inválida'});
  let tpl=cleanText(x.template_nome,512),lang=cleanText(x.template_idioma,20)||'pt_BR',params=Array.isArray(x.template_parametros)?x.template_parametros.map(v=>cleanText(v,200)).filter(Boolean).slice(0,10):[],preview=cleanText(x.mensagem_preview,4000);
  if(modelo){const m=(await pool.query(`SELECT * FROM marketing_modelos WHERE id=$1 AND barbearia_id=$2`,[modelo,tenant(req)])).rows[0];if(m){tpl=tpl||m.template_nome_meta;lang=m.idioma||lang;params=params.length?params:(m.parametros||[]);preview=preview||m.mensagem_preview}}
  const r=await pool.query(`INSERT INTO marketing_campanhas(barbearia_id,nome,objetivo,segmento,segmento_config,modelo_id,template_nome,template_idioma,template_parametros,mensagem_preview,cupom_id,link_destino,investimento,criado_por) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[tenant(req),nome,cleanText(x.objetivo,80)||null,seg,JSON.stringify(x.segmento_config||{}),modelo||null,tpl||null,lang,JSON.stringify(params),preview||null,cupom||null,linkDest,invest,req.usuario.id]);res.status(201).json(r.rows[0]);
}catch(e){console.error(e);res.status(400).json({erro:'Não foi possível criar a campanha'})}});
router.post('/campanhas/:id/agendar',exigirStepUp,async(req,res)=>{const id=intId(req.params.id),quando=req.body.agendada_para?new Date(req.body.agendada_para):new Date(),barbeariaId=tenant(req);if(!id||Number.isNaN(quando.getTime()))return res.status(400).json({erro:'Data inválida'});const c=(await pool.query(`SELECT * FROM marketing_campanhas WHERE id=$1 AND barbearia_id=$2`,[id,barbeariaId])).rows[0];if(!c)return res.status(404).json({erro:'Campanha não encontrada'});const integ=await wp.activeConnection(barbeariaId);if(!integ)return res.status(400).json({erro:'Conecte e ative um provedor WhatsApp antes de agendar a campanha'});if(integ.provedor==='evolution'){if(!c.mensagem_preview)return res.status(400).json({erro:'No Evolution/QR, informe a mensagem da campanha antes de enviar'})}else if(!c.template_nome)return res.status(400).json({erro:integ.provedor==='twilio'?'Informe o Content SID (HX...) da Twilio antes de enviar':'Informe um template oficial do WhatsApp antes de enviar'});await pool.query(`DELETE FROM marketing_envios WHERE campanha_id=$1 AND barbearia_id=$2`,[id,barbeariaId]);if(c.marketing_link_id)await pool.query(`UPDATE marketing_links SET ativo=true,cliques=0,conversoes=0,receita=0,atualizado_em=NOW() WHERE id=$1 AND barbearia_id=$2`,[c.marketing_link_id,barbeariaId]);const r=await pool.query(`UPDATE marketing_campanhas SET status='agendada',agendada_para=$1,total_alvo=0,enviados=0,erros=0,cliques=0,conversoes=0,receita=0,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[quando.toISOString(),id,barbeariaId]);res.json({...r.rows[0],provedor:integ.provedor})});
router.post('/campanhas/:id/pausar',exigirStepUp,async(req,res)=>{const id=intId(req.params.id);const r=await pool.query(`UPDATE marketing_campanhas SET status='pausada',atualizado_em=NOW() WHERE id=$1 AND barbearia_id=$2 AND status IN ('agendada','enviando') RETURNING *`,[id,tenant(req)]);if(!r.rowCount)return res.status(409).json({erro:'Campanha não pode ser pausada'});res.json(r.rows[0])});
router.post('/campanhas/:id/cancelar',exigirStepUp,async(req,res)=>{const id=intId(req.params.id);const r=await pool.query(`UPDATE marketing_campanhas SET status='cancelada',atualizado_em=NOW() WHERE id=$1 AND barbearia_id=$2 AND status NOT IN ('enviada','cancelada') RETURNING *`,[id,tenant(req)]);if(!r.rowCount)return res.status(409).json({erro:'Campanha não pode ser cancelada'});res.json(r.rows[0])});

router.get('/links',async(req,res)=>{res.json((await pool.query(`SELECT l.*,c.nome campanha_nome FROM marketing_links l LEFT JOIN marketing_campanhas c ON c.id=l.campanha_id WHERE l.barbearia_id=$1 ORDER BY l.criado_em DESC`,[tenant(req)])).rows)});
router.post('/links',async(req,res)=>{try{const x=req.body||{},nome=cleanText(x.nome,140,{required:true}),dest=['agendamento','loja'].includes(x.destino)?x.destino:null,camp=intId(x.campanha_id);if(!nome||!dest)return res.status(400).json({erro:'Link inválido'});const token=crypto.randomBytes(12).toString('base64url');const r=await pool.query(`INSERT INTO marketing_links(barbearia_id,campanha_id,nome,token,destino) VALUES($1,$2,$3,$4,$5) RETURNING *`,[tenant(req),camp||null,nome,token,dest]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({erro:'Não foi possível criar o link'})}});
router.patch('/links/:id',async(req,res)=>{const id=intId(req.params.id);const r=await pool.query(`UPDATE marketing_links SET ativo=$1 WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[!!req.body.ativo,id,tenant(req)]);if(!r.rowCount)return res.status(404).json({erro:'Link não encontrado'});res.json(r.rows[0])});

router.get('/indicacoes',async(req,res)=>{const [cfg,rows]=await Promise.all([pool.query(`SELECT * FROM marketing_indicacoes_config WHERE barbearia_id=$1`,[tenant(req)]),pool.query(`SELECT ic.*,c.nome cliente_nome,COUNT(cv.id)::int conversoes FROM marketing_indicacao_codigos ic JOIN clientes c ON c.id=ic.cliente_id LEFT JOIN marketing_indicacao_conversoes cv ON cv.codigo_id=ic.id WHERE ic.barbearia_id=$1 GROUP BY ic.id,c.nome ORDER BY conversoes DESC,c.nome`,[tenant(req)])]);res.json({config:cfg.rows[0]||{ativo:false,tipo_recompensa:'fixo',valor_indicador:10,valor_indicado:10,pedido_minimo:0},codigos:rows.rows})});
router.put('/indicacoes/config',exigirPapel('dono'),exigirStepUp,async(req,res)=>{const x=req.body||{},tipo=['fixo','percentual'].includes(x.tipo_recompensa)?x.tipo_recompensa:'fixo',vi=finiteMoney(x.valor_indicador??10,{max:10000}),vd=finiteMoney(x.valor_indicado??10,{max:10000}),min=finiteMoney(x.pedido_minimo??0,{max:100000});if(vi===null||vd===null||min===null||(tipo==='percentual'&&(vi>100||vd>100)))return res.status(400).json({erro:'Configuração inválida'});const r=await pool.query(`INSERT INTO marketing_indicacoes_config(barbearia_id,ativo,tipo_recompensa,valor_indicador,valor_indicado,pedido_minimo) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(barbearia_id) DO UPDATE SET ativo=EXCLUDED.ativo,tipo_recompensa=EXCLUDED.tipo_recompensa,valor_indicador=EXCLUDED.valor_indicador,valor_indicado=EXCLUDED.valor_indicado,pedido_minimo=EXCLUDED.pedido_minimo,atualizado_em=NOW() RETURNING *`,[tenant(req),!!x.ativo,tipo,vi,vd,min]);res.json(r.rows[0])});
router.post('/indicacoes/cliente/:id',async(req,res)=>{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Cliente inválido'});const c=(await pool.query(`SELECT id FROM clientes WHERE id=$1 AND barbearia_id=$2`,[id,tenant(req)])).rows[0];if(!c)return res.status(404).json({erro:'Cliente não encontrado'});const rc=await referralCode(tenant(req),id);const slug=(await pool.query(`SELECT slug FROM barbearias WHERE id=$1`,[tenant(req)])).rows[0].slug;res.json({...rc,url:`${process.env.APP_URL||''}/loja/${encodeURIComponent(slug)}?ref=${encodeURIComponent(rc.codigo)}`})});

module.exports=router;
