const express=require('express');
const pool=require('../config/db');
const {autenticar,exigirPapel,exigirAssinatura,exigirStepUp}=require('../middlewares/auth');
const {exigirRecurso}=require('../services/planos');
const {recordStockMovement,consumeServiceInputs}=require('../services/advancedOps');
const {intId,cleanText,finiteMoney,finitePercent,csvQuote,isoDate,safeHttpUrl}=require('../utils/validation');
const router=express.Router();
router.use(autenticar,exigirAssinatura);
const b=req=>req.usuario.barbearia_id;
const staff=[exigirPapel('dono','gerente','recepcao')];
const managers=[exigirPapel('dono','gerente')];

router.get('/produtos',...staff,exigirRecurso('pdv_estoque'),async(req,res)=>{try{const r=await pool.query('SELECT * FROM produtos WHERE barbearia_id=$1 ORDER BY ativo DESC,nome',[b(req)]);res.json(r.rows)}catch(e){res.status(500).json({erro:'Erro ao listar produtos'})}});
router.post('/produtos',...managers,exigirRecurso('pdv_estoque'),async(req,res)=>{try{const x=req.body||{},nome=cleanText(x.nome,160,{required:true}),sku=cleanText(x.sku,80)||null,preco=finiteMoney(x.preco),custo=finiteMoney(x.custo??0),estoque=finiteMoney(x.estoque??0,{max:10_000_000}),min=finiteMoney(x.estoque_minimo??0,{max:10_000_000}),imagem=safeHttpUrl(x.imagem_url),fornecedor=x.fornecedor_id?intId(x.fornecedor_id):null,unidade=cleanText(x.unidade,20)||'un',validade=x.validade?isoDate(x.validade):null;if(imagem===false||x.validade&&!validade)return res.status(400).json({erro:'Foto ou validade inválida'});if(!nome||[preco,custo,estoque,min].some(v=>v===null))return res.status(400).json({erro:'Nome e valores não negativos são obrigatórios'});if(fornecedor&&!(await pool.query(`SELECT 1 FROM fornecedores WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[fornecedor,b(req)])).rowCount)return res.status(400).json({erro:'Fornecedor inválido'});const r=await pool.query(`INSERT INTO produtos(barbearia_id,nome,sku,preco,custo,estoque,estoque_minimo,imagem_url,fornecedor_id,unidade,validade,ativo,atualizado_em) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,true,NOW()) RETURNING *`,[b(req),nome,sku,preco,custo,estoque,min,imagem,fornecedor,unidade,validade]);res.status(201).json(r.rows[0])}catch(e){if(e.code==='23505')return res.status(409).json({erro:'SKU já utilizado'});res.status(400).json({erro:'Não foi possível cadastrar o produto'})}});
router.put('/produtos/:id',...managers,exigirRecurso('pdv_estoque'),async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const id=intId(req.params.id),x=req.body||{},nome=cleanText(x.nome,160,{required:true}),sku=cleanText(x.sku,80)||null,preco=finiteMoney(x.preco),custo=finiteMoney(x.custo??0),estoque=finiteMoney(x.estoque??0,{max:10_000_000}),min=finiteMoney(x.estoque_minimo??0,{max:10_000_000}),imagem=safeHttpUrl(x.imagem_url),fornecedor=x.fornecedor_id?intId(x.fornecedor_id):null,unidade=cleanText(x.unidade,20)||'un',validade=x.validade?isoDate(x.validade):null;if(imagem===false||x.validade&&!validade)throw new Error('Foto ou validade inválida');if(!id||!nome||[preco,custo,estoque,min].some(v=>v===null))throw new Error('Valores inválidos');if(fornecedor&&!(await c.query(`SELECT 1 FROM fornecedores WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[fornecedor,b(req)])).rowCount)throw new Error('Fornecedor inválido');const before=(await c.query(`SELECT estoque FROM produtos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[id,b(req)])).rows[0];if(!before)throw new Error('Produto não encontrado');const r=await c.query(`UPDATE produtos SET nome=$1,sku=$2,preco=$3,custo=$4,estoque=$5,estoque_minimo=$6,ativo=$7,imagem_url=$8,fornecedor_id=$9,unidade=$10,validade=$11,atualizado_em=NOW() WHERE id=$12 AND barbearia_id=$13 RETURNING *`,[nome,sku,preco,custo,estoque,min,x.ativo!==false,imagem,fornecedor,unidade,validade,id,b(req)]);const oldStock=Number(before.estoque||0);if(Math.abs(oldStock-Number(estoque))>0.0001)await recordStockMovement(c,{barbeariaId:b(req),produtoId:id,tipo:'ajuste',quantidade:Number(estoque)-oldStock,estoqueAnterior:oldStock,estoquePosterior:Number(estoque),custoUnitario:custo,observacoes:'Ajuste pelo cadastro do produto',usuarioId:req.usuario.id});await c.query('COMMIT');res.json(r.rows[0])}catch(e){try{await c.query('ROLLBACK')}catch{}if(e.code==='23505')return res.status(409).json({erro:'SKU já utilizado'});res.status(400).json({erro:e.message||'Não foi possível editar o produto'})}finally{c.release()}});
router.delete('/produtos/:id',...managers,exigirRecurso('pdv_estoque'),exigirStepUp,async(req,res)=>{try{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Produto inválido'});const r=await pool.query(`DELETE FROM produtos WHERE id=$1 AND barbearia_id=$2 RETURNING id,nome`,[id,b(req)]);if(!r.rowCount)return res.status(404).json({erro:'Produto não encontrado'});res.json({mensagem:'Produto excluído',produto:r.rows[0]})}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível excluir o produto'})}});

router.get('/comissoes',exigirPapel('dono','gerente'),exigirRecurso('comissoes'),async(req,res)=>{try{const inicio=req.query.inicio||new Date().toISOString().slice(0,7)+'-01',fim=req.query.fim||new Date().toISOString().slice(0,10);if(!isoDate(inicio)||!isoDate(fim)||inicio>fim)return res.status(400).json({erro:'Período inválido'});const r=await pool.query(`SELECT br.id,br.nome,
COALESCE(SUM(CASE WHEN a.status='concluido' THEN COALESCE(a.valor_final,a.valor_servico,0)*COALESCE(br.comissao_servico_pct,0)/100 ELSE 0 END),0)::numeric comissao_servicos,
COALESCE((SELECT SUM(v.subtotal_produtos*COALESCE(br.comissao_produto_pct,0)/100) FROM vendas v WHERE v.barbearia_id=$1 AND v.barbeiro_id=br.id AND v.status='finalizada' AND v.subtotal_produtos>0 AND v.criado_em::date BETWEEN $2 AND $3),0)::numeric comissao_produtos,
COUNT(a.id) FILTER(WHERE a.status='concluido')::int atendimentos
FROM barbeiros br LEFT JOIN agendamentos a ON a.barbeiro_id=br.id AND a.barbearia_id=br.barbearia_id AND a.data BETWEEN $2 AND $3
WHERE br.barbearia_id=$1 GROUP BY br.id ORDER BY br.nome`,[b(req),inicio,fim]);res.json(r.rows)}catch(e){console.error(e);res.status(500).json({erro:'Erro ao calcular comissões'})}});
router.put('/comissoes/barbeiros/:id',exigirPapel('dono'),exigirRecurso('comissoes'),exigirStepUp,async(req,res)=>{try{const id=intId(req.params.id),a=finitePercent(req.body.comissao_servico_pct??0),p=finitePercent(req.body.comissao_produto_pct??0);if(!id||a===null||p===null)return res.status(400).json({erro:'Comissão deve ficar entre 0 e 100%'});const r=await pool.query(`UPDATE barbeiros SET comissao_servico_pct=$1,comissao_produto_pct=$2 WHERE id=$3 AND barbearia_id=$4 RETURNING id,nome,comissao_servico_pct,comissao_produto_pct`,[a,p,id,b(req)]);if(!r.rowCount)return res.status(404).json({erro:'Barbeiro não encontrado'});res.json(r.rows[0])}catch(e){res.status(500).json({erro:'Erro ao salvar comissões'})}});

router.get('/vendas',...staff,exigirRecurso('pdv_estoque'),async(req,res)=>{try{const r=await pool.query(`SELECT v.id,v.criado_em,v.total,v.subtotal_servicos,v.subtotal_produtos,v.desconto,v.forma_pagamento,v.status,c.nome cliente,br.nome barbeiro FROM vendas v LEFT JOIN clientes c ON c.id=v.cliente_id AND c.barbearia_id=v.barbearia_id LEFT JOIN barbeiros br ON br.id=v.barbeiro_id AND br.barbearia_id=v.barbearia_id WHERE v.barbearia_id=$1 ORDER BY v.criado_em DESC LIMIT 300`,[b(req)]);res.json(r.rows)}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar histórico de vendas'})}});

router.post('/vendas',...staff,exigirRecurso('pdv_estoque'),async(req,res)=>{
  const c=await pool.connect();
  try{
    await c.query('BEGIN');
    const x=req.body||{},tenant=b(req),desconto=finiteMoney(x.desconto??0,{min:0,max:1_000_000}),itens=Array.isArray(x.itens)?x.itens:[];
    if(desconto===null||!itens.length||itens.length>100)throw new Error('Venda inválida');
    const forma=String(x.forma_pagamento||'dinheiro');if(!['dinheiro','pix','cartao','mercado_pago','pix_manual'].includes(forma))throw new Error('Forma de pagamento inválida');
    let clienteId=intId(x.cliente_id),barbeiroId=intId(x.barbeiro_id),agendamentoId=intId(x.agendamento_id),ag=null;
    if(agendamentoId){
      ag=(await c.query(`SELECT * FROM agendamentos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[agendamentoId,tenant])).rows[0];
      if(!ag)throw new Error('Agendamento inválido');
      if(['cancelado','nao_compareceu'].includes(ag.status))throw new Error('Não é possível finalizar venda de agendamento cancelado/ausente');
      if((await c.query(`SELECT 1 FROM vendas WHERE barbearia_id=$1 AND agendamento_id=$2 AND status='finalizada'`,[tenant,agendamentoId])).rowCount)throw new Error('Este agendamento já possui uma venda finalizada');
      if(clienteId&&Number(clienteId)!==Number(ag.cliente_id))throw new Error('Cliente não corresponde ao agendamento');
      if(barbeiroId&&Number(barbeiroId)!==Number(ag.barbeiro_id))throw new Error('Barbeiro não corresponde ao agendamento');
      clienteId=ag.cliente_id;barbeiroId=ag.barbeiro_id;
    }
    if(clienteId&&!(await c.query('SELECT 1 FROM clientes WHERE id=$1 AND barbearia_id=$2',[clienteId,tenant])).rowCount)throw new Error('Cliente inválido');
    if(barbeiroId&&!(await c.query('SELECT 1 FROM barbeiros WHERE id=$1 AND barbearia_id=$2 AND ativo=true',[barbeiroId,tenant])).rowCount)throw new Error('Barbeiro inválido');

    const normalized=[];let brutoServicos=0,brutoProdutos=0,linkedServiceCount=0;
    for(const it of itens){
      const id=intId(it.id),q=Number(it.quantidade);if(!id||!Number.isInteger(q)||q<1||q>1000)throw new Error('Item/quantidade inválidos');
      if(it.tipo==='produto'){
        const pr=(await c.query('SELECT * FROM produtos WHERE id=$1 AND barbearia_id=$2 AND ativo=true FOR UPDATE',[id,tenant])).rows[0];if(!pr||Number(pr.estoque)<q)throw new Error('Produto inválido ou estoque insuficiente');
        const unit=Number(pr.preco),sub=Number((unit*q).toFixed(2));brutoProdutos+=sub;normalized.push({tipo:'produto',id:pr.id,descricao:cleanText(pr.nome,200),q,unit,sub});
      }else if(it.tipo==='servico'){
        const sv=(await c.query('SELECT * FROM servicos WHERE id=$1 AND barbearia_id=$2 AND ativo=true',[id,tenant])).rows[0];if(!sv)throw new Error('Serviço inválido');
        let unit=Number(sv.preco);
        if(ag){if(Number(sv.id)!==Number(ag.servico_id))throw new Error('Serviço da venda não corresponde ao agendamento');if(q!==1)throw new Error('O serviço do agendamento deve ter quantidade 1');linkedServiceCount++;unit=Number(ag.valor_final??ag.valor_servico??sv.preco??0);}
        const sub=Number((unit*q).toFixed(2));brutoServicos+=sub;normalized.push({tipo:'servico',id:sv.id,descricao:cleanText(sv.nome,200),q,unit,sub});
      }else throw new Error('Tipo de item inválido');
    }
    if(ag&&linkedServiceCount!==1)throw new Error('Inclua exatamente uma vez o serviço do agendamento nesta venda');
    const bruto=Number((brutoServicos+brutoProdutos).toFixed(2));if(desconto>bruto)throw new Error('Desconto não pode superar o valor bruto');

    // Em venda vinculada, desconta produtos primeiro. Assim um sinal já pago nunca é apagado por desconto posterior.
    let descontoProdutos,descontoServicos;
    if(ag){descontoProdutos=Math.min(desconto,brutoProdutos);descontoServicos=desconto-descontoProdutos;}else{descontoServicos=bruto>0?desconto*(brutoServicos/bruto):0;descontoProdutos=desconto-descontoServicos;}
    const liquidoServicos=Number(Math.max(0,brutoServicos-descontoServicos).toFixed(2));
    const liquidoProdutos=Number(Math.max(0,brutoProdutos-descontoProdutos).toFixed(2));
    const total=Number((liquidoServicos+liquidoProdutos).toFixed(2));
    const prePago=ag?Number(Math.max(0,Math.min(Number(ag.valor_pago||0),liquidoServicos)).toFixed(2)):0;
    if(ag&&Number(ag.valor_pago||0)>liquidoServicos+0.009)throw new Error('O desconto deixaria o valor do serviço abaixo do que o cliente já pagou');
    const recebido=Number(Math.max(0,total-prePago).toFixed(2));

    const vr=await c.query(`INSERT INTO vendas(barbearia_id,cliente_id,barbeiro_id,agendamento_id,forma_pagamento,status,total,desconto,subtotal_servicos,subtotal_produtos,valor_pre_pago,valor_recebido) VALUES($1,$2,$3,$4,$5,'finalizada',$6,$7,$8,$9,$10,$11) RETURNING id`,[tenant,clienteId||null,barbeiroId||null,agendamentoId||null,forma,total,desconto,liquidoServicos,liquidoProdutos,prePago,recebido]);
    for(const it of normalized){await c.query(`INSERT INTO venda_itens(venda_id,tipo,referencia_id,descricao,quantidade,valor_unitario,subtotal) VALUES($1,$2,$3,$4,$5,$6,$7)`,[vr.rows[0].id,it.tipo,it.id,it.descricao,it.q,it.unit,it.sub]);if(it.tipo==='produto'){const pr=(await c.query(`SELECT estoque,custo FROM produtos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[it.id,tenant])).rows[0],before=Number(pr.estoque),after=Number((before-it.q).toFixed(3));await c.query('UPDATE produtos SET estoque=$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3',[after,it.id,tenant]);await recordStockMovement(c,{barbeariaId:tenant,produtoId:it.id,tipo:'venda',quantidade:-it.q,estoqueAnterior:before,estoquePosterior:after,custoUnitario:Number(pr.custo||0),referenciaTipo:'venda',referenciaId:vr.rows[0].id,observacoes:'Saída pelo PDV',usuarioId:req.usuario.id})}}await consumeServiceInputs(c,{barbeariaId:tenant,serviceItems:normalized.filter(x=>x.tipo==='servico').map(x=>({referencia_id:x.id,quantidade:x.q,descricao:x.descricao})),referenceType:'venda',referenceId:vr.rows[0].id,usuarioId:req.usuario.id});
    if(agendamentoId){
      const pagoAgoraServico=Number(Math.max(0,liquidoServicos-prePago).toFixed(2));const novoPago=Number(Math.min(liquidoServicos,prePago+pagoAgoraServico).toFixed(2));
      await c.query(`UPDATE agendamentos SET status='concluido',status_pagamento=CASE WHEN $1+0.009 >= $2 THEN 'pago' WHEN $1>0 THEN 'parcial' ELSE 'aguardando' END,valor_pago=$1,valor_final=$2 WHERE id=$3 AND barbearia_id=$4`,[novoPago,liquidoServicos,agendamentoId,tenant]);
    }
    if(clienteId){const fc=(await c.query('SELECT * FROM fidelidade_config WHERE barbearia_id=$1 AND ativo=true',[tenant])).rows[0];if(fc){const pts=Math.max(0,Math.floor(total*Number(fc.pontos_por_real||1)));await c.query(`INSERT INTO fidelidade_saldos(barbearia_id,cliente_id,pontos) VALUES($1,$2,$3) ON CONFLICT(barbearia_id,cliente_id) DO UPDATE SET pontos=fidelidade_saldos.pontos+EXCLUDED.pontos,atualizado_em=NOW()`,[tenant,clienteId,pts]);}}
    await c.query('COMMIT');res.status(201).json({id:vr.rows[0].id,total,valor_pre_pago:prePago,valor_recebido:recebido,servicos:liquidoServicos,produtos:liquidoProdutos});
  }catch(e){try{await c.query('ROLLBACK')}catch{}console.error('PDV:',e.message);res.status(400).json({erro:e.message||'Venda inválida'})}finally{c.release()}
});

router.get('/fila',...staff,exigirRecurso('fila_espera'),async(req,res)=>{try{const r=await pool.query(`SELECT f.*,c.nome cliente,br.nome barbeiro,s.nome servico FROM fila_espera f JOIN clientes c ON c.id=f.cliente_id AND c.barbearia_id=f.barbearia_id LEFT JOIN barbeiros br ON br.id=f.barbeiro_id AND br.barbearia_id=f.barbearia_id JOIN servicos s ON s.id=f.servico_id AND s.barbearia_id=f.barbearia_id WHERE f.barbearia_id=$1 AND f.status='aguardando' ORDER BY f.criado_em`,[b(req)]);res.json(r.rows)}catch(e){res.status(500).json({erro:'Erro ao carregar fila'})}});
router.post('/fila',...staff,exigirRecurso('fila_espera'),async(req,res)=>{try{const x=req.body||{},tenant=b(req),clienteId=intId(x.cliente_id),barbeiroId=x.barbeiro_id?intId(x.barbeiro_id):null,servicoId=intId(x.servico_id),obs=cleanText(x.observacoes,1000)||null;if(!clienteId||!servicoId||(x.barbeiro_id&&!barbeiroId))return res.status(400).json({erro:'Dados da fila inválidos'});if(!(await pool.query(`SELECT 1 FROM clientes WHERE id=$1 AND barbearia_id=$2`,[clienteId,tenant])).rowCount)return res.status(400).json({erro:'Cliente inválido'});if(!(await pool.query(`SELECT 1 FROM servicos WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[servicoId,tenant])).rowCount)return res.status(400).json({erro:'Serviço inválido'});if(barbeiroId&&!(await pool.query(`SELECT 1 FROM barbeiros WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[barbeiroId,tenant])).rowCount)return res.status(400).json({erro:'Barbeiro inválido'});const r=await pool.query(`INSERT INTO fila_espera(barbearia_id,cliente_id,barbeiro_id,servico_id,observacoes) VALUES($1,$2,$3,$4,$5) RETURNING *`,[tenant,clienteId,barbeiroId,servicoId,obs]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({erro:'Não foi possível adicionar à fila'})}});
router.patch('/fila/:id',...staff,exigirRecurso('fila_espera'),async(req,res)=>{try{const id=intId(req.params.id),status=String(req.body.status||'atendido');if(!id||!['aguardando','atendido','cancelado'].includes(status))return res.status(400).json({erro:'Status inválido'});const r=await pool.query(`UPDATE fila_espera SET status=$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[status,id,b(req)]);if(!r.rowCount)return res.status(404).json({erro:'Item da fila não encontrado'});res.json(r.rows[0])}catch(e){res.status(500).json({erro:'Erro ao atualizar fila'})}});

router.get('/crm/:id',...staff,exigirRecurso('crm_avancado'),async(req,res)=>{try{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Cliente inválido'});const c=(await pool.query('SELECT * FROM clientes WHERE id=$1 AND barbearia_id=$2',[id,b(req)])).rows[0];if(!c)return res.status(404).json({erro:'Cliente não encontrado'});const h=await pool.query(`SELECT a.id,a.data,a.horario,a.status,a.status_pagamento,s.nome servico,COALESCE(a.valor_final,a.valor_servico,s.preco) preco,br.nome barbeiro FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id JOIN barbeiros br ON br.id=a.barbeiro_id AND br.barbearia_id=a.barbearia_id WHERE a.cliente_id=$1 AND a.barbearia_id=$2 ORDER BY a.data DESC,a.horario DESC LIMIT 100`,[id,b(req)]);const m=await pool.query(`SELECT COUNT(*) FILTER(WHERE status='concluido')::int visitas,COUNT(*) FILTER(WHERE status='nao_compareceu')::int faltas,COALESCE(SUM(COALESCE(valor_final,valor_servico,0)) FILTER(WHERE status='concluido'),0)::numeric total_gasto,MAX(data) FILTER(WHERE status='concluido') ultima_visita FROM agendamentos WHERE cliente_id=$1 AND barbearia_id=$2`,[id,b(req)]);const fid=await pool.query(`SELECT * FROM fidelidade_saldos WHERE cliente_id=$1 AND barbearia_id=$2`,[id,b(req)]);res.json({cliente:c,metricas:m.rows[0],historico:h.rows,fidelidade:fid.rows[0]||{pontos:0}})}catch(e){res.status(500).json({erro:'Erro ao carregar CRM'})}});
router.get('/avaliacoes',exigirPapel('dono','gerente'),exigirRecurso('avaliacoes'),async(req,res)=>{try{const r=await pool.query(`SELECT av.*,c.nome cliente,br.nome barbeiro,s.nome servico FROM avaliacoes av JOIN agendamentos a ON a.id=av.agendamento_id AND a.barbearia_id=av.barbearia_id JOIN clientes c ON c.id=a.cliente_id AND c.barbearia_id=a.barbearia_id JOIN barbeiros br ON br.id=a.barbeiro_id AND br.barbearia_id=a.barbearia_id JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE av.barbearia_id=$1 ORDER BY av.criado_em DESC LIMIT 200`,[b(req)]);res.json(r.rows)}catch(e){res.status(500).json({erro:'Erro ao carregar avaliações'})}});
router.get('/pacotes',...staff,exigirRecurso('fidelidade'),async(req,res)=>{try{const r=await pool.query('SELECT * FROM pacotes WHERE barbearia_id=$1 ORDER BY ativo DESC,nome',[b(req)]);res.json(r.rows)}catch(e){res.status(500).json({erro:'Erro ao carregar pacotes'})}});
router.post('/pacotes',exigirPapel('dono','gerente'),exigirRecurso('fidelidade'),async(req,res)=>{try{const x=req.body||{},nome=cleanText(x.nome,160,{required:true}),preco=finiteMoney(x.preco??0),descricao=cleanText(x.descricao,2000)||null,validade=Number(x.validade_dias||90);if(!nome||preco===null||!Number.isInteger(validade)||validade<1||validade>3650)return res.status(400).json({erro:'Nome, preço e validade válidos são obrigatórios'});const r=await pool.query(`INSERT INTO pacotes(barbearia_id,nome,preco,descricao,ativo,validade_dias,atualizado_em) VALUES($1,$2,$3,$4,true,$5,NOW()) RETURNING *`,[b(req),nome,preco,descricao,validade]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({erro:'Erro ao criar pacote'})}});
router.get('/fidelidade',exigirPapel('dono','gerente'),exigirRecurso('fidelidade'),async(req,res)=>{const cfg=(await pool.query('SELECT * FROM fidelidade_config WHERE barbearia_id=$1',[b(req)])).rows[0]||{ativo:false,pontos_por_real:1,pontos_recompensa:500};res.json(cfg)});
router.put('/fidelidade',exigirPapel('dono'),exigirRecurso('fidelidade'),exigirStepUp,async(req,res)=>{try{const x=req.body||{},ppr=finiteMoney(x.pontos_por_real??1,{max:1000}),pr=Number(x.pontos_recompensa??500),texto=cleanText(x.recompensa_texto,200)||'Benefício da barbearia';if(ppr===null||!Number.isInteger(pr)||pr<1||pr>10_000_000)return res.status(400).json({erro:'Configuração de fidelidade inválida'});const r=await pool.query(`INSERT INTO fidelidade_config(barbearia_id,ativo,pontos_por_real,pontos_recompensa,recompensa_texto) VALUES($1,$2,$3,$4,$5) ON CONFLICT(barbearia_id) DO UPDATE SET ativo=EXCLUDED.ativo,pontos_por_real=EXCLUDED.pontos_por_real,pontos_recompensa=EXCLUDED.pontos_recompensa,recompensa_texto=EXCLUDED.recompensa_texto RETURNING *`,[b(req),!!x.ativo,ppr,pr,texto]);res.json(r.rows[0])}catch(e){res.status(500).json({erro:'Erro ao salvar fidelidade'})}});
router.get('/relatorios',exigirPapel('dono','gerente'),exigirRecurso('relatorios_avancados'),async(req,res)=>{try{const id=b(req);const r=await pool.query(`SELECT COUNT(*) FILTER(WHERE status='concluido')::int atendimentos,COUNT(*) FILTER(WHERE status='cancelado')::int cancelamentos,COUNT(*) FILTER(WHERE status='nao_compareceu')::int no_show,COUNT(DISTINCT cliente_id) FILTER(WHERE status='concluido')::int clientes_atendidos,COALESCE(AVG(COALESCE(valor_final,valor_servico,0)) FILTER(WHERE status='concluido'),0)::numeric ticket_medio FROM agendamentos WHERE barbearia_id=$1 AND date_trunc('month',data)=date_trunc('month',CURRENT_DATE)`,[id]);const top=await pool.query(`SELECT s.nome,COUNT(*)::int quantidade FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND a.status='concluido' GROUP BY s.id,s.nome ORDER BY quantidade DESC LIMIT 5`,[id]);res.json({resumo:r.rows[0],top_servicos:top.rows})}catch(e){res.status(500).json({erro:'Erro ao carregar relatórios'})}});
router.get('/exportar/:tipo',exigirPapel('dono'),exigirRecurso('exportacao_dados'),async(req,res)=>{try{const tipo=req.params.tipo;let q;if(tipo==='clientes')q=`SELECT nome,telefone,email,observacoes,criado_em FROM clientes WHERE barbearia_id=$1 ORDER BY nome`;else if(tipo==='agendamentos')q=`SELECT a.data,a.horario,a.status,a.forma_pagamento,a.status_pagamento,c.nome cliente,br.nome barbeiro,s.nome servico,COALESCE(a.valor_final,a.valor_servico,s.preco) preco FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id AND c.barbearia_id=a.barbearia_id JOIN barbeiros br ON br.id=a.barbeiro_id AND br.barbearia_id=a.barbearia_id JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 ORDER BY a.data DESC`;else if(tipo==='vendas')q=`SELECT criado_em,total,valor_pre_pago,valor_recebido,desconto,forma_pagamento,status FROM vendas WHERE barbearia_id=$1 ORDER BY criado_em DESC`;else return res.status(400).json({erro:'Exportação inválida'});const rows=(await pool.query(q,[b(req)])).rows;const cols=rows[0]?Object.keys(rows[0]):[];const csv=[cols.map(csvQuote).join(','),...rows.map(x=>cols.map(k=>csvQuote(x[k])).join(','))].join('\r\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="barberflow-${tipo}.csv"`);res.send('\ufeff'+csv)}catch(e){console.error(e);res.status(500).json({erro:'Erro ao exportar dados'})}});
module.exports=router;
