const express=require('express');
const pool=require('../config/db');
const {autenticar,exigirPapel,exigirAssinatura}=require('../middlewares/auth');
const {exigirRecurso,contextoPlano}=require('../services/planos');
const {finitePercent,cleanText}=require('../utils/validation');
const {listGateways,createOauthUrl,finishOauth,connectAsaas,connectPagarme,disconnectGateway}=require('../services/paymentGateways');
const router=express.Router();

router.get('/gateways',autenticar,exigirPapel('dono','gerente'),exigirAssinatura,async(req,res)=>{try{const ctx=await contextoPlano(req.usuario.barbearia_id);res.json({habilitado:ctx.recursos.includes('pagamentos_online'),plano:ctx.plano_efetivo,gateways:await listGateways(req.usuario.barbearia_id)})}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar gateways'})}});
router.get('/config',autenticar,exigirPapel('dono','gerente'),exigirAssinatura,async(req,res)=>{try{const r=await pool.query(`SELECT COALESCE(pagamento_agendamento,'nenhum') pagamento_agendamento,COALESCE(percentual_sinal,50) percentual_sinal,COALESCE(aceitar_mercadopago,false) aceitar_mercadopago,COALESCE(mp_aceitar_pix,true) mp_aceitar_pix,COALESCE(mp_aceitar_cartao,true) mp_aceitar_cartao,COALESCE(aceitar_pix_manual,false) aceitar_pix_manual,pix_chave,pix_nome,pix_banco,COALESCE(aceitar_dinheiro,true) aceitar_dinheiro FROM barbearias WHERE id=$1`,[req.usuario.barbearia_id]);const ctx=await contextoPlano(req.usuario.barbearia_id);res.json({config:r.rows[0],habilitado:ctx.recursos.includes('pagamentos_online'),plano:ctx.plano_efetivo})}catch(e){res.status(500).json({erro:'Erro ao carregar configurações de pagamento'})}});
router.put('/config',autenticar,exigirPapel('dono','gerente'),exigirRecurso('pagamentos_online'),async(req,res)=>{try{const x=req.body||{},modo=['nenhum','total','sinal'].includes(x.pagamento_agendamento)?x.pagamento_agendamento:'nenhum',pct=finitePercent(x.percentual_sinal??50,{min:1,max:100});if(pct===null)return res.status(400).json({erro:'Percentual do sinal inválido'});const pixChave=cleanText(x.pix_chave,200)||null,pixNome=cleanText(x.pix_nome,160)||null,pixBanco=cleanText(x.pix_banco,120)||null;if(x.aceitar_pix_manual&&!pixChave)return res.status(400).json({erro:'Informe a chave do Pix manual'});const mp=await pool.query(`SELECT 1 FROM integracoes_pagamento WHERE barbearia_id=$1 AND provedor='mercadopago' AND status='conectado'`,[req.usuario.barbearia_id]);const oferecerMp=!!x.aceitar_mercadopago&&mp.rowCount>0;const r=await pool.query(`UPDATE barbearias SET pagamento_agendamento=$1,percentual_sinal=$2,aceitar_mercadopago=$3,mp_aceitar_pix=$4,mp_aceitar_cartao=$5,aceitar_pix_manual=$6,pix_chave=$7,pix_nome=$8,pix_banco=$9,aceitar_dinheiro=$10 WHERE id=$11 RETURNING pagamento_agendamento,percentual_sinal,aceitar_mercadopago,mp_aceitar_pix,mp_aceitar_cartao,aceitar_pix_manual,pix_chave,pix_nome,pix_banco,aceitar_dinheiro`,[modo,pct,oferecerMp,x.mp_aceitar_pix!==false,x.mp_aceitar_cartao!==false,!!x.aceitar_pix_manual,pixChave,pixNome,pixBanco,x.aceitar_dinheiro!==false,req.usuario.barbearia_id]);res.json(r.rows[0])}catch(e){console.error(e);res.status(500).json({erro:'Erro ao salvar pagamentos'})}});
router.get('/gateways/:provedor/conectar',autenticar,exigirPapel('dono'),exigirRecurso('pagamentos_online'),async(req,res)=>{try{if(!['pagbank','stripe'].includes(req.params.provedor))return res.status(400).json({erro:'Use o método de conexão indicado para este gateway'});res.json({url:await createOauthUrl(req.params.provedor,req.usuario.barbearia_id)})}catch(e){res.status(503).json({erro:e.message})}});
router.post('/gateways/asaas/conectar',autenticar,exigirPapel('dono'),exigirRecurso('pagamentos_online'),async(req,res)=>{try{await connectAsaas({barbeariaId:req.usuario.barbearia_id,apiKey:req.body?.api_key,environment:req.body?.environment});res.json({mensagem:'Asaas conectado com sucesso'})}catch(e){res.status(400).json({erro:String(e.message||'Falha ao conectar Asaas').slice(0,220)})}});
router.post('/gateways/pagarme/conectar',autenticar,exigirPapel('dono'),exigirRecurso('pagamentos_online'),async(req,res)=>{try{await connectPagarme({barbeariaId:req.usuario.barbearia_id,secretKey:req.body?.secret_key,publicKey:req.body?.public_key});res.json({mensagem:'Pagar.me conectado com sucesso'})}catch(e){res.status(400).json({erro:String(e.message||'Falha ao conectar Pagar.me').slice(0,220)})}});
router.delete('/gateways/:provedor',autenticar,exigirPapel('dono'),exigirRecurso('pagamentos_online'),async(req,res)=>{try{if(req.params.provedor==='mercadopago')return res.status(400).json({erro:'Use a desconexão do Mercado Pago'});await disconnectGateway(req.usuario.barbearia_id,req.params.provedor);res.json({mensagem:'Gateway desconectado'})}catch(e){res.status(400).json({erro:e.message})}});
router.get('/oauth/:provedor/callback',async(req,res)=>{const p=req.params.provedor;try{if(!['pagbank','stripe'].includes(p))throw new Error('Gateway inválido');if(req.query.error)throw new Error(String(req.query.error_description||req.query.error));if(!req.query.code||!req.query.state)throw new Error('Código de autorização ausente');await finishOauth(p,{code:String(req.query.code),state:String(req.query.state)});res.redirect(`/pages/pagamentos.html?gateway=${encodeURIComponent(p)}&status=conectado`)}catch(e){console.error(`OAuth ${p}:`,e);res.redirect(`/pages/pagamentos.html?gateway=${encodeURIComponent(p)}&status=erro&motivo=${encodeURIComponent(String(e.message||'Falha na conexão').slice(0,180))}`)}});
module.exports=router;
