const express=require('express');const {externalSignal}=require('../utils/http');
const crypto=require('crypto');
const pool=require('../config/db');
const {horaParaMinutos,minutosParaHora}=require('../utils/time');
const {notificar}=require('../services/notifications');
const {criarPreferenciaAgendamento,obterPagamento}=require('../services/mercadoPago');
const {getSellerAccessToken}=require('../services/mercadoPagoOAuth');
const {planoEfetivo,trialAtivo}=require('../services/planos');
const {verifyTurnstile,normalizePhone,validEmail,otpHash,timingSafeText}=require('../utils/security');
const {intId,dateWithinBookingWindow,hhmm,cleanText}=require('../utils/validation');
const {lockSlot,slotContext,upsertClient,HOLD_STATUSES}=require('../services/booking');
const {finalizePaidReservation}=require('../services/reservations');
const {resolveMarketingLink,recordMarketingConversion}=require('../services/marketing');
const router=express.Router();

function bookingOtpRequired(){return process.env.PUBLIC_BOOKING_REQUIRE_OTP!=='false'}
function publicToken(v){const t=String(v||'').trim();return /^[A-Za-z0-9_-]{32,200}$/.test(t)?t:null}
async function sendBookingOtp(email,code,barbeariaNome){
  if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM){if(process.env.NODE_ENV==='production')throw new Error('Serviço de OTP não configurado');console.log(`OTP DEV ${email}: ${code}`);return}
  const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[email],subject:`Código de confirmação - ${cleanText(barbeariaNome,120)}`,html:`<p>Seu código para confirmar o agendamento é:</p><p style="font-size:28px;font-weight:700;letter-spacing:4px">${code}</p><p>Ele expira em 10 minutos. Se você não solicitou este agendamento, ignore esta mensagem.</p>`}),signal:externalSignal()});
  if(!r.ok)throw new Error('Falha ao enviar código de confirmação');
}
async function validarBookingOtp(client,{barbeariaId,telefone,email,codigo}){
  if(!bookingOtpRequired())return {ok:true,id:null};
  if(!validEmail(email)||!/^[0-9]{6}$/.test(String(codigo||'')))return {ok:false,error:'Confirme o código enviado ao seu e-mail'};
  const r=await client.query(`SELECT id,code_hash,tentativas FROM booking_otps WHERE barbearia_id=$1 AND telefone=$2 AND LOWER(email)=LOWER($3) AND usado=false AND expira_em>NOW() ORDER BY id DESC LIMIT 1 FOR UPDATE`,[barbeariaId,telefone,email]);
  if(!r.rowCount)return {ok:false,error:'Código inválido ou expirado'};const row=r.rows[0];if(Number(row.tentativas||0)>=5)return {ok:false,error:'Muitas tentativas. Solicite um novo código'};
  if(!timingSafeText(otpHash(String(codigo)),row.code_hash)){await client.query(`UPDATE booking_otps SET tentativas=LEAST(tentativas+1,10) WHERE id=$1`,[row.id]);return {ok:false,error:'Código de confirmação inválido'}}
  return {ok:true,id:row.id};
}
async function tenant(slug){
  const b=(await pool.query(`
    SELECT b.id,b.nome,b.slug,b.telefone,b.email,b.endereco,b.cidade,b.estado,b.logo_url,b.banner_url,b.cor_primaria,b.cor_secundaria,b.cor_botao,b.cor_fundo,b.tema,b.descricao_publica,b.texto_boas_vindas,b.instagram,b.whatsapp_publico,COALESCE(b.mostrar_whatsapp_publico,true) mostrar_whatsapp_publico,COALESCE(b.mostrar_mapa_publico,true) mostrar_mapa_publico,b.mostrar_precos,b.mostrar_duracao,b.politica_cancelamento,
           COALESCE(b.pagamento_agendamento,'nenhum') pagamento_agendamento,COALESCE(b.percentual_sinal,50) percentual_sinal,
           COALESCE(b.aceitar_mercadopago,false) aceitar_mercadopago,COALESCE(b.mp_aceitar_pix,true) mp_aceitar_pix,COALESCE(b.mp_aceitar_cartao,true) mp_aceitar_cartao,
           COALESCE(b.aceitar_pix_manual,false) aceitar_pix_manual,b.pix_chave,b.pix_nome,b.pix_banco,COALESCE(b.aceitar_dinheiro,true) aceitar_dinheiro,
           EXISTS(SELECT 1 FROM integracoes_pagamento ip WHERE ip.barbearia_id=b.id AND ip.provedor='mercadopago' AND ip.status='conectado') mp_conectado,
           ass.plano,ass.status assinatura_status,ass.fim_trial
      FROM barbearias b
      JOIN LATERAL (SELECT plano,status,fim_trial FROM assinaturas a WHERE a.barbearia_id=b.id ORDER BY a.id DESC LIMIT 1) ass ON true
     WHERE b.slug=$1 AND b.ativo=true AND b.excluido_em IS NULL AND b.email_verificado=true
       AND (ass.status='ativa' OR (ass.status='trial' AND ass.fim_trial>=CURRENT_DATE))`,[String(slug||'').slice(0,120)])).rows[0]||null;
  if(!b)return null;const a={plano:b.plano,status:b.assinatura_status,fim_trial:b.fim_trial};b.plano_efetivo=planoEfetivo(a);b.trial_ativo=trialAtivo(a);
  if(['starter','pro'].includes(b.plano_efetivo)){b.logo_url=null;b.banner_url=null;b.cor_primaria='#f59e0b';b.cor_secundaria='#111827';b.cor_botao='#f59e0b';b.cor_fundo='#f7f7f8';b.tema='claro';b.texto_boas_vindas=null;b.instagram=null;b.politica_cancelamento=null;b.mostrar_precos=true;b.mostrar_duracao=true;}
  return b;
}
function valorCobranca(preco,modo,percentual){const total=Number(preco||0);if(modo==='total')return total;if(modo==='sinal')return Math.max(0.01,Math.round((total*Math.max(1,Math.min(100,Number(percentual||50)))/100)*100)/100);return 0}
function metodosPublicos(b){const out=[];if(b.pagamento_agendamento==='nenhum')return out;if(b.aceitar_mercadopago&&b.mp_conectado&&(b.mp_aceitar_pix||b.mp_aceitar_cartao))out.push({id:'mercado_pago',nome:'Mercado Pago',descricao:[b.mp_aceitar_pix?'Pix':'',b.mp_aceitar_cartao?'Cartão':''].filter(Boolean).join(' e ')});if(b.aceitar_pix_manual&&b.pix_chave)out.push({id:'pix_manual',nome:'Pix manual',descricao:'Pague pela chave Pix da barbearia'});if(b.aceitar_dinheiro)out.push({id:'dinheiro',nome:'Dinheiro',descricao:'Pague no atendimento'});return out}

router.get('/:slug',async(req,res)=>{try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});const lojaLiberada=process.env.ENABLE_PUBLIC_STORE==='true'&&['pro','premium'].includes(b.plano_efetivo);const[barbeiros,servicos,loja,produtos]=await Promise.all([pool.query(`SELECT id,nome FROM barbeiros WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[b.id]),pool.query(`SELECT id,nome,duracao,preco FROM servicos WHERE barbearia_id=$1 AND ativo=true ORDER BY nome`,[b.id]),pool.query(`SELECT COALESCE(loja_ativa,false) loja_ativa,loja_titulo,loja_descricao,loja_logo_url,loja_banner_url FROM barbearias WHERE id=$1`,[b.id]),lojaLiberada?pool.query(`SELECT id,nome,preco,imagem_url,descricao_publica,estoque FROM produtos WHERE barbearia_id=$1 AND ativo=true AND COALESCE(mostrar_na_loja,false)=true AND COALESCE(destaque_pagina_publica,false)=true ORDER BY nome LIMIT 6`,[b.id]):Promise.resolve({rows:[]})]);const publico={...b,pix_chave:undefined,pix_nome:undefined,pix_banco:undefined};const lc=loja.rows[0]||{};const lojaPublica={ativa:lojaLiberada&&lc.loja_ativa===true,url:lojaLiberada&&lc.loja_ativa===true?`/loja/${encodeURIComponent(b.slug)}`:null,titulo:lc.loja_titulo||'Loja da barbearia'};res.json({barbearia:publico,barbeiros:barbeiros.rows,servicos:servicos.rows,loja:lojaPublica,produtos_destaque:lojaPublica.ativa?produtos.rows:[],metodos_pagamento:metodosPublicos(b),security:{turnstile_site_key:process.env.TURNSTILE_SITE_KEY||null,booking_otp_required:bookingOtpRequired(),max_booking_days:Number(process.env.MAX_BOOKING_DAYS||120)}})}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar página pública'})}});
router.get('/:slug/loja',async(req,res)=>{try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});if(process.env.ENABLE_PUBLIC_STORE!=='true'||!['pro','premium'].includes(b.plano_efetivo))return res.status(404).json({erro:'Vitrine online não disponível'});const conf=(await pool.query(`SELECT COALESCE(loja_ativa,false) loja_ativa,loja_titulo,loja_descricao,loja_logo_url,loja_banner_url,logo_url,banner_url,whatsapp_publico,nome,endereco,cidade,estado FROM barbearias WHERE id=$1`,[b.id])).rows[0];if(!conf?.loja_ativa)return res.status(404).json({erro:'Loja não disponível'});const produtos=(await pool.query(`SELECT id,nome,preco,imagem_url,descricao_publica,estoque FROM produtos WHERE barbearia_id=$1 AND ativo=true AND COALESCE(mostrar_na_loja,false)=true ORDER BY nome`,[b.id])).rows;res.json({loja:{nome:conf.loja_titulo||`Loja ${conf.nome}`,descricao:conf.loja_descricao||'',logo_url:conf.loja_logo_url||conf.logo_url||null,banner_url:conf.loja_banner_url||conf.banner_url||null,whatsapp:conf.whatsapp_publico||b.telefone||null,endereco:[conf.endereco,conf.cidade,conf.estado].filter(Boolean).join(', '),agendamento_url:`/agendar/${encodeURIComponent(b.slug)}`},produtos});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar loja'})}});

router.post('/:slug/otp/solicitar',async(req,res)=>{try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});if(!bookingOtpRequired())return res.json({mensagem:'Confirmação adicional não exigida'});const telefone=normalizePhone(req.body.telefone),email=String(req.body.email||'').trim().toLowerCase();if(telefone.length<10||email.length>160||!validEmail(email))return res.status(400).json({erro:'Informe WhatsApp e e-mail válidos'});if(!(await verifyTurnstile(req.body.turnstile_token,req.ip,{action:'public_booking'})))return res.status(400).json({erro:'Verificação anti-robô inválida'});const lim=await pool.query(`SELECT COUNT(*)::int qtd FROM booking_otps WHERE barbearia_id=$1 AND (telefone=$2 OR LOWER(email)=LOWER($3)) AND criado_em>NOW()-INTERVAL '30 minutes'`,[b.id,telefone,email]);if(Number(lim.rows[0].qtd)>=3)return res.status(429).json({erro:'Muitos códigos solicitados. Aguarde alguns minutos.'});const code=String(crypto.randomInt(100000,1000000));await pool.query(`UPDATE booking_otps SET usado=true WHERE barbearia_id=$1 AND (telefone=$2 OR LOWER(email)=LOWER($3)) AND usado=false`,[b.id,telefone,email]);const ins=await pool.query(`INSERT INTO booking_otps(barbearia_id,telefone,email,code_hash,expira_em) VALUES($1,$2,$3,$4,NOW()+INTERVAL '10 minutes') RETURNING id`,[b.id,telefone,email,otpHash(code)]);try{await sendBookingOtp(email,code,b.nome)}catch(e){await pool.query(`UPDATE booking_otps SET usado=true WHERE id=$1`,[ins.rows[0].id]);throw e}res.json({mensagem:'Código enviado para seu e-mail. Ele expira em 10 minutos.'})}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível enviar o código agora'})}});

router.get('/:slug/horarios',async(req,res)=>{try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});const barbeiroId=intId(req.query.barbeiro_id),servicoId=intId(req.query.servico_id),data=String(req.query.data||'');if(!barbeiroId||!servicoId||!dateWithinBookingWindow(data))return res.status(400).json({erro:'Parâmetros de data, barbeiro ou serviço inválidos'});const s=await pool.query(`SELECT duracao FROM servicos WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[servicoId,b.id]);if(!s.rowCount)return res.json([]);const br=await pool.query(`SELECT 1 FROM barbeiros WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[barbeiroId,b.id]);if(!br.rowCount)return res.json([]);const dur=Number(s.rows[0].duracao),dow=Number((await pool.query(`SELECT EXTRACT(ISODOW FROM $1::date) dia`,[data])).rows[0].dia);const exp=await pool.query(`SELECT hora_inicio,hora_fim FROM horarios_trabalho WHERE barbeiro_id=$1 AND barbearia_id=$2 AND dia_semana=$3`,[barbeiroId,b.id,dow]);if(!exp.rowCount)return res.json([]);const [ag,rp]=await Promise.all([pool.query(`SELECT a.horario,s.duracao FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND a.barbeiro_id=$2 AND a.data=$3 AND a.status IN ('agendado','confirmado','em_atendimento','concluido')`,[b.id,barbeiroId,data]),pool.query(`SELECT r.horario,s.duracao FROM reservas_pagamento r JOIN servicos s ON s.id=r.servico_id AND s.barbearia_id=r.barbearia_id WHERE r.barbearia_id=$1 AND r.barbeiro_id=$2 AND r.data=$3 AND r.status=ANY($4::text[]) AND r.expira_em>NOW()`,[b.id,barbeiroId,data,HOLD_STATUSES])]);const busy=[...ag.rows,...rp.rows],out=[];for(let m=horaParaMinutos(exp.rows[0].hora_inicio),fim=horaParaMinutos(exp.rows[0].hora_fim);m+dur<=fim;m+=30)if(!busy.some(x=>m<horaParaMinutos(x.horario)+Number(x.duracao)&&m+dur>horaParaMinutos(x.horario)))out.push(minutosParaHora(m));res.json(out)}catch(e){console.error(e);res.status(400).json({erro:'Não foi possível calcular horários para os dados informados'})}});

router.post('/:slug/agendar',async(req,res)=>{const db=await pool.connect();try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});const nome=cleanText(req.body.nome,120,{required:true}),telefone=normalizePhone(req.body.telefone),email=String(req.body.email||'').trim().toLowerCase()||null,barbeiroId=intId(req.body.barbeiro_id),servicoId=intId(req.body.servico_id),data=String(req.body.data||''),horario=hhmm(req.body.horario),forma=req.body.forma_pagamento?String(req.body.forma_pagamento):null,marketingOptIn=req.body.marketing_opt_in===true;if(!nome||telefone.length<10||!barbeiroId||!servicoId||!horario||!dateWithinBookingWindow(data)||email&&(email.length>160||!validEmail(email)))return res.status(400).json({erro:'Preencha todos os campos corretamente'});if(!(await verifyTurnstile(req.body.turnstile_token,req.ip,{action:'public_booking'})))return res.status(400).json({erro:'Verificação anti-robô inválida'});const mkt=await resolveMarketingLink(b.id,req.body.marketing_token,'agendamento');
  await db.query('BEGIN');
  const fluxoOtp=b.pagamento_agendamento==='nenhum'||forma==='dinheiro'||forma==='pix_manual';let otp={ok:true,id:null};if(fluxoOtp){otp=await validarBookingOtp(db,{barbeariaId:b.id,telefone,email,codigo:req.body.otp_code});if(!otp.ok){await db.query('COMMIT');return res.status(400).json({erro:otp.error});}}
  const abuse=await db.query(`SELECT (SELECT COUNT(*) FROM reservas_pagamento WHERE barbearia_id=$1 AND telefone=$2 AND agendamento_id IS NULL AND status=ANY($3::text[]) AND expira_em>NOW())::int holds,(SELECT COUNT(*) FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id AND c.barbearia_id=a.barbearia_id WHERE a.barbearia_id=$1 AND regexp_replace(c.telefone,'\\D','','g')=$2 AND a.data>=CURRENT_DATE AND a.status IN ('agendado','confirmado','em_atendimento'))::int futuros`,[b.id,telefone,HOLD_STATUSES]);if(Number(abuse.rows[0].holds)>=2||Number(abuse.rows[0].futuros)>=6){await db.query('ROLLBACK');return res.status(429).json({erro:'Limite de reservas ativas atingido para este telefone'});}
  await lockSlot(db,b.id,barbeiroId,data);const ctx=await slotContext(db,{barbeariaId:b.id,barbeiroId,servicoId,data,horario});if(!ctx.ok){await db.query('ROLLBACK');return res.status(ctx.code==='CONFLITO'?409:400).json({erro:ctx.error});}
  const total=Number(ctx.servico.preco||0),getClient=()=>upsertClient(db,{barbeariaId:b.id,nome,telefone,email,marketingOptIn,marketingOrigem:'agendamento_publico'});
  if(b.pagamento_agendamento==='nenhum'){const client=await getClient();if(otp.id)await db.query(`UPDATE booking_otps SET usado=true WHERE id=$1`,[otp.id]);const r=await db.query(`INSERT INTO agendamentos(barbearia_id,cliente_id,barbeiro_id,servico_id,data,horario,status,origem,forma_pagamento,status_pagamento,valor_servico,valor_final,marketing_link_id,marketing_campanha_id) VALUES($1,$2,$3,$4,$5,$6,'agendado','publico','nao_informado','nao_exigido',$7,$7,$8,$9) RETURNING id,public_token,data,horario,status`,[b.id,client.id,barbeiroId,servicoId,data,horario,total,mkt?.id||null,mkt?.campanha_id||null]);await db.query('COMMIT');if(mkt)await recordMarketingConversion(pool,{linkId:mkt.id,campaignId:mkt.campanha_id,revenue:0});notificar('agendamento_publico_criado',{barbearia_id:b.id,agendamento_id:r.rows[0].id,cliente:nome,telefone});return res.status(201).json({mensagem:'Agendamento realizado com sucesso',agendamento:{token:r.rows[0].public_token,data:r.rows[0].data,horario:r.rows[0].horario,status:r.rows[0].status},requires_payment:false});}
  if(marketingOptIn)await getClient();
  const methods=metodosPublicos(b).map(x=>x.id);if(!methods.includes(forma)){await db.query('ROLLBACK');return res.status(400).json({erro:'Escolha uma forma de pagamento disponível'});}const charge=valorCobranca(total,b.pagamento_agendamento,b.percentual_sinal);if(charge<=0){await db.query('ROLLBACK');return res.status(400).json({erro:'Serviço sem valor válido para cobrança'});}
  if(forma==='dinheiro'){const client=await getClient();if(otp.id)await db.query(`UPDATE booking_otps SET usado=true WHERE id=$1`,[otp.id]);const ag=await db.query(`INSERT INTO agendamentos(barbearia_id,cliente_id,barbeiro_id,servico_id,data,horario,status,origem,forma_pagamento,status_pagamento,valor_cobrado,valor_pago,valor_servico,valor_final,marketing_link_id,marketing_campanha_id) VALUES($1,$2,$3,$4,$5,$6,'agendado','publico_dinheiro','dinheiro','aguardando',$7,0,$8,$8,$9,$10) RETURNING id,public_token,data,horario,status`,[b.id,client.id,barbeiroId,servicoId,data,horario,charge,total,mkt?.id||null,mkt?.campanha_id||null]);await db.query('COMMIT');if(mkt)await recordMarketingConversion(pool,{linkId:mkt.id,campaignId:mkt.campanha_id,revenue:0});return res.status(201).json({mensagem:'Agendamento realizado. Pagamento em dinheiro no atendimento.',requires_payment:false,agendamento:{token:ag.rows[0].public_token,data:ag.rows[0].data,horario:ag.rows[0].horario,status:ag.rows[0].status}});}
  const minutes=Math.max(5,Math.min(30,Number(process.env.BOOKING_HOLD_MINUTES||15))),holdStatus=forma==='pix_manual'?'aguardando_pix_manual':'aguardando_pagamento';if(forma==='pix_manual'&&otp.id)await db.query(`UPDATE booking_otps SET usado=true WHERE id=$1`,[otp.id]);const reservation=await db.query(`INSERT INTO reservas_pagamento(barbearia_id,barbeiro_id,servico_id,nome,telefone,email,data,horario,valor_total,valor_cobrado,status,expira_em,forma_pagamento,marketing_link_id,marketing_campanha_id,marketing_opt_in) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW()+($12*INTERVAL '1 minute'),$13,$14,$15,$16) RETURNING *`,[b.id,barbeiroId,servicoId,nome,telefone,email,data,horario,total,charge,holdStatus,minutes,forma,mkt?.id||null,mkt?.campanha_id||null,marketingOptIn]);await db.query('COMMIT');const pub=reservation.rows[0].public_token;
  if(forma==='pix_manual')return res.status(201).json({mensagem:'Horário reservado. Faça o Pix e aguarde a confirmação da barbearia.',requires_payment:true,payment_type:'pix_manual',reserva_token:pub,expira_em:reservation.rows[0].expira_em,valor_cobrado:charge,pix:{chave:b.pix_chave,nome:b.pix_nome||b.nome,banco:b.pix_banco||null}});
  try{const seller=await getSellerAccessToken(b.id);const mp=await criarPreferenciaAgendamento({reservaId:reservation.rows[0].id,reservaToken:pub,barbeariaId:b.id,slug:b.slug,servicoId:ctx.servico.id,servicoNome:ctx.servico.nome,valor:charge,nome,email,accessToken:seller,aceitarPix:b.mp_aceitar_pix,aceitarCartao:b.mp_aceitar_cartao});await pool.query(`UPDATE reservas_pagamento SET mp_preference_id=$1,atualizado_em=NOW() WHERE id=$2`,[mp.id,reservation.rows[0].id]);return res.status(201).json({mensagem:'Horário reservado. Conclua o pagamento para confirmar.',requires_payment:true,payment_type:'mercado_pago',checkout_url:mp.init_point,reserva_token:pub,expira_em:reservation.rows[0].expira_em,valor_cobrado:charge});}catch(e){await pool.query(`UPDATE reservas_pagamento SET status='falha_pagamento',atualizado_em=NOW() WHERE id=$1`,[reservation.rows[0].id]);console.error('Preferência pagamento agendamento:',e.status,e.message);return res.status(502).json({erro:e.status===429?'Mercado Pago limitou temporariamente as tentativas. Tente novamente em alguns instantes.':'Não foi possível iniciar o pagamento.'});}
}catch(e){try{await db.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({erro:'Erro ao agendar'})}finally{db.release()}});

router.get('/:slug/reservas/:token',async(req,res)=>{try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});const token=publicToken(req.params.token);if(!token)return res.status(404).json({erro:'Reserva não encontrada'});const r=await pool.query(`SELECT status,expira_em,mp_status,CASE WHEN agendamento_id IS NULL THEN NULL ELSE (SELECT public_token FROM agendamentos WHERE id=agendamento_id AND barbearia_id=$2) END agendamento_token FROM reservas_pagamento WHERE public_token=$1 AND barbearia_id=$2`,[token,b.id]);if(!r.rowCount)return res.status(404).json({erro:'Reserva não encontrada'});res.json(r.rows[0])}catch{res.status(500).json({erro:'Erro ao consultar reserva'})}});
router.post('/:slug/reservas/:token/sincronizar',async(req,res)=>{try{const b=await tenant(req.params.slug);if(!b)return res.status(404).json({erro:'Barbearia não encontrada'});const token=publicToken(req.params.token);if(!token)return res.status(404).json({erro:'Reserva não encontrada'});const rr=await pool.query(`SELECT id,forma_pagamento FROM reservas_pagamento WHERE public_token=$1 AND barbearia_id=$2`,[token,b.id]);if(!rr.rowCount)return res.status(404).json({erro:'Reserva não encontrada'});if(rr.rows[0].forma_pagamento!=='mercado_pago')return res.status(400).json({erro:'Esta reserva não usa Mercado Pago'});const paymentId=String(req.body.payment_id||'').replace(/\D/g,'').slice(0,32);if(!paymentId)return res.status(400).json({erro:'payment_id obrigatório'});const seller=await getSellerAccessToken(b.id);const payment=await obterPagamento(paymentId,seller);res.json(await finalizePaidReservation(rr.rows[0].id,payment))}catch(e){console.error(e.message);res.status(502).json({erro:'Não foi possível sincronizar o pagamento'})}});

async function publicAppointment(slug,token,db=pool){const b=await tenant(slug),safeToken=publicToken(token);if(!b||!safeToken)return null;return (await db.query(`SELECT a.*,s.duracao,b.cancelamento_limite_horas AS barber_cancel_limit FROM agendamentos a JOIN servicos s ON s.id=a.servico_id AND s.barbearia_id=a.barbearia_id LEFT JOIN barbeiros b ON b.id=a.barbeiro_id AND b.barbearia_id=a.barbearia_id WHERE a.public_token=$1 AND a.barbearia_id=$2`,[safeToken,b.id])).rows[0]||null;}
function manageableStatus(s){return ['agendado','confirmado'].includes(String(s));}
router.post('/:slug/agendamentos/:token/cancelar',async(req,res)=>{const db=await pool.connect();try{await db.query('BEGIN');const a=await publicAppointment(req.params.slug,req.params.token,db);if(!a){await db.query('ROLLBACK');return res.status(404).json({erro:'Agendamento não encontrado'});}const locked=await db.query(`SELECT * FROM agendamentos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[a.id,a.barbearia_id]);const cur=locked.rows[0];if(!manageableStatus(cur.status)){await db.query('ROLLBACK');return res.status(409).json({erro:'Este agendamento não pode mais ser cancelado online'});}const limit=Number(cur.cancelamento_limite_horas??6);const ok=(await db.query(`SELECT ($1::date+$2::time)-NOW() >= ($3*INTERVAL '1 hour') ok`,[cur.data,cur.horario,limit])).rows[0].ok;if(!ok){await db.query('ROLLBACK');return res.status(409).json({erro:`Cancelamento permitido até ${limit}h antes do horário`});}const refund=['pago','parcial'].includes(cur.status_pagamento);await db.query(`UPDATE agendamentos SET status='cancelado',reembolso_status=CASE WHEN $1 THEN 'pendente' ELSE COALESCE(reembolso_status,'nao_aplicavel') END WHERE id=$2 AND barbearia_id=$3`,[refund,cur.id,cur.barbearia_id]);await db.query('COMMIT');notificar('agendamento_cancelado_publico',{barbearia_id:cur.barbearia_id,agendamento_id:cur.id,reembolso_pendente:refund});res.json({mensagem:refund?'Agendamento cancelado. O pagamento ficará pendente de reembolso pela barbearia.':'Agendamento cancelado',reembolso_pendente:refund})}catch(e){try{await db.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({erro:'Erro ao cancelar'})}finally{db.release()}});

router.post('/:slug/agendamentos/:token/reagendar',async(req,res)=>{const db=await pool.connect();try{const a=await publicAppointment(req.params.slug,req.params.token,db);if(!a)return res.status(404).json({erro:'Agendamento não encontrado'});if(!manageableStatus(a.status))return res.status(409).json({erro:'Este agendamento não pode mais ser reagendado online'});const date=String(req.body.data||''),time=hhmm(req.body.horario),barberId=intId(req.body.barbeiro_id)||a.barbeiro_id;if(!time||!dateWithinBookingWindow(date,{allowToday:true}))return res.status(400).json({erro:'Nova data ou horário inválido'});const limit=Number(a.cancelamento_limite_horas??6);const cutoff=(await db.query(`SELECT ($1::date+$2::time)-NOW() >= ($3*INTERVAL '1 hour') ok`,[a.data,a.horario,limit])).rows[0].ok;if(!cutoff)return res.status(409).json({erro:`Reagendamento permitido até ${limit}h antes do horário atual`});await db.query('BEGIN');await lockSlot(db,a.barbearia_id,barberId,date);const current=await db.query(`SELECT status FROM agendamentos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[a.id,a.barbearia_id]);if(!current.rowCount||!manageableStatus(current.rows[0].status)){await db.query('ROLLBACK');return res.status(409).json({erro:'Agendamento foi alterado e não pode mais ser reagendado'});}const ctx=await slotContext(db,{barbeariaId:a.barbearia_id,barbeiroId:barberId,servicoId:a.servico_id,data:date,horario:time,ignoreAppointmentId:a.id});if(!ctx.ok){await db.query('ROLLBACK');return res.status(ctx.code==='CONFLITO'?409:400).json({erro:ctx.error});}const status=a.status==='confirmado'||['pago','parcial'].includes(a.status_pagamento)?'confirmado':'agendado';const r=await db.query(`UPDATE agendamentos SET barbeiro_id=$1,data=$2,horario=$3,status=$4 WHERE id=$5 AND barbearia_id=$6 RETURNING public_token,data,horario,status`,[barberId,date,time,status,a.id,a.barbearia_id]);await db.query('COMMIT');res.json({token:r.rows[0].public_token,data:r.rows[0].data,horario:r.rows[0].horario,status:r.rows[0].status})}catch(e){try{await db.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({erro:'Erro ao reagendar'})}finally{db.release()}});
router.post('/:slug/agendamentos/:token/avaliar',async(req,res)=>{try{const a=await publicAppointment(req.params.slug,req.params.token);if(!a||a.status!=='concluido')return res.status(400).json({erro:'Atendimento não elegível para avaliação'});const eligible=(await pool.query(`SELECT CURRENT_DATE-$1::date <= 30 ok`,[a.data])).rows[0].ok;if(!eligible)return res.status(409).json({erro:'O período para avaliação encerrou'});const nota=Number(req.body.nota);if(!Number.isInteger(nota)||nota<1||nota>5)return res.status(400).json({erro:'Nota inválida'});const comment=cleanText(req.body.comentario,1000)||null;const r=await pool.query(`INSERT INTO avaliacoes(barbearia_id,agendamento_id,nota,comentario) VALUES($1,$2,$3,$4) ON CONFLICT(agendamento_id) DO UPDATE SET nota=EXCLUDED.nota,comentario=EXCLUDED.comentario RETURNING *`,[a.barbearia_id,a.id,nota,comment]);res.json(r.rows[0])}catch{res.status(500).json({erro:'Erro ao avaliar'})}});

router.finalizarReservaPagamento=finalizePaidReservation;
router.tenantBySlug=tenant;
module.exports=router;
