const crypto=require('crypto');
const express=require('express');
const pool=require('../config/db');
const {externalSignal}=require('../utils/http');
const {storeTenantBySlug,tenantMpCredentials,shippingConfig,quoteShipping,createOrder,getOrderByToken,markOrderPayment,releaseOrderStock,safeOrderToken}=require('../services/storeCommerce');
const {criarPagamentoLojaPix,criarPagamentoLojaCartao,obterPagamento,safeMercadoPagoCheckoutUrl}=require('../services/mercadoPago');
const {validateCoupon}=require('../services/marketing');
const {publicError}=require('../utils/security');
const router=express.Router();
function money(n){return Math.round(Number(n||0)*100)/100}
async function cartSubtotal(b,itens){const arr=Array.isArray(itens)?itens.slice(0,30):[];if(!arr.length)throw Object.assign(new Error('Carrinho vazio'),{status:400});let total=0;for(const x of arr){const id=Number(x.id),q=Number(x.quantidade);if(!Number.isSafeInteger(id)||id<1||!Number.isInteger(q)||q<1||q>99)throw Object.assign(new Error('Item inválido'),{status:400});const p=(await pool.query(`SELECT preco,estoque FROM produtos WHERE id=$1 AND barbearia_id=$2 AND ativo=true AND COALESCE(mostrar_na_loja,false)=true`,[id,b.id])).rows[0];if(!p||Number(p.estoque)<q)throw Object.assign(new Error('Produto indisponível ou sem estoque'),{status:409});total+=Number(p.preco)*q;}return money(total)}
function safeOrder(o){if(!o)return null;return {token:o.public_token,cliente_nome:o.cliente_nome,tipo_entrega:o.tipo_entrega,distancia_km:o.distancia_km==null?null:Number(o.distancia_km),subtotal:Number(o.subtotal),desconto:Number(o.desconto||0),cupom_codigo:o.cupom_codigo||null,frete:Number(o.frete),total:Number(o.total),forma_pagamento:o.forma_pagamento,status_pagamento:o.status_pagamento,status_pedido:o.status_pedido,status_label:o.status_label,qr_code:o.qr_code||null,qr_code_base64:o.qr_code_base64||null,ticket_url:safeMercadoPagoCheckoutUrl(o.ticket_url),expira_em:o.expira_em,pago_em:o.pago_em,itens:o.itens||[]}}

router.get('/:slug/loja',async(req,res)=>{try{const b=await storeTenantBySlug(req.params.slug);if(!b)return res.status(404).json({erro:'Loja não disponível'});const produtos=(await pool.query(`SELECT id,nome,preco,imagem_url,descricao_publica,estoque FROM produtos WHERE barbearia_id=$1 AND ativo=true AND COALESCE(mostrar_na_loja,false)=true ORDER BY nome`,[b.id])).rows;const cfg=shippingConfig(b);res.json({loja:{nome:b.loja_titulo||`Loja ${b.nome}`,descricao:b.loja_descricao||'',logo_url:b.loja_logo_url||b.logo_url||null,banner_url:b.loja_banner_url||b.banner_url||null,whatsapp:b.whatsapp_publico||b.telefone||null,endereco:[b.endereco,b.cidade,b.estado].filter(Boolean).join(', '),agendamento_url:`/agendar/${encodeURIComponent(b.slug)}`,checkout_ativo:!!b.mp_conectado,public_key:b.mp_public_key||null,retirada:{ativa:cfg.aceitar_retirada,instrucao:cfg.retirada_instrucao},entrega:{ativa:cfg.aceitar_entrega,distancia_max_km:cfg.distancia_max_km,gratis_ate_km:cfg.gratis_ate_km,gratis_acima:cfg.gratis_acima,valor_por_km:cfg.valor_por_km,taxa_base:cfg.taxa_base,frete_minimo:cfg.frete_minimo},pedido_minimo:cfg.pedido_minimo,pagamentos:{pix:cfg.aceitar_pix&&!!b.mp_conectado,cartao:cfg.aceitar_cartao&&!!b.mp_conectado}},produtos});}catch(e){console.error('store_public_load',e);res.status(500).json({erro:'Erro ao carregar loja'})}});
router.get('/:slug/loja/cep/:cep',async(req,res)=>{try{const b=await storeTenantBySlug(req.params.slug);if(!b)return res.status(404).json({erro:'Loja não disponível'});const cep=String(req.params.cep||'').replace(/\D/g,'');if(!/^\d{8}$/.test(cep))return res.status(400).json({erro:'CEP inválido'});const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`,{headers:{Accept:'application/json'},signal:externalSignal()});const d=await r.json();if(!r.ok||d.erro)return res.status(404).json({erro:'CEP não encontrado'});res.json({cep:d.cep||cep,endereco:d.logradouro||'',bairro:d.bairro||'',cidade:d.localidade||'',estado:d.uf||''})}catch(e){res.status(502).json({erro:'Não foi possível consultar o CEP agora'})}});
router.post('/:slug/loja/cupom',async(req,res)=>{try{const b=await storeTenantBySlug(req.params.slug);if(!b)return res.status(404).json({erro:'Loja não disponível'});const subtotal=await cartSubtotal(b,req.body?.itens);const v=await validateCoupon({barbeariaId:b.id,codigo:req.body?.codigo,subtotal,telefone:req.body?.telefone});if(!v.valid)return res.status(400).json({erro:v.error||'Cupom inválido'});res.json({codigo:v.coupon.codigo,desconto:v.discount,subtotal,total_parcial:money(subtotal-v.discount),descricao:v.coupon.descricao||null})}catch(e){const status=Number(e.status)>=400&&Number(e.status)<500?Number(e.status):500;res.status(status).json({erro:publicError(e,'Não foi possível validar o cupom',{allowClient:true}),request_id:req.requestId})}});
router.post('/:slug/loja/frete',async(req,res)=>{try{const b=await storeTenantBySlug(req.params.slug);if(!b)return res.status(404).json({erro:'Loja não disponível'});const subtotal=await cartSubtotal(b,req.body?.itens);const q=await quoteShipping(b,{tipo_entrega:req.body?.tipo_entrega,endereco:req.body?.endereco||{},subtotal});res.json({subtotal,frete:q.frete,total:money(subtotal+q.frete),distancia_km:q.distancia_km,provider:q.provider,duracao_estimada:q.duration||null})}catch(e){const status=Number(e.status)>=400&&Number(e.status)<500?Number(e.status):500;res.status(status).json({erro:publicError(e,'Não foi possível calcular o frete',{allowClient:true}),request_id:req.requestId})}});
router.post('/:slug/loja/pedidos',async(req,res)=>{try{const o=await createOrder({slug:req.params.slug,body:req.body||{}});res.status(201).json({pedido:safeOrder(await getOrderByToken(o.barbearia_id,o.public_token)),public_key:o.public_key||null,config:o.config||null})}catch(e){console.error('store_order_create',e.message);const status=Number(e.status)>=400&&Number(e.status)<500?Number(e.status):500;res.status(status).json({erro:publicError(e,'Não foi possível criar o pedido',{allowClient:true}),request_id:req.requestId})}});
async function orderContext(slug,tok){const b=await storeTenantBySlug(slug);if(!b)return null;const o=await getOrderByToken(b.id,tok);return o?{b,o}:null}
router.get('/:slug/loja/pedidos/:token',async(req,res)=>{try{const ctx=await orderContext(req.params.slug,req.params.token);if(!ctx)return res.status(404).json({erro:'Pedido não encontrado'});if(ctx.o.status_pagamento==='pendente'&&ctx.o.expira_em&&new Date(ctx.o.expira_em)<=new Date()){const db=await pool.connect();try{await db.query('BEGIN');await releaseOrderStock(db,ctx.o.id);await db.query(`UPDATE loja_pedidos SET status_pagamento='expirado',status_pedido='cancelado',atualizado_em=NOW() WHERE id=$1 AND status_pagamento='pendente'`,[ctx.o.id]);await db.query('COMMIT')}catch(e){await db.query('ROLLBACK').catch(()=>{});throw e}finally{db.release()}}res.json({pedido:safeOrder(await getOrderByToken(ctx.b.id,req.params.token))})}catch(e){res.status(500).json({erro:'Erro ao consultar pedido'})}});
router.post('/:slug/loja/pedidos/:token/pix',async(req,res)=>{try{const ctx=await orderContext(req.params.slug,req.params.token);if(!ctx)return res.status(404).json({erro:'Pedido não encontrado'});const {b,o}=ctx;if(o.status_pagamento!=='pendente'||o.status_pedido!=='aguardando_pagamento')return res.status(409).json({erro:'Pedido não está aguardando pagamento'});if(new Date(o.expira_em)<=new Date())return res.status(409).json({erro:'Pedido expirado. Refaça o checkout.'});const cfg=shippingConfig(b);if(!cfg.aceitar_pix)return res.status(400).json({erro:'Pix não está habilitado nesta loja'});const mp=await tenantMpCredentials(b.id);if(!mp.configured)return res.status(503).json({erro:'Mercado Pago não configurado'});const documento=String(req.body?.documento||'').replace(/\D/g,'');if(!/^\d{11,14}$/.test(documento))return res.status(400).json({erro:'Informe CPF ou CNPJ válido'});const pay=await criarPagamentoLojaPix({barbeariaId:b.id,pedidoId:o.id,valor:o.total,email:o.cliente_email,documento,accessToken:mp.accessToken,idempotencyKey:`store-pix-${o.id}`});const tx=pay.point_of_interaction?.transaction_data||{};await pool.query(`UPDATE loja_pedidos SET forma_pagamento='pix',mp_payment_id=$1,mp_status=$2,qr_code=$3,qr_code_base64=$4,ticket_url=$5,atualizado_em=NOW() WHERE id=$6`,[String(pay.id),pay.status||'pending',tx.qr_code||null,tx.qr_code_base64||null,tx.ticket_url||null,o.id]);if(pay.status==='approved')await markOrderPayment(o.id,pay);res.status(pay.status==='approved'?200:202).json({pedido:safeOrder(await getOrderByToken(b.id,o.public_token)),qr_code:tx.qr_code||null,qr_code_base64:tx.qr_code_base64||null,ticket_url:tx.ticket_url||null})}catch(e){console.error('store_pix',e.providerCode||e.status||'provider_error');res.status(e.status||502).json({erro:'Não foi possível gerar o pagamento Pix'})}});
router.post('/:slug/loja/pedidos/:token/cartao',async(req,res)=>{try{const ctx=await orderContext(req.params.slug,req.params.token);if(!ctx)return res.status(404).json({erro:'Pedido não encontrado'});const {b,o}=ctx;if(o.status_pagamento!=='pendente'||o.status_pedido!=='aguardando_pagamento')return res.status(409).json({erro:'Pedido não está aguardando pagamento'});if(new Date(o.expira_em)<=new Date())return res.status(409).json({erro:'Pedido expirado. Refaça o checkout.'});const cfg=shippingConfig(b);if(!cfg.aceitar_cartao)return res.status(400).json({erro:'Cartão não está habilitado nesta loja'});const mp=await tenantMpCredentials(b.id);if(!mp.configured)return res.status(503).json({erro:'Mercado Pago não configurado'});const f=req.body||{};const pay=await criarPagamentoLojaCartao({barbeariaId:b.id,pedidoId:o.id,valor:o.total,email:o.cliente_email,token:f.token,installments:f.installments,paymentMethodId:f.payment_method_id,issuerId:f.issuer_id,identification:f.payer?.identification,accessToken:mp.accessToken,idempotencyKey:`store-card-${o.id}`});await pool.query(`UPDATE loja_pedidos SET forma_pagamento='cartao',mp_payment_id=$1,mp_status=$2,atualizado_em=NOW() WHERE id=$3`,[String(pay.id),pay.status||'unknown',o.id]);await markOrderPayment(o.id,pay);const fresh=await getOrderByToken(b.id,o.public_token);if(pay.status!=='approved')return res.status(['pending','in_process','in_mediation'].includes(pay.status)?202:402).json({erro:'Pagamento não aprovado',pedido:safeOrder(fresh),status:String(pay.status||'unknown').slice(0,30)});res.json({mensagem:'Pagamento aprovado. Pedido confirmado!',pedido:safeOrder(fresh)})}catch(e){console.error('store_card',{status:e.status||null,provider_code:e.providerCode||null,request_id:req.requestId});res.status(e.status===400?400:502).json({erro:'Não foi possível processar o cartão'})}});
router.post('/:slug/loja/pedidos/:token/sincronizar',async(req,res)=>{try{const ctx=await orderContext(req.params.slug,req.params.token);if(!ctx)return res.status(404).json({erro:'Pedido não encontrado'});const {b,o}=ctx;if(!o.mp_payment_id)return res.json({pedido:safeOrder(o)});const mp=await tenantMpCredentials(b.id);if(!mp.configured)return res.status(503).json({erro:'Mercado Pago não configurado'});const pay=await obterPagamento(o.mp_payment_id,mp.accessToken);await markOrderPayment(o.id,pay);res.json({pedido:safeOrder(await getOrderByToken(b.id,o.public_token))})}catch(e){console.error('store_sync',e.message);res.status(502).json({erro:'Não foi possível sincronizar o pagamento'})}});
router.post('/:slug/loja/pedidos/:token/cancelar',async(req,res)=>{const ctx=await orderContext(req.params.slug,req.params.token);if(!ctx)return res.status(404).json({erro:'Pedido não encontrado'});const {b,o}=ctx;if(o.status_pagamento==='pago')return res.status(409).json({erro:'Pedido pago deve ser cancelado pela barbearia para processar reembolso'});if(o.status_pedido==='cancelado')return res.json({pedido:safeOrder(o)});const db=await pool.connect();try{await db.query('BEGIN');await releaseOrderStock(db,o.id);await db.query(`UPDATE loja_pedidos SET status_pedido='cancelado',status_pagamento=CASE WHEN status_pagamento='pendente' THEN 'cancelado' ELSE status_pagamento END,atualizado_em=NOW() WHERE id=$1`,[o.id]);await db.query('COMMIT');res.json({pedido:safeOrder(await getOrderByToken(b.id,o.public_token))})}catch(e){await db.query('ROLLBACK').catch(()=>{});res.status(500).json({erro:'Não foi possível cancelar o pedido'})}finally{db.release()}});
module.exports=router;
