const express=require('express');
const pool=require('../config/db');
const {autenticar,exigirPapel,exigirStepUp}=require('../middlewares/auth');
const {exigirRecurso,contextoPlano}=require('../services/planos');
const {cleanText,safeHttpUrl,intId,finiteMoney}=require('../utils/validation');
const {ensureStorefrontSchema}=require('../services/storefront');
const {ensureStoreCommerceSchema,shippingConfig,tenantMpCredentials}=require('../services/storeCommerce');
const {reembolsarPagamento,obterPagamento}=require('../services/mercadoPago');
const router=express.Router();
router.use(autenticar,exigirPapel('dono','gerente'),exigirRecurso('loja_publica'));

async function configPayload(barbeariaId){
  await ensureStorefrontSchema();await ensureStoreCommerceSchema();
  const b=(await pool.query(`SELECT id,nome,slug,endereco,cidade,estado,logo_url,banner_url,whatsapp_publico,
    COALESCE(loja_ativa,false) loja_ativa,loja_titulo,loja_descricao,loja_logo_url,loja_banner_url,
    COALESCE(loja_aceitar_retirada,true) loja_aceitar_retirada,COALESCE(loja_aceitar_entrega,false) loja_aceitar_entrega,loja_retirada_instrucao,
    COALESCE(loja_pedido_minimo,0) loja_pedido_minimo,COALESCE(loja_frete_taxa_base,0) loja_frete_taxa_base,COALESCE(loja_frete_por_km,2) loja_frete_por_km,
    COALESCE(loja_frete_minimo,0) loja_frete_minimo,loja_frete_gratis_ate_km,loja_frete_gratis_acima,COALESCE(loja_frete_distancia_max_km,20) loja_frete_distancia_max_km,
    COALESCE(loja_aceitar_pix,true) loja_aceitar_pix,COALESCE(loja_aceitar_cartao,true) loja_aceitar_cartao
    FROM barbearias WHERE id=$1`,[barbeariaId])).rows[0];
  const ctx=await contextoPlano(barbeariaId),mp=await tenantMpCredentials(barbeariaId);
  return {barbearia:b,plano:ctx.plano_efetivo,mercadopago:{configurado:mp.configured,webhook_pronto:!!mp.webhookReady},frete_provedor:(process.env.GOOGLE_MAPS_ROUTES_API_KEY||process.env.GOOGLE_MAPS_API_KEY)?'Google Routes':'OpenStreetMap / OSRM'};
}
router.get('/config',async(req,res)=>{try{res.json(await configPayload(req.usuario.barbearia_id))}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar configurações da loja'})}});

router.put('/config',exigirStepUp,async(req,res)=>{try{
  await ensureStoreCommerceSchema();const x=req.body||{},titulo=cleanText(x.loja_titulo,160)||null,descricao=cleanText(x.loja_descricao,2500)||null,logo=safeHttpUrl(x.loja_logo_url),banner=safeHttpUrl(x.loja_banner_url);
  if(logo===false||banner===false)return res.status(400).json({erro:'URL de logo ou banner inválida'});
  const nums={pedido_minimo:finiteMoney(x.loja_pedido_minimo??0,{max:100000}),taxa_base:finiteMoney(x.loja_frete_taxa_base??0,{max:10000}),por_km:finiteMoney(x.loja_frete_por_km??0,{max:10000}),frete_minimo:finiteMoney(x.loja_frete_minimo??0,{max:10000}),gratis_km:x.loja_frete_gratis_ate_km===''||x.loja_frete_gratis_ate_km==null?null:finiteMoney(x.loja_frete_gratis_ate_km,{max:5000}),gratis_valor:x.loja_frete_gratis_acima===''||x.loja_frete_gratis_acima==null?null:finiteMoney(x.loja_frete_gratis_acima,{max:1000000}),max_km:finiteMoney(x.loja_frete_distancia_max_km??20,{min:0.1,max:5000})};
  if(Object.entries(nums).some(([k,v])=>v===null&&!['gratis_km','gratis_valor'].includes(k)))return res.status(400).json({erro:'Configuração de frete inválida'});if((x.loja_frete_gratis_ate_km!==''&&x.loja_frete_gratis_ate_km!=null&&nums.gratis_km===null)||(x.loja_frete_gratis_acima!==''&&x.loja_frete_gratis_acima!=null&&nums.gratis_valor===null))return res.status(400).json({erro:'Regra de frete grátis inválida'});
  const retirada=x.loja_aceitar_retirada!==false,entrega=x.loja_aceitar_entrega===true;if(!retirada&&!entrega)return res.status(400).json({erro:'Ative retirada ou entrega'});if(entrega){const b=(await pool.query(`SELECT endereco,cidade,estado FROM barbearias WHERE id=$1`,[req.usuario.barbearia_id])).rows[0];if(!b?.endereco||!b?.cidade||!b?.estado)return res.status(400).json({erro:'Configure endereço, cidade e UF da barbearia antes de ativar entrega'});}
  const pix=x.loja_aceitar_pix!==false,card=x.loja_aceitar_cartao!==false;if(x.loja_ativa===true&&!pix&&!card)return res.status(400).json({erro:'Ative Pix ou cartão para receber pedidos online'});
  await pool.query(`UPDATE barbearias SET loja_ativa=$1,loja_titulo=$2,loja_descricao=$3,loja_logo_url=$4,loja_banner_url=$5,loja_aceitar_retirada=$6,loja_aceitar_entrega=$7,loja_retirada_instrucao=$8,loja_pedido_minimo=$9,loja_frete_taxa_base=$10,loja_frete_por_km=$11,loja_frete_minimo=$12,loja_frete_gratis_ate_km=$13,loja_frete_gratis_acima=$14,loja_frete_distancia_max_km=$15,loja_aceitar_pix=$16,loja_aceitar_cartao=$17 WHERE id=$18`,[x.loja_ativa===true,titulo,descricao,logo,banner,retirada,entrega,cleanText(x.loja_retirada_instrucao,800)||null,nums.pedido_minimo,nums.taxa_base,nums.por_km,nums.frete_minimo,nums.gratis_km,nums.gratis_valor,nums.max_km,pix,card,req.usuario.barbearia_id]);
  res.json((await configPayload(req.usuario.barbearia_id)).barbearia);
}catch(e){console.error(e);res.status(500).json({erro:'Erro ao salvar configurações da loja'})}});

router.patch('/produtos/:id',exigirStepUp,async(req,res)=>{try{await ensureStorefrontSchema();const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Produto inválido'});const mostrar=req.body?.mostrar_na_loja===true,destaque=mostrar&&req.body?.destaque_pagina_publica===true,descricao=cleanText(req.body?.descricao_publica,1200)||null;const r=await pool.query(`UPDATE produtos SET mostrar_na_loja=$1,destaque_pagina_publica=$2,descricao_publica=$3,atualizado_em=NOW() WHERE id=$4 AND barbearia_id=$5 RETURNING id,nome,mostrar_na_loja,destaque_pagina_publica,descricao_publica`,[mostrar,destaque,descricao,id,req.usuario.barbearia_id]);if(!r.rowCount)return res.status(404).json({erro:'Produto não encontrado'});res.json(r.rows[0])}catch(e){console.error(e);res.status(500).json({erro:'Erro ao atualizar produto da loja'})}});

router.get('/pedidos',async(req,res)=>{try{await ensureStoreCommerceSchema();const status=String(req.query.status||'').trim(),params=[req.usuario.barbearia_id],where=['p.barbearia_id=$1'];if(status){params.push(status);where.push(`p.status_pedido=$${params.length}`)}const r=await pool.query(`SELECT p.id,p.public_token,p.cliente_nome,p.cliente_email,p.cliente_telefone,p.tipo_entrega,p.distancia_km,p.subtotal,p.frete,p.total,p.forma_pagamento,p.status_pagamento,p.status_pedido,p.mp_status,p.criado_em,p.pago_em,p.endereco,p.numero,p.bairro,p.cidade,p.estado,p.cep,(SELECT COUNT(*)::int FROM loja_pedido_itens i WHERE i.pedido_id=p.id) itens FROM loja_pedidos p WHERE ${where.join(' AND ')} ORDER BY p.criado_em DESC LIMIT 200`,params);res.json(r.rows)}catch(e){console.error(e);res.status(500).json({erro:'Erro ao listar pedidos'})}});
router.get('/pedidos/:id',async(req,res)=>{try{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Pedido inválido'});const o=(await pool.query(`SELECT * FROM loja_pedidos WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows[0];if(!o)return res.status(404).json({erro:'Pedido não encontrado'});const itens=(await pool.query(`SELECT i.* FROM loja_pedido_itens i JOIN loja_pedidos p ON p.id=i.pedido_id WHERE i.pedido_id=$1 AND p.barbearia_id=$2 ORDER BY i.id`,[id,req.usuario.barbearia_id])).rows;res.json({...o,itens})}catch(e){res.status(500).json({erro:'Erro ao carregar pedido'})}});
router.patch('/pedidos/:id/status',async(req,res)=>{try{const id=intId(req.params.id),status=String(req.body?.status||'');if(!id||!['confirmado','preparando','pronto','saiu_entrega','concluido'].includes(status))return res.status(400).json({erro:'Status inválido'});const o=(await pool.query(`SELECT tipo_entrega,status_pagamento,status_pedido FROM loja_pedidos WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows[0];if(!o)return res.status(404).json({erro:'Pedido não encontrado'});if(o.status_pagamento!=='pago')return res.status(409).json({erro:'Só pedidos pagos podem avançar no preparo'});if(status==='saiu_entrega'&&o.tipo_entrega!=='entrega')return res.status(400).json({erro:'Pedido de retirada não pode sair para entrega'});const r=await pool.query(`UPDATE loja_pedidos SET status_pedido=$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3 RETURNING *`,[status,id,req.usuario.barbearia_id]);res.json(r.rows[0])}catch(e){res.status(500).json({erro:'Erro ao atualizar pedido'})}});
router.post('/pedidos/:id/cancelar',exigirStepUp,async(req,res)=>{const id=intId(req.params.id);if(!id)return res.status(400).json({erro:'Pedido inválido'});const db=await pool.connect();try{await db.query('BEGIN');const o=(await db.query(`SELECT * FROM loja_pedidos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[id,req.usuario.barbearia_id])).rows[0];if(!o){await db.query('ROLLBACK');return res.status(404).json({erro:'Pedido não encontrado'})}if(o.status_pedido==='concluido'||o.status_pedido==='saiu_entrega'){await db.query('ROLLBACK');return res.status(409).json({erro:'Pedido já saiu para entrega/concluiu; trate o reembolso manualmente'})}if(o.status_pedido==='cancelado'){await db.query('COMMIT');return res.json(o)}
    if(o.status_pagamento==='pago'&&o.mp_payment_id){await db.query('ROLLBACK');const mp=await tenantMpCredentials(req.usuario.barbearia_id);if(!mp.configured)return res.status(503).json({erro:'Mercado Pago não configurado para reembolso'});await reembolsarPagamento(o.mp_payment_id,mp.accessToken);const payment=await obterPagamento(o.mp_payment_id,mp.accessToken);const c=await pool.connect();try{await c.query('BEGIN');const cur=(await c.query(`SELECT * FROM loja_pedidos WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[id,req.usuario.barbearia_id])).rows[0];if(cur.status_pagamento==='pago'){const itens=(await c.query(`SELECT i.produto_id,i.quantidade FROM loja_pedido_itens i JOIN loja_pedidos p ON p.id=i.pedido_id WHERE i.pedido_id=$1 AND p.barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows;for(const it of itens)if(it.produto_id)await c.query(`UPDATE produtos SET estoque=estoque+$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3`,[it.quantidade,it.produto_id,req.usuario.barbearia_id]);if(cur.venda_id)await c.query(`UPDATE vendas SET status='estornada' WHERE id=$1 AND barbearia_id=$2`,[cur.venda_id,req.usuario.barbearia_id]);}await c.query(`UPDATE loja_pedidos SET status_pagamento='reembolsado',status_pedido='cancelado',mp_status=$1,estoque_reservado=false,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3`,[payment.status||'refunded',id,req.usuario.barbearia_id]);await c.query('COMMIT');return res.json({mensagem:'Pedido cancelado e pagamento reembolsado'})}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release()}}
    const itens=(await db.query(`SELECT i.produto_id,i.quantidade FROM loja_pedido_itens i JOIN loja_pedidos p ON p.id=i.pedido_id WHERE i.pedido_id=$1 AND p.barbearia_id=$2`,[id,req.usuario.barbearia_id])).rows;if(o.estoque_reservado)for(const it of itens)if(it.produto_id)await db.query(`UPDATE produtos SET estoque=estoque+$1,atualizado_em=NOW() WHERE id=$2 AND barbearia_id=$3`,[it.quantidade,it.produto_id,req.usuario.barbearia_id]);await db.query(`UPDATE loja_pedidos SET status_pagamento=CASE WHEN status_pagamento='pendente' THEN 'cancelado' ELSE status_pagamento END,status_pedido='cancelado',estoque_reservado=false,atualizado_em=NOW() WHERE id=$1 AND barbearia_id=$2`,[id,req.usuario.barbearia_id]);await db.query('COMMIT');res.json({mensagem:'Pedido cancelado'})
  }catch(e){await db.query('ROLLBACK').catch(()=>{});console.error('cancel_store_order',e.providerCode||e.status||'provider_error');res.status(502).json({erro:'Não foi possível cancelar/reembolsar o pedido'})}finally{db.release()}});
module.exports=router;
