const express=require('express'); const bcrypt=require('bcryptjs'); const pool=require('../config/db'); const {autenticar,exigirPapel,exigirAssinatura}=require('../middlewares/auth'); const {criarAssinatura,obterAssinatura,atualizarStatusAssinatura}=require('../services/mercadoPago'); const {exigirRecurso,contextoPlano}=require('../services/planos'); const router=express.Router(); router.use(autenticar);
router.get('/dashboard',exigirAssinatura,async(req,res)=>{try{const b=req.usuario.barbearia_id;const barber=req.usuario.papel==='barbeiro'?req.usuario.barbeiro_id:null;const vals=[b];let own='';if(barber){vals.push(barber);own=` AND barbeiro_id=$2`;}const r=await pool.query(`SELECT (SELECT COUNT(*) FROM clientes WHERE barbearia_id=$1) clientes,(SELECT COUNT(*) FROM barbeiros WHERE barbearia_id=$1 AND ativo=true) barbeiros,(SELECT COUNT(*) FROM servicos WHERE barbearia_id=$1 AND ativo=true) servicos,(SELECT COUNT(*) FROM agendamentos WHERE barbearia_id=$1 ${own} AND data=CURRENT_DATE AND status NOT IN ('cancelado','nao_compareceu')) agendamentos_hoje,(SELECT COALESCE(SUM(s.preco),0) FROM agendamentos a JOIN servicos s ON s.id=a.servico_id WHERE a.barbearia_id=$1 ${barber?'AND a.barbeiro_id=$2':''} AND a.status='concluido' AND date_trunc('month',a.data)=date_trunc('month',CURRENT_DATE)) faturamento_mes`,vals);const pvals=[b];let pown='';if(barber){pvals.push(barber);pown=' AND a.barbeiro_id=$2';}const prox=await pool.query(`SELECT a.id,a.data,a.horario,a.status,c.nome cliente,b.nome barbeiro,s.nome servico,s.preco FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id JOIN barbeiros b ON b.id=a.barbeiro_id JOIN servicos s ON s.id=a.servico_id WHERE a.barbearia_id=$1 ${pown} AND a.status NOT IN ('cancelado','concluido','nao_compareceu') AND (a.data>CURRENT_DATE OR (a.data=CURRENT_DATE AND a.horario>=CURRENT_TIME)) ORDER BY a.data,a.horario LIMIT 8`,pvals);res.json({resumo:r.rows[0],proximos:prox.rows});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar dashboard'});}});
router.get('/configuracoes',async(req,res)=>{try{const b=await pool.query(`SELECT id,nome,slug,telefone,email,endereco,cidade,estado,logo_url,banner_url,cor_primaria,cor_secundaria,cor_botao,cor_fundo,tema,descricao_publica,texto_boas_vindas,instagram,whatsapp_publico,mostrar_precos,mostrar_duracao,politica_cancelamento,ativo,COALESCE(pagamento_agendamento,'nenhum') pagamento_agendamento,COALESCE(percentual_sinal,50) percentual_sinal,COALESCE(aceitar_mercadopago,false) aceitar_mercadopago,COALESCE(mp_aceitar_pix,true) mp_aceitar_pix,COALESCE(mp_aceitar_cartao,true) mp_aceitar_cartao,COALESCE(aceitar_pix_manual,false) aceitar_pix_manual,pix_chave,pix_nome,pix_banco,COALESCE(aceitar_dinheiro,true) aceitar_dinheiro FROM barbearias WHERE id=$1`,[req.usuario.barbearia_id]);const ctx=await contextoPlano(req.usuario.barbearia_id);res.json({barbearia:b.rows[0],assinatura:ctx.assinatura?{...ctx.assinatura,plano_efetivo:ctx.plano_efetivo,recursos:ctx.recursos,trial_ativo:ctx.trial_ativo,dias_trial:ctx.dias_trial}:null});}catch(e){res.status(500).json({erro:'Erro ao carregar configurações'});}});
router.put('/configuracoes',exigirPapel('dono','gerente'),async(req,res)=>{
  try{
    const ctx=await contextoPlano(req.usuario.barbearia_id); const premium=ctx.recursos.includes('personalizacao_publica'); const publico=ctx.recursos.includes('pagina_publica_simples');
    const atual=(await pool.query(`SELECT * FROM barbearias WHERE id=$1`,[req.usuario.barbearia_id])).rows[0];
    const x=req.body||{};
    const modo=['nenhum','total','sinal'].includes(x.pagamento_agendamento)?x.pagamento_agendamento:'nenhum';
    const pct=Math.min(100,Math.max(1,Number(x.percentual_sinal||50)));
    const adv=(v,k,def=null)=>premium?(v??def):atual[k];
    const pay=(v,k,def=null)=>publico?(v??def):atual[k];
    const r=await pool.query(`UPDATE barbearias SET nome=$1,telefone=$2,email=$3,endereco=$4,cidade=$5,estado=$6,
      logo_url=$7,banner_url=$8,cor_primaria=$9,cor_secundaria=$10,cor_botao=$11,cor_fundo=$12,tema=$13,descricao_publica=$14,texto_boas_vindas=$15,instagram=$16,whatsapp_publico=$17,mostrar_precos=$18,mostrar_duracao=$19,politica_cancelamento=$20,
      pagamento_agendamento=$21,percentual_sinal=$22,aceitar_mercadopago=$23,mp_aceitar_pix=$24,mp_aceitar_cartao=$25,aceitar_pix_manual=$26,pix_chave=$27,pix_nome=$28,pix_banco=$29,aceitar_dinheiro=$30 WHERE id=$31 RETURNING *`,[
      x.nome,x.telefone||null,x.email||null,x.endereco||null,x.cidade||null,x.estado||null,
      adv(x.logo_url,'logo_url'),adv(x.banner_url,'banner_url'),adv(x.cor_primaria,'cor_primaria','#f59e0b'),adv(x.cor_secundaria,'cor_secundaria','#111827'),adv(x.cor_botao,'cor_botao','#f59e0b'),adv(x.cor_fundo,'cor_fundo','#f7f7f8'),adv(['claro','escuro'].includes(x.tema)?x.tema:'claro','tema','claro'),
      publico?(x.descricao_publica||null):atual.descricao_publica,adv(x.texto_boas_vindas,'texto_boas_vindas'),adv(x.instagram,'instagram'),publico?(x.whatsapp_publico||null):atual.whatsapp_publico,adv(x.mostrar_precos!==false,'mostrar_precos',true),adv(x.mostrar_duracao!==false,'mostrar_duracao',true),adv(x.politica_cancelamento,'politica_cancelamento'),
      pay(modo,'pagamento_agendamento','nenhum'),pay(pct,'percentual_sinal',50),pay(!!x.aceitar_mercadopago,'aceitar_mercadopago',false),pay(x.mp_aceitar_pix!==false,'mp_aceitar_pix',true),pay(x.mp_aceitar_cartao!==false,'mp_aceitar_cartao',true),pay(!!x.aceitar_pix_manual,'aceitar_pix_manual',false),pay(x.pix_chave||null,'pix_chave'),pay(x.pix_nome||null,'pix_nome'),pay(x.pix_banco||null,'pix_banco'),pay(x.aceitar_dinheiro!==false,'aceitar_dinheiro',true),req.usuario.barbearia_id]);
    res.json({...r.rows[0],plano_efetivo:ctx.plano_efetivo,recursos:ctx.recursos});
  }catch(e){console.error(e);res.status(500).json({erro:'Erro ao salvar configurações'});}
});
router.get('/usuarios',exigirPapel('dono','gerente'),exigirRecurso('equipe'),async(req,res)=>{const r=await pool.query(`SELECT u.id,u.nome,u.email,u.papel,u.ativo,u.barbeiro_id,u.criado_em,b.nome barbeiro_nome FROM usuarios u LEFT JOIN barbeiros b ON b.id=u.barbeiro_id AND b.barbearia_id=u.barbearia_id WHERE u.barbearia_id=$1 ORDER BY u.nome`,[req.usuario.barbearia_id]);res.json(r.rows);});
router.post('/usuarios',exigirPapel('dono'),exigirRecurso('equipe'),async(req,res)=>{try{const{nome,email,senha,papel,barbeiro_id}=req.body;if(!nome||!email||!senha)return res.status(400).json({erro:'Preencha nome, e-mail e senha'});if(senha.length<8)return res.status(400).json({erro:'A senha deve ter pelo menos 8 caracteres'});const role=['dono','gerente','recepcao','barbeiro'].includes(papel)?papel:'recepcao';let bid=null;if(role==='barbeiro'){if(!barbeiro_id)return res.status(400).json({erro:'Selecione o barbeiro vinculado'});const br=await pool.query(`SELECT id FROM barbeiros WHERE id=$1 AND barbearia_id=$2 AND ativo=true`,[barbeiro_id,req.usuario.barbearia_id]);if(!br.rowCount)return res.status(400).json({erro:'Barbeiro inválido'});bid=barbeiro_id;}const hash=await bcrypt.hash(senha,12);const r=await pool.query(`INSERT INTO usuarios(barbearia_id,nome,email,senha_hash,papel,barbeiro_id,ativo) VALUES($1,$2,$3,$4,$5,$6,true) RETURNING id,nome,email,papel,barbeiro_id,ativo`,[req.usuario.barbearia_id,nome,email.toLowerCase(),hash,role,bid]);res.status(201).json(r.rows[0]);}catch(e){if(e.code==='23505')return res.status(409).json({erro:'E-mail ou barbeiro já vinculado a outro usuário'});res.status(500).json({erro:'Erro ao criar usuário'});}});
router.put('/usuarios/:id',exigirPapel('dono'),exigirRecurso('equipe'),async(req,res)=>{try{const {nome,papel,barbeiro_id}=req.body;const role=['dono','gerente','recepcao','barbeiro'].includes(papel)?papel:'recepcao';if(Number(req.params.id)===Number(req.usuario.id)&&role!=='dono')return res.status(400).json({erro:'Você não pode remover seu próprio papel de dono'});let bid=null;if(role==='barbeiro'){if(!barbeiro_id)return res.status(400).json({erro:'Selecione o barbeiro vinculado'});const br=await pool.query(`SELECT id FROM barbeiros WHERE id=$1 AND barbearia_id=$2`,[barbeiro_id,req.usuario.barbearia_id]);if(!br.rowCount)return res.status(400).json({erro:'Barbeiro inválido'});bid=barbeiro_id;}const r=await pool.query(`UPDATE usuarios SET nome=COALESCE($1,nome),papel=$2,barbeiro_id=$3 WHERE id=$4 AND barbearia_id=$5 RETURNING id,nome,email,papel,barbeiro_id,ativo`,[nome||null,role,bid,req.params.id,req.usuario.barbearia_id]);if(!r.rowCount)return res.status(404).json({erro:'Usuário não encontrado'});res.json(r.rows[0]);}catch(e){if(e.code==='23505')return res.status(409).json({erro:'Barbeiro já vinculado a outro usuário'});res.status(500).json({erro:'Erro ao editar usuário'});}});
router.patch('/usuarios/:id/status',exigirPapel('dono'),exigirRecurso('equipe'),async(req,res)=>{const r=await pool.query(`UPDATE usuarios SET ativo=$1 WHERE id=$2 AND barbearia_id=$3 AND id<>$4 RETURNING id,nome,email,papel,ativo`,[!!req.body.ativo,req.params.id,req.usuario.barbearia_id,req.usuario.id]);if(!r.rowCount)return res.status(400).json({erro:'Usuário não encontrado ou você tentou desativar sua própria conta'});res.json(r.rows[0]);});

router.get('/pagamentos-pendentes',exigirPapel('dono','gerente','recepcao'),async(req,res)=>{try{const r=await pool.query(`SELECT r.id,r.nome,r.telefone,r.data,r.horario,r.valor_cobrado,r.expira_em,r.forma_pagamento,r.status,b.nome barbeiro,s.nome servico FROM reservas_pagamento r JOIN barbeiros b ON b.id=r.barbeiro_id JOIN servicos s ON s.id=r.servico_id WHERE r.barbearia_id=$1 AND r.status='aguardando_pix_manual' ORDER BY r.criado_em DESC LIMIT 100`,[req.usuario.barbearia_id]);res.json(r.rows)}catch(e){res.status(500).json({erro:'Erro ao carregar pagamentos pendentes'})}});
router.post('/pagamentos-pendentes/:id/confirmar',exigirPapel('dono','gerente','recepcao'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const rr=await client.query(`SELECT * FROM reservas_pagamento WHERE id=$1 AND barbearia_id=$2 FOR UPDATE`,[req.params.id,req.usuario.barbearia_id]);if(!rr.rowCount){await client.query('ROLLBACK');return res.status(404).json({erro:'Reserva não encontrada'})}const r=rr.rows[0];if(r.agendamento_id){await client.query('COMMIT');return res.json({mensagem:'Pagamento já confirmado',agendamento_id:r.agendamento_id})}await client.query(`SELECT pg_advisory_xact_lock(hashtext($1))`,[`${r.barbearia_id}:${r.barbeiro_id}:${r.data}`]);const sv=await client.query(`SELECT duracao FROM servicos WHERE id=$1 AND barbearia_id=$2`,[r.servico_id,r.barbearia_id]);const dur=Number(sv.rows[0]?.duracao||0);const cf=await client.query(`SELECT 1 FROM agendamentos a JOIN servicos s ON s.id=a.servico_id WHERE a.barbearia_id=$1 AND a.barbeiro_id=$2 AND a.data=$3 AND a.status NOT IN ('cancelado','nao_compareceu') AND $4::time<a.horario+(s.duracao*INTERVAL '1 minute') AND $4::time+($5*INTERVAL '1 minute')>a.horario LIMIT 1`,[r.barbearia_id,r.barbeiro_id,r.data,r.horario,dur]);if(cf.rowCount){await client.query(`UPDATE reservas_pagamento SET status='pagamento_aprovado_sem_vaga',atualizado_em=NOW() WHERE id=$1`,[r.id]);await client.query('COMMIT');return res.status(409).json({erro:'Pagamento confirmado, mas o horário já foi ocupado. Faça revisão manual.'})}let c=await client.query(`SELECT * FROM clientes WHERE barbearia_id=$1 AND telefone=$2 ORDER BY id LIMIT 1`,[r.barbearia_id,r.telefone]);if(!c.rowCount)c=await client.query(`INSERT INTO clientes(barbearia_id,nome,telefone,email) VALUES($1,$2,$3,$4) RETURNING *`,[r.barbearia_id,r.nome,r.telefone,r.email||null]);const ag=await client.query(`INSERT INTO agendamentos(barbearia_id,cliente_id,barbeiro_id,servico_id,data,horario,status,origem,observacoes,forma_pagamento,status_pagamento,valor_cobrado,valor_pago) VALUES($1,$2,$3,$4,$5,$6,'confirmado','publico_pix_manual','Pix manual confirmado pela equipe','pix_manual','pago',$7,$7) RETURNING *`,[r.barbearia_id,c.rows[0].id,r.barbeiro_id,r.servico_id,r.data,r.horario,r.valor_cobrado]);await client.query(`UPDATE reservas_pagamento SET status='confirmada',agendamento_id=$1,atualizado_em=NOW() WHERE id=$2`,[ag.rows[0].id,r.id]);await client.query('COMMIT');res.json({mensagem:'Pix confirmado e agendamento criado',agendamento:ag.rows[0]})}catch(e){try{await client.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({erro:'Erro ao confirmar Pix manual'})}finally{client.release()}});
router.get('/financeiro',exigirPapel('dono','gerente'),exigirAssinatura,exigirRecurso('financeiro_basico'),async(req,res)=>{try{const{inicio,fim}=req.query;const vals=[req.usuario.barbearia_id];const filtros=[`a.barbearia_id=$1`,`a.status='concluido'`];if(inicio){vals.push(inicio);filtros.push(`a.data >= $${vals.length}`);}if(fim){vals.push(fim);filtros.push(`a.data <= $${vals.length}`);}const r=await pool.query(`SELECT a.id,a.data,c.nome cliente,b.nome barbeiro,s.nome servico,s.preco FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id JOIN barbeiros b ON b.id=a.barbeiro_id JOIN servicos s ON s.id=a.servico_id WHERE ${filtros.join(' AND ')} ORDER BY a.data,a.horario`,vals);const total=r.rows.reduce((s,x)=>s+Number(x.preco||0),0);res.json({itens:r.rows,total,quantidade:r.rowCount,ticket_medio:r.rowCount?total/r.rowCount:0});}catch(e){res.status(500).json({erro:'Erro ao carregar financeiro'});}});
router.get('/financeiro/graficos',exigirPapel('dono','gerente'),exigirAssinatura,exigirRecurso('financeiro_graficos'),async(req,res)=>{try{const b=req.usuario.barbearia_id;const mensal=await pool.query(`SELECT to_char(date_trunc('month',a.data),'YYYY-MM') mes,COALESCE(SUM(s.preco),0)::numeric total,COUNT(*)::int atendimentos FROM agendamentos a JOIN servicos s ON s.id=a.servico_id WHERE a.barbearia_id=$1 AND a.status='concluido' AND a.data>=date_trunc('month',CURRENT_DATE)-INTERVAL '5 months' GROUP BY date_trunc('month',a.data) ORDER BY date_trunc('month',a.data)`,[b]);const barbeiros=await pool.query(`SELECT br.nome,COALESCE(SUM(s.preco),0)::numeric total,COUNT(*)::int atendimentos FROM agendamentos a JOIN servicos s ON s.id=a.servico_id JOIN barbeiros br ON br.id=a.barbeiro_id WHERE a.barbearia_id=$1 AND a.status='concluido' AND date_trunc('month',a.data)=date_trunc('month',CURRENT_DATE) GROUP BY br.id,br.nome ORDER BY total DESC LIMIT 8`,[b]);res.json({mensal:mensal.rows,barbeiros:barbeiros.rows});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar gráficos financeiros'});}});
router.get('/assinatura',exigirPapel('dono'),async(req,res)=>{const ctx=await contextoPlano(req.usuario.barbearia_id);if(!ctx.assinatura)return res.json(null);res.json({...ctx.assinatura,plano_efetivo:ctx.plano_efetivo,recursos:ctx.recursos,trial_ativo:ctx.trial_ativo,dias_trial:ctx.dias_trial});});
router.get('/assinatura/recursos',async(req,res)=>{const ctx=await contextoPlano(req.usuario.barbearia_id);res.json({plano:ctx.assinatura?.plano||null,status:ctx.assinatura?.status||null,plano_efetivo:ctx.plano_efetivo,trial_ativo:ctx.trial_ativo,dias_trial:ctx.dias_trial,fim_trial:ctx.assinatura?.fim_trial||null,recursos:ctx.recursos});});
router.post('/assinatura/checkout',exigirPapel('dono'),async(req,res)=>{try{if(!process.env.MP_ACCESS_TOKEN)return res.status(503).json({erro:'Mercado Pago ainda não configurado no servidor'});const plano=['starter','pro','premium'].includes(req.body.plano)?req.body.plano:'pro';const mp=await criarAssinatura({barbeariaId:req.usuario.barbearia_id,plano,email:req.usuario.email});const r=await pool.query(`UPDATE assinaturas SET plano=$1,provedor='mercadopago',referencia_externa=$2,checkout_url=$3,provedor_status=$4,atualizado_em=NOW() WHERE id=(SELECT id FROM assinaturas WHERE barbearia_id=$5 ORDER BY id DESC LIMIT 1) RETURNING *`,[plano,mp.id,mp.init_point||null,mp.status||'pending',req.usuario.barbearia_id]);res.json({checkout_url:mp.init_point,assinatura:r.rows[0]});}catch(e){console.error('Checkout Mercado Pago:',e.data||e);res.status(502).json({erro:'Não foi possível iniciar a assinatura no Mercado Pago'});}});
router.post('/assinatura/sincronizar',exigirPapel('dono'),async(req,res)=>{try{const r=await pool.query(`SELECT referencia_externa FROM assinaturas WHERE barbearia_id=$1 ORDER BY id DESC LIMIT 1`,[req.usuario.barbearia_id]);const id=r.rows[0]?.referencia_externa;if(!id)return res.status(400).json({erro:'Nenhuma assinatura Mercado Pago vinculada'});const mp=await obterAssinatura(id);const mapa={authorized:'ativa',paused:'inadimplente',canceled:'cancelada'};await pool.query(`UPDATE assinaturas SET status=COALESCE($1,status),provedor_status=$2,checkout_url=COALESCE($3,checkout_url),proxima_cobranca=$4,atualizado_em=NOW() WHERE barbearia_id=$5`,[mapa[mp.status]||null,mp.status,mp.init_point||null,mp.next_payment_date?String(mp.next_payment_date).slice(0,10):null,req.usuario.barbearia_id]);res.json({mensagem:'Assinatura sincronizada',status_mercadopago:mp.status});}catch(e){res.status(502).json({erro:'Não foi possível sincronizar com o Mercado Pago'});}});
router.post('/assinatura/cancelar',exigirPapel('dono'),async(req,res)=>{try{const r=await pool.query(`SELECT referencia_externa FROM assinaturas WHERE barbearia_id=$1 ORDER BY id DESC LIMIT 1`,[req.usuario.barbearia_id]);const id=r.rows[0]?.referencia_externa;if(!id)return res.status(400).json({erro:'Nenhuma assinatura Mercado Pago vinculada'});await atualizarStatusAssinatura(id,'canceled');await pool.query(`UPDATE assinaturas SET status='cancelada',provedor_status='canceled',atualizado_em=NOW() WHERE barbearia_id=$1`,[req.usuario.barbearia_id]);res.json({mensagem:'Assinatura cancelada'});}catch(e){res.status(502).json({erro:'Não foi possível cancelar a assinatura'});}});
module.exports=router;
