const express=require('express');
const crypto=require('crypto');
const pool=require('../config/db');
const {autenticar,exigirPapel,exigirStepUp}=require('../middlewares/auth');
const {exigirRecurso}=require('../services/planos');
const {sendText,processIncoming}=require('../services/whatsapp');
const {enqueue,processEvent}=require('../services/webhookInbox');
const {processByProvider}=require('../services/webhookProcessors');
const qr=require('../services/whatsappQr');
const wp=require('../services/whatsappProviders');
const {cleanText}=require('../utils/validation');
const {normalizePhone}=require('../utils/security');
const {updateWhatsAppMarketingStatus}=require('../services/marketing');
const router=express.Router();

function hashToken(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex')}
function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function messageTextEvolution(m){return m?.message?.conversation||m?.message?.extendedTextMessage?.text||m?.data?.message?.conversation||m?.data?.message?.extendedTextMessage?.text||''}
async function enqueueGeneric(integ,messageId,from,text){if(!integ||!messageId||!from)return;const eventId=`${integ.provedor}:${messageId}`,row=await enqueue('whatsapp_provider',eventId,{connectionId:integ.id,from:String(from),text:String(text||''),messageId:String(messageId)});if(row.status!=='processado')setImmediate(()=>processEvent('whatsapp_provider',eventId,p=>processByProvider('whatsapp_provider',p)).catch(e=>console.error('Webhook WhatsApp provider:',e.message)))}

// Meta Cloud API direta. Cada barbearia possui Verify Token próprio; a assinatura HMAC usa o App Secret da plataforma.
router.get('/webhook',async(req,res)=>{
  try{const mode=req.query['hub.mode'],token=req.query['hub.verify_token'],challenge=req.query['hub.challenge'];if(mode!=='subscribe'||!token)return res.sendStatus(403);const r=await pool.query(`SELECT 1 FROM whatsapp_verify_tokens WHERE token_hash=$1`,[hashToken(token)]);return r.rowCount?res.status(200).send(challenge):res.sendStatus(403)}catch(e){console.error('Verificação webhook Meta:',e.message);return res.sendStatus(500)}
});
router.post('/webhook',async(req,res)=>{
  try{
    const secret=process.env.META_WHATSAPP_APP_SECRET;if(!secret)return res.status(503).send('Webhook Meta indisponível');
    const sig=String(req.headers['x-hub-signature-256']||''),expected='sha256='+crypto.createHmac('sha256',secret).update(req.rawBody||Buffer.from(JSON.stringify(req.body||{}))).digest('hex');if(!safeEqual(sig,expected))return res.sendStatus(401);
    const queued=[];for(const entry of req.body?.entry||[])for(const change of entry.changes||[]){const v=change.value||{},phoneId=v.metadata?.phone_number_id;for(const st of v.statuses||[]){if(st.id)await updateWhatsAppMarketingStatus(st.id,st.status,st.errors).catch(e=>console.error('Status campanha Meta:',e.message));}for(const m of v.messages||[]){if(!m.id||!phoneId)continue;const row=await enqueue('whatsapp',String(m.id),{phoneId:String(phoneId),message:m});queued.push({id:String(m.id),status:row.status});}}
    res.sendStatus(200);for(const q of queued)if(q.status!=='processado')setImmediate(()=>processEvent('whatsapp',q.id,p=>processByProvider('whatsapp',p)).catch(e=>console.error('Webhook Meta:',e.message)));
  }catch(e){console.error('Webhook Meta:',e.message);return res.sendStatus(500)}
});

// 360dialog: o token secreto na URL identifica e autentica a conexão da barbearia.
router.post('/webhook/360dialog/:token',async(req,res)=>{
  try{const integ=await wp.byWebhookToken('360dialog',req.params.token);if(!integ)return res.sendStatus(404);for(const entry of req.body?.entry||[])for(const change of entry.changes||[]){const v=change.value||{};for(const st of v.statuses||[])if(st.id)await updateWhatsAppMarketingStatus(st.id,st.status,st.errors).catch(()=>{});for(const m of v.messages||[])if(m.id&&m.from)await enqueueGeneric(integ,m.id,m.from,m.type==='text'?m.text?.body||'':'');}return res.sendStatus(200)}catch(e){console.error('Webhook 360dialog:',e.message);return res.sendStatus(500)}
});

// Twilio: valida X-Twilio-Signature usando o Auth Token salvo criptografado.
router.post('/webhook/twilio/:token',async(req,res)=>{
  try{const integ=await wp.byWebhookToken('twilio',req.params.token);if(!integ)return res.sendStatus(404);if(!wp.twilioSignatureValid(req,integ))return res.sendStatus(401);const b=req.body||{},mid=b.MessageSid||b.SmsSid;if(mid&&b.MessageStatus)await updateWhatsAppMarketingStatus(mid,b.MessageStatus,b.ErrorCode?[{code:b.ErrorCode,message:b.ErrorMessage}]:[]).catch(()=>{});if(mid&&b.From&&b.Body!==undefined)await enqueueGeneric(integ,mid,String(b.From).replace(/^whatsapp:/,''),b.Body);res.type('text/xml').status(200).send('<Response></Response>')}catch(e){console.error('Webhook Twilio:',e.message);return res.sendStatus(500)}
});

// Evolution/Baileys: endpoint privado por token configurado automaticamente na instância.
router.post('/webhook/evolution/:token',async(req,res)=>{
  try{const integ=await wp.byWebhookToken('evolution',req.params.token);if(!integ)return res.sendStatus(404);const body=req.body||{},event=String(body.event||'').toUpperCase();if(event.includes('CONNECTION'))return res.sendStatus(200);const data=body.data||body,keys=data.key||{},fromMe=keys.fromMe===true||data.fromMe===true;if(fromMe)return res.sendStatus(200);const id=keys.id||data.id,remoteAlt=keys.remoteJidAlt||data.remoteJidAlt,remote=(String(remoteAlt||'').endsWith('@s.whatsapp.net')?remoteAlt:null)||keys.remoteJid||data.remoteJid||data.sender;if(id&&remote){const from=String(remote).split('@')[0];await enqueueGeneric(integ,id,from,messageTextEvolution(data));}return res.sendStatus(200)}catch(e){console.error('Webhook Evolution:',e.message);return res.sendStatus(500)}
});

router.use(autenticar);
router.get('/providers',exigirRecurso('automacoes'),async(req,res)=>{try{
  await wp.ensureWhatsAppProviderSchema();const tenant=req.usuario.barbearia_id,rows=await wp.list(tenant),active=await wp.activeProvider(tenant),availability=wp.platformAvailability();const map=Object.fromEntries(rows.map(r=>[r.provedor,r]));
  // Sincroniza status Evolution com a infraestrutura antes de responder.
  if(map.evolution){try{const st=await qr.status(tenant);map.evolution.status=st.conectado?'conectado':st.status||map.evolution.status;map.evolution.conectado=!!st.conectado}catch{}}
  const result=wp.PROVIDERS.map(id=>({id,nome:wp.LABELS[id],ativo:id===active,conectado:map[id]?.status==='conectado',status:map[id]?.status||'desconectado',numero:map[id]?.numero||null,config:map[id]?.config||{},capabilities:wp.providerCapabilities(id),infra_ready:availability[id].ready,infra_reason:availability[id].reason}));
  if(req.usuario.papel==='dono')for(const x of result){const raw=rows.find(r=>r.provedor===x.id);if(raw){const dbrow=await wp.row(tenant,x.id);if(dbrow)x.webhook_url=await wp.webhookUrlFor(dbrow);}}
  res.json({provedor_ativo:active,providers:result,meta_webhook_url:`${String(process.env.APP_URL||'').replace(/\/$/,'')}/api/whatsapp/webhook`});
}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar provedores do WhatsApp'})}});

router.post('/providers/:provider/connect',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{
  await wp.ensureWhatsAppProviderSchema();const provider=String(req.params.provider||'').toLowerCase(),tenant=req.usuario.barbearia_id,x=req.body||{};if(!wp.PROVIDERS.includes(provider)||provider==='evolution')return res.status(400).json({erro:'Use o fluxo de QR Code para Evolution'});let r,warning=null;
  if(provider==='meta'){
    if(process.env.NODE_ENV==='production'&&!process.env.META_WHATSAPP_APP_SECRET)return res.status(503).json({erro:'A conexão Meta direta ainda não foi habilitada pelo administrador da plataforma'});
    const phone=String(x.phone_number_id||'').replace(/\D/g,'').slice(0,40),waba=String(x.business_account_id||'').replace(/\D/g,'').slice(0,40)||null,numero=normalizePhone(x.numero)||null,token=String(x.access_token||'').trim();if(!phone||phone.length<5||!token||token.length>4096)return res.status(400).json({erro:'Informe Phone Number ID e Access Token válidos'});r=await wp.save(tenant,'meta',{numero,config:{phone_number_id:phone,business_account_id:waba,numero},secretValue:token,status:'conectado'});
    // Mantém tabela legada sincronizada enquanto instalações antigas ainda existirem.
    await pool.query(`INSERT INTO integracoes_whatsapp(barbearia_id,phone_number_id,business_account_id,numero,access_token_enc,status,conectado_em,atualizado_em) VALUES($1,$2,$3,$4,$5,'conectado',NOW(),NOW()) ON CONFLICT(barbearia_id) DO UPDATE SET phone_number_id=EXCLUDED.phone_number_id,business_account_id=EXCLUDED.business_account_id,numero=EXCLUDED.numero,access_token_enc=EXCLUDED.access_token_enc,status='conectado',conectado_em=NOW(),atualizado_em=NOW()`,[tenant,phone,waba,numero,r.secret_enc]).catch(()=>{});
  }else if(provider==='360dialog'){
    const key=String(x.api_key||'').trim(),numero=normalizePhone(x.numero)||null;if(key.length<16||key.length>4096)return res.status(400).json({erro:'Informe a API Key da 360dialog'});r=await wp.save(tenant,provider,{numero,config:{numero},secretValue:key,status:'conectado',webhookToken:crypto.randomBytes(32).toString('base64url')});const wh=await wp.set360Webhook(r);if(!wh.ok)warning=`Conexão salva. Configure o webhook manualmente: ${wh.url||'URL indisponível'} (${wh.aviso})`;
  }else if(provider==='twilio'){
    const sid=String(x.account_sid||'').trim(),auth=String(x.auth_token||'').trim(),sender=String(x.sender||'').trim();if(!auth||auth.length>4096||normalizePhone(sender).length<10)return res.status(400).json({erro:'Informe Account SID, Auth Token e número WhatsApp válidos'});await wp.validateTwilioCredentials(sid,auth);r=await wp.save(tenant,provider,{numero:normalizePhone(sender),config:{account_sid:sid,sender:normalizePhone(sender)},secretValue:auth,status:'conectado',webhookToken:crypto.randomBytes(32).toString('base64url')});warning='Na Twilio, configure a URL de webhook exibida no BarberFlow no WhatsApp Sender/Messaging Service.';
  }
  if(!(await wp.activeConnection(tenant)))await wp.setActiveProvider(tenant,provider);res.json({mensagem:`${wp.LABELS[provider]} conectado`,provedor:provider,webhook_url:await wp.webhookUrlFor(r),aviso:warning});
}catch(e){console.error('whatsapp_provider_connect',req.params.provider,e.message);res.status(502).json({erro:String(e.message||'Erro ao conectar provedor').slice(0,300)})}});

router.post('/providers/:provider/activate',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{const p=String(req.params.provider||'').toLowerCase();await wp.setActiveProvider(req.usuario.barbearia_id,p);res.json({mensagem:`${wp.LABELS[p]} definido como provedor ativo`,provedor:p})}catch(e){res.status(400).json({erro:e.message})}});
router.delete('/providers/:provider',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{const tenant=req.usuario.barbearia_id,p=String(req.params.provider||'').toLowerCase();if(!wp.PROVIDERS.includes(p))return res.status(404).json({erro:'Provedor inválido'});const wasActive=(await wp.activeProvider(tenant))===p;if(p==='evolution')await qr.disconnect(tenant).catch(()=>{});await pool.query(`UPDATE whatsapp_conexoes SET status='desconectado',secret_enc=NULL,webhook_token_hash=NULL,webhook_token_enc=NULL,atualizado_em=NOW() WHERE barbearia_id=$1 AND provedor=$2`,[tenant,p]);if(p==='meta')await pool.query(`UPDATE integracoes_whatsapp SET status='desconectado',access_token_enc=NULL,atualizado_em=NOW() WHERE barbearia_id=$1`,[tenant]);let next=null;if(wasActive){const r=await pool.query(`SELECT provedor FROM whatsapp_conexoes WHERE barbearia_id=$1 AND status='conectado' AND provedor<>$2 ORDER BY atualizado_em DESC LIMIT 1`,[tenant,p]);next=r.rows[0]?.provedor||null;if(next)await wp.setActiveProvider(tenant,next);else await pool.query(`UPDATE automacoes_config SET whatsapp_provedor=NULL,atualizado_em=NOW() WHERE barbearia_id=$1`,[tenant]);}res.json({mensagem:`${wp.LABELS[p]} desconectado`,provedor_ativo:next})}catch(e){res.status(500).json({erro:e.message})}});
router.post('/providers/:provider/test',exigirPapel('dono','gerente'),exigirRecurso('automacoes'),async(req,res)=>{try{const p=String(req.params.provider||'').toLowerCase(),integ=await wp.row(req.usuario.barbearia_id,p);if(!integ||integ.status!=='conectado')return res.status(400).json({erro:'Provedor não conectado'});const telefone=normalizePhone(req.body.telefone);if(telefone.length<10)return res.status(400).json({erro:'Informe um telefone de teste válido'});await wp.sendText(integ,telefone,`Teste BarberFlow ✅ ${wp.LABELS[p]} está enviando mensagens.`);res.json({mensagem:'Mensagem de teste enviada'})}catch(e){res.status(502).json({erro:e.message})}});

router.post('/providers/evolution/start',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{if(!qr.configured())return res.status(503).json({erro:'Evolution API ainda não foi configurada na infraestrutura do BarberFlow'});const d=await qr.start(req.usuario.barbearia_id);let r=await wp.save(req.usuario.barbearia_id,'evolution',{config:{instance_name:d.instance_name||qr.instanceName(req.usuario.barbearia_id)},status:d.conectado?'conectado':'conectando'});const url=await wp.webhookUrlFor(r);if(url)await qr.setWebhook(req.usuario.barbearia_id,url).catch(e=>console.error('Evolution webhook:',e.message));if(d.conectado){await pool.query(`UPDATE whatsapp_conexoes SET status='conectado',conectado_em=COALESCE(conectado_em,NOW()),atualizado_em=NOW() WHERE id=$1`,[r.id]);if(!(await wp.activeConnection(req.usuario.barbearia_id)))await wp.setActiveProvider(req.usuario.barbearia_id,'evolution')}res.json({...d,webhook_url:url})}catch(e){console.error('Evolution:',e.message);res.status(502).json({erro:e.message})}});
router.get('/providers/evolution/status',exigirRecurso('automacoes'),async(req,res)=>{try{const d=await qr.status(req.usuario.barbearia_id),r=await wp.row(req.usuario.barbearia_id,'evolution');if(r){const status=d.conectado?'conectado':d.status||'desconectado';await pool.query(`UPDATE whatsapp_conexoes SET status=$1::varchar,conectado_em=CASE WHEN $1::varchar='conectado' THEN COALESCE(conectado_em,NOW()) ELSE conectado_em END,atualizado_em=NOW() WHERE id=$2`,[status,r.id]);}res.json({...d,provedor:'evolution'})}catch(e){res.status(502).json({erro:e.message})}});

router.post('/verify-token',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{const raw=crypto.randomBytes(24).toString('base64url');await pool.query(`INSERT INTO whatsapp_verify_tokens(barbearia_id,token_hash,criado_em) VALUES($1,$2,NOW()) ON CONFLICT(barbearia_id) DO UPDATE SET token_hash=EXCLUDED.token_hash,criado_em=NOW()`,[req.usuario.barbearia_id,hashToken(raw)]);res.json({verify_token:raw,mensagem:'Token gerado. Copie agora e salve na Meta; ele não será exibido novamente.'})});

router.put('/config',exigirPapel('dono','gerente'),exigirRecurso('automacoes'),async(req,res)=>{
  const x=req.body||{},provider=wp.PROVIDERS.includes(String(x.whatsapp_provedor||''))?String(x.whatsapp_provedor):await wp.activeProvider(req.usuario.barbearia_id);const tpl=v=>{const t=String(v||'').trim();if(!t)return null;if(provider==='twilio')return /^HX[A-Za-z0-9]{20,}$/.test(t)?t:false;return /^[A-Za-z0-9_]{1,512}$/.test(t)?t:false};const t24=tpl(x.template_lembrete_24h),t2=tpl(x.template_lembrete_2h),tp=tpl(x.template_pos_atendimento);if([t24,t2,tp].includes(false))return res.status(400).json({erro:provider==='twilio'?'Na Twilio, informe Content SID começando com HX':'Nome de template inválido'});const m24=cleanText(x.mensagem_lembrete_24h,4000)||null,m2=cleanText(x.mensagem_lembrete_2h,4000)||null,mp=cleanText(x.mensagem_pos_atendimento,4000)||null;
  const r=await pool.query(`INSERT INTO automacoes_config(barbearia_id,lembrete_24h,lembrete_2h,pos_atendimento,template_lembrete_24h,template_lembrete_2h,template_pos_atendimento,canal_lembretes,mensagem_lembrete_24h,mensagem_lembrete_2h,mensagem_pos_atendimento,whatsapp_provedor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(barbearia_id) DO UPDATE SET lembrete_24h=EXCLUDED.lembrete_24h,lembrete_2h=EXCLUDED.lembrete_2h,pos_atendimento=EXCLUDED.pos_atendimento,template_lembrete_24h=EXCLUDED.template_lembrete_24h,template_lembrete_2h=EXCLUDED.template_lembrete_2h,template_pos_atendimento=EXCLUDED.template_pos_atendimento,canal_lembretes=EXCLUDED.canal_lembretes,mensagem_lembrete_24h=EXCLUDED.mensagem_lembrete_24h,mensagem_lembrete_2h=EXCLUDED.mensagem_lembrete_2h,mensagem_pos_atendimento=EXCLUDED.mensagem_pos_atendimento,whatsapp_provedor=EXCLUDED.whatsapp_provedor,atualizado_em=NOW() RETURNING *`,[req.usuario.barbearia_id,!!x.lembrete_24h,!!x.lembrete_2h,!!x.pos_atendimento,t24,t2,tp,provider==='evolution'?'qr':'cloud_api',m24,m2,mp,provider]);res.json(r.rows[0]);
});

// Rotas legadas mantidas para clientes ainda com frontend em cache.
router.get('/status',exigirRecurso('automacoes'),async(req,res)=>{const p=await wp.activeProvider(req.usuario.barbearia_id),integ=await wp.row(req.usuario.barbearia_id,p),c=await pool.query(`SELECT * FROM automacoes_config WHERE barbearia_id=$1`,[req.usuario.barbearia_id]);res.json({conectado:integ?.status==='conectado',integracao:integ?wp.publicRow(integ):null,provedor:p,config:c.rows[0]||null})});
router.post('/teste',exigirPapel('dono','gerente'),exigirRecurso('automacoes'),async(req,res)=>{try{const integ=await wp.activeConnection(req.usuario.barbearia_id);if(!integ)return res.status(400).json({erro:'Nenhum provedor WhatsApp ativo'});const telefone=normalizePhone(req.body.telefone);await sendText(integ,telefone,'Teste BarberFlow ✅ Sua conexão WhatsApp está funcionando.');res.json({mensagem:'Mensagem de teste enviada'})}catch(e){res.status(502).json({erro:e.message})}});

// Compatibilidade 2.8 e anteriores: mantém os endpoints antigos enquanto o navegador pode ter JS em cache.
router.post('/conectar',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{const x=req.body||{},tenant=req.usuario.barbearia_id;if(process.env.NODE_ENV==='production'&&!process.env.META_WHATSAPP_APP_SECRET)return res.status(503).json({erro:'A conexão Meta direta ainda não foi habilitada pelo administrador da plataforma'});const phone=String(x.phone_number_id||'').replace(/\D/g,'').slice(0,40),waba=String(x.business_account_id||'').replace(/\D/g,'').slice(0,40)||null,numero=normalizePhone(x.numero)||null,token=String(x.access_token||'').trim();if(!phone||phone.length<5||!token||token.length>4096)return res.status(400).json({erro:'Informe Phone Number ID e Access Token válidos'});const r=await wp.save(tenant,'meta',{numero,config:{phone_number_id:phone,business_account_id:waba,numero},secretValue:token,status:'conectado'});await pool.query(`INSERT INTO integracoes_whatsapp(barbearia_id,phone_number_id,business_account_id,numero,access_token_enc,status,conectado_em,atualizado_em) VALUES($1,$2,$3,$4,$5,'conectado',NOW(),NOW()) ON CONFLICT(barbearia_id) DO UPDATE SET phone_number_id=EXCLUDED.phone_number_id,business_account_id=EXCLUDED.business_account_id,numero=EXCLUDED.numero,access_token_enc=EXCLUDED.access_token_enc,status='conectado',conectado_em=NOW(),atualizado_em=NOW()`,[tenant,phone,waba,numero,r.secret_enc]).catch(()=>{});if(!(await wp.activeConnection(tenant)))await wp.setActiveProvider(tenant,'meta');res.json({mensagem:'Meta Cloud API conectada',integracao:wp.publicRow(r)})}catch(e){res.status(502).json({erro:String(e.message||'Erro ao conectar WhatsApp').slice(0,300)})}});
router.delete('/conexao',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{const tenant=req.usuario.barbearia_id;await pool.query(`UPDATE whatsapp_conexoes SET status='desconectado',secret_enc=NULL,atualizado_em=NOW() WHERE barbearia_id=$1 AND provedor='meta'`,[tenant]);await pool.query(`UPDATE integracoes_whatsapp SET status='desconectado',access_token_enc=NULL,atualizado_em=NOW() WHERE barbearia_id=$1`,[tenant]).catch(()=>{});res.json({mensagem:'Meta Cloud API desconectada'})}catch(e){res.status(500).json({erro:e.message})}});
router.get('/qr/status',exigirRecurso('automacoes'),async(req,res)=>{try{res.json(await qr.status(req.usuario.barbearia_id))}catch(e){res.status(502).json({erro:e.message})}});
router.post('/qr/iniciar',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{const tenant=req.usuario.barbearia_id,d=await qr.start(tenant);let r=await wp.save(tenant,'evolution',{config:{instance_name:d.instance_name||qr.instanceName(tenant)},status:d.conectado?'conectado':'conectando'});const url=await wp.webhookUrlFor(r);if(url)await qr.setWebhook(tenant,url).catch(()=>{});if(d.conectado&&!(await wp.activeConnection(tenant)))await wp.setActiveProvider(tenant,'evolution');res.json({...d,webhook_url:url})}catch(e){res.status(502).json({erro:e.message})}});
router.delete('/qr/conexao',exigirPapel('dono'),exigirRecurso('automacoes'),exigirStepUp,async(req,res)=>{try{const tenant=req.usuario.barbearia_id;await qr.disconnect(tenant);await pool.query(`UPDATE whatsapp_conexoes SET status='desconectado',atualizado_em=NOW() WHERE barbearia_id=$1 AND provedor='evolution'`,[tenant]);res.json({mensagem:'WhatsApp por QR desconectado'})}catch(e){res.status(500).json({erro:e.message})}});
router.post('/qr/teste',exigirPapel('dono','gerente'),exigirRecurso('automacoes'),async(req,res)=>{try{const telefone=normalizePhone(req.body.telefone);await qr.sendText(req.usuario.barbearia_id,telefone,'Teste BarberFlow ✅ WhatsApp por QR está funcionando.');res.json({mensagem:'Mensagem de teste enviada'})}catch(e){res.status(502).json({erro:e.message})}});
module.exports=router;
