if(requireAuth()){
  document.getElementById('shell').innerHTML=renderShell('agendamentos');let cache=[],hSel='';const role=currentUser().papel;const barberMode=role==='barbeiro';
  if(barberMode) novo.classList.add('hidden');
  async function bases(){const [b,s]=await Promise.all([api('/barbeiros'),api('/servicos')]);barbeiro.innerHTML='<option value="">Selecione</option>'+b.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');servico.innerHTML='<option value="">Selecione</option>'+s.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.nome)} • ${x.duracao} min</option>`).join('');fBarbeiro.innerHTML='<option value="">Todos</option>'+b.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');if(!barberMode){const c=await api('/clientes');cliente.innerHTML='<option value="">Selecione</option>'+c.map(x=>`<option value="${x.id}">${esc(x.nome)} • ${esc(x.telefone)}</option>`).join('')}else{cliente.innerHTML='';if(b.length){fBarbeiro.value=b[0].id;fBarbeiro.disabled=true}}}
  async function slots(){hSel='';if(!barbeiro.value||!servico.value||!data.value){horarios.innerHTML='<span class="muted">Selecione barbeiro, serviço e data.</span>';return}let q=`?barbeiro_id=${barbeiro.value}&servico_id=${servico.value}&data=${data.value}`;if(id.value)q+=`&ignorar_id=${id.value}`;const a=await api(`/agendamentos/horarios-disponiveis${q}`);horarios.innerHTML=a.length?a.map(h=>`<button type="button" class="slot" data-h="${h}">${timeBR(h)}</button>`).join(''):'<span class="muted">Nenhum horário disponível.</span>';document.querySelectorAll('.slot').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');hSel=b.dataset.h})}
  function actionButtons(x){if(barberMode){return `${x.status==='agendado'?`<button class="btn btn-secondary" onclick="setStatus(${x.id},'confirmado')">Confirmar</button>`:''}${['agendado','confirmado'].includes(x.status)?`<button class="btn btn-secondary" onclick="setStatus(${x.id},'em_atendimento')">Iniciar</button>`:''}${x.status==='em_atendimento'?`<button class="btn btn-success" onclick="setStatus(${x.id},'concluido')">Concluir</button>`:''}`}return `<button class="btn btn-secondary" onclick="edit(${x.id})">Editar</button>${x.status==='agendado'?`<button class="btn btn-secondary" onclick="setStatus(${x.id},'confirmado')">Confirmar</button>`:''}${['agendado','confirmado'].includes(x.status)?`<button class="btn btn-secondary" onclick="setStatus(${x.id},'em_atendimento')">Iniciar</button>`:''}${x.status==='em_atendimento'?`<button class="btn btn-success" onclick="setStatus(${x.id},'concluido')">Concluir</button>`:''}${!['cancelado','concluido'].includes(x.status)?`<button class="btn btn-danger" onclick="setStatus(${x.id},'cancelado')">Cancelar</button>`:''}`}
  async function load(){try{const p=new URLSearchParams();if(fData.value)p.set('data',fData.value);if(fBarbeiro.value)p.set('barbeiro',fBarbeiro.value);if(fStatus.value)p.set('status',fStatus.value);cache=await api('/agendamentos'+(p.toString()?`?${p}`:''));lista.innerHTML=cache.length?cache.map(x=>`<tr><td>${dateBR(x.data)}</td><td>${timeBR(x.horario)}</td><td>${esc(x.cliente)}<div class="muted">${esc(x.telefone)}</div></td><td>${esc(x.barbeiro)}</td><td>${esc(x.servico)}</td><td>${money(x.preco)}</td><td><span class="badge status-${x.status}">${x.status.replace('_',' ')}</span></td><td class="actions">${actionButtons(x)}</td></tr>`).join(''):'<tr><td colspan="8">Nenhum agendamento.</td></tr>'}catch(e){flash(msg,e.message,'error')}}
  novo.onclick=()=>{if(barberMode)return;id.value='';cliente.value=barbeiro.value=servico.value='';data.value=new Date().toISOString().slice(0,10);observacoes.value='';hSel='';slots();modal.classList.remove('hidden')};fechar.onclick=()=>modal.classList.add('hidden');barbeiro.onchange=servico.onchange=data.onchange=slots;fData.onchange=fBarbeiro.onchange=fStatus.onchange=load;
  window.edit=async i=>{if(barberMode)return;const x=cache.find(v=>v.id===i);id.value=i;cliente.value=x.cliente_id;barbeiro.value=x.barbeiro_id;servico.value=x.servico_id;data.value=String(x.data).slice(0,10);observacoes.value=x.observacoes||'';await slots();hSel=x.horario;const b=[...document.querySelectorAll('.slot')].find(z=>z.dataset.h===x.horario);if(b)b.classList.add('selected');modal.classList.remove('hidden')};
  salvar.onclick=async()=>{try{if(barberMode)throw new Error('Sem permissão');if(!hSel)throw new Error('Selecione um horário');const body={cliente_id:Number(cliente.value),barbeiro_id:Number(barbeiro.value),servico_id:Number(servico.value),data:data.value,horario:hSel,observacoes:observacoes.value};await api(id.value?`/agendamentos/${id.value}`:'/agendamentos',{method:id.value?'PUT':'POST',body:JSON.stringify(body)});modal.classList.add('hidden');load()}catch(e){flash(msg,e.message,'error')}};
  window.setStatus=async(i,s)=>{try{await api(`/agendamentos/${i}/status`,{method:'PATCH',body:JSON.stringify({status:s})});load()}catch(e){flash(msg,e.message,'error')}};
  (async()=>{await bases();fData.value=new Date().toISOString().slice(0,10);await load();if(location.hash==='#novo'&&!barberMode)novo.click()})()
}
