if(requireAuth()){
  document.getElementById('shell').innerHTML=renderShell('agendamentos');
  const E=id=>document.getElementById(id),role=currentUser().papel,barberMode=role==='barbeiro';let cache=[],barbers=[],hSel='',view=localStorage.getItem('bf_agenda_view')||'grade';
  const statusText=s=>({agendado:'Agendado',confirmado:'Confirmado',em_atendimento:'Em atendimento',concluido:'Concluído',cancelado:'Cancelado',nao_compareceu:'Não compareceu'})[s]||s;
  const phoneDigits=v=>String(v||'').replace(/\D/g,'');
  const waHref=x=>{let p=phoneDigits(x.telefone);if(p.length===10||p.length===11)p='55'+p;return p.length>=12?`https://wa.me/${p}?text=${encodeURIComponent(`Olá ${x.cliente}, aqui é da barbearia. Estou entrando em contato sobre seu agendamento de ${dateBR(x.data)} às ${timeBR(x.horario)}.`)}`:'#'};
  const waButton=(x,small=false)=>`<a class="${small?'appointment-wa':'btn btn-whatsapp appointment-whatsapp-btn'}" href="${waHref(x)}" target="_blank" rel="noopener" title="Falar com ${esc(x.cliente)} no WhatsApp" aria-label="Falar com ${esc(x.cliente)} no WhatsApp">${iconSVG('whatsapp',small?15:17)}${small?'':'<span>WhatsApp</span>'}</a>`;
  const toMinutes=v=>{const [h,m]=String(v||'00:00').slice(0,5).split(':').map(Number);return h*60+m};
  const localDate=()=>{const d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${d.getFullYear()}-${m}-${day}`};
  if(barberMode)E('novo').classList.add('hidden');
  async function bases(){const [b,s]=await Promise.all([api('/barbeiros'),api('/servicos')]);barbers=b;E('barbeiro').innerHTML='<option value="">Selecione</option>'+b.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');E('servico').innerHTML='<option value="">Selecione</option>'+s.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.nome)} • ${x.duracao} min</option>`).join('');E('fBarbeiro').innerHTML='<option value="">Todos</option>'+b.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');if(!barberMode){const c=await api('/clientes');E('cliente').innerHTML='<option value="">Selecione</option>'+c.map(x=>`<option value="${x.id}">${esc(x.nome)} • ${esc(x.telefone)}</option>`).join('')}else{E('cliente').innerHTML='';if(b.length){E('fBarbeiro').value=b[0].id;E('fBarbeiro').disabled=true}}}
  async function slots(){hSel='';if(!E('barbeiro').value||!E('servico').value||!E('data').value){E('horarios').innerHTML='<span class="muted">Selecione barbeiro, serviço e data.</span>';return}let q=`?barbeiro_id=${E('barbeiro').value}&servico_id=${E('servico').value}&data=${E('data').value}`;if(E('id').value)q+=`&ignorar_id=${E('id').value}`;const a=await api(`/agendamentos/horarios-disponiveis${q}`);E('horarios').innerHTML=a.length?a.map(h=>`<button type="button" class="slot" data-h="${h}">${timeBR(h)}</button>`).join(''):'<span class="muted">Nenhum horário disponível.</span>';document.querySelectorAll('.slot').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');hSel=b.dataset.h})}
  function actionButtons(x){if(barberMode){return `${x.status==='agendado'?`<button class="btn btn-secondary" data-click="setStatus(${x.id},'confirmado')">Confirmar</button>`:''}${['agendado','confirmado'].includes(x.status)?`<button class="btn btn-secondary" data-click="setStatus(${x.id},'em_atendimento')">Iniciar</button>`:''}${x.status==='em_atendimento'?`<button class="btn btn-success" data-click="setStatus(${x.id},'concluido')">Concluir</button>`:''}`;}return `<button class="btn btn-secondary" data-click="edit(${x.id})">Editar</button>${x.status==='agendado'?`<button class="btn btn-secondary" data-click="setStatus(${x.id},'confirmado')">Confirmar</button>`:''}${['agendado','confirmado'].includes(x.status)?`<button class="btn btn-secondary" data-click="setStatus(${x.id},'em_atendimento')">Iniciar</button>`:''}${x.status==='em_atendimento'?`<button class="btn btn-success" data-click="setStatus(${x.id},'concluido')">Concluir</button>`:''}${!['cancelado','concluido'].includes(x.status)?`<button class="btn btn-danger" data-click="setStatus(${x.id},'cancelado')">Cancelar</button>`:''}`}
  function setView(next){if(window.matchMedia('(max-width:760px)').matches)next='lista';view=next;localStorage.setItem('bf_agenda_view',view);E('viewGrade').classList.toggle('active',view==='grade');E('viewLista').classList.toggle('active',view==='lista');E('agendaGradePanel').classList.toggle('hidden',view!=='grade');E('agendaListaPanel').classList.toggle('hidden',view!=='lista');}
  function renderSummary(){const valid=cache.filter(x=>!['cancelado','nao_compareceu'].includes(x.status)),confirmed=valid.filter(x=>x.status==='confirmado').length,inService=valid.filter(x=>x.status==='em_atendimento').length,total=valid.reduce((s,x)=>s+Number(x.preco||0),0);E('agendaResumo').innerHTML=`<div><span>Agendamentos</span><strong>${valid.length}</strong></div><div><span>Confirmados</span><strong>${confirmed}</strong></div><div><span>Em atendimento</span><strong>${inService}</strong></div><div><span>Receita prevista</span><strong>${money(total)}</strong></div>`}
  function renderGrid(){const selected=E('fBarbeiro').value;let bs=barbers.filter(x=>x.ativo&&(!selected||String(x.id)===String(selected)));if(barberMode&&cache.length){const ids=new Set(cache.map(x=>Number(x.barbeiro_id)));bs=bs.filter(x=>ids.has(Number(x.id))||String(x.id)===String(selected))}if(!bs.length){E('agendaGrade').innerHTML='<div class="agenda-empty">Nenhum profissional disponível para este filtro.</div>';return}const start=Math.min(8*60,...cache.map(x=>Math.floor(toMinutes(x.horario)/30)*30)),end=Math.max(20*60,...cache.map(x=>Math.ceil((toMinutes(x.horario)+Number(x.duracao||30))/30)*30));const times=[];for(let m=start;m<end;m+=30)times.push(`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`);const colMap=new Map(bs.map((b,i)=>[Number(b.id),i+2]));let html=`<div class="agenda-grid" style="--barber-count:${bs.length};--slot-count:${times.length}"><div class="agenda-grid-corner">Horário</div>${bs.map(b=>`<div class="agenda-barber-head"><div class="agenda-barber-avatar">${esc(b.nome.slice(0,2).toUpperCase())}</div><div><strong>${esc(b.nome)}</strong><span>${cache.filter(x=>Number(x.barbeiro_id)===Number(b.id)&&!['cancelado','nao_compareceu'].includes(x.status)).length} atend.</span></div></div>`).join('')}`;times.forEach((t,ri)=>{html+=`<div class="agenda-time" style="grid-row:${ri+2}">${t}</div>`;bs.forEach((b,bi)=>{html+=`<div class="agenda-slot-cell" style="grid-column:${bi+2};grid-row:${ri+2}"></div>`})});cache.forEach(x=>{const col=colMap.get(Number(x.barbeiro_id));if(!col)return;const row=Math.floor((toMinutes(x.horario)-start)/30)+2,span=Math.max(1,Math.ceil(Number(x.duracao||30)/30));html+=`<article class="agenda-event status-${x.status}" style="grid-column:${col};grid-row:${row}/span ${span}" data-id="${x.id}" tabindex="0"><div class="agenda-event-top"><strong>${timeBR(x.horario)}</strong><span class="badge status-${x.status}">${statusText(x.status)}</span></div><div class="agenda-client-line"><b>${esc(x.cliente)}</b>${waButton(x,true)}</div><span>${esc(x.servico)}</span><small>${Number(x.duracao||30)} min • ${money(x.preco)}</small><button class="agenda-event-open" type="button" data-click="openAppointment(${x.id})">Abrir</button></article>`});html+='</div>';E('agendaGrade').innerHTML=html;}
  function renderList(){E('lista').innerHTML=cache.length?cache.map(x=>`<tr><td>${dateBR(x.data)}</td><td><strong>${timeBR(x.horario)}</strong></td><td><div class="table-client-cell"><div><strong>${esc(x.cliente)}</strong><span>${esc(x.telefone)}</span></div>${waButton(x,true)}</div></td><td>${esc(x.barbeiro)}</td><td>${esc(x.servico)}</td><td>${money(x.preco)}</td><td><span class="badge status-${x.status}">${statusText(x.status)}</span></td><td class="actions">${actionButtons(x)}</td></tr>`).join(''):'<tr><td colspan="8">Nenhum agendamento.</td></tr>';E('agendaCards').innerHTML=cache.length?cache.map(x=>`<article class="agenda-mobile-card"><div class="agenda-mobile-time"><strong>${timeBR(x.horario)}</strong><span>${Number(x.duracao||30)} min</span></div><div class="agenda-mobile-main"><div class="agenda-mobile-head"><div><strong>${esc(x.cliente)}</strong><span>${esc(x.servico)} • ${esc(x.barbeiro)}</span></div><span class="badge status-${x.status}">${statusText(x.status)}</span></div><div class="agenda-mobile-meta"><span>${money(x.preco)}</span>${x.tracking_code?`<span>Cód. ${esc(String(x.tracking_code).match(/.{1,4}/g)?.join('-')||x.tracking_code)}</span>`:''}</div><div class="actions">${waButton(x)}<button class="btn btn-secondary" data-click="openAppointment(${x.id})">Abrir</button></div></div></article>`).join(''):'<div class="agenda-empty">Nenhum agendamento para este dia.</div>';}
  async function load(){try{const p=new URLSearchParams();if(E('fData').value)p.set('data',E('fData').value);if(E('fBarbeiro').value)p.set('barbeiro',E('fBarbeiro').value);if(E('fStatus').value)p.set('status',E('fStatus').value);cache=await api('/agendamentos'+(p.toString()?`?${p}`:''));renderSummary();renderGrid();renderList()}catch(e){flash(E('msg'),e.message,'error')}}
  function contactStrip(x){const box=E('appointmentContact');if(!x){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<div><strong>${esc(x.cliente)}</strong><span>${esc(x.telefone)}${x.tracking_code?` • código ${esc(String(x.tracking_code).match(/.{1,4}/g)?.join('-')||x.tracking_code)}`:''}</span></div>${waButton(x)}`;}
  function statusActions(x){const q=E('quickStatus');if(!x){q.classList.add('hidden');q.innerHTML='';return}q.classList.remove('hidden');q.innerHTML=`<span>Atualizar atendimento</span><div class="actions">${actionButtons(x).replace(/<button class="btn btn-secondary" data-click="edit\([^)]*\)">Editar<\/button>/,'')}</div>`}
  E('novo').onclick=()=>{if(barberMode)return;E('id').value='';E('cliente').value=E('barbeiro').value=E('servico').value='';E('data').value=E('fData').value||localDate();E('observacoes').value='';hSel='';contactStrip(null);statusActions(null);E('agendaModalTitle').textContent='Novo agendamento';E('salvar').classList.remove('hidden');slots();E('modal').classList.remove('hidden')};E('fechar').onclick=()=>E('modal').classList.add('hidden');E('barbeiro').onchange=E('servico').onchange=E('data').onchange=slots;E('fData').onchange=E('fBarbeiro').onchange=E('fStatus').onchange=load;
  window.openAppointment=async i=>{const x=cache.find(v=>Number(v.id)===Number(i));if(!x)return;contactStrip(x);statusActions(x);E('agendaModalTitle').textContent=`${timeBR(x.horario)} • ${x.cliente}`;if(barberMode){E('salvar').classList.add('hidden');['cliente','barbeiro','servico','data','observacoes'].forEach(k=>E(k).disabled=true);E('horarios').innerHTML=`<span class="slot selected">${timeBR(x.horario)}</span>`;E('observacoes').value=x.observacoes||''}else{['cliente','barbeiro','servico','data','observacoes'].forEach(k=>E(k).disabled=false);E('salvar').classList.remove('hidden');E('id').value=i;E('cliente').value=x.cliente_id;E('barbeiro').value=x.barbeiro_id;E('servico').value=x.servico_id;E('data').value=String(x.data).slice(0,10);E('observacoes').value=x.observacoes||'';await slots();hSel=String(x.horario).slice(0,5);const b=[...document.querySelectorAll('.slot')].find(z=>String(z.dataset.h).slice(0,5)===hSel);if(b)b.classList.add('selected')}E('modal').classList.remove('hidden')};window.edit=window.openAppointment;
  E('salvar').onclick=async()=>{try{if(barberMode)throw new Error('Sem permissão');if(!hSel)throw new Error('Selecione um horário');const body={cliente_id:Number(E('cliente').value),barbeiro_id:Number(E('barbeiro').value),servico_id:Number(E('servico').value),data:E('data').value,horario:hSel,observacoes:E('observacoes').value};await api(E('id').value?`/agendamentos/${E('id').value}`:'/agendamentos',{method:E('id').value?'PUT':'POST',body:JSON.stringify(body)});E('modal').classList.add('hidden');await load()}catch(e){flash(E('msg'),e.message,'error')}};
  window.setStatus=async(i,s)=>{try{await api(`/agendamentos/${i}/status`,{method:'PATCH',body:JSON.stringify({status:s})});E('modal').classList.add('hidden');await load()}catch(e){flash(E('msg'),e.message,'error')}};
  const shiftDay=n=>{const d=new Date(`${E('fData').value||localDate()}T12:00:00`);d.setDate(d.getDate()+n);E('fData').value=d.toISOString().slice(0,10);load()};E('diaAnterior').onclick=()=>shiftDay(-1);E('diaSeguinte').onclick=()=>shiftDay(1);E('hoje').onclick=()=>{E('fData').value=localDate();load()};E('viewGrade').onclick=()=>setView('grade');E('viewLista').onclick=()=>setView('lista');
  (async()=>{await bases();E('fData').value=localDate();setView(view);await load();if(location.hash==='#novo'&&!barberMode)E('novo').click()})()
}
