if(requireAuth(['dono'])){
  const $=id=>document.getElementById(id);$('shell').innerHTML=renderShell('assinatura');
  const els={planGrid:$('planGrid'),atual:$('atual'),planoEfetivo:$('planoEfetivo'),statusPlano:$('statusPlano'),proxima:$('proxima'),trial:$('trial'),acoes:$('acoes'),msg:$('msg'),sync:$('sync'),modal:$('paymentModal'),paymentTitle:$('paymentTitle'),summary:$('paymentPlanSummary'),payMsg:$('payMsg'),cardBtn:$('payMethodCard'),pixBtn:$('payMethodPix'),cardPanel:$('cardPanel'),pixPanel:$('pixPanel'),cardContainer:$('cardPaymentBrick_container'),cardFallback:$('cardFallback'),close:$('closePayment'),pixDocumento:$('pixDocumento'),generatePix:$('generatePix'),pixResult:$('pixResult'),pixQr:$('pixQrImage'),pixCode:$('pixCopyCode'),copyPix:$('copyPix'),pixTicket:$('pixTicket'),pixStatus:$('pixLiveStatus')};
  let assinatura=null,catalogo=[],checkoutConfig=null,selectedPlan=null,cardController=null,pixPollTimer=null;
  function store(a){localStorage.setItem('bf_assinatura',JSON.stringify(a||{}));}
  function limiteTexto(p){return p.limite_profissionais==null?'Profissionais ilimitados':`Até ${p.limite_profissionais} profissionais`}
  function planById(id){return catalogo.find(p=>p.id===id)}
  function activeRecurring(){return assinatura?.status==='ativa'&&assinatura?.provedor==='mercadopago'&&assinatura?.provedor_status==='authorized'&&assinatura?.referencia_externa}
  function ctaText(p){if(assinatura?.status==='ativa'&&!assinatura?.trial_ativo&&assinatura?.plano===p.id)return 'Plano atual';if(activeRecurring())return `Migrar para ${p.nome}`;if(assinatura?.status==='ativa'&&assinatura?.provedor==='mercadopago_pix')return assinatura.plano===p.id?`Renovar ${p.nome}`:`Trocar para ${p.nome}`;return `Assinar ${p.nome}`}
  function renderCatalog(){els.planGrid.innerHTML=catalogo.map(p=>{const current=assinatura?.status==='ativa'&&!assinatura?.trial_ativo&&assinatura?.plano===p.id;return `<article class="plan ${p.id==='pro'?'featured':''} ${current?'plan-current':''}" id="plan-${p.id}"><span class="plan-badge">${esc(p.badge)}</span><h2>${esc(p.nome)}${p.id==='premium'?' 🤖':''}</h2><h3>${money(p.preco_mensal)}<small>/mês</small></h3><p class="muted">${esc(p.descricao)}</p><div class="plan-limit">${esc(limiteTexto(p))}</div><ul class="plan-feature-list">${p.destaques.map(x=>`<li>✅ ${esc(x)}</li>`).join('')}</ul>${p.id==='premium'?'<div class="ai-coming-badge">🤖 IA pronta para a próxima integração</div>':''}<button class="btn ${p.id==='pro'?'btn-primary':p.id==='premium'?'btn-dark':'btn-secondary'}" data-plan="${p.id}" ${current?'disabled':''}>${esc(ctaText(p))}</button><small class="plan-annual-ref">Anual de referência: ${money(p.preco_anual_referencia)}/ano — checkout anual em breve</small></article>`}).join('');els.planGrid.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>choosePlan(b.dataset.plan));}
  async function loadCatalog(){const d=await api('/assinatura/catalogo');catalogo=d.planos||[];renderCatalog()}
  async function loadCheckoutConfig(){checkoutConfig=await api('/assinatura/checkout/config');return checkoutConfig}
  async function load(){try{const a=await api('/assinatura');assinatura=a;if(!a){els.atual.textContent='Sem assinatura';renderCatalog();return}store(a);els.planoEfetivo.textContent=planLabel(a.plano_efetivo||a.plano);els.statusPlano.textContent=String(a.status||'-').toUpperCase();els.proxima.textContent=a.proxima_cobranca?dateBR(a.proxima_cobranca):'-';const mode=a.provedor==='mercadopago_pix'?' • Pix mensal pré-pago':a.provedor==='mercadopago'?' • cartão recorrente':'';els.atual.textContent=`Contratado: ${planLabel(a.plano)} • efetivo agora: ${planLabel(a.plano_efetivo)}${a.limite_profissionais?` • limite: ${a.limite_profissionais} profissionais`:' • profissionais ilimitados'}${mode}${a.provedor_status?` • Mercado Pago: ${a.provedor_status}`:''}`;els.trial.innerHTML=a.trial_ativo?`<div class="trial-banner"><strong>✨ Trial Premium ativo</strong><h2 style="margin:6px 0">${a.dias_trial} dia(s) restantes</h2><p>Você está testando todos os recursos Premium gratuitamente até ${dateBR(a.fim_trial)}.</p><div class="trial-progress"><div style="width:${Math.max(5,Math.min(100,(7-Number(a.dias_trial||0))/7*100))}%"></div></div></div>`:'';els.acoes.innerHTML='';if(a.checkout_url&&a.provedor_status==='pending')els.acoes.innerHTML+=`<a class="btn btn-primary" target="_blank" rel="noopener" href="${esc(a.checkout_url)}">Continuar pagamento</a>`;if(a.status!=='cancelada'&&(a.referencia_externa||a.provedor==='mercadopago_pix'))els.acoes.innerHTML+=`<button class="btn btn-danger" id="cancelarAssinatura">Cancelar assinatura</button>`;$('cancelarAssinatura')?.addEventListener('click',cancelar);renderCatalog()}catch(e){flash(els.msg,e.message,'error')}}
  async function choosePlan(id){const p=planById(id);if(!p)return;selectedPlan=p;if(activeRecurring()){try{flash(els.msg,`Migrando para ${p.nome}...`);const r=await api('/assinatura/migrar',{method:'POST',body:JSON.stringify({plano:p.id})});if(r.requires_checkout)return openCheckout(p);flash(els.msg,r.mensagem||'Plano atualizado');await load();return}catch(e){flash(els.msg,e.message,'error');return}}openCheckout(p)}
  async function openCheckout(p){selectedPlan=p;clearInterval(pixPollTimer);els.paymentTitle.textContent=`Assinar ${p.nome}`;els.summary.textContent=`${money(p.preco_mensal)}/mês • ${limiteTexto(p)}`;els.payMsg.classList.add('hidden');els.pixResult.classList.add('hidden');els.pixDocumento.value='';els.modal.classList.remove('hidden');document.body.classList.add('modal-open');selectMethod('card');try{await loadCheckoutConfig();await renderCardBrick()}catch(e){showCardFallback(e.message)}}
  async function closeCheckout(){clearInterval(pixPollTimer);pixPollTimer=null;if(cardController){try{await cardController.unmount()}catch{}cardController=null}els.cardContainer.innerHTML='';els.modal.classList.add('hidden');document.body.classList.remove('modal-open')}
  function selectMethod(method){const card=method==='card';els.cardBtn.classList.toggle('active',card);els.pixBtn.classList.toggle('active',!card);els.cardPanel.classList.toggle('hidden',!card);els.pixPanel.classList.toggle('hidden',card);if(card&&!cardController&&checkoutConfig)renderCardBrick().catch(e=>showCardFallback(e.message))}
  function showCardFallback(message){els.cardFallback.innerHTML=`${esc(message||'O checkout embutido de cartão não está disponível neste ambiente.')} <button type="button" id="externalCard" class="btn btn-secondary" style="margin-left:8px">Continuar no Mercado Pago</button>`;els.cardFallback.classList.remove('hidden');setTimeout(()=>$('externalCard')?.addEventListener('click',externalCheckout),0)}
  async function externalCheckout(){try{const r=await api('/assinatura/checkout',{method:'POST',body:JSON.stringify({plano:selectedPlan.id})});if(r.checkout_url)window.open(r.checkout_url,'_blank','noopener');await closeCheckout();await load()}catch(e){flash(els.payMsg,e.message,'error')}}
  async function renderCardBrick(){if(!selectedPlan)return;if(cardController){try{await cardController.unmount()}catch{}cardController=null}els.cardContainer.innerHTML='';els.cardFallback.classList.add('hidden');if(!checkoutConfig?.cartao_embutido||!checkoutConfig?.public_key||typeof MercadoPago!=='function')return showCardFallback('Para cartão dentro do BarberFlow, configure MP_PUBLIC_KEY no ambiente do Render.');const mp=new MercadoPago(checkoutConfig.public_key,{locale:'pt-BR'}),builder=mp.bricks();cardController=await builder.create('cardPayment','cardPaymentBrick_container',{initialization:{amount:Number(selectedPlan.preco_mensal),payer:{email:currentUser().email||undefined}},customization:{paymentMethods:{types:{excluded:['debit_card','prepaid_card']}}},callbacks:{onReady:()=>{},onError:error=>{console.error('Mercado Pago Brick',error);flash(els.payMsg,'Não foi possível carregar o formulário do cartão','error')},onSubmit:(formData)=>new Promise(async(resolve,reject)=>{try{const r=await api('/assinatura/checkout/cartao',{method:'POST',body:JSON.stringify({plano:selectedPlan.id,token:formData.token})});flash(els.payMsg,r.mensagem||'Pagamento processado');resolve();setTimeout(async()=>{await closeCheckout();await load()},700)}catch(e){flash(els.payMsg,e.message,'error');reject(e)}})}})}
  async function generatePix(){try{const doc=els.pixDocumento.value.replace(/\D/g,'');if(!/^\d{11,14}$/.test(doc))throw new Error('Informe CPF ou CNPJ válido');els.generatePix.disabled=true;els.generatePix.textContent='Gerando Pix...';const r=await api('/assinatura/checkout/pix',{method:'POST',body:JSON.stringify({plano:selectedPlan.id,documento:doc})});els.pixResult.classList.remove('hidden');els.pixCode.value=r.qr_code||'';if(r.qr_code_base64){els.pixQr.src=`data:image/png;base64,${r.qr_code_base64}`;els.pixQr.classList.remove('hidden')}else els.pixQr.classList.add('hidden');if(r.ticket_url){els.pixTicket.href=r.ticket_url;els.pixTicket.classList.remove('hidden')}else els.pixTicket.classList.add('hidden');els.pixResult.scrollIntoView({behavior:'smooth',block:'nearest'});startPixPolling(r.pagamento_id)}catch(e){flash(els.payMsg,e.message,'error')}finally{els.generatePix.disabled=false;els.generatePix.textContent='Gerar QR Code Pix'}}
  function startPixPolling(id){clearInterval(pixPollTimer);let tries=0;const check=async()=>{if(++tries>45){clearInterval(pixPollTimer);els.pixStatus.innerHTML='Pagamento ainda pendente. Você pode usar “Sincronizar Mercado Pago” depois.';return}try{const r=await api(`/assinatura/pagamentos/${id}`),st=r.pagamento?.status;if(st==='pago'){clearInterval(pixPollTimer);els.pixStatus.innerHTML='<strong>✅ Pix aprovado! Plano ativado.</strong>';store(r.assinatura||{});setTimeout(async()=>{await closeCheckout();await load()},1000)}else if(st==='cancelado'||st==='falhou'){clearInterval(pixPollTimer);els.pixStatus.innerHTML='<strong>❌ Pagamento não concluído.</strong>'}}catch(e){console.warn(e.message)}};check();pixPollTimer=setInterval(check,4000)}
  async function cancelar(){if(!confirm('Cancelar a assinatura?'))return;try{await api('/assinatura/cancelar',{method:'POST'});flash(els.msg,'Assinatura cancelada');load()}catch(e){flash(els.msg,e.message,'error')}}
  els.sync.onclick=async()=>{try{await api('/assinatura/sincronizar',{method:'POST'});flash(els.msg,'Assinatura sincronizada');load()}catch(e){flash(els.msg,e.message,'error')}};els.close.onclick=closeCheckout;els.modal.addEventListener('click',e=>{if(e.target===els.modal)closeCheckout()});els.cardBtn.onclick=()=>selectMethod('card');els.pixBtn.onclick=()=>selectMethod('pix');els.generatePix.onclick=generatePix;els.copyPix.onclick=async()=>{try{await navigator.clipboard.writeText(els.pixCode.value);els.copyPix.textContent='Copiado!';setTimeout(()=>els.copyPix.textContent='Copiar código Pix',1200)}catch{els.pixCode.select();document.execCommand('copy')}};
  Promise.all([loadCatalog(),loadCheckoutConfig().catch(()=>null),load()]).catch(e=>flash(els.msg,e.message,'error'));
}
