if(requireAuth(['dono'])){
 document.getElementById('shell').innerHTML=renderShell('assinatura');let assinatura=null,catalogo=[];
 function store(a){localStorage.setItem('bf_assinatura',JSON.stringify(a));}
 function limiteTexto(p){return p.limite_profissionais==null?'Profissionais ilimitados':`Até ${p.limite_profissionais} profissionais`}
 function renderCatalog(){planGrid.innerHTML=catalogo.map(p=>`<article class="plan ${p.id==='pro'?'featured':''}" id="plan-${p.id}"><span class="plan-badge">${esc(p.badge)}</span><h2>${esc(p.nome)}${p.id==='premium'?' 🤖':''}</h2><h3>${money(p.preco_mensal)}<small>/mês</small></h3><p class="muted">${esc(p.descricao)}</p><div class="plan-limit">${esc(limiteTexto(p))}</div><ul class="plan-feature-list">${p.destaques.map(x=>`<li>✅ ${esc(x)}</li>`).join('')}</ul>${p.id==='premium'?'<div class="ai-coming-badge">🤖 IA pronta para a próxima integração</div>':''}<button class="btn ${p.id==='pro'?'btn-primary':p.id==='premium'?'btn-dark':'btn-secondary'}" data-plan="${p.id}">Escolher ${esc(p.nome)}</button><small class="plan-annual-ref">Anual de referência: ${money(p.preco_anual_referencia)}/ano — checkout anual em breve</small></article>`).join('');planGrid.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>checkout(b.dataset.plan));}
 async function loadCatalog(){const d=await api('/assinatura/catalogo');catalogo=d.planos||[];renderCatalog()}
 async function load(){try{const a=await api('/assinatura');assinatura=a;if(!a){atual.textContent='Sem assinatura';return}store(a);document.querySelectorAll('.plan').forEach(x=>x.classList.remove('plan-current'));document.getElementById(`plan-${a.plano_efetivo||a.plano}`)?.classList.add('plan-current');planoEfetivo.textContent=planLabel(a.plano_efetivo||a.plano);statusPlano.textContent=String(a.status||'-').toUpperCase();proxima.textContent=a.proxima_cobranca?dateBR(a.proxima_cobranca):'-';atual.textContent=`Contratado: ${planLabel(a.plano)} • efetivo agora: ${planLabel(a.plano_efetivo)}${a.limite_profissionais?` • limite: ${a.limite_profissionais} profissionais`:' • profissionais ilimitados'}${a.provedor_status?` • Mercado Pago: ${a.provedor_status}`:''}`;trial.innerHTML=a.trial_ativo?`<div class="trial-banner"><strong>✨ Trial Premium ativo</strong><h2 style="margin:6px 0">${a.dias_trial} dia(s) restantes</h2><p>Você está testando todos os recursos Premium gratuitamente até ${dateBR(a.fim_trial)}, incluindo a configuração preparatória da futura IA.</p><div class="trial-progress"><div style="width:${Math.max(5,Math.min(100,(7-Number(a.dias_trial||0))/7*100))}%"></div></div></div>`:'';acoes.innerHTML='';if(a.checkout_url&&a.provedor_status==='pending')acoes.innerHTML+=`<a class="btn btn-primary" target="_blank" rel="noopener" href="${esc(a.checkout_url)}">Continuar pagamento</a> `;if(a.referencia_externa&&a.provedor==='mercadopago'&&a.status!=='cancelada')acoes.innerHTML+=`<button class="btn btn-danger" id="cancelarAssinatura">Cancelar assinatura</button>`;document.getElementById('cancelarAssinatura')?.addEventListener('click',cancelar)}catch(e){flash(msg,e.message,'error')}}
 window.checkout=async p=>{try{flash(msg,`Preparando ${planLabel(p)}...`);const r=await api('/assinatura/checkout',{method:'POST',body:JSON.stringify({plano:p})});if(r.checkout_url)window.open(r.checkout_url,'_blank');await load()}catch(e){flash(msg,e.message,'error')}};
 async function cancelar(){if(!confirm('Cancelar a assinatura recorrente?'))return;try{await api('/assinatura/cancelar',{method:'POST'});flash(msg,'Assinatura cancelada');load()}catch(e){flash(msg,e.message,'error')}}
 sync.onclick=async()=>{try{await api('/assinatura/sincronizar',{method:'POST'});flash(msg,'Assinatura sincronizada');load()}catch(e){flash(msg,e.message,'error')}};
 Promise.all([loadCatalog(),load()]).catch(e=>flash(msg,e.message,'error'));
}
