if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('automacoes');
  if(!hasFeature('automacoes'))document.querySelector('main.main').innerHTML='<header class="topbar"><div><h1>Automações</h1></div></header><div class="upgrade-card"><strong>🔒 Premium</strong><p>WhatsApp, automações e a futura IA ficam no Premium.</p><a class="btn btn-primary" href="/pages/assinatura.html">Ver Premium</a></div>';
  else{
    let qrTimer=null;

    const aiEls={
      status:document.getElementById('aiStatus'),hint:document.getElementById('aiPlanHint'),form:document.getElementById('aiConfigForm'),nome:document.getElementById('aiNome'),tom:document.getElementById('aiTom'),inicio:document.getElementById('aiMensagemInicial'),fallback:document.getElementById('aiMensagemFallback'),consultar:document.getElementById('aiConsultarHorarios'),agendar:document.getElementById('aiCriarAgendamento'),reagendar:document.getElementById('aiReagendar'),cancelar:document.getElementById('aiCancelar'),precos:document.getElementById('aiInformarPrecos'),pagamento:document.getElementById('aiEnviarPagamento'),humano:document.getElementById('aiTransferirSolicitacao'),reclamacao:document.getElementById('aiTransferirReclamacao'),problemaPagamento:document.getElementById('aiTransferirPagamento'),salvar:document.getElementById('salvarIa')
    };
    function setAiDisabled(disabled){[aiEls.nome,aiEls.tom,aiEls.inicio,aiEls.fallback,aiEls.consultar,aiEls.agendar,aiEls.reagendar,aiEls.cancelar,aiEls.precos,aiEls.pagamento,aiEls.humano,aiEls.reclamacao,aiEls.problemaPagamento,aiEls.salvar].forEach(x=>{if(x)x.disabled=disabled})}
    function fillAi(c={}){aiEls.nome.value=c.nome_assistente||'Sofia';aiEls.tom.value=c.tom||'amigavel';aiEls.inicio.value=c.mensagem_inicial||'';aiEls.fallback.value=c.mensagem_fallback||'';aiEls.consultar.checked=c.consultar_horarios!==false;aiEls.agendar.checked=c.criar_agendamento!==false;aiEls.reagendar.checked=c.reagendar!==false;aiEls.cancelar.checked=c.cancelar!==false;aiEls.precos.checked=c.informar_precos!==false;aiEls.pagamento.checked=c.enviar_link_pagamento!==false;aiEls.humano.checked=c.transferir_solicitacao!==false;aiEls.reclamacao.checked=c.transferir_reclamacao!==false;aiEls.problemaPagamento.checked=c.transferir_pagamento!==false}
    async function loadAi(){try{const d=await api('/ia/status');fillAi(d.config||{});aiEls.status.textContent=d.motor_ativo?'IA ativa':'Preparada';aiEls.status.className=`badge ${d.recurso_disponivel?'status-concluido':'status-cancelado'}`;if(d.recurso_disponivel){aiEls.hint.className='notice success';aiEls.hint.textContent='Premium: configuração liberada. O motor de IA ainda não envia mensagens; será conectado na próxima etapa.';setAiDisabled(false)}else if(d.addon_elegivel){aiEls.hint.className='notice';aiEls.hint.textContent='Plano Pro: a IA está prevista como adicional. Faça upgrade para Premium para preparar o assistente.';setAiDisabled(true)}else{aiEls.hint.className='notice';aiEls.hint.textContent='A preparação da IA está disponível no Premium.';setAiDisabled(true)}}catch(e){aiEls.status.textContent='Indisponível';aiEls.hint.className='notice error';aiEls.hint.textContent=e.message;setAiDisabled(true)}}
    aiEls.salvar.onclick=async()=>{try{aiEls.salvar.disabled=true;aiEls.salvar.textContent='Salvando...';const body={nome_assistente:aiEls.nome.value,tom:aiEls.tom.value,mensagem_inicial:aiEls.inicio.value,mensagem_fallback:aiEls.fallback.value,consultar_horarios:aiEls.consultar.checked,criar_agendamento:aiEls.agendar.checked,reagendar:aiEls.reagendar.checked,cancelar:aiEls.cancelar.checked,informar_precos:aiEls.precos.checked,enviar_link_pagamento:aiEls.pagamento.checked,transferir_solicitacao:aiEls.humano.checked,transferir_reclamacao:aiEls.reclamacao.checked,transferir_pagamento:aiEls.problemaPagamento.checked};await api('/ia/config',{method:'PUT',body:JSON.stringify(body)});flash(msg,'Preparação da IA salva. Próximo passo: conectar o motor ao WhatsApp.')}catch(e){flash(msg,e.message,'error')}finally{aiEls.salvar.disabled=false;aiEls.salvar.textContent='Salvar preparação da IA'}};

    webhookUrl.textContent=`${location.origin}/api/whatsapp/webhook`;
    function setQrImage(src){if(!src){qrVisual.classList.add('hidden');qrImage.removeAttribute('src');return}const normalized=String(src).startsWith('data:')?src:`data:image/png;base64,${src}`;qrImage.src=normalized;qrVisual.classList.remove('hidden')}
    function updateChannelUi(){const qr=canal_lembretes.value==='qr';cloudTemplateFields.classList.toggle('hidden',qr);qrMessageFields.classList.toggle('hidden',!qr)}
    canal_lembretes.onchange=updateChannelUi;
    async function loadOfficial(){try{const d=await api('/whatsapp/status');waStatus.textContent=d.conectado?'Conectado':'Não conectado';waStatus.className=`badge ${d.conectado?'status-concluido':'status-cancelado'}`;desconectar.classList.toggle('hidden',!d.conectado);gerarVerify.textContent=d.verify_token_configurado?'Regenerar Verify Token':'Gerar Verify Token';if(d.integracao){phone_number_id.value=d.integracao.phone_number_id||'';business_account_id.value=d.integracao.business_account_id||'';numero.value=d.integracao.numero||''}const c=d.config||{};for(const id of ['lembrete_24h','lembrete_2h','pos_atendimento'])document.getElementById(id).checked=!!c[id];for(const id of ['template_lembrete_24h','template_lembrete_2h','template_pos_atendimento','mensagem_lembrete_24h','mensagem_lembrete_2h','mensagem_pos_atendimento'])document.getElementById(id).value=c[id]||'';canal_lembretes.value=c.canal_lembretes||'cloud_api';updateChannelUi()}catch(e){flash(msg,e.message,'error')}}
    async function loadQr(){try{const d=await api('/whatsapp/qr/status');const status=d.conectado?'Conectado':d.status==='conectando'?'Aguardando QR':d.configurado?'Não conectado':'Conector não configurado';qrStatus.textContent=status;qrStatus.className=`badge ${d.conectado?'status-concluido':d.status==='conectando'?'status-pendente':'status-cancelado'}`;desconectarQr.classList.toggle('hidden',!d.integracao);testarQr.disabled=!d.conectado;if(d.conectado){setQrImage(null);clearInterval(qrTimer);qrTimer=null}}catch(e){qrStatus.textContent='Erro';flash(msg,e.message,'error')}}
    conectar.onclick=async()=>{try{if(!access_token.value&&!waStatus.textContent.includes('Conectado'))throw new Error('Informe o Access Token');await api('/whatsapp/conectar',{method:'POST',body:JSON.stringify({phone_number_id:phone_number_id.value,business_account_id:business_account_id.value,numero:numero.value,access_token:access_token.value})});access_token.value='';flash(msg,'WhatsApp oficial conectado');loadOfficial()}catch(e){flash(msg,e.message,'error')}};
    desconectar.onclick=async()=>{if(!confirm('Desconectar WhatsApp oficial?'))return;try{await api('/whatsapp/conexao',{method:'DELETE'});flash(msg,'WhatsApp oficial desconectado');loadOfficial()}catch(e){flash(msg,e.message,'error')}};
    testar.onclick=async()=>{const tel=prompt('Número para teste, com DDI e DDD:');if(!tel)return;try{await api('/whatsapp/teste',{method:'POST',body:JSON.stringify({telefone:tel})});flash(msg,'Mensagem de teste enviada')}catch(e){flash(msg,e.message,'error')}};
    gerarVerify.onclick=async()=>{try{const d=await api('/whatsapp/verify-token',{method:'POST',body:'{}'});verifyTokenOutput.value=d.verify_token;copiarVerify.classList.remove('hidden');flash(msg,'Verify Token gerado. Copie e cadastre na Meta.')}catch(e){flash(msg,e.message,'error')}};
    copiarVerify.onclick=async()=>{if(!verifyTokenOutput.value)return;try{await navigator.clipboard.writeText(verifyTokenOutput.value);flash(msg,'Verify Token copiado')}catch{verifyTokenOutput.select();document.execCommand('copy');flash(msg,'Verify Token copiado')}};
    iniciarQr.onclick=async()=>{try{iniciarQr.disabled=true;iniciarQr.textContent='Gerando...';const d=await api('/whatsapp/qr/iniciar',{method:'POST',body:'{}'});if(d.conectado){flash(msg,'WhatsApp QR já está conectado');setQrImage(null)}else{if(d.base64)setQrImage(d.base64);else setQrImage(null);pairingCode.textContent=d.pairingCode?`Código de pareamento: ${d.pairingCode}`:d.code&&!d.base64?'O conector retornou um código de conexão. Atualize o status ou gere o QR novamente.':'';flash(msg,'QR gerado. Escaneie com o WhatsApp.');if(qrTimer)clearInterval(qrTimer);qrTimer=setInterval(loadQr,5000)}loadQr()}catch(e){flash(msg,e.message,'error')}finally{iniciarQr.disabled=false;iniciarQr.textContent='Gerar QR Code'}};
    atualizarQr.onclick=loadQr;
    desconectarQr.onclick=async()=>{if(!confirm('Desconectar e remover a sessão QR?'))return;try{await api('/whatsapp/qr/conexao',{method:'DELETE'});setQrImage(null);flash(msg,'Sessão QR removida');loadQr()}catch(e){flash(msg,e.message,'error')}};
    testarQr.onclick=async()=>{const tel=prompt('Número para teste, com DDI e DDD:');if(!tel)return;try{await api('/whatsapp/qr/teste',{method:'POST',body:JSON.stringify({telefone:tel})});flash(msg,'Mensagem de teste enviada pelo QR')}catch(e){flash(msg,e.message,'error')}};
    salvarAuto.onclick=async()=>{try{await api('/whatsapp/config',{method:'PUT',body:JSON.stringify({lembrete_24h:lembrete_24h.checked,lembrete_2h:lembrete_2h.checked,pos_atendimento:pos_atendimento.checked,canal_lembretes:canal_lembretes.value,template_lembrete_24h:template_lembrete_24h.value,template_lembrete_2h:template_lembrete_2h.value,template_pos_atendimento:template_pos_atendimento.value,mensagem_lembrete_24h:mensagem_lembrete_24h.value,mensagem_lembrete_2h:mensagem_lembrete_2h.value,mensagem_pos_atendimento:mensagem_pos_atendimento.value})});flash(msg,'Automações salvas')}catch(e){flash(msg,e.message,'error')}};
    loadOfficial();loadQr();loadAi();
  }
}
