if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('automacoes');
  if(!hasFeature('automacoes'))document.querySelector('main.main').innerHTML='<header class="topbar"><div><h1>Automações</h1></div></header><div class="upgrade-card"><strong>🔒 Recurso Pro</strong><p>WhatsApp e automações ficam disponíveis a partir do Pro. A IA permanece exclusiva do Premium.</p><a class="btn btn-primary" href="/pages/assinatura.html">Ver planos</a></div>';
  else{
    const $=id=>document.getElementById(id),owner=hasRole('dono');let providers=[],selected='meta',active='meta',qrTimer=null,automationConfig={};
    if(!owner)document.querySelectorAll('.owner-provider-action').forEach(x=>x.classList.add('hidden'));
    const providerMeta={meta:{name:'Meta Cloud API',icon:'◉',desc:'Direto pela Meta',official:true},'360dialog':{name:'360dialog',icon:'360',desc:'Parceiro oficial',official:true},twilio:{name:'Twilio',icon:'TW',desc:'Parceiro oficial',official:true},evolution:{name:'Evolution / QR',icon:'QR',desc:'Conexão simples',official:false}};
    function pData(id){return providers.find(x=>x.id===id)||{id,status:'desconectado',conectado:false,config:{},infra_ready:true}}
    function setQrImage(src){if(!src){$('qrVisual').classList.add('hidden');$('qrImage').removeAttribute('src');return}const normalized=String(src).startsWith('data:')?src:`data:image/png;base64,${src}`;$('qrImage').src=normalized;$('qrVisual').classList.remove('hidden')}
    function renderProviderCards(){
      $('providerCards').innerHTML=providers.map(p=>{const m=providerMeta[p.id],status=p.conectado?'Conectado':p.status==='conectando'?'Aguardando QR':'Não conectado';return `<button type="button" class="provider-choice-card ${selected===p.id?'selected':''} ${p.ativo?'active-provider':''}" data-provider="${p.id}"><div class="provider-choice-top"><span class="provider-choice-icon">${m.icon}</span><span class="provider-choice-tags">${m.official?'<em>OFICIAL</em>':'<em class="alt">ALTERNATIVO</em>'}${p.ativo?'<b>ATIVO</b>':''}</span></div><strong>${m.name}</strong><small>${m.desc}</small><span class="provider-state ${p.conectado?'on':p.status==='conectando'?'pending':''}">${status}</span></button>`}).join('');
      document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{selected=b.dataset.provider;renderProviderCards();showSelected()});
    }
    function fillFields(){for(const p of providers){const c=p.config||{};if(p.id==='meta'){$('metaPhoneId').value=c.phone_number_id||'';$('metaWabaId').value=c.business_account_id||'';$('metaNumber').value=p.numero||c.numero||'';$('metaWebhook').textContent=p.webhook_url||`${location.origin}/api/whatsapp/webhook`}if(p.id==='360dialog'){$('d360Number').value=p.numero||'';$('d360Webhook').value=p.webhook_url||''}if(p.id==='twilio'){$('twilioSid').value=c.account_sid||'';$('twilioSender').value=p.numero||c.sender||'';$('twilioWebhook').value=p.webhook_url||''}}}
    function showSelected(){
      ['meta','d360','twilio','evolution'].forEach(k=>$(`${k}Provider`)?.classList.add('hidden'));const id=selected==='360dialog'?'d360':selected;$(`${id}Provider`)?.classList.remove('hidden');const p=pData(selected),m=providerMeta[selected];
      $('providerInfraWarning').classList.toggle('hidden',p.infra_ready!==false);if(p.infra_ready===false)$('providerInfraWarning').textContent=p.infra_reason||`${m.name} ainda não está disponível na infraestrutura.`;
      $('activateProvider').disabled=!p.conectado||selected===active;$('disconnectProvider').disabled=!p.conectado&&p.status!=='conectando';$('testProvider').disabled=!p.conectado;$('disconnectProvider').classList.toggle('hidden',!owner||(!p.conectado&&p.status!=='conectando'));
    }
    function updateReminderUi(){const m=providerMeta[active]||providerMeta.meta;$('reminderProvider').textContent=m.name;$('activeProviderBadge').textContent=`Ativo: ${m.name}`;$('activeProviderBadge').className='badge status-concluido';const evo=active==='evolution',tw=active==='twilio';$('officialTemplateFields').classList.toggle('hidden',evo);$('messageFields').classList.toggle('hidden',!evo);$('labelTemplate24').textContent=tw?'Content SID 24h':'Template 24h';$('labelTemplate2').textContent=tw?'Content SID 2h':'Template 2h';$('labelTemplatePos').textContent=tw?'Content SID pós-atendimento':'Template pós-atendimento';for(const id of ['template_lembrete_24h','template_lembrete_2h','template_pos_atendimento'])$(id).placeholder=tw?'HX...':`barberflow_${id.replace('template_','')}`;$('templateHelp').textContent=evo?'Evolution envia as mensagens livres abaixo. Evite disparos em massa e respeite o consentimento do cliente.':tw?'Na Twilio, use o Content SID (HX...) de cada template aprovado.':'Use os nomes dos templates aprovados no WhatsApp Business. Fora da janela de atendimento, templates são obrigatórios.'}
    function fillAutomation(c={}){automationConfig=c;for(const id of ['lembrete_24h','lembrete_2h','pos_atendimento'])$(id).checked=!!c[id];for(const id of ['template_lembrete_24h','template_lembrete_2h','template_pos_atendimento','mensagem_lembrete_24h','mensagem_lembrete_2h','mensagem_pos_atendimento'])$(id).value=c[id]||''}
    async function loadProviders(){try{const [d,st]=await Promise.all([api('/whatsapp/providers'),api('/whatsapp/status')]);providers=d.providers||[];active=d.provedor_ativo||'meta';if(!providers.some(x=>x.id===selected))selected=active;if(!pData(selected).conectado&&pData(active).conectado)selected=active;fillFields();fillAutomation(st.config||{});renderProviderCards();showSelected();updateReminderUi();if(selected==='evolution'&&pData('evolution').status==='conectando')startQrPoll()}catch(e){flash($('msg'),e.message,'error')}}
    function startQrPoll(){if(qrTimer)clearInterval(qrTimer);qrTimer=setInterval(refreshEvolution,5000)}
    async function refreshEvolution(){try{const d=await api('/whatsapp/providers/evolution/status');const p=pData('evolution');p.status=d.conectado?'conectado':d.status||'desconectado';p.conectado=!!d.conectado;if(d.conectado){setQrImage(null);if(qrTimer)clearInterval(qrTimer);qrTimer=null}renderProviderCards();showSelected();if(d.webhook_error)flash($('msg'),`Evolution conectada, mas webhook com erro: ${d.webhook_error}`,'error');else if(d.webhook_ok){const last=d.ultimo_webhook_em?` Última entrada: ${new Date(d.ultimo_webhook_em).toLocaleString('pt-BR')} (${d.ultimo_webhook_evento||'evento'}).`:' Nenhuma mensagem de entrada chegou ao BarberFlow ainda.';flash($('msg'),`Webhook Evolution configurado.${last}`,'success')}}catch(e){flash($('msg'),e.message,'error')}}
    async function connect(path,body,clear=[]){try{const d=await api(path,{method:'POST',body:JSON.stringify(body)});clear.forEach(id=>$(id).value='');flash($('msg'),d.aviso||d.mensagem,d.aviso?'warning':'success');await loadProviders()}catch(e){flash($('msg'),e.message,'error')}}
    $('connectMeta').onclick=()=>connect('/whatsapp/providers/meta/connect',{phone_number_id:$('metaPhoneId').value,business_account_id:$('metaWabaId').value,numero:$('metaNumber').value,access_token:$('metaToken').value},['metaToken']);
    $('connect360').onclick=()=>connect('/whatsapp/providers/360dialog/connect',{api_key:$('d360Key').value,numero:$('d360Number').value},['d360Key']);
    $('connectTwilio').onclick=()=>connect('/whatsapp/providers/twilio/connect',{account_sid:$('twilioSid').value,auth_token:$('twilioToken').value,sender:$('twilioSender').value},['twilioToken']);
    $('startEvolution').onclick=async()=>{try{$('startEvolution').disabled=true;$('startEvolution').textContent='Gerando...';const d=await api('/whatsapp/providers/evolution/start',{method:'POST',body:'{}'});if(d.base64)setQrImage(d.base64);$('pairingCode').textContent=d.pairingCode?`Código de pareamento: ${d.pairingCode}`:'';if(d.webhook_error)flash($('msg'),`WhatsApp conectado, mas o webhook não foi salvo: ${d.webhook_error}`,'error');else flash($('msg'),d.conectado?'Evolution conectada e webhook configurado':'QR gerado. Escaneie com o WhatsApp.');startQrPoll();await loadProviders()}catch(e){flash($('msg'),e.message,'error')}finally{$('startEvolution').disabled=false;$('startEvolution').textContent='Gerar QR Code'}};
    $('refreshEvolution').onclick=refreshEvolution;
    $('activateProvider').onclick=async()=>{try{await api(`/whatsapp/providers/${selected}/activate`,{method:'POST',body:'{}'});active=selected;flash($('msg'),`${providerMeta[selected].name} agora é o provedor ativo`);await loadProviders()}catch(e){flash($('msg'),e.message,'error')}};
    $('disconnectProvider').onclick=async()=>{try{await api(`/whatsapp/providers/${selected}`,{method:'DELETE'});flash($('msg'),`${providerMeta[selected].name} desconectado`);setQrImage(null);await loadProviders()}catch(e){flash($('msg'),e.message,'error')}};
    $('testProvider').onclick=async()=>{const telefone=$('providerTestPhone').value.trim();if(!telefone)return flash($('msg'),'Informe o número para teste','error');try{await api(`/whatsapp/providers/${selected}/test`,{method:'POST',body:JSON.stringify({telefone})});flash($('msg'),'Mensagem de teste enviada')}catch(e){flash($('msg'),e.message,'error')}};
    $('gerarVerify').onclick=async()=>{try{const d=await api('/whatsapp/verify-token',{method:'POST',body:'{}'});$('verifyTokenOutput').value=d.verify_token;$('copiarVerify').classList.remove('hidden');flash($('msg'),'Verify Token gerado. Copie e configure na Meta.')}catch(e){flash($('msg'),e.message,'error')}};
    $('copiarVerify').onclick=async()=>{if(!$('verifyTokenOutput').value)return;try{await navigator.clipboard.writeText($('verifyTokenOutput').value);flash($('msg'),'Verify Token copiado')}catch{$('verifyTokenOutput').select();document.execCommand('copy')}};
    $('salvarAuto').onclick=async()=>{try{await api('/whatsapp/config',{method:'PUT',body:JSON.stringify({whatsapp_provedor:active,lembrete_24h:$('lembrete_24h').checked,lembrete_2h:$('lembrete_2h').checked,pos_atendimento:$('pos_atendimento').checked,template_lembrete_24h:$('template_lembrete_24h').value,template_lembrete_2h:$('template_lembrete_2h').value,template_pos_atendimento:$('template_pos_atendimento').value,mensagem_lembrete_24h:$('mensagem_lembrete_24h').value,mensagem_lembrete_2h:$('mensagem_lembrete_2h').value,mensagem_pos_atendimento:$('mensagem_pos_atendimento').value})});flash($('msg'),'Automações salvas')}catch(e){flash($('msg'),e.message,'error')}};

    // BarberFlow 4.4 — construtor de fluxo de agendamento por barbearia.
    let whatsappFlows=[],selectedFlowId=null,selectedFlowNode='entrada',lastFlowField=null;
    const flowNodes=[
      {id:'entrada',title:'Entrada',icon:'👋',help:'Primeira impressão do atendimento.',fields:[['boas_vindas','Mensagem de boas-vindas']]},
      {id:'servico',title:'Serviço',icon:'✂️',help:'Apresenta os serviços disponíveis e orienta a escolha.',fields:[['servico','Mensagem com a lista de serviços'],['servico_invalido','Quando a opção de serviço for inválida']]},
      {id:'barbeiro',title:'Profissional',icon:'💈',help:'Mostra os profissionais disponíveis.',fields:[['barbeiro','Mensagem com a lista de profissionais'],['barbeiro_invalido','Quando o profissional for inválido']]},
      {id:'data',title:'Data',icon:'📅',help:'Pergunta o dia desejado e trata indisponibilidade.',fields:[['data','Pergunta da data'],['data_invalida','Quando a data não for entendida'],['sem_horarios','Quando a data não tiver horários']]},
      {id:'horario',title:'Horário',icon:'🕐',help:'Exibe somente horários realmente livres.',fields:[['horario','Mensagem com horários disponíveis'],['horario_invalido','Quando o horário for inválido']]},
      {id:'nome',title:'Cliente',icon:'👤',help:'Coleta o nome usado no agendamento.',fields:[['nome','Pergunta do nome'],['nome_invalido','Quando o nome não for válido']]},
      {id:'pagamento',title:'Pagamento',icon:'💳',help:'Mostra as formas habilitadas na barbearia.',fields:[['pagamento','Mensagem com formas de pagamento'],['pagamento_invalido','Quando a forma for inválida']]},
      {id:'confirmacao',title:'Confirmação',icon:'✅',help:'Mensagens finais para cada cenário de cobrança.',fields:[['confirmacao','Confirmação sem cobrança'],['confirmacao_dinheiro','Confirmação com dinheiro'],['reserva_pix','Reserva aguardando Pix manual'],['reserva_mercado_pago','Reserva aguardando Mercado Pago'],['erro_finalizacao','Erro ao finalizar'],['recomecar','Mensagem para reiniciar o fluxo']]}
    ];
    const flowSample={barbearia:'Barbearia Prime',servico:'Corte Premium',preco:'45,00',barbeiro:'Carlos',data:'05/09/2026',hora:'14:30',cliente:'João',codigo:'ABCD-EFGH-IJKL',link:'Acompanhe: https://barbearia.com/agendamento',valor:'22,50',pix_chave:'11999999999',pix_nome:'Barbearia Prime',pix_banco:'Banco Exemplo',opcoes:'1. Corte Premium — R$ 45,00\n2. Barba — R$ 30,00'};
    const flowVarNames=['barbearia','servico','preco','barbeiro','data','hora','cliente','codigo','link','valor','pix_chave','pix_nome','pix_banco','opcoes'];
    function currentFlow(){return whatsappFlows.find(x=>Number(x.id)===Number(selectedFlowId))||null}
    function flowRenderSample(value){return String(value||'').replace(/\{([a-z_]+)\}/gi,(m,k)=>Object.prototype.hasOwnProperty.call(flowSample,k)?flowSample[k]:m)}
    function commitFlowFields(){const f=currentFlow();if(!f)return;document.querySelectorAll('#flowFields [data-flow-message]').forEach(el=>{f.mensagens[el.dataset.flowMessage]=el.value})}
    function renderFlowList(){
      $('flowList').innerHTML=whatsappFlows.length?whatsappFlows.map(f=>`<button type="button" class="flow-list-card ${Number(f.id)===Number(selectedFlowId)?'selected':''} ${f.ativo?'active':''}" data-flow-id="${Number(f.id)}"><span class="flow-list-icon">${f.ativo?'●':'○'}</span><span><strong>${esc(f.nome)}</strong><small>${esc(f.descricao||'Fluxo personalizado de agendamento')}</small></span>${f.ativo?'<em>ATIVO</em>':''}</button>`).join(''):'<div class="flow-list-empty">Nenhum fluxo criado.</div>';
      document.querySelectorAll('[data-flow-id]').forEach(btn=>btn.onclick=()=>selectFlow(Number(btn.dataset.flowId)));
      const activeFlow=whatsappFlows.find(x=>x.ativo);$('flowActiveBadge').textContent=activeFlow?`Ativo: ${activeFlow.nome}`:'Sem fluxo ativo';$('flowActiveBadge').className=`badge ${activeFlow?'status-concluido':'status-cancelado'}`;
    }
    function renderFlowNodes(){
      $('flowNodeRail').innerHTML=flowNodes.map((n,i)=>`<button type="button" class="flow-node ${n.id===selectedFlowNode?'selected':''}" data-flow-node="${n.id}"><span class="flow-node-index">${i+1}</span><span class="flow-node-icon">${n.icon}</span><span><strong>${n.title}</strong><small>${n.help}</small></span></button>`).join('');
      document.querySelectorAll('[data-flow-node]').forEach(btn=>btn.onclick=()=>{commitFlowFields();selectedFlowNode=btn.dataset.flowNode;renderFlowNodes();renderFlowNode()});
    }
    function renderFlowPreview(){const field=lastFlowField&&document.body.contains(lastFlowField)?lastFlowField:document.querySelector('#flowFields textarea');$('flowPreviewBubble').textContent=flowRenderSample(field?.value||'Selecione uma mensagem para visualizar.');}
    function renderFlowNode(){
      const f=currentFlow(),node=flowNodes.find(x=>x.id===selectedFlowNode)||flowNodes[0];if(!f)return;$('flowStepNumber').textContent=`ETAPA ${flowNodes.indexOf(node)+1} DE ${flowNodes.length}`;$('flowStepTitle').textContent=node.title;$('flowStepHelp').textContent=node.help;$('flowStepIcon').textContent=node.icon;
      $('flowFields').innerHTML=node.fields.map(([key,label])=>`<div class="field flow-message-field"><label>${esc(label)}</label><textarea data-flow-message="${key}" rows="${key.startsWith('confirmacao')||key.startsWith('reserva_')?6:4}" maxlength="1600">${esc(f.mensagens?.[key]||'')}</textarea><small>${key==='servico'||key==='barbeiro'||key==='horario'||key==='pagamento'?'Use {opcoes} onde a lista deve aparecer.':'Personalize o texto mantendo as variáveis necessárias.'}</small></div>`).join('');
      document.querySelectorAll('#flowFields textarea').forEach(el=>{el.addEventListener('focus',()=>{lastFlowField=el;renderFlowPreview()});el.addEventListener('input',renderFlowPreview)});lastFlowField=document.querySelector('#flowFields textarea');renderFlowPreview();
    }
    function renderFlowEditor(){
      const f=currentFlow();$('flowEditorEmpty').classList.toggle('hidden',!!f);$('flowEditor').classList.toggle('hidden',!f);if(!f)return;$('flowName').value=f.nome||'';$('flowDescription').value=f.descricao||'';$('flowTriggers').value=(f.gatilhos||[]).join(', ');$('activateFlowBtn').disabled=!!f.ativo;$('activateFlowBtn').textContent=f.ativo?'Fluxo ativo':'Definir como ativo';$('deleteFlowBtn').disabled=!!f.ativo;$('flowDeleteConfirm').classList.add('hidden');renderFlowNodes();renderFlowNode();
    }
    function selectFlow(id){commitFlowFields();selectedFlowId=id;selectedFlowNode='entrada';renderFlowList();renderFlowEditor()}
    async function loadFlows(preferId=null){try{const d=await api('/whatsapp/flows');whatsappFlows=d.flows||[];const wanted=preferId||selectedFlowId||d.ativo||whatsappFlows[0]?.id;selectedFlowId=whatsappFlows.some(x=>Number(x.id)===Number(wanted))?Number(wanted):(whatsappFlows[0]?.id||null);renderFlowList();renderFlowEditor()}catch(e){flash($('msg'),`Fluxos WhatsApp: ${e.message}`,'error')}}
    function flowPayload(){commitFlowFields();const f=currentFlow();return {nome:$('flowName').value,descricao:$('flowDescription').value,gatilhos:$('flowTriggers').value.split(',').map(x=>x.trim()).filter(Boolean),mensagens:{...(f?.mensagens||{})}}}
    $('flowVariables').innerHTML=flowVarNames.map(v=>`<button type="button" class="flow-var-chip" data-flow-var="${v}">{${v}}</button>`).join('');document.querySelectorAll('[data-flow-var]').forEach(btn=>btn.onclick=()=>{const field=lastFlowField||document.querySelector('#flowFields textarea');if(!field)return;const token=`{${btn.dataset.flowVar}}`,start=field.selectionStart??field.value.length,end=field.selectionEnd??start;field.setRangeText(token,start,end,'end');field.focus();field.dispatchEvent(new Event('input',{bubbles:true}))});
    $('newFlowBtn').onclick=()=>{$('newFlowForm').classList.remove('hidden');$('newFlowName').focus()};$('cancelNewFlowBtn').onclick=()=>{$('newFlowForm').classList.add('hidden');$('newFlowName').value='';$('newFlowDescription').value=''};
    $('createFlowBtn').onclick=async()=>{const nome=$('newFlowName').value.trim();if(nome.length<2)return flash($('msg'),'Informe um nome para o novo fluxo','error');try{$('createFlowBtn').disabled=true;const row=await api('/whatsapp/flows',{method:'POST',body:JSON.stringify({nome,descricao:$('newFlowDescription').value})});$('newFlowForm').classList.add('hidden');$('newFlowName').value='';$('newFlowDescription').value='';await loadFlows(row.id);flash($('msg'),'Novo fluxo criado. Personalize as etapas e ative quando estiver pronto.')}catch(e){flash($('msg'),e.message,'error')}finally{$('createFlowBtn').disabled=false}};
    $('saveFlowBtn').onclick=async()=>{const f=currentFlow();if(!f)return;try{$('saveFlowBtn').disabled=true;$('saveFlowBtn').textContent='Salvando...';const row=await api(`/whatsapp/flows/${f.id}`,{method:'PUT',body:JSON.stringify(flowPayload())});await loadFlows(row.id);flash($('msg'),'Fluxo salvo com sucesso')}catch(e){flash($('msg'),e.message,'error')}finally{$('saveFlowBtn').disabled=false;$('saveFlowBtn').textContent='Salvar alterações'}};
    $('activateFlowBtn').onclick=async()=>{const f=currentFlow();if(!f||f.ativo)return;try{$('activateFlowBtn').disabled=true;await api(`/whatsapp/flows/${f.id}/activate`,{method:'POST',body:'{}'});await loadFlows(f.id);flash($('msg'),`Fluxo “${f.nome}” ativado para novos atendimentos`)}catch(e){flash($('msg'),e.message,'error')}};
    $('duplicateFlowBtn').onclick=async()=>{const f=currentFlow();if(!f)return;try{commitFlowFields();await api(`/whatsapp/flows/${f.id}`,{method:'PUT',body:JSON.stringify(flowPayload())});const copy=await api(`/whatsapp/flows/${f.id}/duplicate`,{method:'POST',body:'{}'});await loadFlows(copy.id);flash($('msg'),'Fluxo duplicado. A cópia está pronta para edição.')}catch(e){flash($('msg'),e.message,'error')}};
    $('deleteFlowBtn').onclick=()=>{const f=currentFlow();if(!f||f.ativo)return;$('flowDeleteConfirm').classList.remove('hidden')};$('cancelDeleteFlowBtn').onclick=()=>$('flowDeleteConfirm').classList.add('hidden');$('confirmDeleteFlowBtn').onclick=async()=>{const f=currentFlow();if(!f)return;try{$('confirmDeleteFlowBtn').disabled=true;await api(`/whatsapp/flows/${f.id}`,{method:'DELETE'});selectedFlowId=null;await loadFlows();flash($('msg'),'Fluxo excluído')}catch(e){flash($('msg'),e.message,'error')}finally{$('confirmDeleteFlowBtn').disabled=false}};

    const aiEls={status:$('aiStatus'),hint:$('aiPlanHint'),form:$('aiConfigForm'),ativo:$('aiAtivo'),nome:$('aiNome'),tom:$('aiTom'),inicio:$('aiMensagemInicial'),fallback:$('aiMensagemFallback'),consultar:$('aiConsultarHorarios'),agendar:$('aiCriarAgendamento'),reagendar:$('aiReagendar'),cancelar:$('aiCancelar'),precos:$('aiInformarPrecos'),pagamento:$('aiEnviarPagamento'),humano:$('aiTransferirSolicitacao'),reclamacao:$('aiTransferirReclamacao'),problemaPagamento:$('aiTransferirPagamento'),salvar:$('salvarIa')};
    function setAiDisabled(disabled){[aiEls.ativo,aiEls.nome,aiEls.tom,aiEls.inicio,aiEls.fallback,aiEls.consultar,aiEls.agendar,aiEls.reagendar,aiEls.cancelar,aiEls.precos,aiEls.pagamento,aiEls.humano,aiEls.reclamacao,aiEls.problemaPagamento,aiEls.salvar].forEach(x=>{if(x)x.disabled=disabled})}
    function fillAi(c={}){aiEls.ativo.checked=!!c.ativo;aiEls.nome.value=c.nome_assistente||'Sofia';aiEls.tom.value=c.tom||'amigavel';aiEls.inicio.value=c.mensagem_inicial||'';aiEls.fallback.value=c.mensagem_fallback||'';aiEls.consultar.checked=c.consultar_horarios!==false;aiEls.agendar.checked=c.criar_agendamento!==false;aiEls.reagendar.checked=c.reagendar!==false;aiEls.cancelar.checked=c.cancelar!==false;aiEls.precos.checked=c.informar_precos!==false;aiEls.pagamento.checked=c.enviar_link_pagamento!==false;aiEls.humano.checked=c.transferir_solicitacao!==false;aiEls.reclamacao.checked=c.transferir_reclamacao!==false;aiEls.problemaPagamento.checked=c.transferir_pagamento!==false}
    async function loadAi(){try{const d=await api('/ia/status');fillAi(d.config||{});aiEls.status.textContent=d.motor_ativo?'IA ativa':'Preparada';aiEls.status.className=`badge ${d.recurso_disponivel?'status-concluido':'status-cancelado'}`;if(d.recurso_disponivel){aiEls.hint.className=d.infra_disponivel?'notice success':'notice warning';aiEls.hint.textContent=d.infra_disponivel?`IA disponível (${d.modelo}). Quando ativa, entende linguagem livre e mantém o fluxo transacional protegido.`:'Premium liberado, mas falta OPENAI_API_KEY no ambiente para ativar o motor.';setAiDisabled(!d.infra_disponivel)}else if(d.addon_elegivel){aiEls.hint.className='notice';aiEls.hint.textContent='A IA está incluída no Premium. Faça upgrade para ativar o assistente inteligente.';setAiDisabled(true)}else{aiEls.hint.className='notice';aiEls.hint.textContent='A preparação da IA está disponível no Premium.';setAiDisabled(true)}}catch(e){aiEls.status.textContent='Indisponível';aiEls.hint.className='notice error';aiEls.hint.textContent=e.message;setAiDisabled(true)}}
    aiEls.salvar.onclick=async()=>{try{aiEls.salvar.disabled=true;aiEls.salvar.textContent='Salvando...';const body={ativo:aiEls.ativo.checked,nome_assistente:aiEls.nome.value,tom:aiEls.tom.value,mensagem_inicial:aiEls.inicio.value,mensagem_fallback:aiEls.fallback.value,consultar_horarios:aiEls.consultar.checked,criar_agendamento:aiEls.agendar.checked,reagendar:aiEls.reagendar.checked,cancelar:aiEls.cancelar.checked,informar_precos:aiEls.precos.checked,enviar_link_pagamento:aiEls.pagamento.checked,transferir_solicitacao:aiEls.humano.checked,transferir_reclamacao:aiEls.reclamacao.checked,transferir_pagamento:aiEls.problemaPagamento.checked};await api('/ia/config',{method:'PUT',body:JSON.stringify(body)});flash($('msg'),aiEls.ativo.checked?'IA salva e ativada.':'Configuração da IA salva.')}catch(e){flash($('msg'),e.message,'error')}finally{aiEls.salvar.disabled=false;aiEls.salvar.textContent='Salvar IA'}};
    loadProviders();loadFlows();loadAi();
  }
}
