if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('barbeiros');
  const dias=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
  let cache=[];
  const byId=id=>document.getElementById(id);
  function initials(name){return String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?'}
  function safePhoto(url){try{const u=new URL(String(url||''));return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
  function avatar(x,size='sm'){const url=safePhoto(x?.foto_url);return `<span class="barber-avatar barber-avatar-${size}">${url?`<img src="${esc(url)}" alt="Foto de ${esc(x.nome)}">`:`<span>${esc(initials(x?.nome))}</span>`}</span>`}
  function renderAgenda(values=[]){agenda.innerHTML=dias.map((d,i)=>{const day=i+1,v=values.find(x=>Number(x.dia_semana)===day),hasBreak=!!(v?.intervalo_inicio&&v?.intervalo_fim);return `<div class="schedule-row" data-schedule-row="${day}"><strong>${d}</strong><label class="schedule-toggle"><input type="checkbox" data-day="${day}" ${v?'checked':''}> Trabalha</label><label class="schedule-time"><span>Entrada</span><input type="time" data-in="${day}" value="${v?timeBR(v.hora_inicio):'08:00'}"></label><label class="schedule-time"><span>Saída</span><input type="time" data-out="${day}" value="${v?timeBR(v.hora_fim):'18:00'}"></label><label class="schedule-break-toggle"><input type="checkbox" data-break="${day}" ${hasBreak?'checked':''}> Intervalo de almoço</label><div class="schedule-break-times ${hasBreak?'':'hidden'}" data-break-times="${day}"><label class="schedule-time"><span>Início</span><input type="time" data-break-in="${day}" value="${hasBreak?timeBR(v.intervalo_inicio):'12:00'}"></label><label class="schedule-time"><span>Fim</span><input type="time" data-break-out="${day}" value="${hasBreak?timeBR(v.intervalo_fim):'13:00'}"></label></div></div>`}).join('');agenda.querySelectorAll('[data-break]').forEach(c=>c.addEventListener('change',()=>agenda.querySelector(`[data-break-times="${c.dataset.break}"]`).classList.toggle('hidden',!c.checked)))}
  function renderPhoto(){const url=safePhoto(byId('foto_url').value);byId('fotoPreview').innerHTML=url?`<img src="${esc(url)}" alt="Prévia da foto do barbeiro">`:`<span class="barber-photo-initials">${esc(initials(byId('nome').value))}</span>`;byId('removerFotoBarbeiro').classList.toggle('hidden',!url)}
  async function uploadPhoto(file){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type))throw new Error('Use uma foto JPG ou PNG.');if(file.size>5*1024*1024)throw new Error('A foto deve ter no máximo 5 MB.');const btn=byId('enviarFotoBarbeiro');btn.disabled=true;btn.textContent='Enviando...';try{const r=await fetch('/api/uploads/barbeiro-imagem',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type,'X-CSRF-Token':csrfToken()},body:file});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.erro||'Não foi possível enviar a foto');byId('foto_url').value=d.url;renderPhoto()}finally{btn.disabled=false;btn.textContent='Enviar foto';byId('foto_file').value=''}}
  async function load(){try{const plan=await api('/assinatura/recursos');cache=await api('/barbeiros');const ativos=cache.filter(x=>x.ativo).length;limitePlano.classList.remove('hidden');limitePlano.className='notice';limitePlano.textContent=plan.limite_profissionais==null?`Plano ${planLabel(plan.plano_efetivo)}: profissionais ilimitados.`:`Plano ${planLabel(plan.plano_efetivo)}: ${ativos}/${plan.limite_profissionais} profissionais ativos.`;novo.disabled=plan.limite_profissionais!=null&&ativos>=plan.limite_profissionais;novo.title=novo.disabled?'Limite do plano atingido':'';lista.innerHTML=cache.map(x=>`<tr><td><div class="barber-list-person">${avatar(x)}<div><strong>${esc(x.nome)}</strong><small>${x.foto_url?'Foto pública configurada':'Sem foto pública'}</small></div></div></td><td>${esc(x.telefone||'-')}</td><td><span class="badge">${x.ativo?'Ativo':'Inativo'}</span></td><td class="actions"><button class="btn btn-secondary" data-click="edit(${x.id})">Editar</button><button class="btn ${x.ativo?'btn-danger':'btn-success'}" data-click="toggle(${x.id},${!x.ativo})">${x.ativo?'Desativar':'Ativar'}</button></td></tr>`).join('');initResponsiveTables()}catch(e){flash(msg,e.message,'error')}}
  novo.onclick=()=>{id.value='';nome.value='';telefone.value='';byId('foto_url').value='';ativo.value='true';renderAgenda();renderPhoto();modal.classList.remove('hidden')};
  fechar.onclick=()=>modal.classList.add('hidden');
  byId('nome').addEventListener('input',()=>{if(!byId('foto_url').value)renderPhoto()});
  byId('enviarFotoBarbeiro').onclick=()=>byId('foto_file').click();
  byId('foto_file').onchange=async()=>{try{await uploadPhoto(byId('foto_file').files?.[0]);flash(msg,'Foto enviada. Salve o barbeiro para aplicar.')}catch(e){flash(msg,e.message,'error')}};
  byId('removerFotoBarbeiro').onclick=()=>{byId('foto_url').value='';renderPhoto()};
  window.edit=async i=>{const x=cache.find(v=>v.id===i);id.value=i;nome.value=x.nome;telefone.value=x.telefone||'';byId('foto_url').value=x.foto_url||'';ativo.value=String(x.ativo);renderPhoto();renderAgenda(await api(`/barbeiros/${i}/horarios`));modal.classList.remove('hidden')};
  window.toggle=async(i,a)=>{try{await api(`/barbeiros/${i}/status`,{method:'PATCH',body:JSON.stringify({ativo:a})});load()}catch(e){flash(msg,e.message,'error')}};
  salvar.onclick=async()=>{try{let bid=id.value;const payload={nome:nome.value,telefone:telefone.value,foto_url:byId('foto_url').value,ativo:ativo.value==='true'};if(bid)await api(`/barbeiros/${bid}`,{method:'PUT',body:JSON.stringify(payload)});else{const b=await api('/barbeiros',{method:'POST',body:JSON.stringify(payload)});bid=b.id}const horarios=[...document.querySelectorAll('[data-day]')].filter(c=>c.checked).map(c=>{const day=c.dataset.day,temIntervalo=document.querySelector(`[data-break="${day}"]`)?.checked===true;return {dia_semana:Number(day),hora_inicio:document.querySelector(`[data-in="${day}"]`).value,hora_fim:document.querySelector(`[data-out="${day}"]`).value,intervalo_inicio:temIntervalo?document.querySelector(`[data-break-in="${day}"]`).value:null,intervalo_fim:temIntervalo?document.querySelector(`[data-break-out="${day}"]`).value:null}});await api(`/barbeiros/${bid}/horarios`,{method:'PUT',body:JSON.stringify({horarios})});modal.classList.add('hidden');await load();flash(msg,'Barbeiro atualizado com sucesso.')}catch(e){flash(msg,e.message,'error')}};
  renderAgenda();renderPhoto();load();
}
