if(requireAuth()){
  document.getElementById('shell').innerHTML=renderShell('clientes');const E=id=>document.getElementById(id),M=E('modal');let all=[];E('clientSearchIcon').innerHTML=iconSVG('search',16);
  const segLabel=s=>({novo:'Novo',fiel:'Fiel',vip:'VIP',risco:'Risco',inativo:'Inativo'})[s]||s||'';const phoneDigits=v=>String(v||'').replace(/\D/g,'');const wa=v=>{let p=phoneDigits(v);if(p.length===10||p.length===11)p='55'+p;return `https://wa.me/${p}`};
  function render(items){const q=String(E('busca').value||'').toLowerCase().trim(),a=items.filter(x=>!q||[x.nome,x.telefone,x.email].some(v=>String(v||'').toLowerCase().includes(q)));E('clientSummary').innerHTML=`<span><strong>${a.length}</strong> cliente${a.length===1?'':'s'}</span>`;E('clientCards').innerHTML=a.length?a.map(x=>`<article class="client-card"><div class="client-card-head"><div class="client-avatar">${esc(String(x.nome||'?').slice(0,2).toUpperCase())}</div><div class="client-identity"><strong>${esc(x.nome)}</strong><span>${esc(x.telefone)}</span></div>${x.segmento?`<span class="client-segment segment-${esc(x.segmento)}">${esc(segLabel(x.segmento))}</span>`:''}</div><div class="client-card-metrics">${x.visitas!==undefined?`<div><span>Visitas</span><strong>${Number(x.visitas||0)}</strong></div><div><span>Total gasto</span><strong>${money(x.total_gasto)}</strong></div><div><span>Última visita</span><strong>${x.ultima_visita?dateBR(x.ultima_visita):'—'}</strong></div>`:`<div class="client-basic-info"><span>E-mail</span><strong>${esc(x.email||'Não informado')}</strong></div>`}</div>${Array.isArray(x.tags)&&x.tags.length?`<div class="client-tags">${x.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}<div class="client-card-actions"><a class="appointment-wa" href="${wa(x.telefone)}" target="_blank" rel="noopener" title="Falar no WhatsApp">${iconSVG('whatsapp',16)}</a><button class="btn btn-secondary" data-click="edit(${x.id})">Ver cliente</button><button class="client-more" data-click="del(${x.id})" title="Excluir">×</button></div></article>`).join(''):'<div class="dashboard-empty"><strong>Nenhum cliente encontrado</strong><span>Cadastre o primeiro cliente ou ajuste sua busca.</span></div>'}
  async function load(){try{let a=await api('/clientes'+(E('busca').value?`?busca=${encodeURIComponent(E('busca').value)}`:''));if(hasFeature('crm_avancado')&&['dono','gerente'].includes(currentUser().papel)){try{const crm=await api('/avancado/crm'),map=new Map(crm.map(x=>[Number(x.id),x]));a=a.map(x=>({...x,...(map.get(Number(x.id))||{})}))}catch{}}all=a;render(a)}catch(e){flash(E('msg'),e.message,'error')}}
  function open(){M.classList.remove('hidden')}function close(){M.classList.add('hidden');E('hist').innerHTML=''}E('novo').onclick=()=>{E('id').value='';E('nome').value=E('telefone').value=E('email').value=E('observacoes').value=E('data_nascimento').value='';E('marketing_opt_in').checked=false;E('tituloModal').textContent='Novo cliente';open()};E('fechar').onclick=close;E('busca').oninput=()=>render(all);
  window.edit=async i=>{const x=all.find(v=>Number(v.id)===Number(i))||((await api('/clientes')).find(v=>Number(v.id)===Number(i)));if(!x)return;E('id').value=x.id;E('nome').value=x.nome;E('telefone').value=x.telefone;E('email').value=x.email||'';E('observacoes').value=x.observacoes||'';E('data_nascimento').value=x.data_nascimento?String(x.data_nascimento).slice(0,10):'';E('marketing_opt_in').checked=!!x.marketing_opt_in;E('tituloModal').textContent=x.nome;open();const h=await api(`/clientes/${i}/historico`);E('hist').innerHTML='<div class="panel-head"><h3>Histórico</h3></div>'+(h.length?h.map(v=>`<div class="client-history-row"><div><strong>${dateBR(v.data)} • ${timeBR(v.horario)}</strong><span>${esc(v.servico)} com ${esc(v.barbeiro)}</span></div><span class="badge status-${v.status}">${esc(v.status.replaceAll('_',' '))}</span></div>`).join(''):'<div class="muted">Sem atendimentos.</div>')};
  E('salvar').onclick=async()=>{try{const body={nome:E('nome').value,telefone:E('telefone').value,email:E('email').value,observacoes:E('observacoes').value,data_nascimento:E('data_nascimento').value||null,marketing_opt_in:E('marketing_opt_in').checked};await api(E('id').value?`/clientes/${E('id').value}`:'/clientes',{method:E('id').value?'PUT':'POST',body:JSON.stringify(body)});close();await load();flash(E('msg'),'Cliente salvo')}catch(e){flash(E('msg'),e.message,'error')}};window.del=async i=>{if(!confirm('Excluir este cliente?'))return;try{await api(`/clientes/${i}`,{method:'DELETE'});await load()}catch(e){flash(E('msg'),e.message,'error')}};load()
}
