if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('config');
  const ids=['nome','telefone','email','endereco','cidade','estado','logo_url','banner_url','cor_primaria','cor_secundaria','cor_botao','cor_fundo','tema','descricao_publica','texto_boas_vindas','instagram','whatsapp_publico','mostrar_precos','mostrar_duracao','politica_cancelamento','pagamento_agendamento','percentual_sinal','aceitar_mercadopago','mp_aceitar_pix','mp_aceitar_cartao','aceitar_pix_manual','pix_chave','pix_nome','pix_banco','aceitar_dinheiro'];
  const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
  const user=currentUser();
  function toggleSinal(){campoSinal.style.display=el.pagamento_agendamento.value==='sinal'?'flex':'none'}
  function togglePixManual(){pixManualCampos.style.display=el.aceitar_pix_manual.checked?'grid':'none'}
  function preview(){const dark=el.tema.value==='escuro';publicPreview.style.background=el.cor_fundo.value||'#f7f7f8';publicPreview.style.color=dark?'#f9fafb':'#18202b';prevBanner.style.backgroundImage=el.banner_url.value?`url("${el.banner_url.value.replace(/"/g,'')}")`:'';prevBanner.classList.toggle('empty',!el.banner_url.value);if(el.logo_url.value)prevLogo.innerHTML=`<img src="${el.logo_url.value.replace(/"/g,'')}" alt="Logo">`;else prevLogo.textContent='✂';prevNome.textContent=el.nome.value||'Barbearia';prevWelcome.textContent=el.texto_boas_vindas.value||'Seu estilo começa aqui';prevDesc.textContent=el.descricao_publica.value||'Descrição da barbearia';prevMeta.textContent=[el.mostrar_duracao.checked?'30 min':'',el.mostrar_precos.checked?'R$ 35,00':''].filter(Boolean).join(' • ');prevMeta.style.display=(el.mostrar_duracao.checked||el.mostrar_precos.checked)?'':'none';prevButton.style.background=el.cor_botao.value||el.cor_primaria.value||'#f59e0b';prevButton.style.color='#111';publicPreview.style.setProperty('--preview-primary',el.cor_primaria.value||'#f59e0b')}
  el.pagamento_agendamento.onchange=toggleSinal;el.aceitar_pix_manual.onchange=togglePixManual;ids.forEach(id=>{if(el[id]&&!['pagamento_agendamento','aceitar_pix_manual'].includes(id))el[id].addEventListener(el[id].type==='checkbox'?'change':'input',preview)});el.tema.addEventListener('change',preview);
  async function loadMP(){try{const st=await api('/mercadopago/status');mpStatus.textContent=st.conectado?'Conectado':'Não conectado';mpStatus.className=`badge ${st.conectado?'status-concluido':'status-cancelado'}`;conectarMP.classList.toggle('hidden',st.conectado);desconectarMP.classList.toggle('hidden',!st.conectado);if(user.papel!=='dono'){conectarMP.disabled=true;desconectarMP.disabled=true}}catch(e){mpStatus.textContent='Indisponível';console.error(e)}}
  conectarMP.onclick=async()=>{try{const r=await api('/mercadopago/conectar');location.href=r.url}catch(e){flash(msg,e.message,'error')}};
  desconectarMP.onclick=async()=>{if(!confirm('Desconectar a conta Mercado Pago desta barbearia?'))return;try{await api('/mercadopago/conexao',{method:'DELETE'});el.aceitar_mercadopago.checked=false;await loadMP();flash(msg,'Mercado Pago desconectado')}catch(e){flash(msg,e.message,'error')}};
  async function carregarPixPendentes(){try{const list=await api('/pagamentos-pendentes');pixPendentes.innerHTML=list.length?list.map(x=>`<div class="pending-payment-row"><div><strong>${esc(x.nome)}</strong><div class="muted">${esc(x.servico)} • ${dateBR(x.data)} ${timeBR(x.horario)} • ${money(x.valor_cobrado)}</div><small>${esc(x.telefone)}</small></div><button class="btn btn-primary" data-confirmar-pix="${x.id}">Confirmar recebimento</button></div>`).join(''):'<p class="muted">Nenhum Pix manual aguardando confirmação.</p>';pixPendentes.querySelectorAll('[data-confirmar-pix]').forEach(b=>b.onclick=async()=>{if(!confirm('Você conferiu o recebimento deste Pix?'))return;try{await api(`/pagamentos-pendentes/${b.dataset.confirmarPix}/confirmar`,{method:'POST'});flash(msg,'Pix confirmado e agendamento criado');carregarPixPendentes()}catch(e){flash(msg,e.message,'error')}})}catch(e){pixPendentes.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
  atualizarPixPendentes.onclick=carregarPixPendentes;
  async function load(){try{const c=await api('/configuracoes');const b=c.barbearia;const recursos=c.assinatura?.recursos||[];const podePublico=recursos.includes('pagina_publica_simples');const podePremium=recursos.includes('personalizacao_publica');const podePagamentos=recursos.includes('pagamentos_online');for(const id of ids){if(!el[id])continue;if(el[id].type==='checkbox')el[id].checked=!!b[id];else if(b[id]!==null&&b[id]!==undefined)el[id].value=b[id]}el.cor_primaria.value=b.cor_primaria||'#f59e0b';el.cor_secundaria.value=b.cor_secundaria||'#111827';el.cor_botao.value=b.cor_botao||'#f59e0b';el.cor_fundo.value=b.cor_fundo||'#f7f7f8';el.tema.value=b.tema||'claro';el.pagamento_agendamento.value=b.pagamento_agendamento||'nenhum';el.percentual_sinal.value=Number(b.percentual_sinal||50);el.mp_aceitar_pix.checked=b.mp_aceitar_pix!==false;el.mp_aceitar_cartao.checked=b.mp_aceitar_cartao!==false;el.aceitar_dinheiro.checked=b.aceitar_dinheiro!==false;toggleSinal();togglePixManual();preview();linkPublico.href=`/agendar/${b.slug}`;linkPublico.classList.toggle('hidden',!podePublico);const publicIds=['descricao_publica','whatsapp_publico'];const premiumIds=['logo_url','banner_url','cor_primaria','cor_secundaria','cor_botao','cor_fundo','tema','texto_boas_vindas','instagram','mostrar_precos','mostrar_duracao','politica_cancelamento'];const paymentIds=['pagamento_agendamento','percentual_sinal','aceitar_mercadopago','mp_aceitar_pix','mp_aceitar_cartao','aceitar_pix_manual','pix_chave','pix_nome','pix_banco','aceitar_dinheiro'];if(!podePublico){[...publicIds,...premiumIds,...paymentIds].forEach(id=>{if(el[id])el[id].disabled=true});document.querySelector('.public-config-grid')?.insertAdjacentHTML('beforebegin','<div class="upgrade-card"><strong>🔒 Página pública</strong><p>Disponível a partir do plano Pro.</p><a class="btn btn-primary" href="/pages/assinatura.html">Ver planos</a></div>')}else if(!podePremium){premiumIds.forEach(id=>{if(el[id])el[id].disabled=true});document.querySelector('.public-config-grid')?.insertAdjacentHTML('beforebegin','<div class="upgrade-card"><strong>🔒 Personalização Premium</strong><p>No Pro sua página pública usa o visual padrão. Logo, banner, cores, tema e opções avançadas ficam disponíveis no Premium.</p><a class="btn btn-primary" href="/pages/assinatura.html">Conhecer Premium</a></div>')}if(!podePagamentos)paymentIds.forEach(id=>{if(el[id])el[id].disabled=true});if(podePagamentos)await Promise.all([loadMP(),carregarPixPendentes()]);else{mpStatus.textContent='Plano Pro necessário';pixPendentes.innerHTML='<p class="muted">Pagamentos no agendamento ficam disponíveis a partir do Pro.</p>';}const q=new URLSearchParams(location.search);if(q.get('mp')==='conectado')flash(msg,'Mercado Pago conectado com sucesso');if(q.get('mp')==='erro')flash(msg,`Falha ao conectar Mercado Pago: ${q.get('motivo')||''}`,'error')}catch(e){flash(msg,e.message,'error')}}
  salvar.onclick=async()=>{try{const body={};for(const id of ids)body[id]=el[id].type==='checkbox'?el[id].checked:el[id].value;body.estado=body.estado.toUpperCase();body.percentual_sinal=Number(body.percentual_sinal||50);if(body.aceitar_pix_manual&&!String(body.pix_chave||'').trim())throw new Error('Informe a chave Pix manual');await api('/configuracoes',{method:'PUT',body:JSON.stringify(body)});flash(msg,'Configurações, pagamentos e página pública salvos')}catch(e){flash(msg,e.message,'error')}};
  load();
}
