if(requireAuth(['dono','gerente'])){
  const $=id=>document.getElementById(id);$('shell').innerHTML=renderShell('loja');let data=null;
  const params=new URLSearchParams(location.search),validSections=['configuracoes','frete','checkout','pedidos'];
  const currentSection=validSections.includes(params.get('secao'))?params.get('secao'):'configuracoes';
  const sectionMeta={configuracoes:['Configurações da loja','Identidade, banner, logo e publicação da sua loja.'],frete:['Frete e retirada','Configure retirada, área de entrega e regras de frete.'],checkout:['Checkout da loja','Defina Pix, cartão e acompanhe a conexão do Mercado Pago.'],pedidos:['Pedidos da loja','Acompanhe pagamentos, preparo, retirada e entrega.']};
  document.querySelectorAll('[data-store-section]').forEach(el=>el.classList.toggle('hidden',el.dataset.storeSection!==currentSection));
  document.querySelectorAll('[data-store-nav]').forEach(a=>a.classList.toggle('active',a.dataset.storeNav===currentSection));
  $('storePageTitle').textContent=sectionMeta[currentSection][0];$('storePageDescription').textContent=sectionMeta[currentSection][1];
  async function upload(file,target){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type))throw new Error('Use JPG ou PNG');if(file.size>5*1024*1024)throw new Error('A imagem deve ter no máximo 5MB');const r=await fetch('/api/uploads/loja-imagem',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type,'X-CSRF-Token':csrfToken()},body:file});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Erro no upload');$(target).value=d.url;return d.url}
  function num(v){return v==null?'':String(Number(v))}
  function fill(){const b=data.barbearia;$('loja_ativa').checked=!!b.loja_ativa;$('loja_titulo').value=b.loja_titulo||'';$('loja_descricao').value=b.loja_descricao||'';$('loja_logo_url').value=b.loja_logo_url||'';$('loja_banner_url').value=b.loja_banner_url||'';$('loja_aceitar_retirada').checked=b.loja_aceitar_retirada!==false;$('loja_aceitar_entrega').checked=!!b.loja_aceitar_entrega;$('loja_retirada_instrucao').value=b.loja_retirada_instrucao||'';$('loja_pedido_minimo').value=num(b.loja_pedido_minimo);$('loja_frete_taxa_base').value=num(b.loja_frete_taxa_base);$('loja_frete_por_km').value=num(b.loja_frete_por_km);$('loja_frete_minimo').value=num(b.loja_frete_minimo);$('loja_frete_gratis_ate_km').value=b.loja_frete_gratis_ate_km==null?'':num(b.loja_frete_gratis_ate_km);$('loja_frete_gratis_acima').value=b.loja_frete_gratis_acima==null?'':num(b.loja_frete_gratis_acima);$('loja_frete_distancia_max_km').value=num(b.loja_frete_distancia_max_km);$('loja_aceitar_pix').checked=b.loja_aceitar_pix!==false;$('loja_aceitar_cartao').checked=b.loja_aceitar_cartao!==false;$('openStore').href=`/loja/${encodeURIComponent(b.slug)}`;$('openStore').classList.toggle('hidden',!b.loja_ativa);$('storeStatus').textContent=b.loja_ativa?'Ativa':'Desativada';$('storeMpStatus').textContent=data.mercadopago?.configurado?'Conectado':'Não configurado';$('storeFreightProvider').textContent=data.frete_provedor||'—';$('storeOriginAddress').textContent=[b.endereco,b.cidade,b.estado].filter(Boolean).join(', ')||'Endereço não configurado';if(!data.mercadopago?.configurado){$('storePaymentWarning').classList.remove('hidden');$('storePaymentWarning').textContent='Conecte o Mercado Pago em Configurações → Pagamentos antes de receber pedidos online.';$('storePaymentWarning').className='notice warning'}else if(!data.mercadopago?.webhook_pronto){$('storePaymentWarning').classList.remove('hidden');$('storePaymentWarning').textContent='Checkout ativo. Para confirmação automática mesmo com a página fechada, salve também o Segredo do webhook em Configurações → Pagamentos → Mercado Pago.';$('storePaymentWarning').className='notice warning'}else{$('storePaymentWarning').classList.add('hidden')}}
  async function load(){try{data=await api('/loja/config');fill();await loadOrders()}catch(e){flash($('msg'),e.message,'error')}}
  function configBody(){return {loja_ativa:$('loja_ativa').checked,loja_titulo:$('loja_titulo').value,loja_descricao:$('loja_descricao').value,loja_logo_url:$('loja_logo_url').value,loja_banner_url:$('loja_banner_url').value,loja_aceitar_retirada:$('loja_aceitar_retirada').checked,loja_aceitar_entrega:$('loja_aceitar_entrega').checked,loja_retirada_instrucao:$('loja_retirada_instrucao').value,loja_pedido_minimo:$('loja_pedido_minimo').value,loja_frete_taxa_base:$('loja_frete_taxa_base').value,loja_frete_por_km:$('loja_frete_por_km').value,loja_frete_minimo:$('loja_frete_minimo').value,loja_frete_gratis_ate_km:$('loja_frete_gratis_ate_km').value,loja_frete_gratis_acima:$('loja_frete_gratis_acima').value,loja_frete_distancia_max_km:$('loja_frete_distancia_max_km').value,loja_aceitar_pix:$('loja_aceitar_pix').checked,loja_aceitar_cartao:$('loja_aceitar_cartao').checked}}
  document.querySelectorAll('.save-store-section').forEach(btn=>btn.onclick=async()=>{try{btn.disabled=true;await api('/loja/config',{method:'PUT',body:JSON.stringify(configBody())});flash($('msg'),'Configurações da loja salvas');await load()}catch(e){flash($('msg'),e.message,'error')}finally{btn.disabled=false}});
  $('uploadStoreLogo').onclick=()=>$('loja_logo_file').click();$('loja_logo_file').onchange=async()=>{try{await upload($('loja_logo_file').files[0],'loja_logo_url');flash($('msg'),'Logo enviada. Salve as configurações.')}catch(e){flash($('msg'),e.message,'error')}};
  $('uploadStoreBanner').onclick=()=>$('loja_banner_file').click();$('loja_banner_file').onchange=async()=>{try{await upload($('loja_banner_file').files[0],'loja_banner_url');flash($('msg'),'Banner enviado. Salve as configurações.')}catch(e){flash($('msg'),e.message,'error')}};
  function statusOptions(o){const opts=o.tipo_entrega==='entrega'?['confirmado','preparando','pronto','saiu_entrega','concluido']:['confirmado','preparando','pronto','concluido'];return opts.map(s=>`<option value="${s}" ${o.status_pedido===s?'selected':''}>${({confirmado:'Confirmado',preparando:'Preparando',pronto:'Pronto',saiu_entrega:'Saiu para entrega',concluido:'Concluído'})[s]}</option>`).join('')}
  function orderCard(o){const addr=o.tipo_entrega==='entrega'?`<div class="store-order-address">📍 ${esc([o.endereco,o.numero,o.bairro,o.cidade,o.estado].filter(Boolean).join(', '))}${o.distancia_km?` • ${Number(o.distancia_km).toFixed(1)} km`:''}</div>`:'<div class="store-order-address">🏪 Retirada na barbearia</div>';return `<article class="store-order-card"><div class="store-order-top"><div><strong>Pedido #${o.id}</strong><span>${esc(o.cliente_nome)} • ${esc(o.cliente_telefone)}</span></div><div class="store-order-total">${money(o.total)}</div></div><div class="store-order-meta"><span class="badge">${esc(o.status_pagamento)}</span><span class="badge">${esc(o.forma_pagamento||'sem pagamento')}</span><span>${new Date(o.criado_em).toLocaleString('pt-BR')}</span></div>${addr}<div class="store-order-actions">${o.status_pagamento==='pago'&&!['cancelado','concluido'].includes(o.status_pedido)?`<select class="order-status" data-id="${o.id}">${statusOptions(o)}</select><button class="btn btn-secondary order-save" data-id="${o.id}">Atualizar</button>`:''}${!['cancelado','concluido','saiu_entrega'].includes(o.status_pedido)?`<button class="btn btn-danger order-cancel" data-id="${o.id}">${o.status_pagamento==='pago'?'Cancelar e reembolsar':'Cancelar'}</button>`:''}</div></article>`}
  async function loadOrders(){try{const q=$('orderFilter').value?`?status=${encodeURIComponent($('orderFilter').value)}`:'';const rows=await api('/loja/pedidos'+q);$('storeOrders').innerHTML=rows.length?rows.map(orderCard).join(''):'<div class="storefront-empty">Nenhum pedido neste filtro.</div>';const now=new Date(),todayLocal=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;$('storeOrdersToday').textContent=rows.filter(x=>String(x.criado_em).slice(0,10)===todayLocal).length;$('storeOrders').querySelectorAll('.order-save').forEach(b=>b.onclick=async()=>{try{const id=Number(b.dataset.id),sel=b.parentElement.querySelector('.order-status');await api(`/loja/pedidos/${id}/status`,{method:'PATCH',body:JSON.stringify({status:sel.value})});flash($('msg'),'Pedido atualizado');loadOrders()}catch(e){flash($('msg'),e.message,'error')}});$('storeOrders').querySelectorAll('.order-cancel').forEach(b=>b.onclick=async()=>{if(!confirm('Cancelar este pedido? Se já estiver pago, o EliteFlow tentará reembolsar automaticamente.'))return;try{await api(`/loja/pedidos/${Number(b.dataset.id)}/cancelar`,{method:'POST'});flash($('msg'),'Pedido cancelado');loadOrders()}catch(e){flash($('msg'),e.message,'error')}})}catch(e){flash($('msg'),e.message,'error')}}
  $('orderFilter').onchange=loadOrders;load();
}
