(()=>{
  const slug=decodeURIComponent(location.pathname.split('/').filter(Boolean).pop()||''),$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),phone=v=>String(v||'').replace(/\D/g,'');
  let store=null,products=[],cart=new Map(),delivery='retirada',quote=null,order=null,cardController=null,pollTimer=null,checkoutKey=null;
  const cartKey=`bf_store_cart_${slug}`,buyerKey=`bf_store_buyer_${slug}`;
  function waUrl(n,p){const d=phone(n);return d?`https://wa.me/${d}?text=${encodeURIComponent(p)}`:null}
  async function jsonFetch(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.erro||'Não foi possível concluir esta ação'),{status:r.status,data:d});return d}
  function saveCart(){localStorage.setItem(cartKey,JSON.stringify([...cart.entries()].map(([id,q])=>({id,q}))))}
  function loadCart(){try{for(const x of JSON.parse(localStorage.getItem(cartKey)||'[]'))if(Number.isInteger(x.id)&&Number.isInteger(x.q)&&x.q>0)cart.set(x.id,x.q)}catch{}}
  function product(id){return products.find(p=>Number(p.id)===Number(id))}
  function cartArray(){return [...cart.entries()].map(([id,quantidade])=>({id,quantidade})).filter(x=>product(x.id))}
  function subtotal(){return cartArray().reduce((a,x)=>a+Number(product(x.id).preco)*x.quantidade,0)}
  function renderProducts(){$('storeCount').textContent=`${products.length} produto(s)`;$('storeProducts').innerHTML=products.length?products.map(p=>`<article class="storefront-card"><div class="storefront-image">${p.imagem_url?`<img src="${esc(p.imagem_url)}" alt="${esc(p.nome)}" loading="lazy">`:'<span>📦</span>'}</div><div class="storefront-card-body"><h3>${esc(p.nome)}</h3><p>${esc(p.descricao_publica||'Produto disponível na barbearia.')}</p><div class="storefront-price-row"><strong>${money(p.preco)}</strong><span class="${Number(p.estoque||0)>0?'in-stock':'out-stock'}">${Number(p.estoque||0)>0?`${Number(p.estoque)} em estoque`:'Esgotado'}</span></div><button class="btn btn-primary storefront-buy" data-add="${p.id}" ${Number(p.estoque||0)<=0||!store.checkout_ativo?'disabled':''}>${store.checkout_ativo?'Adicionar ao carrinho':'Checkout indisponível'}</button></div></article>`).join(''):'<div class="storefront-empty">Nenhum produto publicado no momento.</div>';$('storeProducts').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(Number(b.dataset.add)))}
  function add(id){const p=product(id);if(!p||Number(p.estoque)<=0)return;cart.set(id,Math.min(Number(p.estoque),Number(cart.get(id)||0)+1));saveCart();renderCart();openCart()}
  function setQty(id,q){const p=product(id);if(!p)return;const n=Math.max(0,Math.min(Number(p.estoque),q));if(!n)cart.delete(id);else cart.set(id,n);saveCart();quote=null;renderCart()}
  function renderCart(){const arr=cartArray(),count=arr.reduce((a,x)=>a+x.quantidade,0);$('cartCount').textContent=count;$('cartFabText').textContent=count?money(subtotal()):'Carrinho';$('cartFab').classList.toggle('hidden',!products.length);$('cartItems').innerHTML=arr.length?arr.map(x=>{const p=product(x.id);return `<div class="store-cart-item"><div class="store-cart-mini">${p.imagem_url?`<img src="${esc(p.imagem_url)}" alt="">`:'📦'}</div><div class="store-cart-copy"><strong>${esc(p.nome)}</strong><span>${money(p.preco)}</span></div><div class="store-qty"><button data-minus="${p.id}" type="button">−</button><b>${x.quantidade}</b><button data-plus="${p.id}" type="button">+</button></div></div>`}).join(''):'<div class="storefront-empty">Seu carrinho está vazio.</div>';$('cartItems').querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>setQty(Number(b.dataset.minus),Number(cart.get(Number(b.dataset.minus))||0)-1));$('cartItems').querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>setQty(Number(b.dataset.plus),Number(cart.get(Number(b.dataset.plus))||0)+1));$('cartSubtotal').textContent=money(subtotal());$('cartFreight').textContent=quote?money(quote.frete):delivery==='retirada'?money(0):'Calcular';$('cartTotal').textContent=money(subtotal()+(quote?.frete||0));$('startCheckout').disabled=!arr.length||!store?.checkout_ativo}
  function openCart(){$('cartDrawer').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');$('cartBackdrop').classList.remove('hidden');document.body.classList.add('modal-open')}
  function closeCart(){$('cartDrawer').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');$('cartBackdrop').classList.add('hidden');document.body.classList.remove('modal-open')}
  function loadBuyer(){try{const b=JSON.parse(localStorage.getItem(buyerKey)||'{}');$('buyerName').value=b.nome||'';$('buyerEmail').value=b.email||'';$('buyerPhone').value=b.telefone||''}catch{}}
  function saveBuyer(){localStorage.setItem(buyerKey,JSON.stringify({nome:$('buyerName').value,email:$('buyerEmail').value,telefone:$('buyerPhone').value}))}
  function address(){return {cep:$('deliveryCep').value,endereco:$('deliveryStreet').value,numero:$('deliveryNumber').value,bairro:$('deliveryDistrict').value,cidade:$('deliveryCity').value,estado:$('deliveryState').value,complemento:$('deliveryComplement').value}}
  function updateDeliveryUi(){const isDelivery=delivery==='entrega';$('deliveryPickup').classList.toggle('active',!isDelivery);$('deliveryDelivery').classList.toggle('active',isDelivery);$('deliveryFields').classList.toggle('hidden',!isDelivery);$('pickupInfo').classList.toggle('hidden',isDelivery);$('pickupInfo').textContent=store?.retirada?.instrucao||`Retirada em ${store?.endereco||'barbearia'}.`;$('checkoutSummary').innerHTML=`<div><span>Produtos</span><strong>${money(subtotal())}</strong></div><div><span>Frete</span><strong>${isDelivery?(quote?money(quote.frete):'Calcule o frete'):money(0)}</strong></div><div class="total"><span>Total</span><strong>${money(subtotal()+(isDelivery?(quote?.frete||0):0))}</strong></div>${quote?.distancia_km?`<small>Distância calculada: ${Number(quote.distancia_km).toFixed(1)} km</small>`:''}`}
  function openCheckout(){closeCart();$('checkoutModal').classList.remove('hidden');document.body.classList.add('modal-open');$('checkoutFormArea').classList.remove('hidden');$('paymentArea').classList.add('hidden');$('orderDone').classList.add('hidden');order=null;quote=null;checkoutKey=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`);loadBuyer();if(!store.retirada.ativa&&store.entrega.ativa)delivery='entrega';else delivery='retirada';$('deliveryPickup').classList.toggle('hidden',!store.retirada.ativa);$('deliveryDelivery').classList.toggle('hidden',!store.entrega.ativa);updateDeliveryUi()}
  async function closeCheckout(){clearInterval(pollTimer);pollTimer=null;if(cardController){try{await cardController.unmount()}catch{}cardController=null}$('checkoutModal').classList.add('hidden');document.body.classList.remove('modal-open')}
  async function quoteFreight(){try{if(delivery!=='entrega')return;const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/frete`,{method:'POST',body:JSON.stringify({itens:cartArray(),tipo_entrega:'entrega',endereco:address()})});quote=d;updateDeliveryUi();showCheckout(`Frete calculado: ${money(d.frete)} • ${Number(d.distancia_km).toFixed(1)} km`,'success')}catch(e){quote=null;updateDeliveryUi();showCheckout(e.message,'error')}}
  function showCheckout(msg,type='success'){$('checkoutMsg').textContent=msg;$('checkoutMsg').className=`notice ${type}`;$('checkoutMsg').classList.remove('hidden')}
  async function createOrder(){try{saveBuyer();if(!$('buyerName').value.trim()||!$('buyerEmail').value.trim()||phone($('buyerPhone').value).length<10)throw new Error('Preencha nome, e-mail e WhatsApp');if(delivery==='entrega'&&!quote)await quoteFreight();if(delivery==='entrega'&&!quote)throw new Error('Calcule o frete antes de continuar');$('createOrder').disabled=true;$('createOrder').textContent='Criando pedido...';const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/pedidos`,{method:'POST',body:JSON.stringify({idempotency_key:checkoutKey,nome:$('buyerName').value,email:$('buyerEmail').value,telefone:$('buyerPhone').value,tipo_entrega:delivery,endereco:delivery==='entrega'?address():{},itens:cartArray()})});order=d.pedido;if(!order)throw new Error('Pedido não criado');history.replaceState(null,'',`${location.pathname}?pedido=${encodeURIComponent(order.token)}`);$('checkoutFormArea').classList.add('hidden');$('paymentArea').classList.remove('hidden');selectPayment(store.pagamentos.pix?'pix':'card');showCheckout(`Pedido criado. Total ${money(order.total)}. Conclua o pagamento em até 30 minutos.`,'success')}catch(e){showCheckout(e.message,'error')}finally{$('createOrder').disabled=false;$('createOrder').textContent='Criar pedido e escolher pagamento'}}
  function selectPayment(method){const pix=method==='pix';$('methodPix').classList.toggle('active',pix);$('methodCard').classList.toggle('active',!pix);$('pixArea').classList.toggle('hidden',!pix);$('cardArea').classList.toggle('hidden',pix);if(!pix)renderCard().catch(e=>{showCheckout(e.message,'error')})}
  async function renderCard(){if(!order||!store.public_key||typeof MercadoPago!=='function')throw new Error('Checkout de cartão indisponível');if(cardController){try{await cardController.unmount()}catch{}cardController=null}$('storeCardBrick').innerHTML='';const mp=new MercadoPago(store.public_key,{locale:'pt-BR'}),builder=mp.bricks();cardController=await builder.create('cardPayment','storeCardBrick',{initialization:{amount:Number(order.total),payer:{email:$('buyerEmail').value||undefined}},callbacks:{onReady:()=>{},onError:e=>console.error('store brick',e),onSubmit:(formData)=>new Promise(async(resolve,reject)=>{try{const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/pedidos/${encodeURIComponent(order.token)}/cartao`,{method:'POST',body:JSON.stringify(formData)});order=d.pedido||order;resolve();if(order.status_pagamento==='pago')paymentDone(order);else startPolling()}catch(e){showCheckout(e.message,'error');reject(e)}})}})}
  async function generatePix(){try{const doc=String($('pixDocument').value||'').replace(/\D/g,'');if(!/^\d{11,14}$/.test(doc))throw new Error('Informe CPF ou CNPJ válido');$('generateStorePix').disabled=true;const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/pedidos/${encodeURIComponent(order.token)}/pix`,{method:'POST',body:JSON.stringify({documento:doc})});order=d.pedido||order;$('storePixResult').classList.remove('hidden');$('storePixCode').value=d.qr_code||order.qr_code||'';const img=d.qr_code_base64||order.qr_code_base64;if(img){$('storePixQr').src=`data:image/png;base64,${img}`;$('storePixQr').classList.remove('hidden')}else $('storePixQr').classList.add('hidden');const ticket=d.ticket_url||order.ticket_url;$('storePixTicket').classList.toggle('hidden',!ticket);if(ticket)$('storePixTicket').href=ticket;startPolling()}catch(e){showCheckout(e.message,'error')}finally{$('generateStorePix').disabled=false}}
  function startPolling(){clearInterval(pollTimer);let tries=0;const tick=async()=>{if(!order||++tries>60){clearInterval(pollTimer);return}try{const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/pedidos/${encodeURIComponent(order.token)}/sincronizar`,{method:'POST',body:'{}'});order=d.pedido||order;$('storePixStatus').textContent=`Pagamento: ${order.status_pagamento}`;if(order.status_pagamento==='pago'){clearInterval(pollTimer);paymentDone(order)}else if(['recusado','cancelado','expirado','reembolsado'].includes(order.status_pagamento)){clearInterval(pollTimer);showCheckout('Pagamento não concluído. Refaça o pedido se necessário.','error')}}catch(e){console.warn(e.message)}};tick();pollTimer=setInterval(tick,4000)}
  function paymentDone(o){cart.clear();saveCart();renderCart();$('paymentArea').classList.add('hidden');$('orderDone').classList.remove('hidden');$('orderDoneTitle').textContent='Pagamento aprovado!';$('orderDoneText').textContent=`Pedido confirmado no valor de ${money(o.total)}.`;$('orderDoneStatus').innerHTML=`<strong>${esc(o.status_label||'Confirmado')}</strong><span>${o.tipo_entrega==='entrega'?'A barbearia vai preparar e enviar seu pedido.':'A barbearia vai preparar seu pedido para retirada.'}</span>`}
  async function resumeOrder(tok){try{const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/pedidos/${encodeURIComponent(tok)}`);order=d.pedido;if(!order)return;$('checkoutModal').classList.remove('hidden');$('checkoutFormArea').classList.add('hidden');if(order.status_pagamento==='pago'){paymentDone(order)}else if(order.status_pedido==='cancelado'){showCheckout('Este pedido foi cancelado ou expirou.','error')}else{$('paymentArea').classList.remove('hidden');selectPayment(order.forma_pagamento==='cartao'?'card':'pix');if(order.qr_code){$('storePixResult').classList.remove('hidden');$('storePixCode').value=order.qr_code;if(order.qr_code_base64)$('storePixQr').src=`data:image/png;base64,${order.qr_code_base64}`;startPolling()}}}catch(e){console.warn(e.message)}}
  async function load(){try{const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja`);store=d.loja;products=d.produtos||[];document.title=`${store.nome} - BarberFlow`;$('storeTitle').textContent=store.nome;$('storeDesc').textContent=store.descricao||'Produtos selecionados pela sua barbearia.';$('storeBook').href=store.agendamento_url;if(store.banner_url)$('storeHero').style.backgroundImage=`url(${JSON.stringify(store.banner_url)})`;if(store.logo_url)$('storeLogo').innerHTML=`<img src="${esc(store.logo_url)}" alt="Logo">`;const top=waUrl(store.whatsapp,`Olá! Vim pela loja ${store.nome}.`);if(top){$('storeWhatsappTop').href=top;$('storeWhatsappTop').classList.remove('hidden')}$('methodPix').classList.toggle('hidden',!store.pagamentos.pix);$('methodCard').classList.toggle('hidden',!store.pagamentos.cartao);loadCart();renderProducts();renderCart();const tok=new URLSearchParams(location.search).get('pedido');if(tok)resumeOrder(tok)}catch(e){$('storeMsg').textContent=e.message;$('storeMsg').className='notice error';$('storeProducts').innerHTML='<div class="storefront-empty">Esta loja não está disponível.</div>'}}
  $('cartFab').onclick=openCart;$('closeCart').onclick=closeCart;$('cartBackdrop').onclick=closeCart;$('startCheckout').onclick=openCheckout;$('closeCheckout').onclick=closeCheckout;$('closeDone').onclick=closeCheckout;$('deliveryPickup').onclick=()=>{delivery='retirada';quote={frete:0,distancia_km:0};updateDeliveryUi()};$('deliveryDelivery').onclick=()=>{delivery='entrega';quote=null;updateDeliveryUi()};$('deliveryCep').addEventListener('blur',async()=>{const cep=String($('deliveryCep').value||'').replace(/\D/g,'');if(!/^\d{8}$/.test(cep))return;try{const d=await jsonFetch(`/api/publico/${encodeURIComponent(slug)}/loja/cep/${cep}`);$('deliveryCep').value=d.cep||cep;$('deliveryStreet').value=d.endereco||$('deliveryStreet').value;$('deliveryDistrict').value=d.bairro||$('deliveryDistrict').value;$('deliveryCity').value=d.cidade||$('deliveryCity').value;$('deliveryState').value=d.estado||$('deliveryState').value;quote=null;updateDeliveryUi()}catch(e){console.warn(e.message)}});$('quoteFreight').onclick=quoteFreight;$('createOrder').onclick=createOrder;$('methodPix').onclick=()=>selectPayment('pix');$('methodCard').onclick=()=>selectPayment('card');$('generateStorePix').onclick=generatePix;$('copyStorePix').onclick=async()=>{try{await navigator.clipboard.writeText($('storePixCode').value);$('copyStorePix').textContent='Copiado!';setTimeout(()=>$('copyStorePix').textContent='Copiar Pix',1200)}catch{$('storePixCode').select();document.execCommand('copy')}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('checkoutModal').classList.contains('hidden'))closeCheckout();else closeCart()}});load();
})();
