if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('marketing');
  const $=id=>document.getElementById(id),content=$('marketingContent'),msg=$('marketingMsg');
  const qs=new URLSearchParams(location.search),section=qs.get('secao')||'resumo';
  const sections=[['resumo','📈','Visão geral'],['campanhas','📣','Campanhas'],['publicos','🎯','Públicos'],['cupons','🏷️','Cupons'],['indicacoes','🤝','Indicações'],['links','🔗','Links'],['modelos','💬','Modelos']];
  $('marketingNav').innerHTML=sections.map(([k,i,n])=>`<a href="?secao=${k}" class="${section===k?'active':''}">${i} ${n}</a>`).join('');
  const modal=$('marketingModal'),modalTitle=$('marketingModalTitle'),modalSubtitle=$('marketingModalSubtitle'),modalBody=$('marketingModalBody'),modalSave=$('marketingModalSave');let modalAction=null;
  function closeModal(){modal.classList.add('hidden');document.body.classList.remove('modal-open');modalAction=null}
  function openModal({title,subtitle='',body,save='Salvar',onSave}){modalTitle.textContent=title;$('marketingModalSubtitle').textContent=subtitle;modalBody.innerHTML=body;modalSave.textContent=save;modalAction=onSave;modal.classList.remove('hidden');document.body.classList.add('modal-open');setTimeout(()=>modalBody.querySelector('input,select,textarea')?.focus(),30)}
  $('marketingModalClose').onclick=closeModal;$('marketingModalCancel').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.classList.contains('hidden'))closeModal()});modalSave.onclick=async()=>{if(!modalAction)return;try{modalSave.disabled=true;await modalAction();closeModal()}catch(e){flash(msg,e.message,'error')}finally{modalSave.disabled=false}};
  const val=id=>$(id)?.value,checked=id=>!!$(id)?.checked,copy=async t=>{try{await navigator.clipboard.writeText(t);flash(msg,'Copiado')}catch{const el=document.createElement('textarea');el.value=String(t||'');el.setAttribute('readonly','');el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);el.select();const ok=document.execCommand?.('copy');el.remove();flash(msg,ok?'Copiado':'Não foi possível copiar automaticamente',ok?'success':'error')}};
  const fmtPct=n=>n==null?'—':`${Number(n).toLocaleString('pt-BR')}%`;
  const segmentList=[['todos','Todos com consentimento'],['aniversariantes','Aniversariantes do mês'],['novos','Novos clientes (30 dias)'],['inativos','Clientes inativos'],['vip','Clientes VIP por gasto'],['frequentes','Clientes frequentes'],['faltosos','Clientes com faltas'],['compradores_loja','Compradores da loja'],['carrinho_abandonado','Carrinho abandonado']];
  const segmentOptions=(selected='todos')=>segmentList.map(([v,n])=>`<option value="${v}" ${v===selected?'selected':''}>${n}</option>`).join('');
  function bar(label,value,max){const pct=Math.max(0,Math.min(100,Number(value||0)/Math.max(1,Number(max||1))*100));return `<div class="marketing-bar-row"><div><span>${label}</span><strong>${value||0}</strong></div><div class="marketing-bar"><i style="width:${pct}%"></i></div></div>`}

  async function resumo(){
    const d=await api('/marketing/resumo'),c=d.clientes||{},x=d.campanhas||{},l=d.links||{},cp=d.cupons||{};
    const delivery=Number(x.enviados||0)?Math.round(Number(x.entregues||0)/Number(x.enviados||1)*100):0,read=Number(x.entregues||0)?Math.round(Number(x.lidos||0)/Number(x.entregues||1)*100):0;
    content.innerHTML=`<div class="marketing-hero"><div><span class="eyebrow">CENTRAL DE CRESCIMENTO</span><h2>Marketing da barbearia</h2><p>Segmente clientes, crie ofertas, envie campanhas e acompanhe o retorno até a venda.</p></div><a class="btn btn-primary" href="?secao=campanhas">+ Criar campanha</a></div>
    <div class="cards marketing-kpis"><div class="card"><div class="label">Consentimentos</div><div class="value">${c.optin||0}</div><small>de ${c.clientes||0} clientes</small></div><div class="card"><div class="label">Mensagens enviadas</div><div class="value">${x.enviados||0}</div><small>${x.erros||0} erro(s)</small></div><div class="card"><div class="label">Entregues</div><div class="value">${x.entregues||0}</div><small>${delivery}% das enviadas</small></div><div class="card"><div class="label">Lidas</div><div class="value">${x.lidos||0}</div><small>${read}% das entregues</small></div><div class="card"><div class="label">Conversões rastreadas</div><div class="value">${l.conversoes||0}</div></div><div class="card"><div class="label">Receita atribuída</div><div class="value">${money(l.receita||0)}</div></div></div>
    <div class="marketing-grid-2"><div class="card"><h3>Funil de campanhas</h3>${bar('Enviadas',x.enviados,x.enviados||1)}${bar('Entregues',x.entregues,x.enviados||1)}${bar('Lidas',x.lidos,x.enviados||1)}${bar('Cliques',x.cliques,x.enviados||1)}${bar('Conversões',x.conversoes,x.enviados||1)}</div><div class="card"><h3>Promoções e retorno</h3><div class="marketing-stat-row"><span>Cupons ativos</span><strong>${cp.ativos||0}</strong></div><div class="marketing-stat-row"><span>Usos de cupons</span><strong>${cp.usos||0}</strong></div><div class="marketing-stat-row"><span>Descontos concedidos</span><strong>${money(cp.descontos||0)}</strong></div><div class="marketing-stat-row"><span>Indicações convertidas</span><strong>${d.indicacoes?.conversoes||0}</strong></div><div class="marketing-stat-row"><span>ROI de campanhas</span><strong>${fmtPct(d.roi)}</strong></div></div></div>
    <div class="notice">Só entram nos disparos os clientes com consentimento promocional. O cliente pode cancelar respondendo <strong>SAIR</strong> e autorizar novamente enviando <strong>PROMOÇÕES</strong>.</div>`;
  }

  async function publicos(){
    content.innerHTML=`<div class="section-head"><div><h2>Públicos e segmentação</h2><p>Listas dinâmicas baseadas em comportamento real de agenda, clientes e loja.</p></div></div><div class="marketing-filter-grid"><div class="field"><label>Segmento</label><select id="mkSegment">${segmentOptions()}</select></div><div class="field"><label>Dias / janela</label><input id="mkDias" type="number" min="1" value="60"></div><div class="field"><label>Gasto VIP mínimo</label><input id="mkValor" type="number" min="0" value="500"></div><div class="field"><label>Visitas mínimas</label><input id="mkVisitas" type="number" min="1" value="3"></div><div class="field"><label>Faltas mínimas</label><input id="mkFaltas" type="number" min="1" value="2"></div></div><div class="actions"><button id="mkPreview" class="btn btn-primary">Visualizar público</button><button id="mkExport" class="btn btn-secondary">Exportar CSV</button></div><div id="mkAudience" style="margin-top:18px"></div>`;
    const query=()=>new URLSearchParams({segmento:val('mkSegment'),dias:val('mkDias'),valor_minimo:val('mkValor'),min_visitas:val('mkVisitas'),min_faltas:val('mkFaltas')});
    $('mkPreview').onclick=async()=>{try{const d=await api('/marketing/publicos?'+query());$('mkAudience').innerHTML=`<div class="card"><strong>${d.total} cliente(s) neste público</strong><p class="muted">Amostra de até 100 registros; exportação inclui até 5.000.</p></div><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>WhatsApp</th><th>Visitas</th><th>Total gasto</th><th>Última visita</th></tr></thead><tbody>${d.clientes.map(x=>`<tr><td>${esc(x.nome)}</td><td>${esc(x.telefone)}</td><td>${x.visitas||0}</td><td>${money(x.total_gasto)}</td><td>${dateBR(x.ultima_visita)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum cliente.</td></tr>'}</tbody></table></div>`;initResponsiveTables()}catch(e){flash(msg,e.message,'error')}};
    $('mkExport').onclick=()=>location.href='/api/marketing/publicos/exportar?'+query();
  }

  async function modelos(){
    const rows=await api('/marketing/modelos');content.innerHTML=`<div class="section-head"><div><h2>Modelos WhatsApp</h2><p>Cadastre os templates aprovados no seu provedor oficial. Na Twilio, use o Content SID (HX...). No Evolution/QR, a prévia é usada como mensagem de texto.</p></div><button id="newModel" class="btn btn-primary">+ Modelo</button></div><div class="notice">Para Meta/360dialog, crie no template um botão de URL dinâmica usando <code>${esc(location.origin)}/m/{{1}}</code>.</div><div class="marketing-list">${rows.map(x=>`<article class="card"><div class="section-head"><div><strong>${esc(x.nome)}</strong><p class="muted">Template/Content SID: ${esc(x.template_nome_meta||'não informado')} • ${esc(x.idioma)}</p></div><button class="btn btn-danger" data-del-model="${x.id}">Excluir</button></div><p>${esc(x.mensagem_preview||'Sem prévia.')}</p><small>Variáveis, na ordem do template: ${esc((x.parametros||[]).join(', ')||'nenhuma')}</small></article>`).join('')||'<p class="muted">Nenhum modelo criado.</p>'}</div>`;
    $('newModel').onclick=()=>openModal({title:'Novo modelo WhatsApp',subtitle:'Meta/360dialog: informe o nome aprovado. Twilio: informe o Content SID HX.... Evolution: mantenha uma prévia de texto.',body:`<div class="form-grid"><div class="field"><label>Nome interno</label><input id="fModelName" maxlength="120"></div><div class="field"><label>Template / Content SID</label><input id="fModelMeta" maxlength="512" placeholder="promo_clientes"></div><div class="field"><label>Idioma</label><input id="fModelLang" value="pt_BR"></div><div class="field full"><label>Prévia</label><textarea id="fModelPreview" rows="4" placeholder="Olá {nome}! Use o cupom {cupom}..."></textarea></div><div class="field full"><label>Variáveis do corpo, em ordem</label><input id="fModelParams" placeholder="{nome}, {cupom}, {barbearia}"></div></div>`,onSave:async()=>{await api('/marketing/modelos',{method:'POST',body:JSON.stringify({nome:val('fModelName'),template_nome_meta:val('fModelMeta'),idioma:val('fModelLang'),mensagem_preview:val('fModelPreview'),parametros:String(val('fModelParams')||'').split(',').map(x=>x.trim()).filter(Boolean)})});await modelos()}});
    content.querySelectorAll('[data-del-model]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este modelo?'))return;try{await api('/marketing/modelos/'+b.dataset.delModel,{method:'DELETE'});modelos()}catch(e){flash(msg,e.message,'error')}});
  }

  async function cupons(){
    const [rows,clientes]=await Promise.all([api('/marketing/cupons'),api('/clientes')]);content.innerHTML=`<div class="section-head"><div><h2>Cupons e promoções</h2><p>Descontos aplicados e validados no servidor durante o checkout da loja.</p></div><button id="newCoupon" class="btn btn-primary">+ Cupom</button></div><div class="marketing-coupon-grid">${rows.map(x=>`<article class="card coupon-card ${x.ativo?'':'muted-card'}"><div class="coupon-code">${esc(x.codigo)}</div><p>${esc(x.descricao||'Promoção')}</p><strong>${x.tipo==='percentual'?`${Number(x.valor)}%`:money(x.valor)} OFF</strong><div class="marketing-stat-row"><span>Usos</span><b>${x.usos||0}${x.limite_total?` / ${x.limite_total}`:''}</b></div><div class="marketing-stat-row"><span>Pedido mínimo</span><b>${money(x.pedido_minimo||0)}</b></div>${x.fim?`<small>Válido até ${dateBR(x.fim)}</small>`:''}${x.cliente_nome?`<small>Exclusivo: ${esc(x.cliente_nome)}</small>`:''}<div class="actions"><button class="btn btn-secondary" data-toggle-coupon="${x.id}" data-active="${x.ativo?'1':'0'}">${x.ativo?'Desativar':'Ativar'}</button><button class="btn btn-danger" data-del-coupon="${x.id}">Excluir</button></div></article>`).join('')||'<p class="muted">Nenhum cupom criado.</p>'}</div>`;
    $('newCoupon').onclick=()=>openModal({title:'Novo cupom',subtitle:'A criação exige a confirmação de segurança configurada na sua conta.',body:`<div class="form-grid"><div class="field"><label>Código</label><input id="fCouponCode" maxlength="40" placeholder="VOLTE10"></div><div class="field"><label>Tipo</label><select id="fCouponType"><option value="percentual">Percentual</option><option value="fixo">Valor fixo</option></select></div><div class="field"><label>Desconto</label><input id="fCouponValue" type="number" min="0.01" step="0.01" value="10"></div><div class="field"><label>Pedido mínimo</label><input id="fCouponMin" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>Desconto máximo</label><input id="fCouponMax" type="number" min="0" step="0.01" placeholder="Opcional"></div><div class="field"><label>Limite total de usos</label><input id="fCouponTotal" type="number" min="1" placeholder="Ilimitado"></div><div class="field"><label>Limite por cliente</label><input id="fCouponClientLimit" type="number" min="1" value="1"></div><div class="field"><label>Cliente exclusivo</label><select id="fCouponClient"><option value="">Todos</option>${clientes.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select></div><div class="field"><label>Início</label><input id="fCouponStart" type="datetime-local"></div><div class="field"><label>Fim</label><input id="fCouponEnd" type="datetime-local"></div><div class="field full"><label>Descrição</label><input id="fCouponDesc" maxlength="200" placeholder="10% para voltar esta semana"></div></div>`,onSave:async()=>{await api('/marketing/cupons',{method:'POST',body:JSON.stringify({codigo:val('fCouponCode'),tipo:val('fCouponType'),valor:val('fCouponValue'),pedido_minimo:val('fCouponMin'),desconto_maximo:val('fCouponMax'),limite_total:val('fCouponTotal'),limite_por_cliente:val('fCouponClientLimit'),cliente_id:val('fCouponClient'),inicio:val('fCouponStart')||null,fim:val('fCouponEnd')||null,descricao:val('fCouponDesc')})});await cupons()}});
    content.querySelectorAll('[data-toggle-coupon]').forEach(b=>b.onclick=async()=>{try{await api('/marketing/cupons/'+b.dataset.toggleCoupon,{method:'PATCH',body:JSON.stringify({ativo:b.dataset.active!=='1'})});cupons()}catch(e){flash(msg,e.message,'error')}});content.querySelectorAll('[data-del-coupon]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir cupom?'))return;try{await api('/marketing/cupons/'+b.dataset.delCoupon,{method:'DELETE'});cupons()}catch(e){flash(msg,e.message,'error')}});
  }

  function segmentConfigFromForm(){return {dias:Number(val('fCampDays')||60),valor_minimo:Number(val('fCampValue')||500),min_visitas:Number(val('fCampVisits')||3),min_faltas:Number(val('fCampNoShows')||2)}}
  async function campanhas(){
    const [rows,mods,cups]=await Promise.all([api('/marketing/campanhas'),api('/marketing/modelos'),api('/marketing/cupons')]);content.innerHTML=`<div class="section-head"><div><h2>Campanhas</h2><p>Disparos segmentados pelo provedor WhatsApp ativo, com rastreamento de clique e conversão; entrega/leitura dependem do provedor.</p></div><button id="newCampaign" class="btn btn-primary">+ Campanha</button></div><div class="marketing-list">${rows.map(x=>`<article class="card"><div class="section-head"><div><strong>${esc(x.nome)}</strong><p class="muted">${esc(segmentList.find(s=>s[0]===x.segmento)?.[1]||x.segmento)} • ${esc(x.status)}</p></div><span class="badge">${x.enviados||0}/${x.total_alvo||0}</span></div><div class="marketing-mini-kpis"><span>Entregues <b>${x.entregues||0}</b></span><span>Lidas <b>${x.lidos||0}</b></span><span>Cliques <b>${x.cliques||0}</b></span><span>Conversões <b>${x.conversoes||0}</b></span><span>Receita <b>${money(x.receita)}</b></span><span>Erros <b>${x.erros||0}</b></span></div><p>${esc(x.mensagem_preview||'')}</p>${x.link_token?`<small>Link de campanha: ${esc(location.origin+'/m/'+x.link_token)}</small>`:''}<div class="actions">${['rascunho','pausada','erro'].includes(x.status)?`<button class="btn btn-primary" data-send="${x.id}">Enviar / agendar</button>`:''}${['agendada','enviando'].includes(x.status)?`<button class="btn btn-secondary" data-pause="${x.id}">Pausar</button>`:''}${!['enviada','cancelada'].includes(x.status)?`<button class="btn btn-danger" data-cancel="${x.id}">Cancelar</button>`:''}</div></article>`).join('')||'<p class="muted">Nenhuma campanha.</p>'}</div>`;
    $('newCampaign').onclick=()=>{if(!mods.length){flash(msg,'Crie primeiro um Modelo WhatsApp.','error');return}openModal({title:'Nova campanha',subtitle:'Crie como rascunho; o envio/agendamento exige confirmação de segurança.',body:`<div class="form-grid"><div class="field"><label>Nome</label><input id="fCampName" maxlength="160"></div><div class="field"><label>Objetivo</label><select id="fCampObjective"><option value="vendas">Vendas</option><option value="retencao">Retenção</option><option value="reativacao">Reativação</option><option value="aniversario">Aniversário</option><option value="loja">Loja</option></select></div><div class="field"><label>Público</label><select id="fCampSegment">${segmentOptions()}</select></div><div class="field"><label>Modelo WhatsApp</label><select id="fCampModel">${mods.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select></div><div class="field"><label>Cupom</label><select id="fCampCoupon"><option value="">Sem cupom</option>${cups.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.codigo)}</option>`).join('')}</select></div><div class="field"><label>Botão rastreável</label><select id="fCampLink"><option value="">Sem botão rastreável</option><option value="agendamento">Agendamento</option><option value="loja">Loja</option></select></div><div class="field"><label>Investimento</label><input id="fCampInvestment" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>Dias / janela</label><input id="fCampDays" type="number" min="1" value="60"></div><div class="field"><label>Gasto VIP mínimo</label><input id="fCampValue" type="number" min="0" value="500"></div><div class="field"><label>Visitas mínimas</label><input id="fCampVisits" type="number" min="1" value="3"></div><div class="field"><label>Faltas mínimas</label><input id="fCampNoShows" type="number" min="1" value="2"></div></div><div class="notice">Em Meta/360dialog, o template precisa ter botão URL dinâmica com base <code>${esc(location.origin)}/m/{{1}}</code>.</div>`,onSave:async()=>{await api('/marketing/campanhas',{method:'POST',body:JSON.stringify({nome:val('fCampName'),objetivo:val('fCampObjective'),segmento:val('fCampSegment'),segmento_config:segmentConfigFromForm(),modelo_id:val('fCampModel'),cupom_id:val('fCampCoupon')||null,link_destino:val('fCampLink')||null,investimento:val('fCampInvestment')})});await campanhas()}})};
    content.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>openModal({title:'Enviar campanha',subtitle:'Deixe sem data para iniciar agora ou escolha o agendamento.',save:'Confirmar envio',body:`<div class="field"><label>Data e hora</label><input id="fSchedule" type="datetime-local"></div><div class="notice">O EliteFlow enviará em lotes pelo provedor WhatsApp ativo e continuará processando até concluir o público.</div>`,onSave:async()=>{await api(`/marketing/campanhas/${b.dataset.send}/agendar`,{method:'POST',body:JSON.stringify({agendada_para:val('fSchedule')||null})});await campanhas()}}));
    content.querySelectorAll('[data-pause]').forEach(b=>b.onclick=async()=>{try{await api(`/marketing/campanhas/${b.dataset.pause}/pausar`,{method:'POST',body:'{}'});campanhas()}catch(e){flash(msg,e.message,'error')}});content.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{if(!confirm('Cancelar campanha?'))return;try{await api(`/marketing/campanhas/${b.dataset.cancel}/cancelar`,{method:'POST',body:'{}'});campanhas()}catch(e){flash(msg,e.message,'error')}});
  }

  async function links(){
    const [rows,camps]=await Promise.all([api('/marketing/links'),api('/marketing/campanhas')]);content.innerHTML=`<div class="section-head"><div><h2>Links rastreáveis</h2><p>Meça tráfego vindo de Instagram, bio, anúncios, QR Codes e campanhas.</p></div><button id="newLink" class="btn btn-primary">+ Link</button></div><div class="marketing-list">${rows.map(x=>{const url=`${location.origin}/m/${x.token}`;return `<article class="card ${x.ativo?'':'muted-card'}"><div class="section-head"><div><strong>${esc(x.nome)}</strong><p class="muted">Destino: ${esc(x.destino)}${x.campanha_nome?' • '+esc(x.campanha_nome):''}</p></div><div class="actions"><button class="btn btn-secondary" data-copy-link="${esc(url)}">Copiar</button><button class="btn btn-secondary" data-toggle-link="${x.id}" data-active="${x.ativo?'1':'0'}">${x.ativo?'Desativar':'Ativar'}</button></div></div><code>${esc(url)}</code><div class="marketing-mini-kpis"><span>Cliques <b>${x.cliques}</b></span><span>Conversões <b>${x.conversoes}</b></span><span>Receita <b>${money(x.receita)}</b></span></div></article>`}).join('')||'<p class="muted">Nenhum link.</p>'}</div>`;
    $('newLink').onclick=()=>openModal({title:'Novo link rastreável',body:`<div class="form-grid"><div class="field"><label>Nome</label><input id="fLinkName" maxlength="140"></div><div class="field"><label>Destino</label><select id="fLinkDest"><option value="agendamento">Agendamento</option><option value="loja">Loja</option></select></div><div class="field full"><label>Campanha vinculada</label><select id="fLinkCampaign"><option value="">Nenhuma</option>${camps.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select></div></div>`,onSave:async()=>{await api('/marketing/links',{method:'POST',body:JSON.stringify({nome:val('fLinkName'),destino:val('fLinkDest'),campanha_id:val('fLinkCampaign')||null})});await links()}});
    content.querySelectorAll('[data-copy-link]').forEach(b=>b.onclick=()=>copy(b.dataset.copyLink));content.querySelectorAll('[data-toggle-link]').forEach(b=>b.onclick=async()=>{try{await api('/marketing/links/'+b.dataset.toggleLink,{method:'PATCH',body:JSON.stringify({ativo:b.dataset.active!=='1'})});links()}catch(e){flash(msg,e.message,'error')}});
  }

  async function indicacoes(){
    const [d,clientes]=await Promise.all([api('/marketing/indicacoes'),api('/clientes')]),c=d.config||{};content.innerHTML=`<div class="section-head"><div><h2>Programa de indicação</h2><p>Clientes compartilham um link; após a primeira compra válida, indicador e indicado recebem cupons automaticamente.</p></div></div><div class="card"><h3>Recompensas</h3><div class="form-grid"><label class="check"><input id="refAtivo" type="checkbox" ${c.ativo?'checked':''}> Ativar programa</label><div class="field"><label>Tipo</label><select id="refTipo"><option value="fixo" ${c.tipo_recompensa==='fixo'?'selected':''}>R$ fixo</option><option value="percentual" ${c.tipo_recompensa==='percentual'?'selected':''}>Percentual</option></select></div><div class="field"><label>Quem indica ganha</label><input id="refIndicador" type="number" value="${Number(c.valor_indicador||10)}"></div><div class="field"><label>Indicado ganha</label><input id="refIndicado" type="number" value="${Number(c.valor_indicado||10)}"></div><div class="field"><label>Pedido mínimo para validar</label><input id="refMin" type="number" value="${Number(c.pedido_minimo||0)}"></div></div><button id="saveRef" class="btn btn-primary">Salvar programa</button></div><div class="card"><h3>Gerar link para cliente</h3><div class="actions"><select id="refCliente"><option value="">Selecione</option>${clientes.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select><button id="genRef" class="btn btn-secondary">Gerar / copiar link</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Código</th><th>Conversões</th></tr></thead><tbody>${(d.codigos||[]).map(x=>`<tr><td>${esc(x.cliente_nome)}</td><td>${esc(x.codigo)}</td><td>${x.conversoes||0}</td></tr>`).join('')||'<tr><td colspan="3">Nenhuma indicação gerada.</td></tr>'}</tbody></table></div>`;
    $('saveRef').onclick=async()=>{try{await api('/marketing/indicacoes/config',{method:'PUT',body:JSON.stringify({ativo:checked('refAtivo'),tipo_recompensa:val('refTipo'),valor_indicador:val('refIndicador'),valor_indicado:val('refIndicado'),pedido_minimo:val('refMin')})});flash(msg,'Programa salvo')}catch(e){flash(msg,e.message,'error')}};$('genRef').onclick=async()=>{if(!val('refCliente'))return flash(msg,'Selecione um cliente','error');try{const r=await api('/marketing/indicacoes/cliente/'+val('refCliente'),{method:'POST',body:'{}'});await copy(r.url);indicacoes()}catch(e){flash(msg,e.message,'error')}};initResponsiveTables();
  }

  const runners={resumo,publicos,modelos,cupons,campanhas,links,indicacoes};(runners[section]||resumo)().catch(e=>{content.innerHTML=`<div class="notice error">${esc(e.message)}</div>`});
}
