if(requireAuth(['super_admin'])){
  const $=id=>document.getElementById(id);
  $('shell').innerHTML=renderShell('master');
  let cache=[];
  function periodLabel(p){const [a,m]=String(p).split('-');return new Date(Number(a),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'short',year:'numeric'});}
  function badgeStatus(s){return `<span class="badge master-status-${esc(s||'sem_status')}">${esc(s||'sem status')}</span>`}
  function switchSection(id){
    const meta={visao:['Visão geral','Central do Supermaster','Acompanhe operação, clientes e receita do BarberFlow.'], 'barbearias-sec':['Barbearias','Gestão de barbearias','Controle planos, acessos, assinaturas e ciclo de vida dos clientes.'], 'financeiro-sec':['Financeiro SaaS','Receita e projeções','Analise recorrência, histórico e previsão financeira do BarberFlow.'], 'suporte-sec':['Suporte','Central de suporte','Acompanhe chamados das barbearias e responda com segurança.'], 'perfil-sec':['Meu perfil','Perfil e segurança','Gerencie os seus dados e credenciais do Supermaster.']};
    document.querySelectorAll('.master-section').forEach(x=>x.classList.toggle('hidden',x.id!==id));
    document.querySelectorAll('.master-tab').forEach(x=>x.classList.toggle('active',x.dataset.section===id));
    const m=meta[id]||meta.visao; if($('masterSectionName'))$('masterSectionName').textContent=m[0]; if($('masterPageTitle'))$('masterPageTitle').textContent=m[1]; if($('masterPageSubtitle'))$('masterPageSubtitle').textContent=m[2];
    window.scrollTo({top:0,behavior:'smooth'});
    if(id==='financeiro-sec')financeiro();if(id==='suporte-sec')suporte();if(id==='perfil-sec')perfil();if(id==='barbearias-sec')load();
  }
  document.querySelectorAll('.master-tab').forEach(b=>b.onclick=()=>switchSection(b.dataset.section));
  async function dashboard(){const d=await api('/master/dashboard');$('mTotal').textContent=d.resumo.barbearias_total;$('mAtivas').textContent=d.resumo.barbearias_ativas;$('mTrials').textContent=d.resumo.trials;$('mAssinaturas').textContent=d.resumo.assinaturas_ativas;$('mMrr').textContent=money(d.resumo.mrr);if($('mMrrHero'))$('mMrrHero').textContent=money(d.resumo.mrr);$('mAgenda').textContent=d.resumo.agendamentos_mes;}
  async function financeiro(){try{const d=await api('/master/financeiro?passados=12&futuros=12');$('finMrr').textContent=money(d.resumo.mrr);$('finArr').textContent=money(d.resumo.arr);$('finMes').textContent=money(d.resumo.realizado_mes);$('finAberto').textContent=money(d.resumo.em_aberto);$('fin12').textContent=money(d.resumo.realizado_12m);$('finProj12').textContent=money(d.resumo.projetado_12m);$('fRealMes').textContent=money(d.resumo.realizado_mes);$('fArr').textContent=money(d.resumo.arr);$('fProj12').textContent=money(d.resumo.projetado_12m);$('finAviso').textContent=d.aviso_historico||'';const maxH=Math.max(1,...d.historico.map(x=>x.realizado));$('historicoFinanceiro').innerHTML=d.historico.map(x=>`<div class="master-period"><div><strong>${periodLabel(x.periodo)}</strong><span>${money(x.realizado)} realizado${x.em_aberto?` • ${money(x.em_aberto)} em aberto`:''}</span></div><div class="master-period-bar"><i style="width:${Math.round((x.realizado/maxH)*100)}%"></i></div></div>`).join('');const maxF=Math.max(1,...d.futuro.map(x=>x.projetado));$('futuroFinanceiro').innerHTML=d.futuro.map(x=>`<div class="master-period"><div><strong>${periodLabel(x.periodo)}</strong><span>${money(x.projetado)} • ${x.assinaturas} assinatura(s)</span></div><div class="master-period-bar future"><i style="width:${Math.round((x.projetado/maxF)*100)}%"></i></div></div>`).join('');}catch(e){console.error(e)}}
  async function load(){try{const q=new URLSearchParams();if($('busca').value.trim())q.set('busca',$('busca').value.trim());if($('status').value)q.set('status',$('status').value);cache=await api('/master/barbearias'+(q.toString()?`?${q}`:''));if($('masterTenantCount'))$('masterTenantCount').textContent=cache.length;$('barbearias').innerHTML=cache.length?cache.map(x=>`<tr><td><strong>${esc(x.nome)}</strong><div class="muted">/${esc(x.slug)}</div></td><td>${esc(x.dono||'-')}<div class="muted">${esc(x.dono_email||'-')}</div></td><td><strong>${esc(x.plano||'-')}</strong></td><td>${badgeStatus(x.status)}</td><td>${x.agendamentos_30d} agenda<div class="muted">${x.clientes} clientes • ${x.barbeiros} barbeiros</div></td><td><span class="badge ${x.excluido_em?'master-off':x.ativo?'master-on':'master-off'}">${x.excluido_em?'Excluída':x.ativo?'Ativa':'Bloqueada'}</span></td><td class="actions">${x.excluido_em?`<button class="btn btn-success" data-click="restaurarTenant(${x.id})">Restaurar</button>`:`<button class="btn btn-secondary" data-click="detalhe(${x.id})">Gerenciar</button><button class="btn ${x.ativo?'btn-danger':'btn-success'}" data-click="toggleTenant(${x.id},${!x.ativo})">${x.ativo?'Bloquear':'Ativar'}</button><button class="btn btn-danger" data-click="excluirTenant(${x.id})">Excluir</button>`}</td></tr>`).join(''):'<tr><td colspan="7">Nenhuma barbearia encontrada.</td></tr>';initResponsiveTables();}catch(e){flash($('msg'),e.message,'error')}}
  window.toggleTenant=async(id,ativo)=>{if(!confirm(`${ativo?'Ativar':'Bloquear'} esta barbearia?`))return;try{await api(`/master/barbearias/${id}/status`,{method:'PATCH',body:JSON.stringify({ativo})});await Promise.all([dashboard(),load()])}catch(e){flash($('msg'),e.message,'error')}};
  window.excluirTenant=async id=>{const x=cache.find(v=>v.id===id);if(!x)return;const conf=prompt(`Para excluir ${x.nome}, digite exatamente o nome da barbearia:`);if(conf===null)return;try{await api(`/master/barbearias/${id}`,{method:'DELETE',body:JSON.stringify({confirmacao:conf})});flash($('msg'),'Barbearia excluída com segurança');await Promise.all([dashboard(),load(),financeiro()])}catch(e){flash($('msg'),e.message,'error')}};
  window.restaurarTenant=async id=>{if(!confirm('Restaurar esta barbearia?'))return;try{await api(`/master/barbearias/${id}/restaurar`,{method:'POST'});flash($('msg'),'Barbearia restaurada');await Promise.all([dashboard(),load()])}catch(e){flash($('msg'),e.message,'error')}};
  window.detalhe=async id=>{try{const d=await api(`/master/barbearias/${id}`);const a=d.assinatura||{};$('masterTitulo').textContent=d.barbearia.nome;$('masterDetalhes').innerHTML=`<div class="master-detail-grid"><div class="card"><div class="label">Clientes</div><div class="value">${d.metricas.clientes}</div></div><div class="card"><div class="label">Barbeiros</div><div class="value">${d.metricas.barbeiros}</div></div><div class="card"><div class="label">Agendamentos 30d</div><div class="value">${d.metricas.agendamentos_30d}</div></div><div class="card"><div class="label">Faturamento/mês</div><div class="value">${money(d.metricas.faturamento_mes)}</div></div></div><h3>Plano e assinatura</h3><div class="form-grid"><div class="field"><label>Plano</label><select id="detPlano"><option value="starter">Starter</option><option value="pro">Pro</option><option value="premium">Premium</option></select></div><div class="field"><label>Status</label><select id="detStatus"><option value="trial">Trial</option><option value="ativa">Ativa</option><option value="inadimplente">Inadimplente</option><option value="cancelada">Cancelada</option></select></div><div class="field"><label>Fim do trial</label><input id="detTrial" type="date"></div><div class="field"><label>Próxima cobrança</label><input id="detCobranca" type="date"></div></div><button id="detSalvar" class="btn btn-primary" style="margin-top:14px">Salvar plano/assinatura</button><h3 style="margin-top:22px">Usuários</h3><div class="master-user-list">${d.usuarios.map(u=>`<div><strong>${esc(u.nome)}</strong><span>${esc(u.email)} • ${esc(roleLabel(u.papel))} • ${u.ativo?'ativo':'inativo'}</span></div>`).join('')}</div>`;$('detPlano').value=a.plano||'pro';$('detStatus').value=a.status||'trial';const statusGerenciadoPeloMp=a.provedor==='mercadopago'&&a.referencia_externa;$('detStatus').disabled=!!statusGerenciadoPeloMp;$('detStatus').title=statusGerenciadoPeloMp?'Status sincronizado pelo Mercado Pago':'';$('detTrial').value=a.fim_trial?String(a.fim_trial).slice(0,10):'';$('detCobranca').value=a.proxima_cobranca?String(a.proxima_cobranca).slice(0,10):'';$('detSalvar').onclick=async()=>{try{await api(`/master/barbearias/${id}/assinatura`,{method:'PATCH',body:JSON.stringify({plano:$('detPlano').value,status:$('detStatus').value,fim_trial:$('detTrial').value||null,proxima_cobranca:$('detCobranca').value||null})});flash($('msg'),'Plano/assinatura atualizados');$('masterModal').classList.add('hidden');await Promise.all([dashboard(),load(),financeiro()])}catch(e){flash($('msg'),e.message,'error')}};$('masterModal').classList.remove('hidden')}catch(e){flash($('msg'),e.message,'error')}};

  async function health(){try{const h=await api('/master/system/health');$('healthStatus').textContent=h.ok?'Operacional':'Atenção';$('healthStatus').className=h.ok?'health-ok':'health-warn';$('healthDb').textContent=`${h.db_latency_ms} ms`;$('healthErrors').textContent=h.errors_24h;$('healthSupport').textContent=h.support_open;$('healthDetail').textContent=`Release ${h.release} • uptime ${Math.floor(h.uptime_seconds/60)} min • memória ${h.memory_mb} MB • webhooks com erro ${h.webhook_errors} • automações com erro ${h.automation_errors} • pagamentos pendentes antigos ${h.stale_payments} • backup ${h.backup?`${h.backup.status} em ${new Date(h.backup.criado_em).toLocaleString('pt-BR')}`:(h.backup_remote_configured?'ainda não executado':'remoto não configurado')}`;}catch(e){$('healthStatus').textContent='Indisponível';$('healthStatus').className='health-warn';$('healthDetail').textContent=e.message}}
  async function suporte(){try{const q=$('supportFilter')?.value?`?status=${encodeURIComponent($('supportFilter').value)}`:'';const list=await api('/master/support/tickets'+q);$('masterSupportList').innerHTML=list.length?list.map(x=>`<article class="master-support-ticket"><div class="support-ticket-head"><div><strong>#${x.id} · ${esc(x.assunto)}</strong><small>${esc(x.barbearia)} • ${esc(x.usuario||'-')} • ${new Date(x.criado_em).toLocaleString('pt-BR')}</small></div>${badgeStatus(x.status)}</div><p>${esc(x.mensagem)}</p>${x.resposta?`<div class="support-reply"><strong>Resposta atual</strong><p>${esc(x.resposta)}</p></div>`:''}<textarea id="supportReply${x.id}" maxlength="4000" placeholder="Resposta para a barbearia"></textarea><div class="actions"><button class="btn btn-secondary" data-support-action="em_atendimento" data-id="${x.id}">Em atendimento</button><button class="btn btn-success" data-support-action="resolvido" data-id="${x.id}">Responder e resolver</button><button class="btn btn-dark" data-support-action="fechado" data-id="${x.id}">Fechar</button></div></article>`).join(''):'<p class="muted">Nenhum chamado encontrado.</p>';$('masterSupportList').querySelectorAll('[data-support-action]').forEach(b=>b.onclick=async()=>{try{const resposta=$(`supportReply${b.dataset.id}`)?.value.trim()||null;await api(`/master/support/tickets/${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:b.dataset.supportAction,resposta})});flash($('supportMasterMsg'),'Chamado atualizado');await Promise.all([suporte(),health()])}catch(e){flash($('supportMasterMsg'),e.message,'error')}})}catch(e){flash($('supportMasterMsg'),e.message,'error')}}
  async function perfil(){try{const p=await api('/master/perfil');$('perfilNome').value=p.nome||'';$('perfilEmail').value=p.email||'';$('perfilTelefone').value=p.telefone||'';}catch(e){flash($('perfilMsg'),e.message,'error')}}
  $('salvarPerfil').onclick=async()=>{try{const p=await api('/master/perfil',{method:'PATCH',body:JSON.stringify({nome:$('perfilNome').value,email:$('perfilEmail').value,telefone:$('perfilTelefone').value})});flash($('perfilMsg'),'Dados atualizados');const session=JSON.parse(localStorage.getItem('bf_user')||'null');if(session){session.nome=p.nome;session.email=p.email;localStorage.setItem('bf_user',JSON.stringify(session));}}catch(e){flash($('perfilMsg'),e.message,'error')}};
  $('salvarSenha').onclick=async()=>{if($('senhaNova').value!==$('senhaConfirmar').value)return flash($('senhaMsg'),'As novas senhas não coincidem','error');try{await api('/master/perfil/senha',{method:'PATCH',body:JSON.stringify({senha_atual:$('senhaAtual').value,nova_senha:$('senhaNova').value})});$('senhaAtual').value=$('senhaNova').value=$('senhaConfirmar').value='';alert('Senha alterada. Faça login novamente.');await logout()}catch(e){flash($('senhaMsg'),e.message,'error')}};
  $('masterFechar').onclick=()=>$('masterModal').classList.add('hidden');if($('refreshHealth'))$('refreshHealth').onclick=health;if($('refreshSupport'))$('refreshSupport').onclick=suporte;if($('supportFilter'))$('supportFilter').onchange=suporte;$('filtrar').onclick=load;$('busca').onkeydown=e=>{if(e.key==='Enter')load()};$('atualizar').onclick=()=>Promise.all([dashboard(),financeiro(),load(),health()]);Promise.all([dashboard(),financeiro(),load(),health()]);
}
