if(requireAuth(['super_admin'])){
  const $=id=>document.getElementById(id);
  $('shell').innerHTML=renderShell('master');
  let cache=[];
  function periodLabel(p){const [a,m]=String(p).split('-');return new Date(Number(a),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'short',year:'numeric'});}
  function badgeStatus(s){return `<span class="badge master-status-${esc(s||'sem_status')}">${esc(s||'sem status')}</span>`}
  function switchSection(id){
    const meta={visao:['Visão geral','Central do Supermaster','Acompanhe operação, clientes e receita do BarberFlow.'], 'barbearias-sec':['Barbearias','Gestão de barbearias','Controle planos, acessos, assinaturas e ciclo de vida dos clientes.'], 'financeiro-sec':['Financeiro SaaS','Receita e projeções','Analise recorrência, histórico e previsão financeira do BarberFlow.'], 'pagamentos-master-sec':['Pagamentos','Gateways da plataforma','Conecte os gateways usados nas cobranças das assinaturas do BarberFlow.'], 'suporte-sec':['Suporte','Central de suporte','Acompanhe chamados das barbearias e responda com segurança.'], 'seguranca-master-sec':['Segurança','Autenticação em dois fatores','Gerencie o autenticador e a proteção da conta Supermaster.'], 'perfil-sec':['Meu perfil','Perfil e segurança','Gerencie os seus dados e credenciais do Supermaster.']};
    document.querySelectorAll('.master-section').forEach(x=>x.classList.toggle('hidden',x.id!==id));
    document.querySelectorAll('.master-tab').forEach(x=>x.classList.toggle('active',x.dataset.section===id));
    const m=meta[id]||meta.visao; if($('masterSectionName'))$('masterSectionName').textContent=m[0]; if($('masterPageTitle'))$('masterPageTitle').textContent=m[1]; if($('masterPageSubtitle'))$('masterPageSubtitle').textContent=m[2];
    window.scrollTo({top:0,behavior:'smooth'});
    if(id==='financeiro-sec')financeiro();if(id==='pagamentos-master-sec')gatewaysMaster();if(id==='suporte-sec'){suporte();loadMasterSupportSettings();}if(id==='seguranca-master-sec')masterSecurity();if(id==='perfil-sec')perfil();if(id==='barbearias-sec')load();
  }
  document.querySelectorAll('.master-tab').forEach(b=>b.onclick=()=>switchSection(b.dataset.section));
  async function dashboard(){const d=await api('/master/dashboard');$('mTotal').textContent=d.resumo.barbearias_total;$('mAtivas').textContent=d.resumo.barbearias_ativas;$('mTrials').textContent=d.resumo.trials;$('mAssinaturas').textContent=d.resumo.assinaturas_ativas;$('mMrr').textContent=money(d.resumo.mrr);if($('mMrrHero'))$('mMrrHero').textContent=money(d.resumo.mrr);$('mAgenda').textContent=d.resumo.agendamentos_mes;if($('mInadimplentes'))$('mInadimplentes').textContent=d.resumo.inadimplentes||0;if($('mCanceladas'))$('mCanceladas').textContent=d.resumo.canceladas||0;const total=(d.planos||[]).reduce((s,x)=>s+Number(x.quantidade||0),0);if($('mPlanMixMini'))$('mPlanMixMini').innerHTML=(d.planos||[]).length?(d.planos||[]).map(x=>`<div class="master-plan-mini-row"><span>${esc(planLabel(x.plano))}</span><div><i style="width:${total?Math.max(5,Number(x.quantidade||0)*100/total):0}%"></i></div><strong>${Number(x.quantidade||0)}</strong></div>`).join(''):'<p class="muted">Nenhuma assinatura ativa.</p>';hydrateIcons();}
  async function financeiro(){try{
    const d=await api('/master/financeiro?passados=12&futuros=12');
    $('finMrr').textContent=money(d.resumo.mrr);$('finArr').textContent=money(d.resumo.arr);$('finMes').textContent=money(d.resumo.realizado_mes);$('finAberto').textContent=money(d.resumo.em_aberto);$('fin12').textContent=money(d.resumo.realizado_12m);$('finProj12').textContent=money(d.resumo.projetado_12m);$('fRealMes').textContent=money(d.resumo.realizado_mes);$('fArr').textContent=money(d.resumo.arr);$('fProj12').textContent=money(d.resumo.projetado_12m);$('finAviso').textContent=d.aviso_historico||'';
    const maxH=Math.max(1,...d.historico.map(x=>x.realizado));
    $('historicoFinanceiro').innerHTML=d.historico.map(x=>`<div class="master-period"><div><strong>${periodLabel(x.periodo)}</strong><span>${money(x.realizado)} realizado${x.em_aberto?` • ${money(x.em_aberto)} em aberto`:''}</span></div><div class="master-period-bar"><i style="width:${Math.round((x.realizado/maxH)*100)}%"></i></div></div>`).join('');
    const maxF=Math.max(1,...d.futuro.map(x=>x.projetado));
    $('futuroFinanceiro').innerHTML=d.futuro.map(x=>`<div class="master-period"><div><strong>${periodLabel(x.periodo)}</strong><span>${money(x.projetado)} • ${x.assinaturas} assinatura(s)</span></div><div class="master-period-bar future"><i style="width:${Math.round((x.projetado/maxF)*100)}%"></i></div></div>`).join('');
    if($('masterRevenueChart'))$('masterRevenueChart').innerHTML=d.historico.map(x=>`<div class="master-revenue-col" title="${periodLabel(x.periodo)} • ${money(x.realizado)}"><strong>${money(x.realizado)}</strong><i style="height:${Math.max(3,Math.round((x.realizado/maxH)*170))}px"></i><span>${periodLabel(x.periodo).split(' ')[0]}</span></div>`).join('');
    const totalPlan=Math.max(1,(d.planos||[]).reduce((a,x)=>a+Number(x.quantidade||0),0));
    if($('masterPlanMix'))$('masterPlanMix').innerHTML=(d.planos||[]).map(x=>`<div class="master-metric-row"><div><strong>${esc(String(x.plano||'').toUpperCase())}</strong><span>${x.quantidade} • ${money(x.mrr)}/mês</span></div><div class="master-metric-track"><i style="width:${Math.round(Number(x.quantidade||0)/totalPlan*100)}%"></i></div></div>`).join('')||'<p class="muted">Sem assinaturas ativas.</p>';
    const totalStatus=Math.max(1,(d.cobrancas_status||[]).reduce((a,x)=>a+Number(x.quantidade||0),0));
    if($('masterCollectionStatus'))$('masterCollectionStatus').innerHTML=(d.cobrancas_status||[]).map(x=>`<div class="master-metric-row"><div><strong>${esc(x.status)}</strong><span>${x.quantidade} • ${money(x.total)}</span></div><div class="master-metric-track"><i style="width:${Math.round(Number(x.quantidade||0)/totalStatus*100)}%"></i></div></div>`).join('')||'<p class="muted">Sem cobranças registradas.</p>';
  }catch(e){console.error(e)}}
  async function load(){try{const q=new URLSearchParams();if($('busca').value.trim())q.set('busca',$('busca').value.trim());if($('status').value)q.set('status',$('status').value);cache=await api('/master/barbearias'+(q.toString()?`?${q}`:''));if($('masterTenantCount'))$('masterTenantCount').textContent=cache.length;$('barbearias').innerHTML=cache.length?cache.map(x=>{const purge=x.exclusao_programada_em?Math.max(0,Math.ceil((new Date(x.exclusao_programada_em)-Date.now())/86400000)):null;return `<tr><td><strong>${esc(x.nome)}</strong><div class="muted">/${esc(x.slug)}</div></td><td>${esc(x.dono||'-')}<div class="muted">${esc(x.dono_email||'-')}</div></td><td><strong>${esc(x.plano||'-')}</strong></td><td>${badgeStatus(x.status)}</td><td>${x.agendamentos_30d} agenda<div class="muted">${x.clientes} clientes • ${x.barbeiros} barbeiros</div></td><td><span class="badge ${x.excluido_em?'master-off':x.ativo?'master-on':'master-off'}">${x.excluido_em?'Lixeira':x.ativo?'Ativa':'Bloqueada'}</span>${x.excluido_em&&purge!==null?`<div class="muted">Exclusão permanente em ${purge} dia(s)</div>`:''}</td><td class="actions">${x.excluido_em?`<button class="btn btn-success" data-click="restaurarTenant(${x.id})">Restaurar</button><button class="btn btn-danger" data-click="excluirTenantPermanente(${x.id})">Excluir permanentemente</button>`:`<button class="btn btn-secondary" data-click="detalhe(${x.id})">Gerenciar</button><button class="btn ${x.ativo?'btn-danger':'btn-success'}" data-click="toggleTenant(${x.id},${!x.ativo})">${x.ativo?'Bloquear':'Ativar'}</button><button class="btn btn-danger" data-click="excluirTenant(${x.id})">Excluir por 30 dias</button><button class="btn btn-danger btn-outline-danger" data-click="excluirTenantPermanente(${x.id})">Excluir permanentemente</button>`}</td></tr>`}).join(''):'<tr><td colspan="7">Nenhuma barbearia encontrada.</td></tr>';initResponsiveTables();}catch(e){flash($('msg'),e.message,'error')}}
  window.toggleTenant=async(id,ativo)=>{if(!confirm(`${ativo?'Ativar':'Bloquear'} esta barbearia?`))return;try{await api(`/master/barbearias/${id}/status`,{method:'PATCH',body:JSON.stringify({ativo})});await Promise.all([dashboard(),load()])}catch(e){flash($('msg'),e.message,'error')}};
  async function confirmTenantDelete(x,permanente=false){const conf=prompt(`${permanente?'EXCLUSÃO PERMANENTE':'Lixeira por 30 dias'} — digite exatamente o nome da barbearia:\n${x.nome}`);if(conf===null)return null;return {confirmacao:conf}}
  window.excluirTenant=async id=>{const x=cache.find(v=>v.id===id);if(!x)return;const body=await confirmTenantDelete(x,false);if(!body)return;try{await api(`/master/barbearias/${id}`,{method:'DELETE',body:JSON.stringify(body)});flash($('msg'),'Barbearia movida para a lixeira por 30 dias');await Promise.all([dashboard(),load(),financeiro()])}catch(e){flash($('msg'),e.message,'error')}};
  window.excluirTenantPermanente=async id=>{const x=cache.find(v=>v.id===id);if(!x)return;if(!confirm('Esta ação apaga definitivamente os dados da barbearia e não pode ser desfeita. Continuar?'))return;const body=await confirmTenantDelete(x,true);if(!body)return;try{await api(`/master/barbearias/${id}/permanente`,{method:'DELETE',body:JSON.stringify(body)});flash($('msg'),'Barbearia excluída permanentemente');await Promise.all([dashboard(),load(),financeiro()])}catch(e){flash($('msg'),e.message,'error')}};
  window.restaurarTenant=async id=>{if(!confirm('Restaurar esta barbearia?'))return;try{await api(`/master/barbearias/${id}/restaurar`,{method:'POST'});flash($('msg'),'Barbearia restaurada');await Promise.all([dashboard(),load()])}catch(e){flash($('msg'),e.message,'error')}};
  window.detalhe=async id=>{try{const d=await api(`/master/barbearias/${id}`);const a=d.assinatura||{};$('masterTitulo').textContent=d.barbearia.nome;$('masterDetalhes').innerHTML=`<div class="master-detail-grid"><div class="card"><div class="label">Clientes</div><div class="value">${d.metricas.clientes}</div></div><div class="card"><div class="label">Barbeiros</div><div class="value">${d.metricas.barbeiros}</div></div><div class="card"><div class="label">Agendamentos 30d</div><div class="value">${d.metricas.agendamentos_30d}</div></div><div class="card"><div class="label">Faturamento/mês</div><div class="value">${money(d.metricas.faturamento_mes)}</div></div></div><h3>Plano e assinatura</h3><div class="form-grid"><div class="field"><label>Plano</label><select id="detPlano"><option value="starter">Starter</option><option value="pro">Pro</option><option value="premium">Premium</option></select></div><div class="field"><label>Status</label><select id="detStatus"><option value="trial">Trial</option><option value="ativa">Ativa</option><option value="inadimplente">Inadimplente</option><option value="cancelada">Cancelada</option></select></div><div class="field"><label>Fim do trial</label><input id="detTrial" type="date"></div><div class="field"><label>Próxima cobrança</label><input id="detCobranca" type="date"></div></div><button id="detSalvar" class="btn btn-primary" style="margin-top:14px">Salvar plano/assinatura</button><h3 style="margin-top:22px">Usuários</h3><div class="master-user-list">${d.usuarios.map(u=>`<div><strong>${esc(u.nome)}</strong><span>${esc(u.email)} • ${esc(roleLabel(u.papel))} • ${u.ativo?'ativo':'inativo'}</span></div>`).join('')}</div>`;$('detPlano').value=a.plano||'pro';$('detStatus').value=a.status||'trial';const statusGerenciadoPeloMp=a.provedor==='mercadopago'&&a.referencia_externa;$('detStatus').disabled=!!statusGerenciadoPeloMp;$('detStatus').title=statusGerenciadoPeloMp?'Status sincronizado pelo Mercado Pago':'';$('detTrial').value=a.fim_trial?String(a.fim_trial).slice(0,10):'';$('detCobranca').value=a.proxima_cobranca?String(a.proxima_cobranca).slice(0,10):'';$('detSalvar').onclick=async()=>{try{await api(`/master/barbearias/${id}/assinatura`,{method:'PATCH',body:JSON.stringify({plano:$('detPlano').value,status:$('detStatus').value,fim_trial:$('detTrial').value||null,proxima_cobranca:$('detCobranca').value||null})});flash($('msg'),'Plano/assinatura atualizados');$('masterModal').classList.add('hidden');await Promise.all([dashboard(),load(),financeiro()])}catch(e){flash($('msg'),e.message,'error')}};$('masterModal').classList.remove('hidden')}catch(e){flash($('msg'),e.message,'error')}};

  async function health(){try{const h=await api('/master/system/health');$('healthStatus').textContent=h.ok?'Operacional':'Atenção';$('healthStatus').className=h.ok?'health-ok':'health-warn';$('healthDb').textContent=`${h.db_latency_ms} ms`;$('healthErrors').textContent=h.errors_24h;$('healthSupport').textContent=h.support_open;$('healthDetail').textContent=`Release ${h.release} • uptime ${Math.floor(h.uptime_seconds/60)} min • memória ${h.memory_mb} MB • webhooks com erro ${h.webhook_errors} • automações com erro ${h.automation_errors} • pagamentos pendentes antigos ${h.stale_payments} • backup ${h.backup?`${h.backup.status} em ${new Date(h.backup.criado_em).toLocaleString('pt-BR')}`:(h.backup_remote_configured?'ainda não executado':'remoto não configurado')}`;}catch(e){$('healthStatus').textContent='Indisponível';$('healthStatus').className='health-warn';$('healthDetail').textContent=e.message}}
  async function loadMasterSupportSettings(){try{const d=await api('/master/settings/support');if($('masterSupportWhatsapp'))$('masterSupportWhatsapp').value=d.whatsapp||'';}catch(e){flash($('masterSupportConfigMsg'),e.message,'error')}}
  async function saveMasterSupportSettings(){const whatsapp=String($('masterSupportWhatsapp')?.value||'').trim();try{$('saveMasterSupportWhatsapp').disabled=true;$('saveMasterSupportWhatsapp').textContent='Salvando...';const d=await api('/master/settings/support',{method:'PUT',body:JSON.stringify({whatsapp})});$('masterSupportWhatsapp').value=d.whatsapp||'';flash($('masterSupportConfigMsg'),d.mensagem||'WhatsApp do suporte atualizado')}catch(e){flash($('masterSupportConfigMsg'),e.message,'error')}finally{$('saveMasterSupportWhatsapp').disabled=false;$('saveMasterSupportWhatsapp').textContent='Salvar WhatsApp'}}
  async function suporte(){try{const q=$('supportFilter')?.value?`?status=${encodeURIComponent($('supportFilter').value)}`:'';const list=await api('/master/support/tickets'+q);$('masterSupportList').innerHTML=list.length?list.map(x=>`<article class="master-support-ticket"><div class="support-ticket-head"><div><strong>#${x.id} · ${esc(x.assunto)}</strong><small>${esc(x.barbearia)} • ${esc(x.usuario||'-')} • ${new Date(x.criado_em).toLocaleString('pt-BR')}</small></div>${badgeStatus(x.status)}</div><p>${esc(x.mensagem)}</p>${x.resposta?`<div class="support-reply"><strong>Resposta atual</strong><p>${esc(x.resposta)}</p></div>`:''}<textarea id="supportReply${x.id}" maxlength="4000" placeholder="Resposta para a barbearia"></textarea><div class="actions"><button class="btn btn-secondary" data-support-action="em_atendimento" data-id="${x.id}">Em atendimento</button><button class="btn btn-success" data-support-action="resolvido" data-id="${x.id}">Responder e resolver</button><button class="btn btn-dark" data-support-action="fechado" data-id="${x.id}">Fechar</button></div></article>`).join(''):'<p class="muted">Nenhum chamado encontrado.</p>';$('masterSupportList').querySelectorAll('[data-support-action]').forEach(b=>b.onclick=async()=>{try{const resposta=$(`supportReply${b.dataset.id}`)?.value.trim()||null;await api(`/master/support/tickets/${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:b.dataset.supportAction,resposta})});flash($('supportMasterMsg'),'Chamado atualizado');await Promise.all([suporte(),health()])}catch(e){flash($('supportMasterMsg'),e.message,'error')}})}catch(e){flash($('supportMasterMsg'),e.message,'error')}}
  const masterGatewayMarks={mercadopago:'MP',pagbank:'PB',asaas:'AS',pagarme:'PM',stripe:'ST'};
  let masterGateways=[],masterGatewayCurrent=null,masterGatewayTrigger=null;
  function masterGatewayField(f){if(f.tipo==='select')return `<div class="field"><label>${esc(f.label)}</label><select name="${f.id}" ${f.required?'required':''}>${(f.options||[]).map(o=>`<option value="${esc(o[0])}">${esc(o[1])}</option>`).join('')}</select></div>`;return `<div class="field"><label>${esc(f.label)}${f.required?' *':''}</label><input name="${f.id}" type="${f.tipo==='password'?'password':'text'}" autocomplete="off" maxlength="1500" ${f.required?'required':''} placeholder="${esc(f.placeholder||'')}"></div>`}
  function renderMasterGateways(){
    const grid=$('masterGatewayGrid');if(!grid)return;
    grid.innerHTML=masterGateways.map(g=>`<article class="master-gateway-card ${g.credenciais_salvas?'connected':''}"><div class="gateway-card-head"><div class="gateway-brand ${g.id}">${masterGatewayMarks[g.id]||'PG'}</div><div class="gateway-title"><strong>${esc(g.nome)}</strong><span>${esc((g.metodos||[]).join(' • '))}</span></div><span class="gateway-status ${g.credenciais_salvas?'ok':''}">${g.credenciais_salvas?'Conectado':'Não configurado'}</span></div><p>${esc(g.descricao||'')}</p><div class="gateway-required-fields"><strong>Credenciais:</strong> ${(g.campos||[]).map(c=>esc(c.label)).join(' • ')}</div>${g.id==='mercadopago'?`<div class="gateway-capability"><span>${iconSVG('trend',14)}</span>Usado no Pix e cartão das assinaturas do BarberFlow</div>`:`<div class="gateway-capability"><span>${iconSVG('shield',14)}</span>Conexão preparada para drivers futuros da plataforma</div>`}<div class="gateway-card-actions"><button class="btn btn-primary" type="button" data-master-gateway="${g.id}">${g.credenciais_salvas?'Atualizar':'Conectar'}</button>${g.credenciais_salvas?`<button class="btn btn-danger btn-outline-danger" type="button" data-master-gateway-remove="${g.id}">Remover</button>`:''}</div></article>`).join('');
    $('masterGatewaysCount').textContent=`${masterGateways.filter(x=>x.credenciais_salvas).length}/${masterGateways.length}`;
    grid.querySelectorAll('[data-master-gateway]').forEach(b=>b.onclick=()=>openMasterGateway(b.dataset.masterGateway));
    grid.querySelectorAll('[data-master-gateway-remove]').forEach(b=>b.onclick=()=>removeMasterGateway(b.dataset.masterGatewayRemove));
  }
  async function gatewaysMaster(){try{const r=await api('/master/payment-gateways');masterGateways=r.gateways||[];renderMasterGateways()}catch(e){flash($('masterGatewayMsg'),e.message,'error')}}
  function openMasterGateway(id){const g=masterGateways.find(x=>x.id===id);if(!g)return;masterGatewayCurrent=g;masterGatewayTrigger=document.activeElement;$('masterGatewayModalTitle').textContent=`${g.nome} — credenciais da plataforma`;$('masterGatewayModalDesc').textContent=g.credenciais_salvas?'Preencha os campos para substituir a conexão atual. Os segredos salvos não são exibidos novamente.':'Informe as credenciais da conta que receberá as assinaturas do BarberFlow.';$('masterGatewayFields').innerHTML=(g.campos||[]).map(masterGatewayField).join('');$('masterGatewayModal').classList.remove('hidden');document.body.classList.add('modal-open');$('masterGatewayFields').querySelector('input,select')?.focus()}
  function closeMasterGateway(){masterGatewayCurrent=null;$('masterGatewayModal').classList.add('hidden');document.body.classList.remove('modal-open');$('masterGatewayForm').reset();$('masterGatewayFields').innerHTML='';masterGatewayTrigger?.focus?.();masterGatewayTrigger=null}
  async function removeMasterGateway(id){const g=masterGateways.find(x=>x.id===id);if(!confirm(`Remover as credenciais ${g?.nome||id} da plataforma?`))return;try{await api(`/master/payment-gateways/${id}`,{method:'DELETE'});flash($('masterGatewayMsg'),'Credenciais removidas');await gatewaysMaster()}catch(e){flash($('masterGatewayMsg'),e.message,'error')}}
  let masterMfaPending=false,masterMfaSecretRaw='';
  const masterDigits6=v=>String(v||'').replace(/\D/g,'').slice(0,6);
  function masterResetMfaUi(){
    masterMfaPending=false;masterMfaSecretRaw='';
    $('masterMfaRotateBox')?.classList.add('hidden');$('masterMfaNewBox')?.classList.add('hidden');
    if($('masterMfaCurrentPassword'))$('masterMfaCurrentPassword').value='';
    if($('masterMfaCurrentCode'))$('masterMfaCurrentCode').value='';
    if($('masterMfaNewCode'))$('masterMfaNewCode').value='';
    if($('masterMfaConfirmPassword'))$('masterMfaConfirmPassword').value='';
    if($('masterMfaSecret'))$('masterMfaSecret').textContent='—';
    if($('masterMfaOpenApp'))$('masterMfaOpenApp').href='#';
  }
  async function masterSecurity(){
    try{
      const d=await api('/auth/security-status');
      const active=!!d.mfa_enabled;
      $('masterMfaStatus').textContent=active?'2FA ativo':'2FA obrigatório';
      $('masterMfaStatus').className=`badge ${active?'status-concluido':'status-cancelado'}`;
      $('masterMfaStatusText').textContent=active?'Protegido por aplicativo autenticador':'Configuração necessária';
      if(!active)flash($('masterMfaMsg'),'O Supermaster deve manter o 2FA ativo. Faça logout e entre novamente para concluir o setup obrigatório.','error');
    }catch(e){flash($('masterMfaMsg'),e.message,'error')}
  }
  if($('masterMfaCurrentCode'))$('masterMfaCurrentCode').oninput=e=>e.target.value=masterDigits6(e.target.value);
  if($('masterMfaNewCode'))$('masterMfaNewCode').oninput=e=>e.target.value=masterDigits6(e.target.value);
  if($('masterMfaRotateStart'))$('masterMfaRotateStart').onclick=()=>{masterResetMfaUi();$('masterMfaRotateBox').classList.remove('hidden');$('masterMfaCurrentPassword').focus()};
  if($('masterMfaRotateCancel'))$('masterMfaRotateCancel').onclick=masterResetMfaUi;
  if($('masterMfaNewCancel'))$('masterMfaNewCancel').onclick=async()=>{try{if(masterMfaPending)await api('/auth/mfa/rotate/cancel',{method:'POST',body:'{}'})}catch{}masterResetMfaUi();flash($('masterMfaMsg'),'Troca cancelada. O autenticador atual continua válido.')};
  if($('masterMfaGenerate'))$('masterMfaGenerate').onclick=async()=>{
    const senha=$('masterMfaCurrentPassword').value,code=masterDigits6($('masterMfaCurrentCode').value);
    if(!senha)return flash($('masterMfaMsg'),'Informe sua senha atual','error');
    if(code.length!==6)return flash($('masterMfaMsg'),'Informe o código atual de 6 dígitos','error');
    try{
      $('masterMfaGenerate').disabled=true;$('masterMfaGenerate').textContent='Gerando…';
      const d=await api('/auth/mfa/rotate/start',{method:'POST',body:JSON.stringify({senha,code})});
      masterMfaPending=true;masterMfaSecretRaw=d.secret||'';
      $('masterMfaSecret').textContent=String(d.secret||'').replace(/(.{4})/g,'$1 ').trim();
      $('masterMfaOpenApp').href=d.otpauth_uri||'#';
      $('masterMfaConfirmPassword').value=senha;
      $('masterMfaRotateBox').classList.add('hidden');$('masterMfaNewBox').classList.remove('hidden');$('masterMfaNewCode').focus();
      flash($('masterMfaMsg'),'Nova chave criada. O autenticador antigo continua funcionando até a confirmação.');
    }catch(e){flash($('masterMfaMsg'),e.message,'error')}finally{$('masterMfaGenerate').disabled=false;$('masterMfaGenerate').textContent='Gerar nova chave'}
  };
  if($('masterMfaCopy'))$('masterMfaCopy').onclick=async()=>{try{await navigator.clipboard.writeText(masterMfaSecretRaw);$('masterMfaCopy').textContent='Copiado';setTimeout(()=>$('masterMfaCopy').textContent='Copiar chave',1300)}catch{flash($('masterMfaMsg'),'Não foi possível copiar automaticamente. Selecione a chave manualmente.','error')}};
  if($('masterMfaConfirm'))$('masterMfaConfirm').onclick=async()=>{
    const senha=$('masterMfaConfirmPassword').value,code=masterDigits6($('masterMfaNewCode').value);
    if(!senha)return flash($('masterMfaMsg'),'Confirme sua senha','error');
    if(code.length!==6)return flash($('masterMfaMsg'),'Informe o código do novo aplicativo','error');
    try{
      $('masterMfaConfirm').disabled=true;$('masterMfaConfirm').textContent='Ativando…';
      await api('/auth/mfa/rotate/confirm',{method:'POST',body:JSON.stringify({senha,code})});
      masterResetMfaUi();await masterSecurity();flash($('masterMfaMsg'),'Novo aplicativo autenticador ativado. A chave anterior foi invalidada.');
    }catch(e){flash($('masterMfaMsg'),e.message,'error')}finally{$('masterMfaConfirm').disabled=false;$('masterMfaConfirm').textContent='Ativar novo autenticador'}
  };
  async function perfil(){try{const p=await api('/master/perfil');$('perfilNome').value=p.nome||'';$('perfilEmail').value=p.email||'';$('perfilTelefone').value=p.telefone||'';}catch(e){flash($('perfilMsg'),e.message,'error')}}
  $('salvarPerfil').onclick=async()=>{try{const p=await api('/master/perfil',{method:'PATCH',body:JSON.stringify({nome:$('perfilNome').value,email:$('perfilEmail').value,telefone:$('perfilTelefone').value})});flash($('perfilMsg'),'Dados atualizados');const session=JSON.parse(localStorage.getItem('bf_user')||'null');if(session){session.nome=p.nome;session.email=p.email;localStorage.setItem('bf_user',JSON.stringify(session));}}catch(e){flash($('perfilMsg'),e.message,'error')}};
  $('salvarSenha').onclick=async()=>{if($('senhaNova').value!==$('senhaConfirmar').value)return flash($('senhaMsg'),'As novas senhas não coincidem','error');try{await api('/master/perfil/senha',{method:'PATCH',body:JSON.stringify({senha_atual:$('senhaAtual').value,nova_senha:$('senhaNova').value})});$('senhaAtual').value=$('senhaNova').value=$('senhaConfirmar').value='';alert('Senha alterada. Faça login novamente.');await logout()}catch(e){flash($('senhaMsg'),e.message,'error')}};
  if($('masterGatewayClose'))$('masterGatewayClose').onclick=closeMasterGateway;if($('masterGatewayCancel'))$('masterGatewayCancel').onclick=closeMasterGateway;if($('masterGatewayModal'))$('masterGatewayModal').onclick=e=>{if(e.target===$('masterGatewayModal'))closeMasterGateway()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('masterGatewayModal')&&!$('masterGatewayModal').classList.contains('hidden'))closeMasterGateway()});
  if($('masterGatewayForm'))$('masterGatewayForm').onsubmit=async e=>{e.preventDefault();if(!masterGatewayCurrent)return;const body={};new FormData(e.currentTarget).forEach((v,k)=>body[k]=v);try{$('masterGatewaySave').disabled=true;$('masterGatewaySave').textContent='Salvando...';await api(`/master/payment-gateways/${masterGatewayCurrent.id}/credenciais`,{method:'POST',body:JSON.stringify(body)});const nome=masterGatewayCurrent.nome;closeMasterGateway();await gatewaysMaster();flash($('masterGatewayMsg'),`${nome} conectado com segurança`)}catch(err){flash($('masterGatewayMsg'),err.message,'error')}finally{$('masterGatewaySave').disabled=false;$('masterGatewaySave').textContent='Salvar credenciais'}};
  $('masterFechar').onclick=()=>$('masterModal').classList.add('hidden');if($('refreshHealth'))$('refreshHealth').onclick=health;if($('refreshSupport'))$('refreshSupport').onclick=suporte;if($('saveMasterSupportWhatsapp'))$('saveMasterSupportWhatsapp').onclick=saveMasterSupportSettings;if($('supportFilter'))$('supportFilter').onchange=suporte;$('filtrar').onclick=load;$('busca').onkeydown=e=>{if(e.key==='Enter')load()};$('atualizar').onclick=()=>Promise.all([dashboard(),financeiro(),load(),health()]);Promise.all([dashboard(),financeiro(),load(),health()]);
}
