if(requireAuth(['super_admin'])){
  document.getElementById('shell').innerHTML=renderShell('master');
  let cache=[];
  async function dashboard(){const d=await api('/master/dashboard');mTotal.textContent=d.resumo.barbearias_total;mAtivas.textContent=d.resumo.barbearias_ativas;mTrials.textContent=d.resumo.trials;mAssinaturas.textContent=d.resumo.assinaturas_ativas;mMrr.textContent=money(d.resumo.mrr);mAgenda.textContent=d.resumo.agendamentos_mes;}
  function badgeStatus(s){return `<span class="badge master-status-${esc(s||'sem_status')}">${esc(s||'sem status')}</span>`}
  async function load(){try{const q=new URLSearchParams();if(busca.value.trim())q.set('busca',busca.value.trim());if(status.value)q.set('status',status.value);cache=await api('/master/barbearias'+(q.toString()?`?${q}`:''));barbearias.innerHTML=cache.length?cache.map(x=>`<tr><td><strong>${esc(x.nome)}</strong><div class="muted">/${esc(x.slug)}</div></td><td>${esc(x.dono||'-')}<div class="muted">${esc(x.dono_email||'-')}</div></td><td>${esc(x.plano||'-')}</td><td>${badgeStatus(x.status)}</td><td>${x.agendamentos_30d} agenda<div class="muted">${x.clientes} clientes • ${x.barbeiros} barbeiros</div></td><td><span class="badge ${x.ativo?'master-on':'master-off'}">${x.ativo?'Ativa':'Bloqueada'}</span></td><td class="actions"><button class="btn btn-secondary" onclick="detalhe(${x.id})">Ver</button><button class="btn ${x.ativo?'btn-danger':'btn-success'}" onclick="toggleTenant(${x.id},${!x.ativo})">${x.ativo?'Bloquear':'Ativar'}</button></td></tr>`).join(''):'<tr><td colspan="7">Nenhuma barbearia encontrada.</td></tr>';initResponsiveTables();}catch(e){flash(msg,e.message,'error')}}
  window.toggleTenant=async(id,ativo)=>{if(!confirm(`${ativo?'Ativar':'Bloquear'} esta barbearia?`))return;try{await api(`/master/barbearias/${id}/status`,{method:'PATCH',body:JSON.stringify({ativo})});await Promise.all([dashboard(),load()])}catch(e){flash(msg,e.message,'error')}};
  window.detalhe=async id=>{try{const d=await api(`/master/barbearias/${id}`);const a=d.assinatura||{};masterTitulo.textContent=d.barbearia.nome;masterDetalhes.innerHTML=`<div class="master-detail-grid"><div class="card"><div class="label">Clientes</div><div class="value">${d.metricas.clientes}</div></div><div class="card"><div class="label">Barbeiros</div><div class="value">${d.metricas.barbeiros}</div></div><div class="card"><div class="label">Agendamentos 30d</div><div class="value">${d.metricas.agendamentos_30d}</div></div><div class="card"><div class="label">Faturamento/mês</div><div class="value">${money(d.metricas.faturamento_mes)}</div></div></div><h3>Assinatura</h3><div class="form-grid"><div class="field"><label>Plano</label><select id="detPlano"><option value="starter">Starter</option><option value="pro">Pro</option><option value="premium">Premium</option></select></div><div class="field"><label>Status</label><select id="detStatus"><option value="trial">Trial</option><option value="ativa">Ativa</option><option value="inadimplente">Inadimplente</option><option value="cancelada">Cancelada</option></select></div><div class="field"><label>Fim do trial</label><input id="detTrial" type="date"></div><div class="field"><label>Próxima cobrança</label><input id="detCobranca" type="date"></div></div><button id="detSalvar" class="btn btn-primary" style="margin-top:14px">Salvar assinatura</button><h3 style="margin-top:22px">Usuários</h3><div class="master-user-list">${d.usuarios.map(u=>`<div><strong>${esc(u.nome)}</strong><span>${esc(u.email)} • ${esc(roleLabel(u.papel))} • ${u.ativo?'ativo':'inativo'}</span></div>`).join('')}</div>`;detPlano.value=a.plano||'pro';detStatus.value=a.status||'trial';detTrial.value=a.fim_trial?String(a.fim_trial).slice(0,10):'';detCobranca.value=a.proxima_cobranca?String(a.proxima_cobranca).slice(0,10):'';detSalvar.onclick=async()=>{try{await api(`/master/barbearias/${id}/assinatura`,{method:'PATCH',body:JSON.stringify({plano:detPlano.value,status:detStatus.value,fim_trial:detTrial.value||null,proxima_cobranca:detCobranca.value||null})});flash(msg,'Assinatura atualizada');masterModal.classList.add('hidden');await Promise.all([dashboard(),load()])}catch(e){flash(msg,e.message,'error')}};masterModal.classList.remove('hidden')}catch(e){flash(msg,e.message,'error')}};
  masterFechar.onclick=()=>masterModal.classList.add('hidden');filtrar.onclick=load;busca.onkeydown=e=>{if(e.key==='Enter')load()};atualizar.onclick=()=>Promise.all([dashboard(),load()]);Promise.all([dashboard(),load()]);
}
