if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('pagamentos');
  const user=currentUser(),msg=document.getElementById('msg'),gatewayModal=document.getElementById('gatewayModal'),gatewayModalTitle=document.getElementById('gatewayModalTitle'),gatewayModalDesc=document.getElementById('gatewayModalDesc'),gatewayCredentialForm=document.getElementById('gatewayCredentialForm'),gatewayCredentialFields=document.getElementById('gatewayCredentialFields'),saveGatewayCredential=document.getElementById('saveGatewayCredential'),closeGatewayModal=document.getElementById('closeGatewayModal'),cancelGatewayCredential=document.getElementById('cancelGatewayCredential'),campoSinal=document.getElementById('campoSinal'),pixManualCampos=document.getElementById('pixManualCampos'),salvarPagamentos=document.getElementById('salvarPagamentos'),pixPendentes=document.getElementById('pixPendentes'),atualizarPixPendentes=document.getElementById('atualizarPixPendentes');
  const ids=['pagamento_agendamento','percentual_sinal','aceitar_mercadopago','mp_aceitar_pix','mp_aceitar_cartao','aceitar_pix_manual','pix_chave','pix_nome','pix_banco','aceitar_dinheiro'];
  const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
  const pixConfirmModal=document.getElementById('pixManualConfirmModal'),pixConfirmDetails=document.getElementById('pixManualConfirmDetails'),pixConfirmFeedback=document.getElementById('pixManualConfirmFeedback'),pixConfirmButton=document.getElementById('pixManualConfirmButton'),pixConfirmCancel=document.getElementById('pixManualConfirmCancel'),pixConfirmClose=document.getElementById('pixManualConfirmClose');
  let pendingPixRows=[],selectedPendingPix=null;
  let gatewayData=[],paymentsEnabled=false,currentGateway=null,lastGatewayTrigger=null;
  const providerMark={mercadopago:'MP',pagbank:'PB',asaas:'AS',pagarme:'PM',stripe:'ST'};
  function statusLabel(g){return g.credenciais_salvas?'Credenciais salvas':'Aguardando credenciais'}
  function capabilityText(g){if(g.id==='mercadopago'){if(!g.credenciais_salvas)return 'Preencha as credenciais para liberar o checkout';return g.webhook_ready?'Checkout + confirmação automática por webhook prontos':'Checkout pronto • adicione o segredo do webhook para confirmação automática em segundo plano'}return 'Credenciais preparadas • driver será conectado depois'}
  function renderGateways(){
    const grid=document.getElementById('gatewayGrid'),owner=user.papel==='dono';
    grid.innerHTML=gatewayData.map(g=>{
      let action='';
      if(!paymentsEnabled)action='<a class="btn btn-secondary" href="/pages/assinatura.html">Disponível no Pro</a>';
      else if(!owner)action='<button type="button" class="btn btn-secondary" disabled>Somente o dono configura</button>';
      else action=`<button type="button" class="btn btn-primary gateway-configure" data-provider="${g.id}">${g.credenciais_salvas?'Atualizar':'Informar'} credenciais</button>${g.credenciais_salvas?`<button type="button" class="btn btn-danger gateway-remove" data-provider="${g.id}">Remover</button>`:''}`;
      return `<article class="gateway-card ${g.credenciais_salvas?'connected':''}"><div class="gateway-card-head"><div class="gateway-brand ${g.id}">${providerMark[g.id]||'PG'}</div><div class="gateway-title"><strong>${esc(g.nome)}</strong><span>${esc(g.metodos.join(' • '))}</span></div><span class="gateway-status ${g.credenciais_salvas?'ok':''}">${esc(statusLabel(g))}</span></div><p>${esc(g.descricao)}</p><div class="gateway-capability"><span>${g.id==='mercadopago'?'⚡':'🔐'}</span>${esc(capabilityText(g))}</div><div class="gateway-required-fields"><strong>Necessário:</strong> ${g.campos.map(c=>esc(c.label)+(c.required?'':' (opcional)')).join(' • ')}</div><div class="gateway-card-actions">${action}</div></article>`;
    }).join('');
    grid.querySelectorAll('.gateway-configure').forEach(b=>b.onclick=()=>openCredentialModal(b.dataset.provider));
    grid.querySelectorAll('.gateway-remove').forEach(b=>b.onclick=()=>removeCredentials(b.dataset.provider));
    document.getElementById('credentialsCount').textContent=String(gatewayData.filter(x=>x.credenciais_salvas).length);
    updateCheckoutStatus();
  }
  async function loadGateways(){const r=await api('/pagamentos/gateways');paymentsEnabled=!!r.habilitado;gatewayData=r.gateways||[];document.getElementById('paymentLock').classList.toggle('hidden',paymentsEnabled);renderGateways()}
  function fieldHtml(f){if(f.tipo==='select')return `<div class="field"><label>${esc(f.label)}</label><select name="${f.id}" ${f.required?'required':''}>${(f.options||[]).map(o=>`<option value="${esc(o[0])}">${esc(o[1])}</option>`).join('')}</select></div>`;return `<div class="field"><label>${esc(f.label)}${f.required?' *':''}</label><input name="${f.id}" type="${f.tipo==='password'?'password':'text'}" autocomplete="off" maxlength="1500" ${f.required?'required':''} placeholder="${esc(f.placeholder||'')}"></div>`}
  function openCredentialModal(provider){const g=gatewayData.find(x=>x.id===provider);if(!g)return;lastGatewayTrigger=document.activeElement;currentGateway=g;gatewayModalTitle.textContent=`Credenciais — ${g.nome}`;gatewayModalDesc.textContent=g.credenciais_salvas?'Preencha somente para substituir as credenciais atuais. Os valores salvos não são exibidos novamente.':'Informe as credenciais da conta da própria barbearia.';gatewayCredentialFields.innerHTML=g.campos.map(fieldHtml).join('');gatewayModal.classList.remove('hidden');document.body.classList.add('modal-open');gatewayCredentialFields.querySelector('input,select')?.focus()}
  function closeCredentialModalFn(){currentGateway=null;gatewayModal.classList.add('hidden');document.body.classList.remove('modal-open');gatewayCredentialForm.reset();gatewayCredentialFields.innerHTML='';if(lastGatewayTrigger&&typeof lastGatewayTrigger.focus==='function')lastGatewayTrigger.focus();lastGatewayTrigger=null}
  closeGatewayModal.onclick=cancelGatewayCredential.onclick=closeCredentialModalFn;gatewayModal.onclick=e=>{if(e.target===gatewayModal)closeCredentialModalFn()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!gatewayModal.classList.contains('hidden'))closeCredentialModalFn()});
  gatewayCredentialForm.onsubmit=async e=>{e.preventDefault();if(!currentGateway)return;const body={};new FormData(gatewayCredentialForm).forEach((v,k)=>body[k]=v);try{saveGatewayCredential.disabled=true;saveGatewayCredential.textContent='Salvando...';await api(`/pagamentos/gateways/${currentGateway.id}/credenciais`,{method:'POST',body:JSON.stringify(body)});const name=currentGateway.nome;closeCredentialModalFn();await loadGateways();flash(msg,`Credenciais ${name} salvas com segurança`)}catch(e){flash(msg,e.message,'error')}finally{saveGatewayCredential.disabled=false;saveGatewayCredential.textContent='Salvar credenciais'}};
  async function removeCredentials(provider){const g=gatewayData.find(x=>x.id===provider);if(!confirm(`Remover as credenciais de ${g?.nome||provider}?`))return;try{await api(`/pagamentos/gateways/${provider}`,{method:'DELETE'});if(provider==='mercadopago'){el.aceitar_mercadopago.checked=false;await saveConfig(false)}await loadGateways();flash(msg,`Credenciais ${g?.nome||''} removidas`)}catch(e){flash(msg,e.message,'error')}}
  function toggleSinal(){campoSinal.style.display=el.pagamento_agendamento.value==='sinal'?'flex':'none';updateOverview()}
  function togglePixManual(){pixManualCampos.style.display=el.aceitar_pix_manual.checked?'grid':'none'}
  function updateOverview(){const mode=el.pagamento_agendamento.value;document.getElementById('chargeMode').textContent=mode==='total'?'Valor total':mode==='sinal'?`${Number(el.percentual_sinal.value||50)}% de sinal`:'Sem antecipação';document.getElementById('chargeModeHint').textContent=mode==='nenhum'?'Cliente paga no atendimento':'Cobrança antes da confirmação';updateCheckoutStatus()}
  function updateCheckoutStatus(){const mp=gatewayData.find(x=>x.id==='mercadopago'),ready=!!mp?.credenciais_salvas,enabled=!!el.aceitar_mercadopago?.checked;const badge=document.getElementById('checkoutStatus');if(!paymentsEnabled){badge.textContent='Plano Pro necessário';badge.className='badge status-cancelado'}else if(enabled&&ready){badge.textContent='Checkout pronto';badge.className='badge status-concluido'}else if(enabled&&!ready){badge.textContent='Faltam credenciais MP';badge.className='badge status-cancelado'}else{badge.textContent='Checkout online desativado';badge.className='badge'}document.getElementById('checkoutGateway').textContent=ready?'Mercado Pago':'Não configurado'}
  async function loadConfig(){const r=await api('/pagamentos/config');paymentsEnabled=!!r.habilitado;const c=r.config||{};ids.forEach(id=>{if(el[id].type==='checkbox')el[id].checked=!!c[id];else if(c[id]!==null&&c[id]!==undefined)el[id].value=c[id]});el.mp_aceitar_pix.checked=c.mp_aceitar_pix!==false;el.mp_aceitar_cartao.checked=c.mp_aceitar_cartao!==false;el.aceitar_dinheiro.checked=c.aceitar_dinheiro!==false;toggleSinal();togglePixManual();ids.forEach(id=>el[id].disabled=!paymentsEnabled);salvarPagamentos.disabled=!paymentsEnabled;if(!paymentsEnabled)document.getElementById('paymentLock').classList.remove('hidden');updateCheckoutStatus()}
  async function saveConfig(showMessage=true){const body={};ids.forEach(id=>body[id]=el[id].type==='checkbox'?el[id].checked:el[id].value);body.percentual_sinal=Number(body.percentual_sinal||50);const r=await api('/pagamentos/config',{method:'PUT',body:JSON.stringify(body)});if(!r.aceitar_mercadopago)el.aceitar_mercadopago.checked=false;updateOverview();if(showMessage)flash(msg,'Configuração do checkout salva')}
  salvarPagamentos.onclick=async()=>{try{salvarPagamentos.disabled=true;salvarPagamentos.textContent='Salvando...';await saveConfig()}catch(e){flash(msg,e.message,'error')}finally{salvarPagamentos.disabled=!paymentsEnabled;salvarPagamentos.textContent='Salvar checkout'}};
  el.pagamento_agendamento.onchange=toggleSinal;el.percentual_sinal.oninput=updateOverview;el.aceitar_pix_manual.onchange=togglePixManual;el.aceitar_mercadopago.onchange=updateCheckoutStatus;
  function whatsappFailureText(reason){return ({whatsapp_not_connected:'WhatsApp não conectado',invalid_phone:'telefone do cliente inválido',not_found:'agendamento não encontrado'})[String(reason||'')]||'não foi possível entregar a mensagem'}
  function closePixConfirmModal(){if(!pixConfirmModal)return;pixConfirmModal.classList.add('hidden');document.body.classList.remove('modal-open');selectedPendingPix=null;pixConfirmFeedback.className='notice hidden';pixConfirmFeedback.textContent='';pixConfirmButton.disabled=false;pixConfirmButton.textContent='Confirmar Pix recebido';pixConfirmCancel.textContent='Cancelar'}
  function openPixConfirmModal(id){const x=pendingPixRows.find(row=>Number(row.id)===Number(id));if(!x)return;selectedPendingPix=x;pixConfirmDetails.innerHTML=`<div><span>Cliente</span><strong>${esc(x.nome||'Cliente')}</strong></div><div><span>WhatsApp</span><strong>${esc(x.telefone||'—')}</strong></div><div><span>Serviço</span><strong>${esc(x.servico||'Serviço')}</strong></div><div><span>Profissional</span><strong>${esc(x.barbeiro||'Profissional')}</strong></div><div><span>Data e horário</span><strong>${dateBR(x.data)} às ${timeBR(x.horario)}</strong></div><div class="dashboard-pix-modal-value"><span>Valor a conferir</span><strong>${money(x.valor_cobrado)}</strong></div>`;pixConfirmFeedback.className='notice hidden';pixConfirmFeedback.textContent='';pixConfirmButton.disabled=false;pixConfirmButton.textContent='Confirmar Pix recebido';pixConfirmCancel.textContent='Cancelar';pixConfirmModal.classList.remove('hidden');document.body.classList.add('modal-open');requestAnimationFrame(()=>pixConfirmButton.focus())}
  async function confirmPendingPix(){if(!selectedPendingPix)return;const id=selectedPendingPix.id;try{pixConfirmButton.disabled=true;pixConfirmButton.textContent='Confirmando…';const r=await api(`/pagamentos-pendentes/${id}/confirmar`,{method:'POST'});if(r.whatsapp_enviado===true){pixConfirmFeedback.className='notice success';pixConfirmFeedback.innerHTML='<strong>Pagamento aprovado.</strong> Agendamento criado e confirmação enviada ao cliente pelo WhatsApp.'}else if(r.whatsapp_enviado===false){pixConfirmFeedback.className='notice warning';pixConfirmFeedback.innerHTML=`<strong>Agendamento criado.</strong> A confirmação não foi enviada automaticamente: ${esc(whatsappFailureText(r.whatsapp_motivo))}.`}else{pixConfirmFeedback.className='notice success';pixConfirmFeedback.textContent=r.mensagem||'Pagamento já estava confirmado.'}pixConfirmButton.textContent='Concluído';pixConfirmCancel.textContent='Fechar';await loadPendingPix()}catch(e){pixConfirmFeedback.className='notice error';pixConfirmFeedback.textContent=e.message;pixConfirmButton.disabled=false;pixConfirmButton.textContent='Tentar novamente'}}
  async function loadPendingPix(){try{pendingPixRows=await api('/pagamentos-pendentes');pixPendentes.innerHTML=pendingPixRows.length?pendingPixRows.map(x=>`<article class="pending-payment-row"><div class="pending-payment-copy"><strong>${esc(x.nome)}</strong><div class="muted">${esc(x.servico)} • ${esc(x.barbeiro||'Profissional')}</div><small>${dateBR(x.data)} às ${timeBR(x.horario)} • ${money(x.valor_cobrado)} • ${esc(x.telefone)}</small></div><button class="btn btn-primary pending-payment-confirm" type="button" data-confirmar-pix="${x.id}">Confirmar Pix</button></article>`).join(''):'<div class="dashboard-pix-empty"><strong>Nenhum Pix aguardando aprovação</strong><span>As reservas por Pix manual aparecerão aqui para conferência.</span></div>';pixPendentes.querySelectorAll('[data-confirmar-pix]').forEach(b=>b.onclick=()=>openPixConfirmModal(b.dataset.confirmarPix))}catch(e){pixPendentes.innerHTML=`<div class="dashboard-pix-empty error"><strong>Não foi possível carregar os pagamentos</strong><span>${esc(e.message)}</span></div>`}}
  pixConfirmButton?.addEventListener('click',confirmPendingPix);pixConfirmCancel?.addEventListener('click',closePixConfirmModal);pixConfirmClose?.addEventListener('click',closePixConfirmModal);pixConfirmModal?.addEventListener('click',e=>{if(e.target===pixConfirmModal)closePixConfirmModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pixConfirmModal&&!pixConfirmModal.classList.contains('hidden'))closePixConfirmModal()});
  atualizarPixPendentes.onclick=loadPendingPix;
  async function boot(){try{await Promise.all([loadConfig(),loadGateways(),loadPendingPix()])}catch(e){flash(msg,e.message,'error')}}
  boot();
}
