if(requireAuth(['dono','gerente'])){
  document.getElementById('shell').innerHTML=renderShell('pagamentos');
  const user=currentUser(),msg=document.getElementById('msg');
  const gatewayModal=document.getElementById('gatewayModal'),gatewayModalTitle=document.getElementById('gatewayModalTitle'),gatewayModalDesc=document.getElementById('gatewayModalDesc'),closeGatewayModal=document.getElementById('closeGatewayModal'),gatewayCredentialForm=document.getElementById('gatewayCredentialForm'),asaasFields=document.getElementById('asaasFields'),pagarmeFields=document.getElementById('pagarmeFields'),asaasEnvironment=document.getElementById('asaasEnvironment'),asaasApiKey=document.getElementById('asaasApiKey'),pagarmeSecretKey=document.getElementById('pagarmeSecretKey'),pagarmePublicKey=document.getElementById('pagarmePublicKey'),saveGatewayCredential=document.getElementById('saveGatewayCredential'),cancelGatewayCredential=document.getElementById('cancelGatewayCredential'),campoSinal=document.getElementById('campoSinal'),pixManualCampos=document.getElementById('pixManualCampos'),salvarPagamentos=document.getElementById('salvarPagamentos'),pixPendentes=document.getElementById('pixPendentes'),atualizarPixPendentes=document.getElementById('atualizarPixPendentes');
  const ids=['pagamento_agendamento','percentual_sinal','aceitar_mercadopago','mp_aceitar_pix','mp_aceitar_cartao','aceitar_pix_manual','pix_chave','pix_nome','pix_banco','aceitar_dinheiro'];
  const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
  let gatewayData=[],paymentsEnabled=false,currentModal=null;
  const providerMark={mercadopago:'MP',pagbank:'PB',asaas:'AS',pagarme:'PM',stripe:'ST'};
  function statusLabel(g){if(g.conectado)return 'Conectado';if(g.status==='erro')return 'Erro na conexão';if(!g.plataforma_pronta&&g.tipo==='oauth')return 'Aguardando configuração';return 'Não conectado'}
  function checkoutText(g){if(g.checkout)return g.conectado?'Checkout online ativo':'Checkout já implementado';return 'Conexão pronta • cobrança em próxima etapa'}
  function renderGateways(){
    const grid=document.getElementById('gatewayGrid');
    grid.innerHTML=gatewayData.map(g=>{
      const owner=user.papel==='dono',canConnect=paymentsEnabled&&owner;
      let action='';
      if(g.conectado&&owner)action=`<button type="button" class="btn btn-danger gateway-disconnect" data-provider="${g.id}">Desconectar</button>`;
      else if(g.conectado)action='<span class="muted">Somente o dono pode desconectar</span>';
      else if(!paymentsEnabled)action='<a class="btn btn-secondary" href="/pages/assinatura.html">Disponível no Pro</a>';
      else if(!owner)action='<button type="button" class="btn btn-secondary" disabled>Somente o dono conecta</button>';
      else if(g.tipo==='oauth'&&!g.plataforma_pronta)action='<button type="button" class="btn btn-secondary" disabled>Plataforma ainda não configurada</button>';
      else action=`<button type="button" class="btn btn-primary gateway-connect" data-provider="${g.id}">Conectar ${esc(g.nome)}</button>`;
      return `<article class="gateway-card ${g.conectado?'connected':''}"><div class="gateway-card-head"><div class="gateway-brand ${g.id}">${providerMark[g.id]||'PG'}</div><div class="gateway-title"><strong>${esc(g.nome)}</strong><span>${esc(g.metodos.join(' • '))}</span></div><span class="gateway-status ${g.conectado?'ok':g.status==='erro'?'error':''}">${esc(statusLabel(g))}</span></div><p>${esc(g.descricao)}</p><div class="gateway-capability"><span>${g.checkout?'⚡':'🔌'}</span>${esc(checkoutText(g))}</div>${g.conta_id?`<div class="gateway-account">Conta: <strong>${esc(String(g.conta_id).slice(0,28))}</strong></div>`:''}${g.ultimo_erro&&!g.conectado?`<div class="gateway-error">${esc(g.ultimo_erro)}</div>`:''}<div class="gateway-card-actions">${action}</div></article>`;
    }).join('');
    grid.querySelectorAll('.gateway-connect').forEach(b=>b.onclick=()=>connectGateway(b.dataset.provider));
    grid.querySelectorAll('.gateway-disconnect').forEach(b=>b.onclick=()=>disconnectGateway(b.dataset.provider));
    const connected=gatewayData.filter(x=>x.conectado);document.getElementById('connectedCount').textContent=String(connected.length);
    const checkout=gatewayData.find(x=>x.checkout_ativo);document.getElementById('checkoutGateway').textContent=checkout?checkout.nome:'Nenhum';
  }
  async function loadGateways(){const r=await api('/pagamentos/gateways');paymentsEnabled=!!r.habilitado;gatewayData=r.gateways||[];document.getElementById('paymentLock').classList.toggle('hidden',paymentsEnabled);renderGateways()}
  async function connectGateway(provider){
    if(provider==='mercadopago'){try{const r=await api('/mercadopago/conectar');location.href=r.url}catch(e){flash(msg,e.message,'error')}return}
    if(['pagbank','stripe'].includes(provider)){try{const r=await api(`/pagamentos/gateways/${provider}/conectar`);location.href=r.url}catch(e){flash(msg,e.message,'error')}return}
    if(['asaas','pagarme'].includes(provider))openCredentialModal(provider);
  }
  async function disconnectGateway(provider){const g=gatewayData.find(x=>x.id===provider);if(!confirm(`Desconectar ${g?.nome||provider} desta barbearia?`))return;try{if(provider==='mercadopago')await api('/mercadopago/conexao',{method:'DELETE'});else await api(`/pagamentos/gateways/${provider}`,{method:'DELETE'});if(provider==='mercadopago'){el.aceitar_mercadopago.checked=false;await saveConfig(false)}await loadGateways();flash(msg,`${g?.nome||'Gateway'} desconectado`)}catch(e){flash(msg,e.message,'error')}}
  function openCredentialModal(provider){currentModal=provider;gatewayModalTitle.textContent=`Conectar ${provider==='asaas'?'Asaas':'Pagar.me'}`;gatewayModalDesc.textContent=provider==='asaas'?'Cole uma chave de API criada por um administrador da conta Asaas.':'Use as chaves exibidas na área de Desenvolvimento da conta Pagar.me.';asaasFields.classList.toggle('hidden',provider!=='asaas');pagarmeFields.classList.toggle('hidden',provider!=='pagarme');gatewayModal.classList.remove('hidden');document.body.classList.add('modal-open')}
  function closeCredentialModal(){currentModal=null;gatewayModal.classList.add('hidden');document.body.classList.remove('modal-open');gatewayCredentialForm.reset()}
  closeGatewayModal.onclick=cancelGatewayCredential.onclick=closeCredentialModal;gatewayModal.onclick=e=>{if(e.target===gatewayModal)closeCredentialModal()};
  gatewayCredentialForm.onsubmit=async e=>{e.preventDefault();if(!currentModal)return;try{saveGatewayCredential.disabled=true;saveGatewayCredential.textContent='Validando...';if(currentModal==='asaas')await api('/pagamentos/gateways/asaas/conectar',{method:'POST',body:JSON.stringify({api_key:asaasApiKey.value,environment:asaasEnvironment.value})});else await api('/pagamentos/gateways/pagarme/conectar',{method:'POST',body:JSON.stringify({secret_key:pagarmeSecretKey.value,public_key:pagarmePublicKey.value})});closeCredentialModal();await loadGateways();flash(msg,'Gateway validado e conectado com segurança')}catch(e){flash(msg,e.message,'error')}finally{saveGatewayCredential.disabled=false;saveGatewayCredential.textContent='Validar e conectar'}};
  function toggleSinal(){campoSinal.style.display=el.pagamento_agendamento.value==='sinal'?'flex':'none';updateOverview()}
  function togglePixManual(){pixManualCampos.style.display=el.aceitar_pix_manual.checked?'grid':'none'}
  function updateOverview(){const mode=el.pagamento_agendamento.value;document.getElementById('chargeMode').textContent=mode==='total'?'Valor total':mode==='sinal'?`${Number(el.percentual_sinal.value||50)}% de sinal`:'Sem antecipação';document.getElementById('chargeModeHint').textContent=mode==='nenhum'?'Cliente paga no atendimento':'Cobrança antes da confirmação'}
  async function loadConfig(){const r=await api('/pagamentos/config');paymentsEnabled=!!r.habilitado;const c=r.config||{};ids.forEach(id=>{if(el[id].type==='checkbox')el[id].checked=!!c[id];else if(c[id]!==null&&c[id]!==undefined)el[id].value=c[id]});el.mp_aceitar_pix.checked=c.mp_aceitar_pix!==false;el.mp_aceitar_cartao.checked=c.mp_aceitar_cartao!==false;el.aceitar_dinheiro.checked=c.aceitar_dinheiro!==false;toggleSinal();togglePixManual();ids.forEach(id=>el[id].disabled=!paymentsEnabled);salvarPagamentos.disabled=!paymentsEnabled;if(!paymentsEnabled)document.getElementById('paymentLock').classList.remove('hidden')}
  async function saveConfig(showMessage=true){const body={};ids.forEach(id=>body[id]=el[id].type==='checkbox'?el[id].checked:el[id].value);body.percentual_sinal=Number(body.percentual_sinal||50);const r=await api('/pagamentos/config',{method:'PUT',body:JSON.stringify(body)});if(!r.aceitar_mercadopago)el.aceitar_mercadopago.checked=false;updateOverview();if(showMessage)flash(msg,'Configurações de pagamento salvas')}
  salvarPagamentos.onclick=async()=>{try{salvarPagamentos.disabled=true;salvarPagamentos.textContent='Salvando...';await saveConfig()}catch(e){flash(msg,e.message,'error')}finally{salvarPagamentos.disabled=!paymentsEnabled;salvarPagamentos.textContent='Salvar configurações de pagamento'}};
  el.pagamento_agendamento.onchange=toggleSinal;el.percentual_sinal.oninput=updateOverview;el.aceitar_pix_manual.onchange=togglePixManual;
  async function loadPendingPix(){try{const list=await api('/pagamentos-pendentes');pixPendentes.innerHTML=list.length?list.map(x=>`<div class="pending-payment-row"><div><strong>${esc(x.nome)}</strong><div class="muted">${esc(x.servico)} • ${dateBR(x.data)} ${timeBR(x.horario)} • ${money(x.valor_cobrado)}</div><small>${esc(x.telefone)}</small></div><button class="btn btn-primary" data-confirmar-pix="${x.id}">Confirmar recebimento</button></div>`).join(''):'<p class="muted">Nenhum Pix manual aguardando confirmação.</p>';pixPendentes.querySelectorAll('[data-confirmar-pix]').forEach(b=>b.onclick=async()=>{if(!confirm('Você conferiu o recebimento deste Pix?'))return;try{await api(`/pagamentos-pendentes/${b.dataset.confirmarPix}/confirmar`,{method:'POST'});flash(msg,'Pix confirmado e agendamento criado');loadPendingPix()}catch(e){flash(msg,e.message,'error')}})}catch(e){pixPendentes.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
  atualizarPixPendentes.onclick=loadPendingPix;
  async function boot(){try{await Promise.all([loadConfig(),loadGateways(),loadPendingPix()]);const q=new URLSearchParams(location.search),st=q.get('status'),gw=q.get('gateway');if(st==='conectado')flash(msg,`${gw==='mercadopago'?'Mercado Pago':gw==='pagbank'?'PagBank':'Stripe'} conectado com sucesso`);if(st==='erro')flash(msg,`Falha ao conectar ${gw||'gateway'}: ${q.get('motivo')||''}`,'error')}catch(e){flash(msg,e.message,'error')}}
  boot();
}
