const slug=location.pathname.split('/').filter(Boolean).pop();let hSel='',cfg=null,tsId=null;const qs=new URLSearchParams(location.search);
function flash(el,text,type=''){el.textContent=text;el.className='notice '+type}
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function validManageToken(v){return /^[A-Za-z0-9_-]{32,200}$/.test(String(v||'').trim())}
function maskManageToken(v){const t=String(v||'').trim();if(!t)return '';return t.length<=8?'••••••••':`${t.slice(0,4)}••••••${t.slice(-4)}`}
function rememberManageToken(v){const t=String(v||'').trim();if(!validManageToken(t))return;sessionStorage.setItem('bf_manage_token',t);manageToken.value=t}
function safeUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function aplicarTema(b){const root=document.documentElement;root.style.setProperty('--public-primary',b.cor_primaria||'#f59e0b');root.style.setProperty('--public-secondary',b.cor_secundaria||'#111827');root.style.setProperty('--public-button',b.cor_botao||b.cor_primaria||'#f59e0b');root.style.setProperty('--public-bg',b.cor_fundo||'#f7f7f8');document.body.classList.toggle('public-dark',b.tema==='escuro');const banner=safeUrl(b.banner_url);if(banner)heroPublico.style.backgroundImage=`url("${banner}")`;const logo=safeUrl(b.logo_url);if(logo){const im=document.createElement('img');im.src=logo;im.alt=`Logo ${b.nome}`;logoPublica.replaceChildren(im)}titulo.textContent=b.nome;boasVindas.textContent=b.texto_boas_vindas||'';boasVindas.style.display=b.texto_boas_vindas?'':'none';descricaoPublica.textContent=b.descricao_publica||'';descricaoPublica.style.display=b.descricao_publica?'':'none';const locationText=[b.endereco,b.cidade,b.estado].filter(Boolean).join(', ');endereco.textContent=locationText;if(b.mostrar_whatsapp_publico!==false&&b.whatsapp_publico){const phone=String(b.whatsapp_publico).replace(/\D/g,'');whatsappLink.href=`https://wa.me/${phone}?text=${encodeURIComponent('Olá! Vim pela página de agendamento e gostaria de falar com a barbearia.')}`;whatsappLink.classList.remove('hidden')}if(b.mostrar_mapa_publico!==false&&locationText){const q=encodeURIComponent(locationText),card=document.getElementById('publicLocationCard'),label=document.getElementById('publicLocationAddress'),search=document.getElementById('mapSearchLink'),directions=document.getElementById('mapDirectionsLink');if(label)label.textContent=locationText;if(search)search.href=`https://www.google.com/maps/search/?api=1&query=${q}`;if(directions)directions.href=`https://www.google.com/maps/dir/?api=1&destination=${q}`;card?.classList.remove('hidden')}if(b.instagram){const ig=String(b.instagram).replace(/^@/,'').trim();instagramLink.href=`https://instagram.com/${encodeURIComponent(ig)}`;instagramLink.classList.remove('hidden')}if(b.politica_cancelamento){politicaTexto.textContent=b.politica_cancelamento;politicaBox.classList.remove('hidden')}}


function initTurnstile(){const key=cfg?.security?.turnstile_site_key;if(!key)return;if(!window.turnstile)return setTimeout(initTurnstile,250);if(tsId===null)tsId=turnstile.render('#turnstileBox',{sitekey:key,theme:'auto',action:'public_booking'})}
function tsToken(){return tsId!==null&&window.turnstile?turnstile.getResponse(tsId):''}function resetTs(){if(tsId!==null&&window.turnstile)turnstile.reset(tsId)}
function otpNecessario(){if(!cfg?.security?.booking_otp_required)return false;const b=cfg.barbearia;return b.pagamento_agendamento==='nenhum'||['dinheiro','pix_manual'].includes(forma_pagamento.value)}
function atualizarOtp(){const on=otpNecessario();otpBox.classList.toggle('hidden',!on);email.required=on;if(!on){otpCode.value='';otpMsg.textContent=''}}
async function load(){const r=await fetch(`/api/publico/${encodeURIComponent(slug)}`);const d=await r.json();if(!r.ok){msg.textContent=d.erro;msg.className='notice error';return}cfg=d;const b=d.barbearia;document.title=`Agendamento - ${b.nome}`;aplicarTema(b);servico.innerHTML='<option value="">Selecione</option>'+d.servicos.map(s=>{const meta=[b.mostrar_duracao!==false?`${s.duracao} min`:'',b.mostrar_precos!==false?money(s.preco):''].filter(Boolean).join(' • ');return `<option value="${Number(s.id)}" data-preco="${Number(s.preco||0)}">${esc(s.nome)}${meta?' • '+esc(meta):''}</option>`}).join('');barbeiro.innerHTML='<option value="">Selecione</option>'+d.barbeiros.map(x=>`<option value="${Number(x.id)}">${esc(x.nome)}</option>`).join('');if(b.pagamento_agendamento!=='nenhum'){formaPagamentoBox.classList.remove('hidden');forma_pagamento.innerHTML='<option value="">Selecione</option>'+d.metodos_pagamento.map(m=>`<option value="${esc(m.id)}">${esc(m.nome)}${m.descricao?' • '+esc(m.descricao):''}</option>`).join('');if(!d.metodos_pagamento.length){pagamentoInfo.className='notice error';pagamentoInfo.textContent='Esta barbearia exige pagamento, mas ainda não configurou uma forma de recebimento.';agendar.disabled=true}}initTurnstile();atualizarPagamentoInfo();atualizarOtp();await processarRetornoPagamento()}
function atualizarPagamentoInfo(){if(!cfg)return;const b=cfg.barbearia;if(b.pagamento_agendamento==='nenhum'){pagamentoInfo.className='notice hidden';formaPagamentoBox.classList.add('hidden');agendar.textContent='Confirmar agendamento';return}const opt=servico.options[servico.selectedIndex],preco=Number(opt?.dataset?.preco||0),valor=b.pagamento_agendamento==='total'?preco:preco*Number(b.percentual_sinal||50)/100;pagamentoInfo.className='notice';pagamentoInfo.textContent=b.pagamento_agendamento==='total'?`Valor do agendamento: ${money(valor)}.`:`Sinal de ${Number(b.percentual_sinal||50)}%: ${money(valor)}.`;const fp=forma_pagamento.value;agendar.textContent=fp==='mercado_pago'?'Reservar e pagar no Mercado Pago':fp==='pix_manual'?'Reservar e ver chave Pix':fp==='dinheiro'?'Confirmar e pagar no local':'Continuar'}
async function slots(){hSel='';atualizarPagamentoInfo();if(!servico.value||!barbeiro.value||!data.value){horarios.innerHTML='<span class="muted">Selecione serviço, barbeiro e data.</span>';return}horarios.innerHTML='<span class="muted">Buscando horários disponíveis…</span>';const r=await fetch(`/api/publico/${encodeURIComponent(slug)}/horarios?servico_id=${encodeURIComponent(servico.value)}&barbeiro_id=${encodeURIComponent(barbeiro.value)}&data=${encodeURIComponent(data.value)}`);const a=await r.json();horarios.innerHTML=a.length?a.map(h=>`<button type="button" class="slot" data-h="${esc(h)}">${esc(h.slice(0,5))}</button>`).join(''):'<span class="muted">Sem horários disponíveis.</span>';document.querySelectorAll('.slot').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');hSel=b.dataset.h}))}
servico.addEventListener('change',slots);barbeiro.addEventListener('change',slots);data.addEventListener('change',slots);forma_pagamento.addEventListener('change',()=>{atualizarPagamentoInfo();atualizarOtp()});
enviarOtp.addEventListener('click',async()=>{try{if(!otpNecessario())return;if(!email.value||!telefone.value)throw new Error('Informe WhatsApp e e-mail antes de solicitar o código');const token=tsToken();if(cfg?.security?.turnstile_site_key&&!token)throw new Error('Conclua a verificação anti-robô');enviarOtp.disabled=true;const r=await fetch(`/api/publico/${encodeURIComponent(slug)}/otp/solicitar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telefone:telefone.value,email:email.value,turnstile_token:token})});const d=await r.json();if(!r.ok)throw new Error(d.erro);otpMsg.textContent=d.mensagem;otpMsg.className='muted';resetTs()}catch(e){otpMsg.textContent=e.message;otpMsg.className='notice error'}finally{enviarOtp.disabled=false}});
agendar.addEventListener('click',async()=>{try{if(!hSel)throw new Error('Selecione um horário');if(cfg.barbearia.pagamento_agendamento!=='nenhum'&&!forma_pagamento.value)throw new Error('Selecione a forma de pagamento');if(otpNecessario()&&!/^[0-9]{6}$/.test(otpCode.value.trim()))throw new Error('Informe o código de confirmação de 6 dígitos');agendar.disabled=true;pixManualInfo.className='notice hidden';const r=await fetch(`/api/publico/${encodeURIComponent(slug)}/agendar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:nome.value,telefone:telefone.value,email:email.value,servico_id:Number(servico.value),barbeiro_id:Number(barbeiro.value),data:data.value,horario:hSel,forma_pagamento:forma_pagamento.value||null,turnstile_token:tsToken(),otp_code:otpCode.value.trim(),marketing_token:qs.get('mkt')||null,marketing_opt_in:!!document.getElementById('marketingOptIn')?.checked})});const d=await r.json();if(!r.ok)throw new Error(d.erro);resetTs();if(d.agendamento?.token){rememberManageToken(d.agendamento.token);msg.textContent=`${d.mensagem||'Agendamento confirmado.'} Código seguro salvo neste dispositivo: ${maskManageToken(d.agendamento.token)}`;msg.className='notice success'}if(d.payment_type==='pix_manual'){msg.textContent=`Horário reservado por alguns minutos. Faça o Pix de ${money(d.valor_cobrado)}.`;msg.className='notice success';pixManualInfo.textContent=`Chave Pix: ${d.pix.chave} • Recebedor: ${d.pix.nome}${d.pix.banco?' • Banco: '+d.pix.banco:''}`;pixManualInfo.className='notice success';sessionStorage.setItem('bf_reserva',d.reserva_token);return}if(d.requires_payment&&d.checkout_url){sessionStorage.setItem('bf_reserva',d.reserva_token);location.href=d.checkout_url;return}otpCode.value='';hSel='';await slots()}catch(e){msg.textContent=e.message;msg.className='notice error';agendar.disabled=false;resetTs();atualizarPagamentoInfo()}});
async function processarRetornoPagamento(){const reserva=qs.get('reserva');if(!reserva)return;msg.textContent='Verificando seu pagamento...';msg.className='notice';const paymentId=qs.get('payment_id')||qs.get('collection_id');if(paymentId){try{await fetch(`/api/publico/${encodeURIComponent(slug)}/reservas/${encodeURIComponent(reserva)}/sincronizar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment_id:paymentId})})}catch{}}for(let i=0;i<6;i++){try{const r=await fetch(`/api/publico/${encodeURIComponent(slug)}/reservas/${encodeURIComponent(reserva)}`);const d=await r.json();if(r.ok&&d.status==='confirmada'){if(d.agendamento_token)rememberManageToken(d.agendamento_token);msg.textContent=`Pagamento aprovado! Agendamento confirmado.${d.agendamento_token?' Código seguro salvo: '+maskManageToken(d.agendamento_token):''}`;msg.className='notice success';return}if(r.ok&&d.status==='aguardando_pix_manual'){msg.textContent='Pix aguardando confirmação da barbearia.';msg.className='notice';return}if(r.ok&&d.status==='pagamento_aprovado_sem_vaga'){msg.textContent='Pagamento aprovado, mas houve conflito de horário. A barbearia fará a revisão.';msg.className='notice error';return}}catch{}await new Promise(x=>setTimeout(x,1500))}msg.textContent='Pagamento em processamento.';msg.className='notice'}
async function manageAction(action,body={}){const token=String(manageToken.value||'').trim();if(!validManageToken(token))return flash(manageMsg,'Informe um código seguro válido','error');const r=await fetch(`/api/publico/${encodeURIComponent(slug)}/agendamentos/${encodeURIComponent(token)}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();manageMsg.textContent=d.mensagem||(r.ok?'Operação concluída':d.erro);manageMsg.className='notice '+(r.ok?'success':'error');return{r,d}}
cancelarPub.addEventListener('click',()=>manageAction('cancelar'));reagendarPub.addEventListener('click',async()=>{const nd=prompt('Nova data (AAAA-MM-DD):'),nh=prompt('Novo horário (HH:MM):');if(nd&&nh)await manageAction('reagendar',{data:nd,horario:nh})});avaliarPub.addEventListener('click',async()=>{const nota=prompt('Nota de 1 a 5:','5');if(nota)await manageAction('avaliar',{nota:Number(nota),comentario:prompt('Comentário (opcional):','')||''})});
const savedManageToken=sessionStorage.getItem('bf_manage_token');if(validManageToken(savedManageToken))manageToken.value=savedManageToken;const localToday=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};data.min=localToday();load();
