if(requireAuth(['dono','gerente','recepcao','barbeiro'])){
  document.getElementById('shell').innerHTML=renderShell('suporte');
  const form=document.getElementById('supportForm'),msg=document.getElementById('msg'),tickets=document.getElementById('tickets'),contact=document.getElementById('contactBox');
  function statusLabel(s){return ({aberto:'Aberto',em_atendimento:'Em atendimento',resolvido:'Resolvido',fechado:'Fechado'})[s]||s}
  async function loadConfig(){try{const c=await api('/suporte/config');const parts=[];if(c.email)parts.push(`E-mail: <a href="mailto:${encodeURIComponent(c.email)}">${esc(c.email)}</a>`);if(c.whatsapp){const n=String(c.whatsapp).replace(/\D/g,'');parts.push(`WhatsApp: <a href="https://wa.me/${n}" target="_blank" rel="noopener">falar com suporte</a>`)}contact.innerHTML=parts.length?`Contato direto: ${parts.join(' • ')}`:'Use o formulário acima para falar com o suporte.'}catch{contact.textContent='Use o formulário acima para falar com o suporte.'}}
  async function load(){try{const list=await api('/suporte/tickets');tickets.innerHTML=list.length?list.map(x=>`<article class="support-ticket"><div class="support-ticket-head"><div><strong>#${x.id} · ${esc(x.assunto)}</strong><small>${esc(x.categoria)} · ${new Date(x.criado_em).toLocaleString('pt-BR')}</small></div><span class="badge support-status-${esc(x.status)}">${esc(statusLabel(x.status))}</span></div><p>${esc(x.mensagem)}</p>${x.resposta?`<div class="support-reply"><strong>Resposta do BarberFlow</strong><p>${esc(x.resposta)}</p></div>`:''}${x.status==='resolvido'?`<button class="btn btn-secondary" data-close-ticket="${x.id}">Fechar chamado</button>`:''}</article>`).join(''):'<p class="muted">Você ainda não abriu nenhum chamado.</p>';tickets.querySelectorAll('[data-close-ticket]').forEach(b=>b.onclick=async()=>{try{await api(`/suporte/tickets/${b.dataset.closeTicket}/fechar`,{method:'PATCH'});load()}catch(e){flash(msg,e.message,'error')}})}catch(e){tickets.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
  form.onsubmit=async e=>{e.preventDefault();try{enviarChamado.disabled=true;await api('/suporte/tickets',{method:'POST',body:JSON.stringify({categoria:categoria.value,assunto:assunto.value,mensagem:mensagem.value})});form.reset();flash(msg,'Chamado enviado. Você pode acompanhar a resposta nesta página.');load()}catch(err){flash(msg,err.message,'error')}finally{enviarChamado.disabled=false}};
  atualizarTickets.onclick=load;loadConfig();load();
}
